### ISSUE TITLE
Toggle monitoring disables hotkeys

### ISSUE THREAD

**Issue by notEvil** [autokey/autokey#10]
Hello,

as this is my first issue I'd like to ask whether issues related to autokey (not python 3) are appreciated here or if they should be taken to https://groups.google.com/forum/#!forum/autokey-users?

The problem I'm experiencing is that whenever I toggle monitoring by using the corresponding hotkey, keys which are used in scripts and phrases as hotkey trigger (no modifiers) wouldn't find their way through autokey anymore. They just stop working. If they are used as abbreviation trigger, it's fine.

**Comment by troxor** [comment]
This is a good venue for bug reports that have a reliable reproduction case. Discussion around general usage are better served in the autokey-users group.
