### ISSUE TITLE
crashing after clipboard-insertion

### ISSUE THREAD

**Issue by gituser823** [autokey/autokey#102]
## Classification:

Crash/Hang/Data Loss

## Reproducibility:

Sometimes

## Summary

Sometimes the Keyboard is locked and I cant type anymore after I tried to insert something with autokey.
I think this only happens, when I use the insertion method Clipboard.
I used the old autokey with python2 before and there i had the same problem.
now switching to autokey-py3 didnt help obviously.

## Steps to Reproduce

I am in Chrome and type the Abbreviation.

## Expected Results

My Text should be inserted and the Keyboard should not be locked.

## Actual Results

My Keyboard is locked and nothing is inserted.

## Version

AutoKey-Py3 version 

Autokey-gtk 0.93.10

Installed via: (PPA, pip, …).

dont remember

Distro:

Linux Mint

**Comment by troxor** [comment]
Not enough information given to investigate. Please provide a reproduction case.

**Comment by luziferius** [comment]
@gituser823 Just to ping you about this in case you hadn’t seen: This was fixed in 0.95.1.
