### ISSUE TITLE
Segfault when trying to start autokey-qt

### ISSUE THREAD

**Issue by sicherist** [autokey/autokey#104]
## Classification:

Crash

## Reproducibility:

Always

## Summary

Autokey-qt used to work flawlessly for the last months but suddenly it stopped working. When starting the program from the shell it quits with a python segmentation fault message.

## Steps to Reproduce

`autokey-qt --verbose`

## Expected Results

Autokey-qt should start.

## Actual Results

Error message:

`Fatal Python error: Segmentation fault

Current thread 0x00007f6ebd339700 (most recent call first):
  File "<frozen importlib._bootstrap>", line 222 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 906 in create_module
  File "<frozen importlib._bootstrap>", line 577 in module_from_spec
  File "<frozen importlib._bootstrap>", line 666 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 969 in _find_and_load
  File "/usr/lib/python3/dist-packages/autokey/qtapp.py", line 24 in <module>
  File "<frozen importlib._bootstrap>", line 222 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 665 in exec_module
  File "<frozen importlib._bootstrap>", line 673 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 969 in _find_and_load
  File "/usr/bin/autokey-qt", line 56 in <module>
Speicherzugriffsfehler (Speicherabzug geschrieben)
`

## Version

0.93.10-1 

Installed via: PPA

Distro: Kubuntu 16.04 with KDE backports

## Notes

I would appreciate any hints to where I might start looking for a solution, as autokey-py3 is one of the most frequently used tools on my computer.

**Comment by troxor** [comment]
the Qt interface is nearing EOL, until #56 is implemented. The libraries it currently depends on have been deprecated for some time now.

**Comment by sicherist** [comment]
Thank you for your fast reply! Do you have any idea what package was updated in the last couple of days that might have caused this?

**Comment by troxor** [comment]
I have absolutely no idea, but it wasn't this one! Check /var/log/dpkg.log, /var/log/yum.log, or similar.

**Comment by luziferius** [comment]
@sicherist You may want to try the newest version. As of version `0.94.1-0ubuntu7`, the PPA contains a (almost) complete rewrite of the Qt GUI. You may want to give it a try.

**Comment by sicherist** [comment]
Great to hear that you rewrote the QT-Code! Unfortunately I'm still on Xenial but I will try it out as soon as I upgrade to Bionic.

**Comment by luziferius** [comment]
It should work on xenial. Or you can try to manually install the debian packages I built. Those are attached to the [github release page](https://github.com/autokey/autokey/releases/tag/v0.95.1)
Those should work, if the dependencies are satisfiable on xenial.

**Comment by sicherist** [comment]
I installed the deb-packages, but it won't run. It depends on python3-pyqt5.qsci which I can't get to install. I think this is a problem specific to my Ubuntu-installation.

> python3-pyqt5.qsci :
>Depends: libqt5scintilla2-12v5 (>= 2.9) but it is not going to be installed
>Depends: sip-py3api-11.3 but it is not installable
>

**Comment by luziferius** [comment]
Congratulations, it seems you just found a bug in the Ubuntu package repository! They bundle a version of `python3-pyqt5.qsci` that depends on the virtual package [`sip-py3api-11.3`](https://packages.ubuntu.com/artful/sip-py3api-11.3) which is only available in `artful`(17.10).

Then you’ll have to manually purge the autokey packages and revert back to your previous version.
Or monkey-patch your system by manually installing https://packages.ubuntu.com/artful/python3-sip . (That is a dangerous operation! No support and no guarantees when going that way!)
Or report the packaging bug with `python3-pyqt5.qsci` to Ubuntu. (maybe a mailing list? launchpad? I don’t know.)

**Comment by sicherist** [comment]
The bug might be in the Kubuntu backports-repository but I have not yet had time to look into it. However the monkey-patching worked fine and I'm running autokey-qt 0.95.1 now :) Thanks a lot for your work! 

There are two differences I noticed in comparison to the gtk-version:

1. Sometimes I accidentally hit my autokey-shortcut. Then the menu pops up but there is no way to cancel without pasting a phrase. The menu stays on top until I chose any phrase. I would love to see a button to cancel or being able to close the menu with "Esc" on the keyboard.

2. Keyboard navigation in the phrases menu. In the gtk-version I can select a phrase using the arrow keys and the phrases are numbered so they can be selected by entering the number on the keyboard. It would be great if this was also possible in qt.

Both things would be nice to have but even without, I'm very glad that autokey exists and is still worked on!

**Comment by luziferius** [comment]
There are even more differences ;) See #158 for some points.

Both your points boil down to one thing: The opened menu has no keyboard focus.

On my system, the menu properly gets the focus, so can be navigated using the arrow keys and cancelled with ESC. Hmmm, there is this old comment in the code:

https://github.com/autokey/autokey/blob/54bd77c664aa1403d296b66a78dfa25e9ebdf902/lib/autokey/qtui/popupmenu.py#L126

The numbering is missing, because the contributor who added it, did it only for the GTK GUI.

As a workaround, you may want to add an empty phrase you can paste when hitting the hotkey accidentally.
Autokey does not allow this, but you may be able to "cheat" by using the text cursor positioning macro `<cursor>`. If this is the only content, it will result in an empty phrase during the processing.
You may want to check the verbose log on the command line while trying this. I have no idea if it crashes autokey. If it does, please file an issue ;)

**Comment by sicherist** [comment]
Thanks for the `<cursor>`-workaround :)
