### ISSUE TITLE
Lockfile and log file shouldn't be in XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by founderio** [autokey/autokey#106]
## Classification:

Enhancement

## Reproducibility:

Always

## Summary

Lockfile and log file shouldn't be in XDG_CONFIG_HOME

## Steps to Reproduce

Launch the application and look for autokey.log and autokey.pid.

## Expected Results

The files should all follow the [XDG Base Directory Specification](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html).
- autokey.log should be in $XDG_CACHE_HOME/autokey or $XDG_DATA_HOME/autokey (the standard is not clear on that)
- autokey.pid should be in $XDG_RUNTIME_DIR/autokey

## Actual Results

- They both are located in $XDG_CONFIG_HOME/autokey where they should not be, as both files are not configuration files.

## Version

AutoKey-Py3 version 0.93.10, but probably applies to all versions.
Installed via AUR on Arch Linux.

## Notes

The relevant code looks to be located here: https://github.com/autokey-py3/autokey/blob/master/lib/autokey/common.py#L22
If accepted, I could provide a pull request for this issue.

**Comment by troxor** [comment]
Code PRs are always welcome! This looks like a pretty straightforward and logical change.
