### ISSUE TITLE
New GalliumOS on chromebook autokey error.

### ISSUE THREAD

**Issue by quoderatd2** [autokey/autokey#108]
## Classification:

Bug
## Reproducibility:

Always
## Summary

I can't get autokey to launch
## Steps to Reproduce

I followed the steps to install using 
sudo add-apt-repository ppa:troxor/autokey
sudo apt update
sudo apt install autokey-gtk

It was successfully done but 
then I proceeded to start it.

autokey-gtk
(I am new to linux so I didn't understand what was meant by the PATH...)
## Expected Results

I expected it to work but 
## Actual Results

- Instead, I got error messages as shown in attachment.

If helpful, submit screenshots of the issue to help debug. `autokey-gtk --verbose` output is also useful.

## Version

AutoKey-Py3 version ???

If the problem is known to
![autokey_error](https://user-images.githubusercontent.com/33797665/32987593-258821e2-cce8-11e7-83a2-a71a01231f45.png)
 be present in more than one version, please list all of those.

Installed via: (PPA, pip, …).
PPA
Distro: GalliumOS

## Notes

Describe any debugging steps you've taken yourself.

If you've found a workaround, provide it here.

**Comment by luziferius** [comment]
The PATH is a shell variable containing a list of directories that is searched for executable program files. You can execute `echo $PATH` on the shell to see its content.

Those error messages might not be fatal errors, although looking scary. Try launching autokey-gtk with the `-c` switch, like `autokey-gtk -c`. This forces autokey to show the main window upon start. Without the `-c`, autokey sits as an icon in the system tray and has to be manually opened by clicking the icon.

(Side note: The PPA you used to install is no longer updated. You can remove it and use the new PPA, as described in the current README: `ppa:sporkwitch/autokey`. This repository is currently for Ubuntu 18.04 only, so it might not be compatible with GalliumOS, which is built on top of the older Ubuntu 16.04 release.)
