### ISSUE TITLE
Trigger new phrases immediately by default

### ISSUE THREAD

**Issue by ghost** [autokey/autokey#111]
## Classification:

Enhancement

## Reproducibility:

Always

## Summary

I suggest to create a setting which lets users specify that new phrases should trigger immediately. 

I am a heavy user of the `phrase from selection` script, and I tend to use a special character (the hash sign) to delimit my phrases / distinguish them from other stuff ... and I want them all to trigger immediately. I have written a little shell script (see below) to watch the directory, make a replacement in the JSON file, and restart autokey. But it would be better to be able to do all of this from within autokey. This could be an application-wide setting (okay solution but not a great solution); or, even better, this functionality could be exposed through `engine.create_phrase`.

Shell script/workaround: 
```
while true # run indefinitely
do
	# watch directory for new files
	inotifywait -e create --format %w%f "/home/user_name/.config/autokey/data/My Phrases" | while read FILE
	do 
		# replace text in file; note the "|" for literal replacement (no regex)
		sed -i.bak 's|"immediate": false,|"immediate": true,|' "$FILE"

		# stop & restart autokey
		killall autokey-gtk
		autokey-gtk
	done
done
```

**Comment by troxor** [comment]
Patches for this feature are welcome, though at some point you may be better off just reimplementing a custom solution.
