### ISSUE TITLE
PPA out dated 

### ISSUE THREAD

**Issue by MasterCATZ** [autokey/autokey#112]
Err:14 http://ppa.launchpad.net/troxor/autokey/ubuntu artful Release     
  404  Not Found
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/troxor/autokey/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by troxor** [comment]
Dupe of #81
