### ISSUE TITLE
X protocol error:

### ISSUE THREAD

**Issue by rnmhdn** [autokey/autokey#115]
## Classification:

Bug

## Reproducibility:

Always

## Summary

This thing is almost impossible to install!

## Steps to Reproduce

I installed it with pip. it didn't work. I installed it with ppa. it didn't work. it just showed the autokey and autokey kde logos in my applications but when I clicked on them. nth happened. I downloaded the old autokey from googlecodes and tried to build that. which didn't work either. I tried with python setup.py install. didn't work. finally after a few days it just started to work by itself. Not that it worked! but at least it could show the gui! But it wasn't functioning correctly at all. It couldn't save the phrases and nth. So today I did locate autokey and removed all the files I could find. then tried to isntall with pip. didn't work. then tried sudo apt install autokey-gtk. And could finally do something after manually installing dbus etc. now when I issue sudo autokey-gtk I get:
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 260, sequence_number = 15, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 260, sequence_number = 16, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 260, sequence_number = 17, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 260, sequence_number = 18, major_opcode = 33, minor_opcode = 0

I have never tried to install a package and fail as much as I've failed with this!

Distro:
Ubuntu 16.04

**Comment by troxor** [comment]
Those X errors are most likely benign, check if the process is running and provide more detail if you still believe this is a bug. Autokey may be starting in the background.
