### ISSUE TITLE
This has not worked since I remember :(

### ISSUE THREAD

**Issue by qcol** [autokey/autokey#118]
I have been following the development of this program for a long time, but I know its functionality only from descriptions and screens. On previous Ubuntu/Mint versions, the program was installed but had to hang during the first use of any keyboard shortcut. It was a known bug reported on many forums but nobody could fix it.  More forks, versions.... none of them worked. In fact, this has not worked since I remember it. Now I see new git repo, but again it is not possible to install it either on Ubuntu 17.04 or on 17.10. Why is it so difficult to make it just working?  

## Classification:

Can't install (no repository for Ubuntu 17.04, 17.10) 

## Version

Last

If the problem is known to be present in more than one version, please list all of those.

PPA

Distro:

17.04, 17.10

**Comment by qcol** [comment]
I will only add that the Autokey present in the default 17.10 repository is installed but has an old error - it hangs the system after using any shortcut.

**Comment by darenschwenke** [comment]
Ubuntu 17 is based on Wayland, which replaces X.  Autokey was based on X,
and the core architecture of Wayland is designed to prevent how Autokey
worked.
It will never work without changes to Wayland, and you are unlikely to find
anything else that does either.

**Comment by qcol** [comment]
I switched to xfce (xubuntu desktop) - no change. 
Autokey from default repository doesn't work (hanging). 
ppa:troxor/autokey - can't install as well as 17.04  - The repository does not have a Release file 
https://github.com/autokey/autokey/issues/81

**Comment by troxor** [comment]
Some rough package building instructions are provided in the wiki. I haven't had a chance to install, test and build packages for later versions of Ubuntu. Also, as @darenschwenke said, it won't work on Wayland anyway.
