### ISSUE TITLE
how donate

### ISSUE THREAD

**Issue by DoctorSubtilis** [autokey/autokey#122]
## Classification:

Enhancement

## Reproducibility:

Always

## Summary

I cannot donate at [this link](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=L333CPRZ6J8JC): error message "PayPal cannot process this transaction because of a problem with the seller's website. Please contact the seller directly to resolve this problem."

## Steps to Reproduce

I click on Help - donate

## Expected Results

- This should happen.

## Actual Results

- Instead, this happens. :(

If helpful, submit screenshots of the issue to help debug. `autokey-gtk --verbose` output is also useful.

## Version

AutoKey-Py3 version ???

If the problem is known to be present in more than one version, please list all of those.

Installed via: (PPA, pip, …).

Distro: Kubuntu 17.10

## Notes

Describe any debugging steps you've taken yourself.

If you've found a workaround, provide it here.

**Comment by troxor** [comment]
The donation link was removed some time ago as the original author left the project. Feel free to donate to the EFF or another noble charity on behalf of Autokey if you so desire.
