### ISSUE TITLE
compileuic.sh   breaks build

### ISSUE THREAD

**Issue by sigoa** [autokey/autokey#131]
after a pykdeuic4-3.5   run, autokey is totally broken. this app is low pre-alpha quality
not even the paths in  compileuic.sh    are correct. what is this ?

pristine master does build + run though. bad first impression.

**Comment by luziferius** [comment]
That is old legacy stuff, just like many 'testing functions' at the bottom of source files. That path was forgotten when all code was pulled out of a generic »src« folder during python 3 port.

Simply: Do not run this, there is no need to. I think the original author used the UI files, generated python code and then modified the generated classes afterwards, so regenerating breaks everything. It got never removed from the tree, but is currently not used by anything.

(Side note: But do not add a pull request removing the UI files. I’ll clean that mess up by re-using them and dropping the pykdeuic4 generated python files, here: https://github.com/luziferius/autokey/tree/qt4_ui_cleanup)
