### ISSUE TITLE
PPA is not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by cbrchrt** [autokey/autokey#136]
## Classification:

Installation

## Reproducibility:

Always

## Summary

Cannot add ppa to Ubuntu 18.04 LTS

## Steps to Reproduce

sudo add-apt-repository ppa:troxor/autokey

## Expected Results

Not fail

## Actual Results

E: The repository 'http://ppa.launchpad.net/troxor/autokey/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
If helpful, submit screenshots of the issue to help debug. `autokey-gtk --verbose` output is also useful.

## Version

Latest

Installed via: PPA

Distro: Ubuntu 18.04

## Notes

none

**Comment by josephj11** [comment]
Last I saw, the only working PPA is for 16.04. WE need someone with the time and expertise to add other PPA versions.

**Comment by sporkwitch** [comment]
Looking into this; only just started messing with repackaging things to fix bugs / dep issues locally.  Can confirm #140 builds fine for me locally on kubuntu 18.04 (sans qt support, though the -gtk works fine in KDE), but still need to figure out how to properly update things so I can submit it for use in the PPA.

**Comment by troxor** [comment]
0.94.1 package pushed to my PPA, hopefully it doesn't break 16.04... Give it a shot!

**Comment by sporkwitch** [comment]
`Err:28 http://ppa.launchpad.net/troxor/autokey/ubuntu bionic Release`
`404  Not Found [IP: 91.189.95.83 80]`

Still no 18.04 release file

**Comment by troxor** [comment]
this PPA has become more effort than it's worth. If anyone wants to set one up, or suggest autokey for inclusion in Ubuntu, then go for it.

**Comment by sporkwitch** [comment]
Working it, just trying to resolve build deps right now; the launchpad build env isn't passing the gi.require_version('Gtk', '3.0') part, gotta figure out what it's missing to be able to get it.

https://launchpadlibrarian.net/370080042/buildlog_ubuntu-bionic-amd64.autokey_0.94.1-0ubuntu3_BUILDING.txt.gz

(did have to nuke the debian/changelog and start fresh so it would let me start a new ppa)

**Comment by josephj11** [comment]
Great. I get a lot of installation questions on the list. It will be much
easier just to tell them to use the PPA again. When you get it to work, I'd
appreciate it if you would take a look at the wiki
<https://github.com/autokey/autokey/wiki/Installing> and either improve it
or tell me what to fix to make it more accurate.

**Comment by sporkwitch** [comment]
Will do; I think i'm almost there.  Comparing against the official repo's package, it looks like they just yanked the require_version call out so it doesn't fail in the build env.  Trying it here, now it's just crying about upstream changes lol

**Comment by sporkwitch** [comment]
@josephj11 @troxor Published and seems to be working:
https://launchpad.net/~sporkwitch/+archive/ubuntu/autokey

@cbruchert feel free to give it a shot, let me know if you have any issues with it

**Comment by cbrchrt** [comment]
@sporkwitch it worked for me. Thanks!

**Comment by rtizzy** [comment]
@sporkwitch Would you mind repackaging the 16.04 version in there as well? The previous maintainer removed the Xenial version :/

**Comment by sporkwitch** [comment]
@rtizzy I'll look into it; I'm not an expert on package maintenance by any stretch, so I'll have to figure out what I need to do different to publish for multiple versions.  For me it was mostly a matter of convenience, since I typically run latest LTS, so if I'm going to build it anyway I may as well push it out for others as well.

In the meantime, you can pull the source yourself and use `dpkg-buildpackage -b` to create a deb file locally that you can install with `dpkg -i`.  The ppa/bionic branch on my fork of the repo is up to date as of today and published to the PPA, you may be able to simply swap out deps as needed, if the current ones aren't in the 16.04 repos.  Can't promise stability though; I just maintain the 18.04 PPA, I've not found the time to really knuckle down and dig through the main code to see if it necessarily needs these latest versions we're using or if it'll still behave with older deps.

**Comment by rtizzy** [comment]
Thanks for the tip @sporkwitch.

Is the code for managing this PPA on github? I imagine you're using a build system such as travis or Jenkins that then pushes to some sort of repository.

If you'll send that my way I will review and see about making a pull for it. 

I work with CI/CD recently but would like to learn about some package management.

**Comment by luziferius** [comment]
@rtizzy The configuration/management files used to build debian packages reside in the [`debian`](https://github.com/autokey/autokey/tree/master/debian) directory in the source tree. The Updates applied to it for PPA builds are [here](https://github.com/autokey/autokey/tree/master/debian).
As far as I know, the whole process is not automated at the moment.
