### ISSUE TITLE
Main Window doesn't remember open folders

### ISSUE THREAD

**Issue by cbrchrt** [autokey/autokey#137]
## Classification:

UI/Usability

## Reproducibility:

Always

## Summary

When opening the main window I have to 

## Steps to Reproduce

Select 'Show Main Window' on the Autokey icon in the desktop panel bar.

## Expected Results

Main window should open with the folders open from the previous time.

## Actual Results

All folders are closed.

## Version

0.90.4

Installed via: PPA

Distro: Ubuntu 17.10

## Notes

none

**Comment by josephj11** [comment]
Version 0.90.4 is no longer under development. If you can reproduce this in 0.94.0, You can reopen this issue. It seems like a reasonable fix or enhancement to me if it doesn't already work (but I'm not one of the developers.)
