### ISSUE TITLE
Autokey 0.94.1 "Automatically start AutoKey at login" not working.

### ISSUE THREAD

**Issue by BiNh0X** [autokey/autokey#149]
**System**
Ubuntu MATE 18.04 LTS

Autokey 0.94.1 "Automatically start AutoKey at login" not working.

"Automatically start AutoKey at login" checkbox not save state on clicking in "OK" button.
![captura de tela em 2018-05-22 13-54-27](https://user-images.githubusercontent.com/39527989/40377778-24b9ddf2-5dc8-11e8-8616-d0f99b4da60f.png)

**Comment by sporkwitch** [comment]
CNR
Kubuntu 18.04 LTS
Autokey 0.94.1-0ubuntu3

Try uninstalling and reinstalling.  Also verify ~/.config/autokey and its contents are writeable

**Comment by BiNh0X** [comment]
It does not work and ~/.config/autokey is writable. All configuration options save, except for automatic login initialization.

**Comment by sporkwitch** [comment]
PPA or built it yourself?

**Comment by BiNh0X** [comment]
PPA.

**Comment by sporkwitch** [comment]
I'll try to spin up a VM later and see if i can reproduce.

**Comment by BiNh0X** [comment]
Dear,

After I installed XDM and this one goes to automatic startup, AutoKey has now accepted to save the state "Automatically start AutoKey at login" checkbox. What is it? 
EDIT.: This is a new system installation.

![1](https://user-images.githubusercontent.com/39527989/40404111-7121a166-5e2c-11e8-8138-a597010b27c9.png)
![2](https://user-images.githubusercontent.com/39527989/40404112-7145a084-5e2c-11e8-8476-160acd4e05ad.png)

**Comment by AdamPS** [comment]
I have the same problem on Ubuntu 18.04 (vanilla - not mate or kubuntu).

autokey-gtk 0.95.1

Is there any more information that we can provide to help?  Thanks

**Comment by luziferius** [comment]
Try to create the `~/.config/autostart` folder. I suspect that it is missing on your system.
This directory is used by the desktop environment. During startup, it reads all `.desktop` files in there and executes them.

The current implementation does not check if the directory exists and then even completely silences the error messages to make sure you don’t know why it fails… :1st_place_medal: :-1: 

Here, it checks if the file exists, and if not, creates it. This fails, if the parent directory is missing.
https://github.com/autokey/autokey/blob/abf33455a2d2c6ae2ae848c6621f19564392340f/lib/autokey/gtkui/settingsdialog.py#L105-L116

Fixing this should be pretty easy and will (probably) go into 0.95.3.

**Comment by AdamPS** [comment]
Great, thanks @luziferius, creating that directory fixed it.

This also explains @BiNh0X situation where installing XDM fixed it - presumably that app created the autostart directory.

**Comment by luziferius** [comment]
I’ve rewritten the autostart handling. Fixed it in https://github.com/autokey/autokey/commit/0420250f7232d0a181ec20d271910b3e00216892 and added a user data migration task in https://github.com/autokey/autokey/commit/4334f8da174115e25b7845f77df70947ae46023d

**Comment by AdamPS** [comment]
Great thanks, Adam
