### ISSUE TITLE
Pass user input to script

### ISSUE THREAD

**Issue by syko** [autokey/autokey#172]
## Classification:

Enhancement

## Summary

It would be nice to get access to what triggered the script from within it. This would enable us to create much more advanced scripts that produce different output depending on the trigger.

Is this doable and something you might consider? (might give it a go myself)

## Steps to Reproduce (if applicable)

- Setup multiple abbreviations to trigger the same script: `foo_bar, bar_foo, foo_foo`
- Type abbreviation `foo_bar`
- use script to access user input, eg. `keyboard.send_keys(user_input.replace('_', '-')`)

## Expected Results

- `foo-bar` appears

## Version

AutoKey version: 0.95.1

Used GUI (Gtk, Qt, or both): Gtk

Installed via: PPA.

Distro: Ubuntu 18.04

EDIT: changed from 'matched abbeviation' to 'user input' as that would be more useful and enable scripts to leverage other Autokey functionality like ignoring case.

**Comment by luziferius** [comment]
This looks like a good idea. And it gives the "assign multiple abbreviations" feature a good purpose other than just "nice to have" redundancy.

I looked around and it should be quite easy to implement in just a couple of lines. If you wish to contribute, you can do a pull request. ;)

This is the script executing function in the `ScriptRunner` class:
https://github.com/autokey/autokey/blob/abf33455a2d2c6ae2ae848c6621f19564392340f/lib/autokey/service.py#L455-L471
That `buffer` parameter contains the abbreviation text including trigger characters when triggered by an abbreviation or an empty string if triggered by a menu, a hotkey or the "Run script" button. So in case of being triggered by an abbreviation, in your example it would include e.g. `foo_bar<your_trigger_character>`.

The `process_buffer` function extracts the trigger characters and returns them in `stringAfter` variable, which can be used to strip the trigger off.

The [`Engine`](https://github.com/autokey/autokey/blob/abf33455a2d2c6ae2ae848c6621f19564392340f/lib/autokey/scripting.py#L1123) class already contains functions for script argument and return value passing (used with phrase macros). You can extend this class with another getter function for the abbreviation.
And set the value before the script is executed:
https://github.com/autokey/autokey/blob/abf33455a2d2c6ae2ae848c6621f19564392340f/lib/autokey/service.py#L464-L465
The Engine class instance can be retrieved from the `scope` variable.

Remember to add the new function to [`api.txt`](https://github.com/autokey/autokey/blob/master/lib/autokey/qtui/data/api.txt) to add it to the autocomplete suggestions in the Qt GUI.
And add """doc strings""" to the new API function that will be displayed in the [API documentation](https://autokey.github.io/), (when the online version gets updated…)

**Comment by syko** [comment]
Cool!
Thanks for the pointers. I'll try and take a look during the weekend :+1:

**Comment by syko** [comment]
Sry, I was gonna get to it eventually but had some computer troubles and now I'm no longer on linux :/

**Comment by luziferius** [comment]
No problem. :)
Then I’ll implement it for the next version (or so).

**Comment by luziferius** [comment]
Implemented in https://github.com/autokey/autokey/commit/f1727cf41caf75306a9cc603d2cbb7f845734367.
The API call both returns the used abbreviation and the trigger character, if any.

This will be part of the next version.
