### ISSUE TITLE
resources folder does not exist

### ISSUE THREAD

**Issue by CIT-DarrellTang** [autokey/autokey#176]
## Classification:

Bug

## Reproducibility:

Always

## Summary

Per Thomas Hess, opening an issue for the following error message:

`FileNotFoundError: UI file not found: /usr/local/lib/python3.6/site-packages/autokey-0.95.2-py3.6.egg/autokey/qtui/resources/ui/settingsdialog.ui`

## Steps to Reproduce (if applicable)
Running Fedora KDE Spin
Download https://github.com/autokey/autokey/archive/v0.95.2.zip
`python3 setup.py install`
`sudo dnf install python3-dbus`
`pip3 install pyinotify`
`sudo dnf install python3-xlib`
`sudo dnf install python3-qt5`
`autokey-qt`

## Expected Results

Autokey should start.

## Actual Results

```
/usr/local/lib/python3.6/site-packages/autokey-0.95.2-py3.6.egg/autokey/qtui/common.py:38: UserWarning: Compiled Qt resources file not found. If autokey is launched directly from the source directory, this is expected and harmless. If not, this indicates a failure in the resource compilation.
  warnings.warn(warn_msg)
Traceback (most recent call last):
  File "/usr/local/bin/autokey-qt", line 11, in <module>
    load_entry_point('autokey==0.95.2', 'console_scripts', 'autokey-qt')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/autokey-0.95.2-py3.6.egg/autokey/qtui/__main__.py", line 23, in <module>
    from autokey.qtapp import Application
  File "/usr/local/lib/python3.6/site-packages/autokey-0.95.2-py3.6.egg/autokey/qtapp.py", line 41, in <module>
    from autokey.qtui.configwindow import ConfigWindow
  File "/usr/local/lib/python3.6/site-packages/autokey-0.95.2-py3.6.egg/autokey/qtui/configwindow.py", line 31, in <module>
    from .settings import SettingsDialog
  File "/usr/local/lib/python3.6/site-packages/autokey-0.95.2-py3.6.egg/autokey/qtui/settings/__init__.py", line 21, in <module>
    from .settingsdialog import SettingsDialog
  File "/usr/local/lib/python3.6/site-packages/autokey-0.95.2-py3.6.egg/autokey/qtui/settings/settingsdialog.py", line 31, in <module>
    class SettingsDialog(*common.inherits_from_ui_file_with_name("settingsdialog")):
  File "/usr/local/lib/python3.6/site-packages/autokey-0.95.2-py3.6.egg/autokey/qtui/common.py", line 137, in load_ui_from_file
    ui_file = _get_ui_qfile(name)
  File "/usr/local/lib/python3.6/site-packages/autokey-0.95.2-py3.6.egg/autokey/qtui/common.py", line 126, in _get_ui_qfile
    raise FileNotFoundError("UI file not found: " + file_path)
FileNotFoundError: UI file not found: /usr/local/lib/python3.6/site-packages/autokey-0.95.2-py3.6.egg/autokey/qtui/resources/ui/settingsdialog.ui
```

## Version

AutoKey version: v0.95.2

Used GUI (Gtk, Qt, or both): Qt

If the problem is known to be present in more than one version, please list all of those.

Installed via: (PPA, pip3, …). python script install

Distro: Fedora

**Comment by CIT-DarrellTang** [comment]
Had to run `sudo dnf install -y python3-qscintilla-qt5` before Autokey window would open but phrases not executing.

`autokey-qt` now produces:

```
/usr/local/lib/python3.6/site-packages/autokey-0.95.2-py3.6.egg/autokey/qtui/common.py:38: UserWarning: Compiled Qt resources file not found. If autokey is launched directly from the source directory, this is expected and harmless. If not, this indicates a failure in the resource compilation.
  warnings.warn(warn_msg)
qt.svg: Cannot open file '/usr/local/lib/python3.6/site-packages/config/autokey-status.svg', because: No such file or directory
qt.svg: Cannot open file '/usr/local/lib/python3.6/site-packages/config/autokey-status.svg', because: No such file or directory
qt.svg: Cannot open file '/usr/local/lib/python3.6/site-packages/config/autokey-status.svg', because: No such file or directory
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 590, sequence_number = 1767, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 590, sequence_number = 1768, major_opcode = 33, minor_opcode = 0
```

**Comment by luziferius** [comment]
Would you mind trying out the current git head? (You can get a ZIP archive from here: https://github.com/autokey/autokey/archive/master.zip)

I tweaked the packaging and installation process, so the installation should (hopefully) work now.
This commit https://github.com/autokey/autokey/commit/6d56337f789c7ca3e94cfcadc1596cbe34cdf4d4 should cause the icons to be included and  https://github.com/autokey/autokey/commit/b8518cfb2ce374a6dfd0c74226a74c42f593442d fixes the icon search paths.

Before installing, please uninstall the current installation using `pip3 uninstall autokey` and verify there are no leftovers from the previous fiddling.

If `FileNotFoundError: UI file not found: /usr/local/lib/python3.6/site-packages/autokey-0.95.2-py3.6.egg/autokey/qtui/resources/ui/settingsdialog.ui` comes up again, please also include the output of `python3 setup.py install`. This error is an installation issue, where the used `setuptools` library doesn’t copy things even if told to do so.

**Comment by CIT-DarrellTang** [comment]
that seems to be working! Thank you so much! I am getting this output when I run it from a terminal:
```
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 590, sequence_number = 1925, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 590, sequence_number = 1926, major_opcode = 33, minor_opcode = 0
```

Is that something to be concerned about? Also, how do I create a desktop icon/menu item for this? Or is that outside the scope of what you can help with? 

Thanks again! i was getting tired of typing everything out!

Darrell

**Comment by josephj11** [comment]
Since you're using KDE, setting up a desktop icon should be easy.
(lots of steps, but easy ;)  )
The following is how I would do it. You can change all the locations and names of things to your liking.

First, open a terminal and do

    locate -b autokey.png

If you find it, save the path in your clipboard or write it down for later
If you don't find it, it's not necessary, but I can email it to you later.
Close or minimize the terminal
 
In your panel, there's an application launcher icon. Right click on it and select Edit Applications
Click on Utilities
In the top menu, click on New Item
Name it AutoKey and select OK
Fill in the panel to the right
Name: AutoKey (KDE)
Description: Keyboard Automation
Comment: whatever you want
Command autokey-qt

Select Enable Launch Feedback

Click Save in the upper left corner of the screen
There's a box for an icon to the right of where you filled in Name: , Click on it
That will bring up Icon selection
Select Other Icons and click Browse.
Enter the location you saved for the Icon in the first step
If you didn't find it, then select any icon you like or leave it blank
Save it again
Close the menu editor

Now it's in your launcher.

Right click on your desktop and make sure widgets are unlocked
The context menu will say "Lock Widgets" if they are already unlocked.
Left click on the Application Launcher button in your panel
Find the new entry for AutoKey that you just created
Left click and drag the entry onto your desktop, panel, or quick launcher widget
Right click on your desktop and lock your widgets again
Done!

You can add icons for any program this way.

**Comment by luziferius** [comment]
Hmmm. setup.py is supposed to place a launcher into the menu. Here, it ships the .desktop files for both GUIs: https://github.com/autokey/autokey/blob/c7b06f94536c91ebd4a530104be7e7ad3bd8a9f8/setup.py#L154-L156
They should reside inside `/usr/local/share/applications` for manual installations (and  `/usr/share/applications` when installed through a package manager). At least that is what setup.py is told to do. KDE is supposed to find those and automatically place them inside your menus.
If it does not pick them up, place `autokey-qt.desktop` into `~/.local/share/applications`. This directory _is_ picked up by KDE.

**Comment by CIT-DarrellTang** [comment]
done! Thank you so much! I think it's all working as expected. I do have a strange thing with a created phrase that pastes the wrong first character. Changes from a 'C' to a 'É` which makes my password fail. should i go back to the user forums for that?

**Comment by josephj11** [comment]
Great you got it working. What did you do exactly? I'm trying to document this stuff for our wiki.

The last is definitely a separate issue. We've seen it a lot, but how it got/gets fixed - I'm not sure.
I'd probably go back to Gitter for this.

**Comment by luziferius** [comment]
A fix for the originally reported issue is in 0.95.3.
I’m not quite happy with the fix, but it will do for now.
