### ISSUE TITLE
Support for high unicode (multi-linqual) characters

### ISSUE THREAD

**Issue by Script-Nomad** [autokey/autokey#183]
## Classification:
Feature (New) ( Similar to #128 )

## Summary
So, hear me out, but I came across autokey while searching for a way to quickly produce emoticons.
... yes ... shallow I know...
But it gave me an idea for a feature which does not appear to be present, and that is support for unicode characters that exist in other alphabets. Alphabets like katakana, sanskrit, chinese alphabet, cyrillics, and so on do not appear to currently be supported in this program.

My personal reasons aside, I feel this would be a worthwhile feature to implement in order to encourage international use. Presently, when unsupported characters are encountered they are simply omitted, which is fine, but if the target audience for autokey should expand across boarders, support for additional unicode characters should be included.

## Expected Results

- Unicode & Multi-byte unicode characters should be accepted as input/output

## Version

AutoKey version: 0.90.4

Used GUI (Gtk, Qt, or both): GTK

If the problem is known to be present in more than one version, please list all of those.

Installed via: Ubuntu PPA (Software Center)

Distro: Ubuntu 18.04

**Comment by luziferius** [comment]
Thank you for reminding us that the whole input and typing code has to be re-written ;-)

You should be able to output unicode characters by using the clipboard pasting mode.
So put your emoticons into phrases and set the pasting mode to clipboard. If you assign a hotkey to the parent folder, you get a nice menu with all defined phrases as choices.

But you should update to the latest version. 0.90.4 is 6 years old and crashes when using the clipboard. It may completely lock your keyboard until you kill the process.

**Comment by Script-Nomad** [comment]
Daaaaang, 6 years? Ubuntu's software center needs to get with the times o_O

I will update off the master branch and try this out. Thanks for the tip.
