### ISSUE TITLE
How to implement scripts running continuously (and working with selections)?

### ISSUE THREAD

**Issue by lpirl** [autokey/autokey#185]
Dear all. Thanks a lot for this mighty tool.

I want to try to implement a few IDE-like keyboard actions using scripts. E.g., automatically closing brackets, esp. enclosing the current selection in brackets when hitting '('. (Same goes for other kinds of brackets and ticks but that is not really relevant here).

As far as I understand:
I cannot use abbreviations since the trigger character would replace the selection.
Hence, I need to use a script.
The script would have to run continuously.
So would setting "Trigger immediately" and then use an infinitive loop inside the script be the correct (and most efficient) way of implementing this?
It feels a bit like a hack since I'd expect there are ways to have scripts running constantly.

What are your thoughts on this?

## Version

AutoKey version: 0.90.4
Used GUI (Gtk, Qt, or both): Gtk
Installed via: apt
Distro: Debian

**Comment by luziferius** [comment]
You want to enclose selected text in brackets, when hitting `(`. This means an abbreviation can’t be used, as you pointed out. But your conclusion is a bit off. You can implement this by using hotkeys instead.

If you assign a hotkey to a script, phrase or folder, autokey will _grab_ that key completely. So assigning `(` as a hotkey to a script and then pressing it won’t insert any `(` and instead call your script.

So your Script can contain the following to enclose selected text with brackets:
```
selected_text = clipboard.get_selection()
keyboard.send_keys("({})".format(selected_text))
# Alternatively, if you have Python 3.6:
# keyboard.send_keys(f"({selected_text})")
```
Or, if you prefer one-liners: `keyboard.send_keys(f"({clipboard.get_selection()})")` (Use .format() if on Python 3.5)
As another alternative, if you don’t want to delete the text and re-type it in autokey (for whatever reason): Determine the length of the selected text and navigate the editor window with arrow keys to only insert the brackets.

**Comment by lpirl** [comment]
Awesome, thanks @luziferius.
In order not having to implement a script per "auto close character combination" (`(`, `'`, `"`, …) – can I access the triggering key in the script as well?

**Comment by luziferius** [comment]
Unfortunately, that’s currently not possible. Even if it were possible (#172), you currently can’t assign more than one hotkey to a script.
If you wish to not duplicate code, you can look here for an example how to centralize logic in a single script and having multiple trigger scripts to work around that limitation: https://github.com/luziferius/autokey_scripts/tree/master/NumpadIME

**Comment by lpirl** [comment]
Thanks again @luziferius for the quick reply.
