### ISSUE TITLE
autokey can not use in archlinux(manjaro)

### ISSUE THREAD

**Issue by improve100** [autokey/autokey#199]
## Classification:
Bug
## Reproducibility:
Always
## Summary
autokey can not use in archlinux(manjaro)
## Steps to Reproduce (if applicable)

1. sudo pacman -S autokey 
$ sudo pacman -S autokey
error: target not found: autokey

2.use yaourt
$ yaourt autokey
1 aur/autokey-py3 0.95.3-2 (38) (0.34)
    Python 3 port of AutoKey, a desktop automation utility for Linux and X11   
    with new features.
==> Enter n° of packages to be installed (e.g., 1 2 3 or 1-3)                  
==> ---------------------------------------------------------                  
==> 1
==> Downloading autokey-py3 PKGBUILD from AUR...                               
x .SRCINFO
x PKGBUILD
x requires.patch
DaveB commented on 2018-08-08 06:42                                            
D1ceWard commented on 2018-08-08 08:22                                         
zerophase commented on 2018-08-08 14:43                                        
dark-saber commented on 2018-08-08 15:05                                       
dark-saber commented on 2018-08-08 15:29                                       
autokey-py3 0.95.3-2  (2018-08-21 20:49)
( Unsupported package: Potentially dangerous ! )                               
==> Edit PKGBUILD ? [Y/n] ("A" to abort) 

3.use pip install
$ pip3 install autokey
Collecting autokey
  Using cached https://files.pythonhosted.org/packages/05/c1/26dc115e66d846beb602cda383060092fe71933499e41f10e9558da06ddc/autokey-0.93.10-py3-none-any.whl
Collecting pyinotify (from autokey)
  Using cached https://files.pythonhosted.org/packages/e3/c0/fd5b18dde17c1249658521f69598f3252f11d9d7a980c5be8619970646e1/pyinotify-0.9.6.tar.gz     
Collecting dbus-python (from autokey)
  Using cached https://files.pythonhosted.org/packages/3f/e7/4edb582d1ffd5ac3c84188deea32e960b5c8c0fe1da56ce70224f85ce542/dbus-python-1.2.8.tar.gz   
Requirement already satisfied: python3-xlib in /usr/lib/python3.7/site-packages (from autokey) (0.15)                                                
Installing collected packages: pyinotify, dbus-python, autokey
  Running setup.py install for pyinotify ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-xepkcw6o/pyinotify/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-l9h9j34k/install-record.txt --single-version-externally-managed --compile:                                                                         
    running install
    running build
    running build_py
    creating build
    creating build/lib
    copying python3/pyinotify.py -> build/lib
    running install_lib
    copying build/lib/pyinotify.py -> /usr/lib/python3.7/site-packages
    error: could not create '/usr/lib/python3.7/site-packages/pyinotify.py': Permission denied                                                       

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-xepkcw6o/pyinotify/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-l9h9j34k/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-xepkcw6o/pyinotify/

**Comment by luziferius** [comment]
Autokey is in the Arch AUR repository only. In your second try, you got the right package.
This line(`( Unsupported package: Potentially dangerous ! )`) is a safety measure to notify users about the package source and is caused by trying to install something from the AUR.

The AUR is unchecked by the main Arch maintainers, so all Packages there are automatically flagged as potentially dangerous.

The pip3 install:
`error: could not create '/usr/lib/python3.7/site-packages/pyinotify.py': Permission denied`
You have run the pip3 install as root to be able to write there. Or install as a user using the `--user` switch.

**Comment by improve100** [comment]
step2:  yaourt autokey
ython-37.pyc exists in filesystem
python-xlib: /usr/lib/python3.7/site-packages/Xlib/xobject/__pycache__/drawable.cpython-37.pyc exists in filesystem
python-xlib: /usr/lib/python3.7/site-packages/Xlib/xobject/__pycache__/fontable.cpython-37.pyc exists in filesystem
python-xlib: /usr/lib/python3.7/site-packages/Xlib/xobject/__pycache__/icccm.cpython-37.pyc exists in filesystem
python-xlib: /usr/lib/python3.7/site-packages/Xlib/xobject/__pycache__/resource.cpython-37.pyc exists in filesystem
python-xlib: /usr/lib/python3.7/site-packages/Xlib/xobject/colormap.py exists in filesystem
python-xlib: /usr/lib/python3.7/site-packages/Xlib/xobject/cursor.py exists in filesystem
python-xlib: /usr/lib/python3.7/site-packages/Xlib/xobject/drawable.py exists in filesystem
python-xlib: /usr/lib/python3.7/site-packages/Xlib/xobject/fontable.py exists in filesystem
python-xlib: /usr/lib/python3.7/site-packages/Xlib/xobject/icccm.py exists in filesystem
python-xlib: /usr/lib/python3.7/site-packages/Xlib/xobject/resource.py exists in filesystem
Errors occurred, no packages were upgraded.
==> Restart building autokey-py3 ? [y/N]
==> ------------------------------------
==> N

**Comment by ddysher** [comment]
I've installed autokey on arch today and it works fine.  The problem with ur installation is mostly likely due to conflict package.

**Comment by muhlinux** [comment]
It works flawlessly in Manjaro installed with pamac for me.

**Comment by x3a** [comment]
@improve100 It looks like you've installed _python-xlib_ via `pip` instead of using your package manager. Reinstalling it properly should fix this.

@luziferius Giving the advice to invoke `pip3` is bad in this case, as it potentially leads to conflicts with the package manager.

**Comment by kreezxil** [comment]
I recommend someone close this issue, it is clearly an issue of a scared user who doesn't understand what the messages mean. And also a user doesn't know when to use SUDO or ROOT (root bad).
