### ISSUE TITLE
Update PyPi to latest version

### ISSUE THREAD

**Issue by y2kbadbug** [autokey/autokey#203]
## Classification:

Enhancement?

## Reproducibility:

Always

## Summary

PyPi is currently at 0.93.10 which is severely outdated.

## Steps to Reproduce (if applicable)

pip3 (or pip-3.x in FreeBSD) install autokey

## Expected Results

Latest version 0.95.4 should install

## Actual Results

Outdated version installs.

## Notes

I am currently porting autokey to FreeBSD and need this updated as using GitHub for PyPi installs is not recommended.  Until it's updated I will resort to using GitHub, but would love to update it later.

Thanks!

**Comment by troxor** [comment]
Updated to 0.95.4 in PyPI, and Packaging wiki page updated with how to do so if anyone wants to share ownership over that Package. https://github.com/autokey/autokey/wiki/Packaging
