### ISSUE TITLE
Is there a command to display the main window when running?

### ISSUE THREAD

**Issue by danielrosehill** [autokey/autokey#205]
Is there a command to display the main window when running?

**Comment by luziferius** [comment]
You can use the global hotkey, as defined in the settings to show the window. (It defaults to `<super>+k`).

If it has to be a command/executable you want to call, you can just try to start another instance (`autokey-qt` or `autokey-gtk` does not matter).
The new instance checks if another one is running. If so, it pings the running instance to show its main window (using a dbus call) and then exits.
That is the canonical way.

If you wish, you can emit that dbus call directly, e.g. by using `dbus-send`. The interface name is `org.autokey.Service` and the method name is `show_configure`. You can use `qdbusviewer` to explore what is available.

This command uses the dbus directly to open the main window of a running AutoKey instance:
```
dbus-send --session --type=method_call --dest="org.autokey.Service" "/AppService" "org.autokey.Service.show_configure"
```
You can use the dbus interface to run autokey scripts or paste phrases or show autokey folder pop-ups

**Comment by luziferius** [comment]
I've put my writeup from above into the FAQ, together with some other things. So this is documented.

https://github.com/autokey/autokey/wiki/FAQ
