### ISSUE TITLE
autokey-gtk --verbose on SSH term gets core dump?

### ISSUE THREAD

**Issue by LorenAmelang** [autokey/autokey#209]
## Classification:

Bug

## Reproducibility:

Always

## Summary

If I enter "autokey-gtk --verbose" on an SSH terminal I get a core dump error.

## Steps to Reproduce (if applicable)

No special tweaks like #175, just type the command. 

## Expected Results

I guess there really is not a GUI window available via SSH, but getting a core dump seems a bit extreme. As a newbie, I thought maybe I could watch the verbose log via SSH, and the GUI part could go on the regular screen...  

## Actual Results

See file. Even on the local console, it gets 'Xlib.error.BadWindow' errors...
`
## Version

AutoKey version: 0.95.3

Used GUI (Gtk, Qt, or both): either

If the problem is known to be present in more than one version, please list all of those.

Installed via: (PPA, pip3, …). AUR

Distro: Antergos 18

## Notes

If you've found a workaround, please provide it here.

Just don't do this! Once you know...  

[gazp9 AutoKey log.txt](https://github.com/autokey/autokey/files/2551253/gazp9.AutoKey.log.txt)

**Comment by josephj11** [comment]
This seems pretty bizarre. Why would you expect AutoKey to work over `ssh` when `ssh` does not even support a GUI at all? Is AutoKey even running on the target machine? You'd need a remote X session to  have a remote GUI at all (which I don't think you really need or want for what you're trying to accomplish).

I think it's quite reasonable for AutoKey to crash if it can't even find X. It's like trying to drive your car with all its safety features under a lake. It just isn't designed to do that.

**Comment by luziferius** [comment]
Sounds like a reasonable reason to launch it over ssh.
I tried it using `autokey-qt` and it quits gracefully.
```
$ autokey-qt 
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.
```
The crash you get comes from inside `gi`, which belongs to the GTK/GDK bindings. That’s nothing we can do about. (Other than testing the executability in the environment ourselves.)
You have to either use X forwarding, then the GUI runs locally, or you have to specify the target display by setting the `DISPLAY` variable to point to your remotely running desktop session.

**Comment by LorenAmelang** [comment]
@luziferius

Thanks for tolerating a total newbie!  You're right, the Qt version quits gracefully. (And is much nicer on screen.) At the time I couldn't use it - "You need to install qscintilla separately. If PyQt is already installed, then you should just have to install the qscintilla python bindings." Bindings fixed it. 

I'd love to use X forwarding, but that is proving even harder to set up. So I'd still like to watch the verbose log over SSH...  No way to set DISPLAY in my remote client. Can I default it somewhere on the target Linux, without opening another can of worms? Where?

**Comment by luziferius** [comment]
@LorenAmelang 
Normally, you’d just need to run `DISPLAY=<somevalue> autokey-qt` where `<somevalue>` should be replaced by an identifier for your _remotely_ running X session. Normally, it is `:0.0`, so it might work by just running `DISPLAY=:0.0 autokey-qt --verbose`. The GUI should then be connected to your remote X server and output the log over ssh.
### X forwarding
Just use `ssh -X` when connecting to enable it. ssh takes care of the rest to get remote applications to render locally. Note that this is generally slow and might not be what you want based on your initial description.

**Comment by LorenAmelang** [comment]
@luziferius
$ DISPLAY=:0.0 autokey-qt --verbose worked perfectly from the SSH terminal - Thanks! 

```
2018-11-08 21:08:08,636 DEBUG - service - Raw key: 'h', modifiers: [<Key.SHIFT: '<shift>'>, <Key.SUPER: <super>'>], Key: H
2018-11-08 21:08:08,636 DEBUG - service - Window visible title: 'Desktop', Window class: 'nemo-desktop.Nemo-desktop'
2018-11-08 21:08:08,638 INFO - service - Matched hotkey phrase/script with prompt=False
2018-11-08 21:08:08,641 DEBUG - service - Script runner executing: Script('TD40')
2018-11-08 21:08:08,642 ERROR - service - Ignored locking error in handle_keypress
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/autokey/service.py", line 207, in __tryReleaseLock
    self.configManager.lock.release()
RuntimeError: release unlocked lock
[sudo] password for loren: 2018-11-08 21:08:08,948 DEBUG - iomediator - Key.SHIFT released
2018-11-08 21:08:08,968 DEBUG - iomediator - Key.SUPER released
--> typed sudo password in verbose log terminal...  
sudo: /home/loren/rfcommbind: command not found
````
I finally noticed my utterly stupid error there...  The command needs to be:
subprocess.run(['sudo', '/home/loren/rfcommbind.sh'])
but somehow I'd entered 
subprocess.run(['sudo', '/home/loren/rfcommbind'])
in the AutoKey window! 

With the proper command, it works! 

I had a nasty problem with the gtk window going crazy with adding or deleting characters when using it via VNC. For no apparent reason it would insert or delete a hundred or more at full repeat speed. (It also shreds the screen image diagonally over and over, I've given up on it.) But that means I have to walk across the room to the actual AutoKey machine - guess I forgot a couple of letters. 

(I know this seems strange, but my vision is so bad it is worth using SSH and remote desktop from this beautiful Surface Book screen. The actual AutoKey notebook screen will do for remote testing, but is painful for long debugging sessions.) 

As for "Just use ssh -X when connecting", I'm using Windows 10 and Bitvise SSH as my client. I don't believe there is any place for the "-X". This seems a bit like my problem:
https://bhoom.wordpress.com/2017/02/11/bitvise-x11-forwarding-problem/

But he doesn't connect. I actually connect to 3389 and get a nice black window with controls in the middle of the top - there is just nothing else in it. Guess I need to try some other clients...

**Comment by LorenAmelang** [comment]
Well, using the proper command it works after I've typed my sudo password into the verbose debug terminal once. For a short time. Password apparently times out much sooner than when I'm directly using it. 

This struggle is now moved to [https://groups.google.com/forum/#!topic/autokey-users/gpQFjZHVGjk](https://groups.google.com/forum/#!topic/autokey-users/gpQFjZHVGjk)
