### ISSUE TITLE
Autokey 0.95.2 inserts the trigger key

### ISSUE THREAD

**Issue by dogweather** [autokey/autokey#210]
After upgrading from 0.90 I believe (via uprgading Fedora from 28 to 29), Autokey is now inserting the character portion of phrase triggers. The configuration worked fine before the upgrade.

I'm sorry, I don't have time to complete a detailed bug report now. I'm posting this to see if anyone else is experiencing this. Will return to edit this issue.

EDIT: It looks like this is a duplicate of https://github.com/autokey/autokey/issues/181 although I'm experiencing it with GTK. I'll try to upgrade to 0.95.4 and see if that resolves it.

**Comment by dogweather** [comment]
Yep, this is fixed in 0.95.4.

**Comment by josephj11** [comment]
If you have an issue that may be a bug, but you're not sure or need other assistance with diagnosing/documenting it, then the place to post is on [Gitter](https://gitter.im/autokey/autokey).

If you have a usage/scripting question (anything that's not a bug), then the place to start is on our support [list](https://groups.google.com/forum/#!forum/autokey-users).
