### ISSUE TITLE
Fatal error if user enters an invalid regex

### ISSUE THREAD

**Issue by dogweather** [autokey/autokey#212]
## Classification:

Crash / locks up

## Reproducibility:

Always

## Summary

We don't seem to do any validation on the user's input for regex matching. The app then doesn't gracefully handle a regex string which Python `re` doesn't parse.

## Steps to Reproduce (if applicable)

1. Enter a malformed regex for a phrase, like the single character, `*`.
2. Attempt to save this change.
3. Try to trigger the phrase.

## Expected Results

**Good:** The app shouldn't crash. 
**Better:** It should trap and output `re` errors somewhere. 
**Best:** the app should validate the user input by attempting an `re` compile when a user provides a regex. If it fails, then the regex won't be saved.

## Actual Results

The app progressively locks up, and the UI needs to be killed. The server then crashes.

## Version

AutoKey version: **0.95.4**

Used GUI (Gtk, Qt, or both): **Gtk** 

Distro: **Fedora**

## Notes

I think this would be a good first PR for me to work on.

**Comment by luziferius** [comment]
Go ahead if you wish ;)

**Comment by BlueDrink9** [comment]
@dogweather  did you get anywhere with this? If not, I'll take a look.

**Comment by luziferius** [comment]
I dug a bit: This function breaks, because it takes unprocessed user data and shoves it into re.compile() without checking for errors.
https://github.com/autokey/autokey/blob/13d3b1074b524ad7c15d8636f79672794aefac5e/lib/autokey/model.py#L287-L291

**Comment by dogweather** [comment]
@BlueDrink9 No, I haven't gotten started. I found it difficult to work on the code - I'm not sure which branch to work off of, and how to get the tests passing before I start.

**Comment by BlueDrink9** [comment]
I'll see what I can do

**Comment by BlueDrink9** [comment]
We recently added a CONTRIBUTORS.md that describes how to run the tests, but on my system there are currently a handful not passing anyway.

**Comment by dogweather** [comment]
That's good to hear. Another issue was that the branches on GitHub didn't have the latest coding; commits hadn't been pushed up, so I inadvertently duplicated some work. And so I stopped. Basically, the project doesn't seem to use GitHub for the latest code. That's a roadblock.

@luziferius  It looks like `develop` is two weeks old. Is it ready for someone to work off of?

I also believe it's very important for all tests on `master` or `develop` to be passing because I'll know if I break something. So before I (and people who code like I do) can contribute, the broken tests need to be commented out or fixed.

**Comment by luziferius** [comment]
@dogweather I didn’t work on new features, so develop is up to date. I do push commits when I’m done working on something. I was working alone on AK in the past, so I didn’t push new branches whenever I started working on something. I can start pushing unfinished work branches that took longer than one coding session to indicate work in progress.

**Comment by luziferius** [comment]
> […] but on my system there are currently a handful not passing anyway.

I opened #334 for this.

**Comment by dogweather** [comment]
@luziferius Awesome, thanks! I'll check out the PR

**Comment by luziferius** [comment]
Just released 0.95.10, which contains the fix for this issue.
