### ISSUE TITLE
Memory leaks in autokey-qt

### ISSUE THREAD

**Issue by copyme** [autokey/autokey#217]
## Classification:

Bug

## Reproducibility:

Hard to say

## Summary

autokey-qt has allocated around 28 GB of memory see 

![image](https://user-images.githubusercontent.com/456607/48559050-74dae680-e8f3-11e8-8170-4174f6ad6023.png)

## Version

AutoKey version: 0.95.4

Used GUI (Gtk, Qt, or both): Qt5 (5.9.4)

Installed via: home made RPMs

Distro: openSUSE Leap 15 Plasma 5

**Comment by luziferius** [comment]
Did you log out and log in again? Then this might be a duplicate of #198

**Comment by copyme** [comment]
@luziferius you are right it looks like a duplicated issue. Closing.
