### ISSUE TITLE
Setup.py fails. Please see the included terminal output

### ISSUE THREAD

**Issue by ineuw** [autokey/autokey#218]
I am using Linux Mint 19, 64bit which comes with Python 3.6 installed and I assume it is as good as the recommended Python 3.5. On trying to run setup.py, I got the following errors:

./setup.py: 18: ./setup.py: import: not found
./setup.py: 19: ./setup.py: import: not found
from: can't read /var/mail/collections
./setup.py: 21: ./setup.py: import: not found
from: can't read /var/mail/pathlib
./setup.py: 23: ./setup.py: import: not found
./setup.py: 24: ./setup.py: import: not found
./setup.py: 26: ./setup.py: try:: not found
from: can't read /var/mail/setuptools
./setup.py: 28: ./setup.py: except: not found
./setup.py: 29: ./setup.py: Syntax error: word unexpected (expecting ")")

**Comment by luziferius** [comment]
I looked at it, and the `setup.py` does not begin with `#!/usr/bin/env python3`, thus your shell does not know how to launch it. It tries to read it as a shell script and fails.

Just start it using `python3 setup.py install` or (the nowadays recommended way): `pip3 install .`

**Comment by ineuw** [comment]
Thanks for your speedy reply. Managed to wade through the pitfalls of assumptions, installed it, and it works fine. As a guide to the perplexed, I plan to update the documentation to include the various possible scenarios that can exist before a successful installation.

**Comment by luziferius** [comment]
I’ll re-open, because this is something that can be improved.
It is quite easy to enable setup.py to be called like you tried first.

**Comment by ineuw** [comment]
pip3 was missing, although many posts elsewhere indicated that it should have been included with Python 3. After numerous attempts, I did the following to fix the problem and it did the trick.

sudo apt install python3-pip
pip3 install setuptools
sudo python3 setup.py install

In addition, I uninstalled Python 2 version 0.90.4  just in case, because I noticed that both use the same data in /home/user/.config.

**Comment by ineuw** [comment]
Finally managed to install Python 3 Autokey which was accomplished by simply adding the the shebang ** #!/usr/bin/env python3 ** to the 1st line of he file and using the following commands.

sudo apt install python3-pip
pip3 install setuptools
sudo python3 setup.py install

Thanks again
