### ISSUE TITLE
autokey-qt installs but doesn't launch (KDE Neon)

### ISSUE THREAD

**Issue by dixhuit** [autokey/autokey#219]
## Classification:

Bug

## Reproducibility:

Always

## Summary

autokey-qt installs fine via apt but doesn't launch.

## Steps to Reproduce (if applicable)

- Perform the regular apt installation as per the README.
- Invoke Krunner, search for AutoKey and hit enter.
- Run `autokey-qt` from the command-line.

## Expected Results

AutoKey GUI should launch.

## Actual Results

Launching from Krunner seems to launch the App momentarily in the taskbar panel but immediately quits before the GUI or shortcut/notification icon appear.

Running `autokey-qt` from the command-line throws the following error:

```
Traceback (most recent call last):
  File "/usr/bin/autokey-qt", line 11, in <module>
    load_entry_point('autokey==0.95.1', 'console_scripts', 'autokey-qt')()
  File "/usr/lib/python3/dist-packages/autokey/qtapp.py", line 110, in __init__
    self._configure_root_logger()
  File "/usr/lib/python3/dist-packages/autokey/qtapp.py", line 169, in _configure_root_logger
    backupCount=common.MAX_LOG_COUNT
  File "/usr/lib/python3.6/logging/handlers.py", line 150, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.6/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/dan/.local/share/autokey/autokey.log'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_autokey-qt.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/autokey-qt", line 11, in <module>
    load_entry_point('autokey==0.95.1', 'console_scripts', 'autokey-qt')()
  File "/usr/lib/python3/dist-packages/autokey/qtapp.py", line 110, in __init__
    self._configure_root_logger()
  File "/usr/lib/python3/dist-packages/autokey/qtapp.py", line 169, in _configure_root_logger
    backupCount=common.MAX_LOG_COUNT
  File "/usr/lib/python3.6/logging/handlers.py", line 150, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.6/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/dan/.local/share/autokey/autokey.log'
```

## Version

AutoKey version: 0.95.1

Used GUI (Gtk, Qt, or both): Qt

Installed via: PPA

Distro: KDE Neon 5.14

## Notes

- I tried the GTK version and that works as expected.
- I notice that a bunch of QT stuff was fixed in 0.95.3 - if that's the solution, how do I install that from a package manger?
- I'm a bit of a Linux noob.

**Comment by josephj11** [comment]
Not sure if the following will fix things for you, but here are several thoughts:

There are very few differences between the GTK and QT versions and they both use the same autokey-common to do all the work, so, as long as you don't mind having the GTK libraries installed, there's no reason not to use the GTK version.

IIRC, KDE Neon is Ubuntu based and uses apt/dpkg for package management. If that's the case, you can install the latest version as follows:

Before doing the following, be sure to make a backup of your AutoKey data in case anything goes wrong. You can do that by copying the `$HOME/.config/autokey` directory to another location being sure that your backup also includes hidden files (each script and phrase has one). You can see them using `ls -a` in the subdirectories where they are stored.

````
Head over to

https://github.com/autokey/autokey/releases/tag/v0.95.4

and get the common package and either or both of the front ends (GTK or QT)
saving them to a local directory.

Change into that directory (cd dir-path)

Then install the using:

sudo dpkg --install autokey-common_0.95.4-0_all.deb
autokey-qt_0.95.4-0_all.deb
(the above should all be on one line)
````
This will get you the most current version.

Since this is just the package itself, it will not be upgraded by your package manager when newer versions are released, so you'll either have to do that manually or switch back to the repo version once it surpasses this version.

**Comment by josephj11** [comment]
Now that I bothered to read the traceback (which I should have done first!), the first thing to try is just creating an empty autokey log which is what it couldn't find:

````
mkdir -p ~/.local/share/autokey
cd ~/.local/share/autokey
touch autokey.log
````
This is a known installation bug which was fixed, apparently some time after 0.95.1.

**Comment by josephj11** [comment]
Appears to be a duplicate of #170

**Comment by dixhuit** [comment]
Thanks for all this, will give it a go. So how come the PPA is still only providing 0.95.1?

**Comment by luziferius** [comment]
@danbohea Because the PPA maintainer vanished some time ago due to issues.
@sporkwitch Do you have some time to publish 0.95.4?

**Comment by luziferius** [comment]
> Since this is just the package itself, it will not be upgraded by your package manager when newer versions are released, so you'll either have to do that manually or switch back to the repo version once it surpasses this version.

apt will automatically update over your manually installed packages, if the repository is newer. So if `0.95.5` or `0.96.0` will be released in the future and pushed to the repository, you will automatically get the update.
