### ISSUE TITLE
Cannot add abbreviation

### ISSUE THREAD

**Issue by Elliria** [autokey/autokey#220]
## Classification:

Enhancement

## Reproducibility:

Always

## Summary

Attempting to add an abbreviation to a phrase fails to add the abbreviation and displays a notification message.

## Steps to Reproduce (if applicable)

1) Open the File menu.
2) Click New.
3) Click Phrase.
4) Type in a name for the phrase.
5) Click OK.
6) Click the top Set button on the bottom right.
7) Click Add.
8) Type in an abbreviation.
9) Click OK.

## Expected Results

The abbreviation should be added.

## Actual Results

A pop-up is displayed with this message: "You must specify at least one abbreviation"

## Version

AutoKey version: 

Used GUI (Gtk, Qt, or both): 

autokey-gtk 0.90.4

Installed via: package manager

Distro:

Ubuntu 16.04

## Notes

What's missing from the above steps is another step that should come before step 9, and that's to press the Enter key or click in the empty white space beneath the input box. This is a step I've overlooked and taken a while to figure out and, apparently, I'm not the only one. It would be nice if that step was made obvious in some way.

Below are a few suggestions, one of which might make the user experience a bit smoother:
	* Add a tooltip that's displayed while typing in the input box.
	* Add another button (Add, Set, Remove or maybe Add, Accept, Remove).
	* Add some helpful text beneath "Abbreviations" above the input box or beneath the buttons below the input box.
	* Add some placeholder text into input box that says something like, "Type abbreviation here and press the Enter key to accept it."

**Comment by josephj11** [comment]
This has been fixed. 0.90.4 is almost seven years old and unmaintained. Unfortunately, the Ubuntu packagers haven't gotten the memo.

If you have phrases and scripts you need to save then:
Make a full backup of $HOME/.config/autokey (including hidden files).
Then uninstall AutoKey.
Next, follow the instructions [here](https://github.com/autokey/autokey/wiki/Installing#debian-and-derivatives).
That will get you up to version 0.95.1 (soon to be upgraded to 0.95.4).

In addition to many bug fixes, this version also adds Xautomation support which allows you to search the screen for an image and move the mouse cursor to it - making it possible to access all sorts of things that keyboard actions alone could not reach.

This version is based on Python3.x, so if you have any scripts which use Python syntax/features which changed from Python2.x, you will have to convert them. Most simple scripts should be unaffected by these changes.

**Comment by Elliria** [comment]
Ah, sorry about that. It's probably my fault for not having upgraded to the latest Ubuntu LTS release yet. Thank you for the instructions and all the information and, most of all, for Autokey. It's really quite amazing when you mess around with it and see what all it's capable of.

**Comment by josephj11** [comment]
Last I saw 18.04 had the old version in the repos too.  I just tried sending them a note, but I'm not sure how to contact the actual packagers.

**Comment by Elliria** [comment]
The `dpkg -s autokey-gtk | grep "Maintainer"` command gives this result:

Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Luke Faraone <lfaraone@debian.org>

It looks like Ubuntu Developers are probably the best bet.

**Comment by josephj11** [comment]
Thanks! I didn't know how to do that. I think Luke was active on our list, but it was many years ago.
