### ISSUE TITLE
Autokey-gtk in the system tray icon appears as a blank icon placeholder

### ISSUE THREAD

**Issue by ineuw** [autokey/autokey#221]
## Classification:
Feature (Old)

## Reproducibility:
Always

## Summary
In Linux Mint Cinnamon v19, the Autokey-gtk system tray icon appears as a blank icon placeholder.

Summary of the problem.
It is not known what app it represents, and there is no tooltip info
![missing autokey icon](https://user-images.githubusercontent.com/10367016/49275216-9afe9b80-f448-11e8-9213-bf3c6846e755.png)
## This should happen.
display Autokey icon
## Actual Results
- Instead, this happens. :(

AutoKey version: 
0.95.4

Used GUI (Gtk, Qt, or both): 
GTK

Installed via: (PPA, pip3, …).
Pip3

Distro:
Linux Mint 19 Cinnamon 64 bit

**Comment by luziferius** [comment]
The GTK GUI version still only loads its own icon from the system icon theme. So it can't display it's own icon, if it is not part of the theme.
This seems to be a limitation of the pip3 installation process, or the GTK GUI not including the icons as resources in the source code.
`pip3` seems to not copy the icon where it should be. So you want to fetch the SVG icons from the repository (https://github.com/autokey/autokey/tree/master/config) and manually place them into your system icon theme at `/usr/local/share/icons/your-theme-name/scalable/apps`
The setup.py file should give additional hints there the files belong:
https://github.com/autokey/autokey/blob/b875c2690f45a8776a3bedd3c3ae525bd6e6f5f2/setup.py#L138-161

**Comment by ineuw** [comment]
Thank you, you are very prompt and most kind. I think I can figure out the rest.

**Comment by luziferius** [comment]
You want the `autokey.svg` file and all the `autokey-status-*.svg` files.

The system should find them, if you place them into the highcolor icon theme. I think this is used as a fallback theme, regardless of your used theme. At least this is what the setup.py script does.

About the tootip: There should be one. At least the Qt GUI has one, showing the current state.

I haven't touched the GTK GUI yet, except for some small fixes... I think it has a tooltip and hope it fixes itself when it finds the icon.

**Comment by ineuw** [comment]
Copying icons to the system tray folder was not necessary. The Autokey icon was activated as soon as a script generated an error. Both normal (white) and error (red) icons are working as they should, and the icon returns to white when the error message is cleared. This was not working in the Python 2 version. Please consider the issue closed and thanks for your help.

**Comment by luziferius** [comment]
Does it still work after you restart autokey? Or do you have to trigger a script error each time you start autokey to make it show the icon?

**Comment by ineuw** [comment]
It works fine, in fact after viewing an a script error message, the red icon resets itself to white. This never worked in the python2 version. On the other hand, there used to be a non-working context menu option to view and clear the error, which for now can only be viewed and cleared in the main screen. If this could be made workable, it would simplify things.

**Comment by luziferius** [comment]
Ok, then the blank icon thing was a one-time issue.
That other issue is a separate thing. I tried it and can reproduce it on my system, so I’ll open an issue ticket for this, so that it won’t be forgotten.

**Comment by ineuw** [comment]
Thanks. The blank icon is gone permanently.

**Comment by luziferius** [comment]
Hmmm. I thought a bit about this issue. Maybe the icon was not initialized on the first start.
So instead of loading one of the expected icons, like `autokey-status-light` (the light `A`), it loaded ` `, which is obviously empty and non-existent.
This causes the icon to be broken, until the error handler set it to a valid state. The state was then saved to the `autokey.json` configuration file and thus permanently fixed your issue.

I’ll look at the code and re-open this issue, if this proves to be right.

**Comment by deragon** [comment]
In Gnome 3.34, Ubuntu 19.10, using branch master, up to date as of 2020-02-29 17:05:05 EST, the tray icon does not show.

I read the comments but I fail to understand the source of the problem.  I run `python3 setup.py install` to install.  I have the default Ubuntu theme.  Rebooted the computer and the problem persists.  Is something wrong with my setup or should I open a new bug report?

![image](https://user-images.githubusercontent.com/7698377/75615818-ea81ba80-5b16-11ea-9ea6-fb7a6d1d6759.png)

**Comment by luziferius** [comment]
@deragon Did you do a completely fresh installation of AutoKey, so running it for the first time?
Please open the AutoKey configuration file in
`/home/<your_user_name>/.config/autokey/autokey.json` in a text editor and report the value assigned to the `"notificationIcon"` entry.

As an example, mine is set to `"notificationIcon": "autokey-status-dark"`.

If this is empty, it indicates that this value is not properly initialized when the configuration is written the first time.

You can open the AutoKey settings and set the icon theme to a light or dark item. Just choose one, save (and restart AutoKey, if you use the GTK GUI). Then it should show up. If not, there is another issue lingering somewhere.

**Comment by ineuw** [comment]
I get the wrong icon (book with a star?) which is almost invisible as opposed to the "A" icon.

**Comment by deragon** [comment]
@luziferius, I tried the following:

$ fgrep notifica autokey.*
autokey.json:        "notificationIcon": "autokey-status-dark",
autokey.json~:        "notificationIcon": "autokey-status",

Same issue.  Icon not showing up with either values.  I may need to reinstall autokey...  Reruning 

`sudo python3 setup.py install`

..over and over after git `pull might` cause some issues...  I asked again in issue #352 how to uninstall when installing from Git, just to be sure to clear everything.  I am waiting your answer in issue #352 to proceed.  Thank you.

**Update**

Got the following when calling `Help/About Autokey`.   It might provide you a better clue:

```
[hans@demloka autokey] Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/autokey-0.95.10-py3.7.egg/autokey/gtkui/configwindow.py", line 1282, in on_show_about
    p = Gtk.IconTheme.get_default().load_icon(common.ICON_FILE, 100, 0)
gi.repository.GLib.Error: gtk-icon-theme-error-quark: Icon 'autokey' not present in theme Adwaita (0)

```

**Comment by luziferius** [comment]
> $ fgrep notifica autokey.*
> autokey.json: "notificationIcon": "autokey-status-dark",
> autokey.json~: "notificationIcon": "autokey-status",

Thanks. Then it is correctly initialized. Hmm.
AutoKey should install the icons to `/usr/share/icons/hicolor/scalable/apps/`. The GTK GUI currently _requires_ the icons to be present in the used icon theme, as it does not ship them as internal package data.
So please verify that the icons are present in the path quoted above:
![AutoKey-Icons](https://user-images.githubusercontent.com/2143820/75629119-9393e800-5bdf-11ea-8e9b-371124f5af31.png)
As far as I know, the `hicolor` icon theme is used as a fallback, if an icon is not found in the currently used theme. So it should fall back to using it, as the `Adwaita` theme does not provide icons for AutoKey.

Edit:
As seen here:
https://github.com/autokey/autokey/blob/c0c2e2939f2352a1d3d83c8edafc9007848d6a1e/setup.py#L139-L143
`setup.py` copies the list of icon files from the repository (lines 140-143) to `share/icons/hicolor/scalable/apps` below the installation prefix (`/usr/` by default on installation as root).

**Comment by deragon** [comment]
Icon is missing in that directory:

```
$ ls -l /usr/share/icons/hicolor/scalable/apps | fgrep -i key
-rw-r--r-- 1 root root  95631 Sep 23 11:28 ibus-keyboard.svg
```

Following are all the files releated to Autokey's icon on my system:

```
$ locate autokey-status | fgrep -i .svg
/usr/local/lib/python3.7/dist-packages/autokey-0.95.10-py3.7.egg/autokey/qtui/resources/icons/autokey-status-dark.svg
/usr/local/lib/python3.7/dist-packages/autokey-0.95.10-py3.7.egg/autokey/qtui/resources/icons/autokey-status-error.svg
/usr/local/lib/python3.7/dist-packages/autokey-0.95.10-py3.7.egg/autokey/qtui/resources/icons/autokey-status.svg
/usr/local/lib/python3.7/dist-packages/autokey-0.95.10-py3.7.egg/share/icons/Humanity/scalable/apps/autokey-status-error.svg
/usr/local/lib/python3.7/dist-packages/autokey-0.95.10-py3.7.egg/share/icons/Humanity/scalable/apps/autokey-status.svg
/usr/local/lib/python3.7/dist-packages/autokey-0.95.10-py3.7.egg/share/icons/hicolor/scalable/apps/autokey-status-dark.svg
/usr/local/lib/python3.7/dist-packages/autokey-0.95.10-py3.7.egg/share/icons/hicolor/scalable/apps/autokey-status-error.svg
/usr/local/lib/python3.7/dist-packages/autokey-0.95.10-py3.7.egg/share/icons/hicolor/scalable/apps/autokey-status.svg
/usr/local/lib/python3.7/dist-packages/autokey-0.95.10-py3.7.egg/share/icons/ubuntu-mono-dark/apps/48/autokey-status-error.svg
/usr/local/lib/python3.7/dist-packages/autokey-0.95.10-py3.7.egg/share/icons/ubuntu-mono-dark/apps/48/autokey-status.svg
/usr/local/lib/python3.7/dist-packages/autokey-0.95.10-py3.7.egg/share/icons/ubuntu-mono-light/apps/48/autokey-status-error.svg
/usr/local/lib/python3.7/dist-packages/autokey-0.95.10-py3.7.egg/share/icons/ubuntu-mono-light/apps/48/autokey-status.svg
/usr/local/lib/python3.7/dist-packages/autokey-0.95.9-py3.7.egg/share/icons/Humanity/scalable/apps/autokey-status-error.svg
/usr/local/lib/python3.7/dist-packages/autokey-0.95.9-py3.7.egg/share/icons/Humanity/scalable/apps/autokey-status.svg
/usr/local/lib/python3.7/dist-packages/autokey-0.95.9-py3.7.egg/share/icons/hicolor/scalable/apps/autokey-status-dark.svg
/usr/local/lib/python3.7/dist-packages/autokey-0.95.9-py3.7.egg/share/icons/hicolor/scalable/apps/autokey-status-error.svg
/usr/local/lib/python3.7/dist-packages/autokey-0.95.9-py3.7.egg/share/icons/hicolor/scalable/apps/autokey-status.svg
/usr/local/lib/python3.7/dist-packages/autokey-0.95.9-py3.7.egg/share/icons/ubuntu-mono-dark/apps/48/autokey-status-error.svg
/usr/local/lib/python3.7/dist-packages/autokey-0.95.9-py3.7.egg/share/icons/ubuntu-mono-dark/apps/48/autokey-status.svg
/usr/local/lib/python3.7/dist-packages/autokey-0.95.9-py3.7.egg/share/icons/ubuntu-mono-light/apps/48/autokey-status-error.svg
/usr/local/lib/python3.7/dist-packages/autokey-0.95.9-py3.7.egg/share/icons/ubuntu-mono-light/apps/48/autokey-status.svg
<autokey git directory>/autokey/build/lib/autokey/qtui/resources/icons/autokey-status-dark.svg
<autokey git directory>/autokey/build/lib/autokey/qtui/resources/icons/autokey-status-error.svg
<autokey git directory>/autokey/build/lib/autokey/qtui/resources/icons/autokey-status.svg
<autokey git directory>/autokey/config/autokey-status-dark.svg
<autokey git directory>/autokey/config/autokey-status-error.svg
<autokey git directory>/autokey/config/autokey-status.svg
<autokey git directory>/autokey/config/Humanity/autokey-status-error.svg
<autokey git directory>/autokey/config/Humanity/autokey-status.svg
<autokey git directory>/autokey/config/ubuntu-mono-dark/autokey-status-error.svg
<autokey git directory>/autokey/config/ubuntu-mono-dark/autokey-status.svg
<autokey git directory>/autokey/config/ubuntu-mono-light/autokey-status-error.svg
<autokey git directory>/autokey/config/ubuntu-mono-light/autokey-status.svg
<autokey git directory>/autokey/lib/autokey/qtui/resources/icons/autokey-status-dark.svg
<autokey git directory>/autokey/lib/autokey/qtui/resources/icons/autokey-status-error.svg
<autokey git directory>/autokey/lib/autokey/qtui/resources/icons/autokey-status.svg
```

**Comment by luziferius** [comment]
That’s not where they are supposed to be:
> ```
> /usr/local/lib/python3.7/dist-packages/autokey-0.95.10-py3.7.egg/share/icons/Humanity/scalable/apps/autokey-status-error.svg
> /usr/local/lib/python3.7/dist-packages/autokey-0.95.10-py3.7.egg/share/icons/Humanity/scalable/apps/autokey-status.svg
> /usr/local/lib/python3.7/dist-packages/autokey-0.95.10-py3.7.egg/share/icons/hicolor/scalable/apps/autokey-status-dark.svg
> /usr/local/lib/python3.7/dist-packages/autokey-0.95.10-py3.7.egg/share/icons/hicolor/scalable/apps/autokey-status-error.svg
> /usr/local/lib/python3.7/dist-packages/autokey-0.95.10-py3.7.egg/share/icons/hicolor/scalable/apps/autokey-status.svg
> /usr/local/lib/python3.7/dist-packages/autokey-0.95.10-py3.7.egg/share/icons/ubuntu-mono-dark/apps/48/autokey-status-error.svg
> /usr/local/lib/python3.7/dist-packages/autokey-0.95.10-py3.7.egg/share/icons/ubuntu-mono-dark/apps/48/autokey-status.svg
> /usr/local/lib/python3.7/dist-packages/autokey-0.95.10-py3.7.egg/share/icons/ubuntu-mono-light/apps/48/autokey-status-error.svg
> /usr/local/lib/python3.7/dist-packages/autokey-0.95.10-py3.7.egg/share/icons/ubuntu-mono-light/apps/48/autokey-status.svg
> /usr/local/lib/python3.7/dist-packages/autokey-0.95.9-py3.7.egg/share/icons/Humanity/scalable/apps/autokey-status-error.svg
> /usr/local/lib/python3.7/dist-packages/autokey-0.95.9-py3.7.egg/share/icons/Humanity/scalable/apps/autokey-status.svg
> /usr/local/lib/python3.7/dist-packages/autokey-0.95.9-py3.7.egg/share/icons/hicolor/scalable/apps/autokey-status-dark.svg
> /usr/local/lib/python3.7/dist-packages/autokey-0.95.9-py3.7.egg/share/icons/hicolor/scalable/apps/autokey-status-error.svg
> /usr/local/lib/python3.7/dist-packages/autokey-0.95.9-py3.7.egg/share/icons/hicolor/scalable/apps/autokey-status.svg
> /usr/local/lib/python3.7/dist-packages/autokey-0.95.9-py3.7.egg/share/icons/ubuntu-mono-dark/apps/48/autokey-status-error.svg
> /usr/local/lib/python3.7/dist-packages/autokey-0.95.9-py3.7.egg/share/icons/ubuntu-mono-dark/apps/48/autokey-status.svg
> /usr/local/lib/python3.7/dist-packages/autokey-0.95.9-py3.7.egg/share/icons/ubuntu-mono-light/apps/48/autokey-status-error.svg
> /usr/local/lib/python3.7/dist-packages/autokey-0.95.9-py3.7.egg/share/icons/ubuntu-mono-light/apps/48/autokey-status.svg
> ```

So the prefix `/usr/local/lib/python3.7/dist-packages/autokey-0.95.10-py3.7.egg/` is _definitely_ wrong. Those should be in `/usr/share/icons/…` or `/usr/local/share/icons/…`. That’s why GTK can’t find the icon files.

I  have no idea why they are placed _there_, though…
You are running Ubuntu, so you can grab the current packages from
https://packages.ubuntu.com/search?suite=focal&searchon=names&keywords=autokey
and install them via `dpkg`. [Or build your own packages.](https://github.com/autokey/autokey/wiki/Packaging)
Those packages place the icons in the right directory.

**Comment by deragon** [comment]
I uninstalled with instructions found at [python setup.py uninstall](https://stackoverflow.com/questions/1550226/python-setup-py-uninstall).  I then reinstalled with `sudo pip3 install .`.

Now, the icon shows up!  But it is way to dark... Why is that?  Another bug?  Should I open a new issue for it?

![Autokey - Tray icon too dark](https://user-images.githubusercontent.com/7698377/75639088-1d9e7980-5bfd-11ea-8515-0e11122e69de.png)

**Comment by ineuw** [comment]
deragon, I resolved this issue a few hours ago using Linux Mint 19.3, but my installation is from a ppa. https://launchpad.net/~nemonein/+archive/ubuntu/autokey. My panel icon was an old autokey icon resembled a book with a tiny star which changed to red in case of an error. I found these old icons in these folders and the icons were the same size (96 pixels) regardless of what was written on the folders.

/usr/share/icons/Mint-Y/panel/16/autokey-status-error.svg
/usr/share/icons/Mint-Y/panel/16/autokey-status.svg

/usr/share/icons/Mint-Y/panel/22/autokey-status-error.svg
/usr/share/icons/Mint-Y/panel/22/autokey-status.svg

/usr/share/icons/Mint-Y/panel/24/autokey-status-error.svg
/usr/share/icons/Mint-Y/panel/24/autokey-status.svg

I pasted the same three icons in each of the above, not knowing which folder is used.

![icons_used](https://user-images.githubusercontent.com/10367016/75666977-cb814680-5c44-11ea-8739-611905ffdcb8.png)

**Comment by luziferius** [comment]
@deragon You can choose between a light and a dark theme in the settings. (Qt GUI updates instantly on saving the settings, the GTK GUI currently requires an application restart.) If the shown icon on your screenshot _is_ the light one, then there is something wrong with the rendering of SVGs on your system. If so, you might be affected by something similar to #160.

@ineuw When installing from the PPA, the packages place the icons in the right place. The installation method is different from using `pip3`. When using the packages, the file placement is done a-priori at the package build time, whilst it is done live at the installation when using pip3. So the installation script may decide to do weird stuff, whilst the packages are just unpacked and therefore result in the same file layout all the time.
If you got some different icons, then it seems that your theme overrides the default icons placed into the `hicolor` fallback theme.

**Comment by deragon** [comment]
@luziferius, the wrong theme was selected.  Selecting the light theme fixed this.  Case closed for me.  Thank you!

That said, I am surprised that the dark theme icon is soo dark.  Pretty much no contrast with the background.  Anyhow, since we have the option to choose the light theme, there is no problem.

![Workspace 1_052](https://user-images.githubusercontent.com/7698377/75720650-e2f01c00-5ca4-11ea-8742-0723f6015000.png)

**Comment by luziferius** [comment]
This is how the dark icon looks on a light theme:
![notification_area](https://user-images.githubusercontent.com/2143820/75727222-b6f48b00-5ce4-11ea-908d-a77aab65c87f.png)
So the essence of this is that installing via `python3 setup.py install` installs the icons into the wrong directory. So using `pip3 install` is the only correct way to go. I’ll see if I can find any occurrences of the old instructions and update or remove them.

**Comment by ineuw** [comment]
I am fine. All I needed to know which folder(s) holds the icons. I also found these older images. with the same names. Can anyone recall what they are?

![autokey-status-error](https://user-images.githubusercontent.com/10367016/75733683-f199fb80-5cc3-11ea-8036-d97ea5fec9d9.png)
![autokey-status-error-old](https://user-images.githubusercontent.com/10367016/75733684-f199fb80-5cc3-11ea-87db-c17d7a0f51ce.png)

**Comment by luziferius** [comment]
@ineuw Never seen them before. I think they are part of the 'Mint-Y' icon theme. Those are definitely coming from a third party.

**Comment by deragon** [comment]
On my system, I search with:

```
$ locate -i autokey.png
/usr/local/lib/python3.7/dist-packages/autokey/qtui/resources/icons/autokey.png
/usr/local/lib/python3.7/dist-packages/autokey-0.95.9-py3.7.egg/share/icons/hicolor/96x96/apps/autokey.png
/usr/local/share/icons/hicolor/96x96/apps/autokey.png
/var/lib/app-info/icons/ubuntu-eoan-universe/64x64/autokey-gtk_autokey.png
/vol/data/base/software/devel/autokey/build/lib/autokey/qtui/resources/icons/autokey.png
/vol/data/base/software/devel/autokey/config/autokey.png
/vol/data/base/software/devel/autokey/lib/autokey/qtui/resources/icons/autokey.png
```
All these icons are all the same, the original one with blue background.  I have no clue where does my white icon comes from.  I wish I could help more, but I cannot.

**Comment by luziferius** [comment]
@deragon The white, black and red _`A`_ icons are SVGs named `autokey-status*.svg` (* is a wildcard)
(We only ship the main program icon as a PNG, mostly because of #160)

`/usr/local/share/icons/hicolor/96x96/apps/autokey.png` is loaded by the GTK+ GUI from the icon theme
`/usr/local/lib/python3.7/dist-packages/autokey/qtui/resources/icons/autokey.png` is a fallback, loaded by the Qt GUI in case it can’t find the icon from the icon theme.

**Comment by zzapper** [comment]
used locate to find the following 4 files and copied them to /usr/share/icons/hicolor/scalable/apps/
thus obtaining
 
/usr/share/icons/hicolor/scalable/apps/autokey-status-dark.svg
/usr/share/icons/hicolor/scalable/apps/autokey-status-error.svg
/usr/share/icons/hicolor/scalable/apps/autokey-status.svg
/usr/share/icons/hicolor/scalable/apps/autokey.svg

now have the white A in my toolbar
(linuxmint 20 ulyana)

**Comment by zzapper** [comment]
so linuxmint 20.3 June 2020 autokey 0.96   still got this issue:-
###### So Don't Use > sudo python3 setup.py install ### 

# the following solves the issue
cd /tmp/ && git clone https://github.com/autokey/autokey.git 
cd autokey && sudo pip3 install .
autokey-gtk &
# (Now you have Nice 'A' Icon in Tray)

**Comment by ineuw** [comment]
You should be posting this at Linux Mint on Github. There are many issues with Gnome, GTK and the panel. For cinnamon, it's  https://github.com/linuxmint/cinnamon
![220620_double_icons_autokey](https://user-images.githubusercontent.com/10367016/175800576-8bfa3365-001f-4624-8e58-2c2518efdb7d.jpg)
![220624_duplicate_icons_xfce4-notes](https://user-images.githubusercontent.com/10367016/175800577-df959557-65a5-4a62-9cf5-2587242d97f1.jpg)
.
