### ISSUE TITLE
change "paste using" en block

### ISSUE THREAD

**Issue by herrdeh** [autokey/autokey#228]
The quite new selector "paste using" (keyboard, clipboard, mouse selection...) is a really good feature. But shall I really change the settings of 30 phrases per hand?
Hopefully, somebody could write a routine to change all the settings with one control.

**Comment by luziferius** [comment]
AutoKey currently has no batch property editor, sorry.

A suggestion: You can edit the configuration files for scripts and phrases by hand. (And automate that!)

Phrases are stored in `$XDG_CONFIG_HOME/autokey/data/<Your_directory_structure>` (by default).
For each item (for example `name.txt`), there is a configuration file named `.name.json` (notice the leading dot, marking this as a hidden file).
Example: (The interesting part is in the bottom of that listing)
```
{
    "type": "phrase",
    "description": "issue_196",
    "modes": [],
    "usageCount": 0,
    "prompt": false,
    "omitTrigger": false,
    "matchCase": false,
    "showInTrayMenu": false,
    "abbreviation": {
        "abbreviations": [],
        "backspace": true,
        "ignoreCase": false,
        "immediate": false,
        "triggerInside": false,
        "wordChars": "[\\w]"
    },
    "hotkey": {
        "modifiers": [
            "<alt>",
            "<shift>"
        ],
        "hotKey": "n"
    },
    "filter": {
        "regex": null,
        "isRecursive": false
    },
    "sendMode": "kb"
}
```
The send mode is controlled by `sendMode`. Set this from `kb` (meaning keyboard) to your preferred pasting key combination. e.g. `<ctrl>+v`

You can use python3 to change this: (Exit autokey and Do a backup first!!)
(You have done that backup, right?)
from the directory containing the files, run python3 and execute something like this:
(Keep in mind that this will also modify the json config of the containing directory, so you might want to copy that one back from your backup, after running this. This code requires Python 3.6.)
```
import json, pathlib
for filename in pathlib.Path(".").glob("*.json"):
    with open(filename, "r") as file:  # Read the json from the config file
        config = json.load(file)
    # Alter the sendMode to your needs
    config["sendMode"] = "<ctrl>+v"
    with open(filename, "w") as file:  # Write the changed config back
        json.dump(config, file)
```

**Comment by herrdeh** [comment]
Great, thank you!
