### ISSUE TITLE
Autokey gentoo layman

### ISSUE THREAD

**Issue by Plautin** [autokey/autokey#232]
## Classification: Crash

(Pick one of: Bug, Crash/Hang/Data Loss, Performance, UI/Usability, Feature (New), Enhancement)

## Reproducibility: Always

(Pick one of: Always, Sometimes, Rarely, Unable, I Didn't Try)

## Version

AutoKey version: desktop automation utility for Linux and X11

Used GUI (Gtk, Qt, or both): 

If the problem is known to be present in more than one version, please list all of those.

Installed via: (PPA, pip3, …). gentoo layman

Linux Distribution:

## Summary

Summary of the problem : Overlay "y2kbadbug" does not exist

## Steps to Reproduce (if applicable)

- I do this : layman -a y2kbadbug
- I do that : layman -o 'https://github.com/autokey/autokey.git/master/raw/luziferius' -f -a y2kbadbug

## Expected Results

- This should happen. Fetching remote list...  * Fetch Ok   * Adding overlay...

## Actual Results

- Instead, this happens. :( Exception: Overlay "y2kbadbug" does not exist. 
 * CLI: Errors occurred processing action add
 * Exception: Overlay "y2kbadbug" does not exist.

If helpful, submit screenshots of the issue to help debug.\
Debugging output, obtained by launching autokey via `autokey-gtk --verbose` (or `autokey-qt --verbose`, if you use the Qt interface) is also useful.\
Please upload the log somewhere accessible or put the output into a code block (enclose in triple backticks).
```
Example code block. Replace this whith your log content.
```

## Notes

Describe any debugging steps you've taken yourself.

If you've found a workaround, please provide it here.

**Comment by Plautin** [comment]
A help for this issue ?

**Comment by luziferius** [comment]
@Plautin have some patience with bug reports and don’t close them yourself, if you did not fix it yourself. Otherwise the reports may be missed ;)

The Overlay maintainer seems to have deleted the repository, thus the information in the README is outdated. Sorry.
You may have to create one yourself. Or use pip3 to install autokey from the repository, which should be the easy solution.

**Comment by y2kbadbug** [comment]
So this was my layman repo but i don't use gentoo anymore, so it's really only there for reference now.  

If you need the original files they still exist on my github profile.
