### ISSUE TITLE
FIX not able to disable Ctrl+F7 opening up Autokey paste menu #blocker

### ISSUE THREAD

**Issue by allanlaal** [autokey/autokey#233]
its blocking my other apps

I have no hotkeys configured in Autokey 0.95.1

**Comment by luziferius** [comment]
The *My Phrases* folder that is created on first launch has `<ctrl>+<f7>` assigned.
https://github.com/autokey/autokey/blob/d2f1840ca141229e72fc587a7f6b07acdf8420a9/lib/autokey/configmanager/predefined_user_files.py#L197-L200

You can select that folder and clear the hotkey, if it bothers you. Don’t forget to click the save button after editing hotkeys or abbreviations. 

Or does clearing the hotkey not work?
