### ISSUE TITLE
Autokey does not react

### ISSUE THREAD

**Issue by DutchPete** [autokey/autokey#235]
## Classification: Performance

(Pick one of: Bug, Crash/Hang/Data Loss, Performance, UI/Usability, Feature (New), Enhancement)

## Reproducibility: Always

(Pick one of: Always, Sometimes, Rarely, Unable, I Didn't Try)

## Version

AutoKey version: 0.90.4

Used GUI (Gtk, Qt, or both): Gtk

If the problem is known to be present in more than one version, please list all of those.

Installed via: Synaptic Pakage Manager (PPA, pip3, …).

Linux Distribution: MX

## Summary

Summary of the problem.
I have Ak open, but when I want to test using the sample phrase for home address (abbreviation to be used is adr) nothing happens, or the cursor just jumps to the next line.

Same happens when I try to use the sample insert date (I set ALT+D as the hotkey combination).

## Steps to Reproduce (if applicable)

- I do this
- I do that

## Expected Results

- This should happen.
address gets inserted automatically, or
date is inserted automatically

## Actual Results

- Instead, this happens. :(
Nothing happens.

If helpful, submit screenshots of the issue to help debug.\
Debugging output, obtained by launching autokey via `autokey-gtk --verbose` (or `autokey-qt --verbose`, if you use the Qt interface) is also useful.\
Please upload the log somewhere accessible or put the output into a code block (enclose in triple backticks).
```
** (autokey-gtk:15211): WARNING **: 19:55:12.475: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
/usr/lib/python2.7/dist-packages/autokey/gtkapp.py:24: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, GObject, GLib
/usr/lib/python2.7/dist-packages/autokey/gtkui/notifier.py:19: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, Notify
/usr/lib/python2.7/dist-packages/autokey/gtkui/notifier.py:28: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3
/usr/lib/python2.7/dist-packages/autokey/gtkui/configwindow.py:20: PyGIWarning: GtkSource was imported without specifying a version first. Use gi.require_version('GtkSource', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Pango, GtkSource, Gdk, Gio
2018-12-15 19:55:12,543 DEBUG - root - AutoKey is already running as pid 10173
```

## Notes

Describe any debugging steps you've taken yourself.

If you've found a workaround, please provide it here.

**Comment by josephj11** [comment]
You need a more current version of AutoKey. Then, see if the issue persists.

0.90.4 is almost seven years old and unmaintained. Unfortunately, some packagers haven't gotten the memo (Debian Mepis MX).

If you have phrases and scripts you need to save then:
Make a full backup of $HOME/.config/autokey (including hidden files).
Then uninstall AutoKey.
Next, follow the instructions [here](https://github.com/autokey/autokey/wiki/Installing).

That will get you up to version 0.95.1 (soon to be upgraded to 0.95.4).

In addition to many bug fixes, this version also adds Xautomation support which allows you to search the screen for an image and move the mouse cursor to it - making it possible to access all sorts of things that keyboard actions alone could not reach.

This version is based on Python3.x, so if you have any scripts which use Python syntax/features which changed from Python2.x, you will have to convert them. Most simple scripts should be unaffected by these changes.

**Comment by DutchPete** [comment]
@josephj11 : 1st off, I am a newbie, so I apologise for any stupid remarks/questions.
I spent an hour trying to work out how to install it with PIP. I had to install PIP 1st, then I tried to install Ak via PIP but that did not work, here is the output:
```
$ pip3 install --user git+https://github.com/autokey/autokey
Collecting git+https://github.com/autokey/autokey
  Cloning https://github.com/autokey/autokey to /var/tmp/pip-zla_5q6e-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /var/tmp/pip-zla_5q6e-build/
```
But, since I was using MX Linux I decided to check out MX test packages, and Ak 0.95.2 was listed, so I installed that. Nevertheless, the result is the same as before: it does not react, nothing happens :-(((

**Comment by josephj11** [comment]
I've seen that message before. Now, if I can find out where ...

Did you uninstall 0.90.4 before installing the newer version? I've seen problems from the old version keeping Python2 modules around which can conflict with the Python3 versions AutoKey now uses.
I just tried `import setuptools` from an interactive Python3 prompt and it worked fine.
I'm not  sure, but I ran an `apt-file find setuptools` (I'm running kubuntu 18.04), and it found a package named `python3-setuptools` which is installed on my system. See if you have the equivalent package installed on your system.

**Comment by DutchPete** [comment]
@josephj11 : Yes, I uninstalled v. 0.90.4 before installing 0.95.2, that is standard procedure in Windows too ;-)
`setuptools` is not present on my system. Can you tell me what steps to take to install it? You mentioned 

> I just tried `import setuptools` from an interactive Python3 prompt .....

I would not know how to do that.

**Comment by josephj11** [comment]
We'll have to wait for one of the devs to help you.

AutoKey itself and AutoKey scripts are written in Python3, so if you run into problems writing or debugging a script, you can work on the parts of it that don't use the AutoKey API (like calculate something or build a response string) directly in Python.

You just open a terminal on your desktop and type `python3`. That starts the Python3 interpreter which will run any Python3 statements you type into it. That's what I did with the import above. It didn't actually run anything; it just made the functions in the setuptools module available to be run. (To exit the Python3 interpreter, you type `quit()`.)

I just figured out that MX is a Debian derivative. That means you can use `apt` to manage packages on your system.

Open a terminal and type

`sudo apt install python3-setuptools`

and see what happens. (It will ask for your user password.)

**Comment by DutchPete** [comment]
@josephj11 : thanks for that Joe, it worked. After installing the `setuptools` I said to myself that since Ak 0.95 was already installed (yesterday, albeit not with PIP which is where the `setuptools` issue arose) I needn't have installed `setuptools` anymore. But I left it because it will probably come in handy in the future.

I just tried Ak and it works, even for a script I created from an example, so I am happy.
Would you happen to know if there is an Autokey forum?

**Comment by luziferius** [comment]
@DutchPete You’ll need to install `python3-setuptools` to be able to use pip3.

Ubuntu package link (just for reference): https://packages.ubuntu.com/bionic/python3-setuptools, Debian package link: https://packages.debian.org/stretch/python3-setuptools

Edit: It seems i posted my original answer from an outdated browser cache and didn’t see Joe’s answer…

There is the Google groups mail based forum: https://groups.google.com/forum/#!forum/autokey-users
