### ISSUE TITLE
clipboard.get_clipboard() raises exception of clipboard is empty

### ISSUE THREAD

**Issue by shane-kerr** [autokey/autokey#236]
## Classification:

Bug

## Reproducibility:

Always

## Version

AutoKey version: 

0.95.4

Used GUI (Gtk, Qt, or both): 

Gtk

If the problem is known to be present in more than one version, please list all of those.

Unknown

Installed via: (PPA, pip3, …).

pip3

Linux Distribution:

Ubuntu 18.10

## Summary

I am using a script which gets the contents of the keyboard. After boot it failed with an error. I checked and it was raising an `Exception` when calling `clipboard.get_clipboard()`, because the clipboard was empty.

![image](https://user-images.githubusercontent.com/1943584/50081099-ea392000-01ed-11e9-808d-58de2b79afcb.png)

## Steps to Reproduce (if applicable)

- Clear the clipboard (either logging in to a desktop, or using a password safe which clears the clipboard after a timeout, or any other way of clearing the clipboard)
- Run a script with `clipboard.get_clipboard()`

## Expected Results

- Probably `clipboard.get_clipboard()` should return an empty string, `""`. Alternately it could return `None`, but that is likely to cause other coding errors.

## Actual Results

- Script error.

## Notes

This is easy to work around:

```python
try:
    clipboard_contents = clipboard.get_clipboard()
except:
    clipboard_contents = ""
```

**Comment by luziferius** [comment]
Thank you for reporting this corner case.

At least, both the GTK and Qt interface should be consistent, and the empty clipboard behaviour should be documented.

Normally, raising exceptions is the most Pythonic way to handle this kind of situation.
Returning `None` may be an alternative.

I don’t know, if it is possible to have an empty string in the clipboard and if this is different from having an empty clipboard, so returning `""` *may* be ambiguous.

**Comment by shane-kerr** [comment]
Hm... looking at the documentation it is clear:

https://autokey.github.io/lib.scripting.GtkClipboard-class.html

It does seem counter-intuitive to me, but clearly this was a design decision. I'm okay if you want to close the ticket as "Closed: RTFM". :wink:

**Comment by luziferius** [comment]
It was a design decision in the Python Gtk bindings AutoKey uses, although a bad one.

One should never do a `raise Exception()` in Python, because that is the base class. Catching it forces catching of all kinds of exceptions. It really should be a `RuntimeException` or similar.

And it seems to be inconsistent with the Qt clipboard interface.
So I’ll keep this open until the next bugfix release. The interface needs to be unified between both GUIs.

**Comment by Elliria** [comment]
It's fixed in **AutoKey 0.96.0**. I believe it was fixed in  [commit #837](https://github.com/autokey/autokey/pull/837/commits/efb4dd640b9c8c86cbf59ee9a5ed7725b1b09972).

**Comment by jidaikobo-shibata** [comment]
This problem is probably unresolved. I am using version 0.95.10, but the code below did not work.

```python
clipboard_contents = clipboard.get_selection()

if clipboard_contents == '':
    ....
```

However, I got it working by adding the code below shown in this issue.

```python
try:
    clipboard_contents = clipboard.get_selection()
except:
    clipboard_contents = ''
       
if clipboard_contents == '':
    ....
```

thanks

**Comment by josephj11** [comment]
If at first you don't succeed, "try:", "try:" again. LOL

I'm going to close this as won't fix as anything X11 isn't likely to improve and if we can get Wayland working, we'll have a whole new set of issues.
