### ISSUE TITLE
Add API functions to call AutoKey scripts as functions

### ISSUE THREAD

**Issue by luziferius** [autokey/autokey#246]
## Classification:

Enhancement to the scripting API

## Version

AutoKey version: All < 0.96.0

## Summary

Add functionality to call scripts like functions.

## Proposal:

- Add further optional arguments (`*args, **kwargs`) to [`engine.run_script(script_name)`](https://autokey.github.io/lib.scripting.Engine-class.html#run_script)
- Arguments can be accessed using a getter function. Something like [`engine.get_macro_arguments()`](https://autokey.github.io/lib.scripting.Engine-class.html#get_macro_arguments)?
- Return values can be set using the existing `engine.set_return_value()`
- engine.run_script() should return the value set by `engine.set_return_value()`

## Notes
There is a possible workaround that involves using the global scripting store. It takes quite some effort to use, because it is persistent and needs to be cleared after usage to not carry old data.

**Comment by josephj11** [comment]
Is this the thing we talked about where currently, you can't use an AutoKey script in a script in the Modules directory because the scripting API isn't available?

**Comment by luziferius** [comment]
Not really. The API currently has [`engine.run_script(script_name)`](https://autokey.github.io/lib.scripting.Engine-class.html#run_script), which can be used to run normal scripts.


But you can’t supply arguments to the script or return values from executed scripts.
I’d like to change that. This adds further optional arguments to this API function to simplify advanced scripting.

The API in imported modules thing: That needs to overwrite the `import` mechanic. That should probably go into a different enhancement issue, so that it is not forgotten.

Edit: I’ll give a usage example:
Let’s look at this cellphone keyboard emulator script: https://github.com/luziferius/autokey_scripts/tree/master/NumpadIME
It allows typing text using only the number pad. It can be used to type small amount of text in a really space constraint environment, when you only have space for a USB number pad keyboard.

This is the main logic centralized in one script: https://github.com/luziferius/autokey_scripts/blob/master/NumpadIME/NumpadIME_type_key.py
This is a trigger script, for example the script assigned to `<NP_1>`: https://github.com/luziferius/autokey_scripts/blob/master/NumpadIME/NumpadIME_key_1.py
I’d like to change that from passing values around using the global store to simply adding the argument to the function call.
The script should look like this one-liner: `engine.run_script("NumpadIME_type_key", "1")`. The last parameter is then the script parameter that will be passed to the executed script.
This removes the necessity to use the global scripting store to pass around values.

**Comment by josephj11** [comment]
OK. Thanks.

**Comment by BlueDrink9** [comment]
I'll take a look at this.

**Comment by luziferius** [comment]
@BlueDrink9 Thank you for taking interest in this. I’ve assigned you to mark this issue as in progress. 

In case you want to drop this and can’t un-assign yourself, just ping me to remove the assignment.
