### ISSUE TITLE
Autokey could not start because can't create local folder

### ISSUE THREAD

**Issue by ghost** [autokey/autokey#250]
## Classification:

Bug

## Reproducibility:

Always

## Version

AutoKey version: `0.95.2`

Used GUI (Gtk, Qt, or both): both

Installed via: PPA

- http://mxrepo.com/mx/testrepo/pool/test/a/autokey

Linux Distribution: MX Linux MX-17.1 (aka Debian 9.x Stretch)

## Summary

*Autokey* can't create folder `~/.local/share/autokey/` and can't create file `~/.local/share/autokey/autokey.log`

### Terminal log

```
$ autokey-qt
Traceback (most recent call last):
  File "/usr/bin/autokey-qt", line 11, in <module>
    load_entry_point('autokey==0.95.2', 'console_scripts', 'autokey-qt')()
  File "/usr/lib/python3/dist-packages/autokey/qtapp.py", line 110, in __init__
    self._configure_root_logger()
  File "/usr/lib/python3/dist-packages/autokey/qtapp.py", line 169, in _configure_root_logger
    backupCount=common.MAX_LOG_COUNT
  File "/usr/lib/python3.5/logging/handlers.py", line 150, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.5/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.5/logging/__init__.py", line 1009, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.5/logging/__init__.py", line 1038, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/me/.local/share/autokey/autokey.log'
```

## Notes

If manually create folder `~/.local/share/autokey/` — then *Autokey* started normally.

**Comment by luziferius** [comment]
That’s a known bug in 0.95.1 and .2. It was fixed some time ago in 0.95.3
After the manual directory creation, it will work normally.
You may want to update to 0.95.5, which contains some additional bug fixes (see the changelogs here: https://github.com/autokey/autokey/releases)

By the way: The repository you used does not belong to us, thus we have no control over it’s release cycle and update policy. In fact, I’ve never seen this repository before. 

(Duplicate of #170)

**Comment by ghost** [comment]
> I’ve never seen this repository before.

FYI, check Autokey page on Repology.

- http://repology.org/metapackage/autokey/versions

[![Packaging status](https://repology.org/badge/vertical-allrepos/autokey.svg)](https://repology.org/metapackage/autokey)

**Comment by luziferius** [comment]
Thank you very much for the link! I didn’t know that site, looks like a really good site to track distribution updates.

The Debian/Ubuntu situation is unfortunate. all derived distributions sit on the same old version, because the Debian package maintainer stopped his work.

**Comment by ghost** [comment]
> It was fixed some time ago in 0.95.3

There was no notes about it in Changelog of `0.95.3`

- https://github.com/autokey/autokey/releases/tag/v0.95.3

**Comment by luziferius** [comment]
It crashed, because the logger tries to write a log file, but the parent directory does not yet exist. Changelog quote (yeah, may not be that obvious): 
> - Qt GUI: Create the user data directories before initializing the logger system. This prevents crashes when autokey-qt is used for the first time or when the user wiped all previous data. Fixes #170

**Comment by ghost** [comment]
OK.

> Thank you very much for the link! I didn’t know that site, looks like a really good site to track distribution updates.

FTR, you could use Repology badges in `README.md` or on other webpages

- https://repology.org/metapackage/autokey/badges

**Comment by luziferius** [comment]
I've put the badges on the wiki front page. The wiki home was a bit empty, and now it shows some useful info :)
