### ISSUE TITLE
(KDE) Main window always opens even 'show main window' is unchecked.

### ISSUE THREAD

**Issue by nemonein** [autokey/autokey#251]
## Classification:

UI/Usability

## Reproducibility:

Always

## Version

AutoKey version: 0.95.5

Used GUI (Gtk, Qt, or both): QT

Installed via: Github Release (Deb package)

Linux Distribution: KDE Neon (Kubuntu based)

## Summary

On KDE Plasma, turn on 'Restore previous session'.
  System Settings - Startup and Shutdown - Desktop Session - On Login - Restore previous session

On Autokey settings, 
  turn on 'Automatically start Autokey after login'
  turn off 'Show main window when starting'

Then, reboot.
Autokey's main window is not supposed to show, but it does.
If the setting, 'Restore previous session' is unchecked, no windows is showing(working as intended).

## Steps to Reproduce (if applicable)

See the above section.

## Expected Results

- No window showing.

## Actual Results

- Main window appears when starting.

## Notes

- I have not been able to turn on 'Restore previous session' because of the issue #198. Now #198 is fixed, I could turn it on, but there's a little annoyance here.

**Comment by luziferius** [comment]
The session restoration and the autostart both trigger, starting two instances. This causes the first to open the GUI. Thats why it opens regardless the settings on login.

Exclude AutoKey from the session restoration mechanism to fix this.

Try this experiment: While AutoKey runs with a closed window, start another instance using the KDE menu. Result: The original instance opens the GUI.

**Comment by nemonein** [comment]
Thanks. Excluding autokey-qt works good.
You may close this issue.

**Comment by luziferius** [comment]
I’ve added this to the Troubleshooting Wiki page. https://github.com/autokey/autokey/wiki/Troubleshooting
