### ISSUE TITLE
Update the Arch Linux AUR link in the README

### ISSUE THREAD

**Issue by luziferius** [autokey/autokey#260]
The Arch AUR package name was updated to be just `autokey`, thus the link is outdated and broken.

TODO: Update the Arch AUR link in the README

**Comment by prosoitos** [comment]
I don't think there is a link, but it seems that the last update broke AutoKey for me (unless I am missing something).

I can launch AutoKey and open the window, but none of my scripts nor phrases work anymore.

I am on Arch Linux.

Thanks!

**Comment by josephj11** [comment]
It might help if we can what AutoKey sees. Try starting a trace and trigger
one of your phrases or scripts then post back here with the output.

Instructions here
<https://github.com/autokey/autokey-python2/wiki/Problem-Reporting-Guide>.

**Comment by luziferius** [comment]
Seems you have missed the point? ;) The AUR link in the README is outdated. The Arch AUR maintainer has updated the package name. This is a reminder to update it.
