### ISSUE TITLE
Debian Package Maintainer Needed

### ISSUE THREAD

**Issue by josephj11** [autokey/autokey#269]
## Classification: Enhancement

(Pick one of: Bug, Crash/Hang/Data Loss, Performance, UI/Usability, Feature (New), Enhancement)

## Reproducibility: Always

(Pick one of: Always, Sometimes, Rarely, Unable, I Didn't Try)

## Version

AutoKey version: Most current

Used GUI (Gtk, Qt, or both): both

If the problem is known to be present in more than one version, please list all of those.

Installed via: (PPA, pip3, …).

Linux Distribution: Debian and derivatives - installed via distribution provided repositories

## Summary

Help Wanted:
We need someone to maintain the AutoKey package for Debian (as a Debian maintainer)

## Steps to Reproduce (if applicable)

- Install from any Debian-based distro

## Expected Results

- The most current version of AutoKey should be installed

## Actual Results

- 0.90.4 gets installed :(

## Notes
Workaround:
Answer all the people (one by one) who make it as far as our support list or Gitter and point them to our manual installation instructions.

**Comment by dixhuit** [comment]
Does this explain the error:

```
The repository 'http://ppa.launchpad.net/sporkwitch/autokey/ubuntu cosmic Release' does not have a release file.
```

when running:

```sh
sudo add-apt-repository ppa:sporkwitch/autokey
```

?

**Comment by josephj11** [comment]
Not quite. That's our "old" PPA. The maintainer disappeared, so we can't update it. It was Bionic only IIRC.
Many distros are derived from Debian, so if that was up to date they would be too.

**Comment by nemonein** [comment]
I'm not sure this is what you want, but, as long as you supplies 'debian' folder(autokey-common.*, changelog, contol, etc), I can manage the PPA for autokey. (I'm not a developer, so I don't have any knowledge to create the 'debian' files.)
I already do this for several packages, such as [Bomi](https://github.com/xylosper/bomi).

Please take a look at my [PPAs](https://launchpad.net/~nemonein).

**Comment by bjohas** [comment]
Hi both,
Just wondering whether there's a stable way of getting a more up-to-date release on Ubuntu 19.10.
Many thanks!

**Comment by luziferius** [comment]
@bjohas Currently only grabbing packages I attached to the releases here: https://github.com/autokey/autokey/releases
Or building your own packages, as explained here: https://github.com/autokey/autokey/wiki/Packaging

The best were, if this gets updated: https://packages.ubuntu.com/source/disco/autokey

**Comment by luziferius** [comment]
The issue seems to be resolved.
Debian just accepted 0.95.9 in the their `unstable` repositories: https://tracker.debian.org/pkg/autokey
