### ISSUE TITLE
Phrase refuses to trigger

### ISSUE THREAD

**Issue by Jack-Chronicle** [autokey/autokey#273]
## Classification:

Bug

## Reproducibility:

Always

## Version

AutoKey version: 0.95.4

Used GUI (Gtk, Qt, or both): both

If the problem is known to be present in more than one version, please list all of those.

Installed via: Software Center (Solus)

Linux Distribution: Solus

## Summary

Some phrases won't trigger inside of a word even when set to do so

## Expected Results

- The phrase triggers as part of a word

## Actual Results

- Instead, they will only trigger from a space

**Comment by luziferius** [comment]
First, please verify that this also happens on the latest version (0.95.6), too. Just grab a ZIP archive from the assets list attached to the release here: https://github.com/autokey/autokey/releases/tag/v0.95.6 ([Direct link](https://github.com/autokey/autokey/archive/v0.95.6.zip)), extract it, exit the currently running AutoKey instance (if any) and run 0.95.6 directly from the extracted ZIP archive. See also: https://github.com/autokey/autokey#zero-installation-method

If it still happens on 0.95.6, we can try to get this fixed.

There are a few things I need to know.
What I get from your report is that there are two phrases configured to trigger immediately, but only one expands, and the other does not. (The other only expands on a space or similar trigger character).

I’ll need the exact Phrase configuration for the failing phrases. With this, I should be able to reproduce it on my system. (For example, 0.95.5 contained a bug that only happened on a specific combination of phrase settings (#254).)
You can either provide the hidden `.json` file that contains the phrase configuration and is stored alongside the phrase, or post a screenshot of the abbreviation settings window.

**Comment by Jack-Chronicle** [comment]
![Screenshot from 2019-04-24 10:37:26](https://user-images.githubusercontent.com/18507378/56677133-1291c900-667d-11e9-869d-6bd7d32063bd.png)


{
    "type": "phrase",
    "description": "zero",
    "modes": [
        1
    ],
    "usageCount": 72,
    "prompt": false,
    "omitTrigger": true,
    "matchCase": true,
    "showInTrayMenu": false,
    "abbreviation": {
        "abbreviations": [
            "o"
        ],
        "backspace": true,
        "ignoreCase": true,
        "immediate": false,
        "triggerInside": true,
        "wordChars": "[\\w]"
    },
    "hotkey": {
        "modifiers": [],
        "hotKey": null
    },
    "filter": {
        "regex": null,
        "isRecursive": false
    },
    "sendMode": "kb"
}

**Comment by Jack-Chronicle** [comment]
I can't set it to trigger immediately because I have another phrase that triggers with "oo", and i'm not sure if I could have that one trigger if this one does so automatically
I had a similar problem back when I was using AHK, but I got around that by simply changing the trigger characters for it to everything but being followed by an "o"

**Comment by luziferius** [comment]
Well… Yeah. Based on your configuration, the reported result is expected.
`Omit trigger character` causes AutoKey to not re-type the trigger character after expansion.
`Trigger when typed as part of a word` causes AK to find the abbreviation, while you type it as part of a word. So `to<space>` will expand to `t<your_phrase><space>` (in your posted case).
You need to tick `Trigger immediately` to trigger as soon as the abbreviation is completely typed out.

> I can't set it to trigger immediately because I have another phrase that triggers with "oo", and i'm not sure if I could have that one trigger if this one does so automatically

You can, if you have the undo functionality enabled, and your phrase content does not contain special characters. (That is anything in the form `<key_name>` or `<code[integer_key_code]>`.)
You have to type `o`, wait the expansion, undo that using the `<backspace>` key, then type the second `o`. I doubt, that this is convenient.


> I had a similar problem back when I was using AHK, but I got around that by simply changing the trigger characters for it to everything but being followed by an "o"

That works in AK, too. The `Trigger on` field is editable. You can supply a character list that is used as trigger characters. Beware that this is directly fed as a character group into a Python3 regular expression. This feature is a bit brittle, currently, so beware. See #212, for details. You have to escape Python-RE special characters properly. Without having checked this in code, as far as I know, you can’t put a negation, so you probably have to spell out all characters, except for `o`. This behaviour _might_ be improved some time in the future.

**Comment by Jack-Chronicle** [comment]
Oh, thanks... couldn't find anywhere that says what the options did, so I wasn't actually sure what "omit trigger character" did... I edited the trigger on for every character but o and it fixed it. Thanks for the help :smile: 

And by any chance do you know if theres a way to auto-capitalize the first letter of each word using autokey? I just started using it recently, and not to good with coding in python

**Comment by luziferius** [comment]
And `Match case` implements a 4-way logic (in my examples denoted like `abbreviation`→`Phrase`):
`lowercase`→`converted to lower case`
`UPPERCASE`→`CONVERTED TO UPPER CASE`
`First_character_upper`→`First character in phrase is upper case, rest lower case.`
`everything_Else` → `Capitalisation kept AS  iN the stORed Phrase`

> And by any chance do you know if theres a way to auto-capitalize the first letter of each word using autokey?

There are some, but this might prove impractical. AutoKey has it’s roots in a text expander type application that reacts on specific abbreviations and hotkeys. So doing continuous text modification during typing is out of scope. And solutions to problems out of it’s initial scope tend to be cumbersome.

And currently, you can’t disable scripts/phrases or whole folders completely, so the capitalisation feature will be always-on. (There is a feature request for this, though. #179)

1. The current [`develop` branch](https://github.com/autokey/autokey/tree/develop) (that is ahead of the current master by some small features) contains a new feature, an [API call](https://github.com/autokey/autokey/commit/19bb7c3f3517ff9cd22c6a40f296a229183a4045) for scripts that makes triggered abbreviation and trigger character available to the script code. You can create a simple script, that requests the abbreviation, converts it to upper case and types it out in upper case. Assign _all_ lower case letters as single-letter abbreviations. Keep `Trigger when typed as part of a word` and `Ignore case` disabled. Enable `Trigger immediately`. Then it will convert all letters that follow a word separator to upper case, thus capitalise all words.
2. This works on currently released versions: Create a Phrase for each lower case letter that solely contains the upper case equivalent. For each Phrase, assign the lower case letter as the only abbreviation. Keep `Trigger when typed as part of a word` and `Ignore case` disabled. Enable `Trigger immediately`.

Both solutions will collide with any other defined (lower case) abbreviation, so the end result may not be what you want. So sadly, the answer is probably »no, unless you want to sacrifice the whole abbreviation trigger mechanic«.
