### ISSUE TITLE
AutoKey won't start complainig about gi module

### ISSUE THREAD

**Issue by hiredgunhouse** [autokey/autokey#277]
## Classification:

Bug

## Reproducibility:

Always

## Version

AutoKey version: 

Gtk

If the problem is known to be present in more than one version, please list all of those.

Installed via: pip3

Linux Distribution: Ubuntu 16

## Summary

autokey-gtk won't start

## Steps to Reproduce (if applicable)

- I do this in my zsh shell
autokey-gtk[ENTER]

## Expected Results

- This should happen.
Run succesfully

## Actual Results

- Instead, this happens. :(

➜ autokey-gtk
Traceback (most recent call last):
  File "/home/peter/cli-ve/bin/autokey-gtk", line 6, in <module>
    from autokey.gtkui.__main__ import main
  File "/home/peter/cli-ve/lib/python3.5/site-packages/autokey/gtkui/__main__.py", line 4, in <module>
    from autokey.gtkapp import Application
  File "/home/peter/cli-ve/lib/python3.5/site-packages/autokey/gtkapp.py", line 37, in <module>
    import gi
ImportError: No module named 'gi'

**Comment by josephj11** [comment]
That's a new one. I'm not good with pip3. Where did you get the source so we can determine the version you are attempting to use?

0.95.7 is the most recent.

Since you're using Ubuntu, you can install from our deb files if you don't plan on working directly with the source code.

I just updated the [installation instructions](https://github.com/autokey/autokey/wiki/Installing#debian-and-derivatives).

**Comment by luziferius** [comment]
On Ubuntu, the package it complians about is called `python3-gi`.

If you don’t want to use the provided packages, you can build the Debian packages yourself. I recently updated the Wiki page explaining the process here: [Packaging](https://github.com/autokey/autokey/wiki/Packaging)

Either way, if `apt` resolves the dependecies, it’ll work definitely. `pip` can’t install some of the dependencies, because some are not published on PyPI …

**Comment by hiredgunhouse** [comment]
@josephj11 
I used the pip3 instructions from the repo's homepage (README file).

@luziferius 
I installed the `python3-gi` but that did not help :/

I suppose that the reason might be related to the fact that my main python in system is 2.7 and I used a virtual env with python3 set as default.

Anyway I tried those instructions https://github.com/autokey/autokey#ubuntu-mint-debian and got the gtk version working, qt version fails but that does not matter much in my case.

Also it seems there is some issue with the apt repository as I get following error when I run `apt-get update`:

```
W: The repository 'http://ppa.launchpad.net/sporkwitch/autokey/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/sporkwitch/autokey/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
BTW. I'm running Ubuntu 16.04.06 LTS

Anyway thanks for help, it works now.
Also big thank you for making it, I moved from Windows to Linux and AutoKey was one of a few things I missed a lot.

**Comment by Qwerty-Space** [comment]
I also get this on Manjaro

```
Traceback (most recent call last):
  File "/home/qwerty/.pyenv/versions/3.7.3/bin/autokey-gtk", line 11, in <module>
    load_entry_point('autokey==0.95.7', 'console_scripts', 'autokey-gtk')()
  File "/home/qwerty/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/qwerty/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/home/qwerty/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/home/qwerty/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/qwerty/.pyenv/versions/3.7.3/lib/python3.7/site-packages/autokey/gtkui/__main__.py", line 4, in <module>
    from autokey.gtkapp import Application
  File "/home/qwerty/.pyenv/versions/3.7.3/lib/python3.7/site-packages/autokey/gtkapp.py", line 37, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

```

**Comment by luziferius** [comment]
@Qwerty-Space You need the Python GObject Introspection package AKA `gi`. The Arch [AUR package](https://aur.archlinux.org/packages/autokey) should give you hints what you need (i.e. the dependency list tailored for Arch), even if you don’t want to install from the AUR. Package link: https://www.archlinux.org/packages/extra/x86_64/python-gobject/

**Comment by Qwerty-Space** [comment]
@luziferius I do have that installed from the Manjaro extra repo
