### ISSUE TITLE
Qt version doesn't react to the xmodmap changes without restart

### ISSUE THREAD

**Issue by ghost** [autokey/autokey#278]
## Classification:

Bug

## Reproducibility:

Always

## Version

AutoKey version: 0.95.7

Used GUI: both

Installed via: package manager (eopkg)
Linux Distribution: Solus 4

## Summary

I have a keyboard with extra keys. These keys are not recognized by default so I have to use a program and xmodmap to make them work.
I set autokey to autostart and load the xmodmap file manually after startup.
This works with autokey-gtk, but not with the qt version, which doesn't react to the xmodmap changes. I have to restart autokey-qt and then it works.

## Steps to Reproduce (if applicable)

- start autokey-qt
- load xmodmap file "xmodmap /path/to/xmodmap-file"

## Expected Results

- setting a key shows correct key code
- pressing the set key triggers the script

## Actual Results

- setting a key shows wrong key code or no key code at all
- pressing the set key doesn't trigger the script

Debugging output (started `autokey-qt --verbose`, loaded the xmodmap file, tried to set a key and quit) https://pastebin.com/Tsbf3ZEp

**Comment by luziferius** [comment]
Thanks for reporting.

This'll nees some investigations. 


Bases on your description, an alternative solution for your use case might be possible:

If your extra key enabling program can also run shell sripts/external commands AND you don't need AutoKey window filters AND (you don't use modifier keys with those extra keys OR that program handles modifiers internally), you can plug in AutoKey directly.

Instead of creating a key press on which AutoKey reacts, you can use the `autokey-run` command to direcly send commands from that program to AutoKey via it's DBus interface.

Try `autokey-run --help` to see, what's available.

**Comment by ghost** [comment]
> If your extra key enabling program can also run shell sripts

That program is [this one](https://github.com/Gibtnix/Apex-Macros).
I run `apex-macros enable` then the keys get some default behaviour, some get a key code and some don't (when trying to assign them in autokey).

To get all keys working I use these files (adapted from [here](https://github.com/tuxmark5/ApexCtl)):
- [/etc/udev/hwdb.d/90-apex.hwdb](https://pastebin.com/VYcLdjcA)
- [/etc/udev/rules.d/90-apexctl.rules](https://pastebin.com/AZvsrXXV)
- [Xmodmap](https://pastebin.com/ZBJUxaS4)

I always used the gtk version, but the latest system updates messed something up with the gtk version (missed a dependency), so I installed the qt version and noticed this behaviour.

For now I'll keep using the gtk version.

**Comment by sebastiansam55** [comment]
This is because the GTK version hooks into the "Gdk.Keymap" and ties an event to the "keys-changed" signal. See https://github.com/autokey/autokey/blob/23bb8f522f208f5c5eac91e83945c1d633f30ee3/lib/autokey/interface.py#L226-L228

I'll dig around on google and see if there is anything equivalent.

**Comment by sebastiansam55** [comment]
Might be able to tie both into X's MappingNotify event? When I use `xdotool key ISO_Level3_Shift` (on a mapping without it) I get a MappingNotifiy in `xev` along with the GTK version triggers the `keys-changed` event
