### ISSUE TITLE
Phrases show up wrong on Firefox and Thunderbird

### ISSUE THREAD

**Issue by ri0t** [autokey/autokey#28]
Every now and then, random characters in autokey's output are missing.
I guess it is sending the letters too fast for those javascript laden sites/browsers.

The same issue has been seen in the (upstream?) repository:
https://code.google.com/p/autokey/issues/detail?id=278

**Comment by Moilleadoir** [comment]
I realise this project is more-or-less unmaintained at the moment, but I thought I should record my ‘me too’ for future reference. This is the exact and only context that I need AutoKey for — simplifying input of complicated markup on websites. I used to use AutoHotKey for this purpose in Windows.

Using the keystroke method, it’s slow and unreliable with random chars missing. This actually makes debugging inserted CSS/HTML more tedious than typing it.

Using the clipboard method, AutoKey tends to hang or do nothing or both.

**Comment by ineuw** [comment]
Moilleadoir, I also use Autokey to input HTML on the Wikipedia and Wikisource on Linux. I do know that Autokey cannot input from the keyboard, or copy and paste extended ANSI characters . An interesting limitation, considering that it's Python running on Linux. But I do copy and paste from the clipboard regular characters.

if you can post a snippet of the code you are having problems with I may be able to help.

**Comment by Moilleadoir** [comment]
Actually I don’t even use code, just phrases. But even something like this regularly goes wrong.

````
<div class="img-left">
  <div class="img-polaroid img-spaced" style="text-align: center;"><img src="images/blog/2015-08-14-chinese-sparrows.jpg" alt="Two tree sparrows (Passer montanus) fight under overhanging millet" height="481" width="552" />
    <div class="figcaption" style="width: 550px; text-align: center;">Two tree sparrows (<em>Passer montanus</em>) fight under overhanging millet <a target="_blank" title="University of Cambridge Library" href="http://cudl.lib.cam.ac.uk/view/PR-FH-00910-00083-00098/35"><i class="icon-link"></i></a></div>
</div>
</div>
````

**Comment by ineuw** [comment]
This is similar to what I do but a lot more complex. Which fields are the variables?

**Comment by Moilleadoir** [comment]
No variables. It’s just saved as a ‘phrase’. I just want that dumped in on a keystroke, but I don’t get it all. Random characters are missing.

**Comment by ineuw** [comment]
Is this what you are doing? 

selected = clipboard.get_selection()
keyboard.send_key(selected)

Yes, The quotes are the problem, not the HTML. Is copy and paste manually OK?  there are some Linux software that let's you examine the clipboard contents. Unfortunately, I am in Windows now, but will try it (my) tomorrow. Also, check out some of the sample scripts, if you haven't yet done so.

**Comment by Moilleadoir** [comment]
Once again, it’s not using the script feature. It’s using the inbuilt ‘phrases’ feature.

**Comment by ineuw** [comment]
Hi Moilleadoir. I was looking to get back to you, but lost your email and couldn't find this page. For the above HTML code if there are no variables, why don't you just copy and paste?  I don't think Autokey can put such a string together. 

As for this post "Once again, it’s not using the script feature. It’s using the inbuilt ‘phrases’ feature.", I have no clue what you mean?

**Comment by Moilleadoir** [comment]
The main AutoKey window has a tree-view at the left: the top folder is for _phrases_ whose insertion can be triggered by abbreviations or keyboard shortcuts, the bottom folder is for _scripts_ that can be triggered by abbreviations or keyboard shortcuts. I’m only using the _My Phrases_ section.
![autokey](https://cloud.githubusercontent.com/assets/1229543/12285259/57da147a-ba0c-11e5-813b-73bcf9c3ec4a.jpg)

**Comment by ineuw** [comment]
I never used this feature. I always used scripts with variables. So, I
really can't help you. But, thanks for the screen shot. . . . and what is
wrong using the phrases?
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Moilleadoir** [comment]
As the OP said, random characters are missing (which is not a good thing in HTML) using the keyboard method. Using the clipboard method usually it doesn’t work at all. If the main window is open it often crashes.

**Comment by ineuw** [comment]
Have you pasted your code somewhere manually to see if it's correct?
because I pasted it into a web page but got a mess here:

https://en.wikisource.org/wiki/User:Ineuw/Sandbox8

**Comment by Moilleadoir** [comment]
A wiki is not a good way to test HTML. Perhaps wikisource don’t allow IMG tags for example?This code is for use on my Joomla! site where it works fine.

Anyway this is beside the point. More than one person has reported a problem with what the program _actually_ does. The content isn’t the issue. If the program accepts and displays your text, that’s what you expect back.

**Comment by ineuw** [comment]
I agree but it was my only quick option. Wish I could help you but Autokey
seems to go nowher and my programming knowledge is minimal.

**Comment by Moilleadoir** [comment]
No problem. I was only posting to record a ‘me too’.

**Comment by josephj11** [comment]
I don't know how to fix this one, but since it's a fairly long phrase, is
there any possibility that AutoKey may be "typing" too fast for the
receiving application?

If you're not sure, you could rewrite one phrase as a macro and put the
text of the phrase through my delay function to see if that helps.

I just added it at the end of the Contributed Scripts section of our wiki.

https://github.com/autokey/autokey/wiki/Contributed-Scripts

BTW, I assume you have installed from GitHub. If not, you may want to do
that because the latest version of AutoKey has a number of fixes for
international character sets.

https://github.com/autokey/autokey/wiki/Installing-from-GitHub

We don't have any developers at the moment, but we are keeping the project
alive and supporting it.

For support, please use
https://groups.google.com/forum/#!forum/autokey-users  . I check that quite
often, but get here infrequently. That is where almost all of our users are
who may also be able to assist you.

Joe

**Comment by Moilleadoir** [comment]
I installed from a repo but I’m pretty sure it’s the same version - 0.90.4. In any case, I’ll pursue a workaround on Google Groups.

**Comment by josephj11** [comment]
The version in our GitHub project is 0.90.4-1. It's slightly newer and was
never packaged AFAIK because it was never formally released. Best of luck.
Joer
