### ISSUE TITLE
AutoKey crashes on Ubuntu 18.10

### ISSUE THREAD

**Issue by AlienKevin** [autokey/autokey#287]
## Classification:

Crash

## Reproducibility:

Always

## Version

AutoKey version: Downloaded on May 22
Used GUI (Gtk, Qt, or both): Gtk
Installed via: ppa:sporkwitch/autokey
Linux Distribution: Ubuntu 18.10

## Summary

Abbreviation phrases disappear but the expansion is not shown. AutoKey also crashes after my first launch.

Output of `autokey-gtk --verbose`:
```bash
/usr/lib/python2.7/dist-packages/autokey/gtkapp.py:24: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, GObject, GLib
/usr/lib/python2.7/dist-packages/autokey/gtkui/notifier.py:19: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, Notify
/usr/lib/python2.7/dist-packages/autokey/gtkui/notifier.py:28: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3
/usr/lib/python2.7/dist-packages/autokey/gtkui/configwindow.py:20: PyGIWarning: GtkSource was imported without specifying a version first. Use gi.require_version('GtkSource', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Pango, GtkSource, Gdk, Gio
2019-05-22 06:33:31,784 DEBUG - root - AutoKey is already running as pid 9462
```

**Comment by luziferius** [comment]
Hmmm. There are three things with this report I’d like to point out:
- The sporkwitch Repository only offers packages for 18.04 / bionic. 
- It says `python2.7`, while AutoKey from that Repository _only_ runs on Python >= 3.5. (And Python 3 is automatically used). So you probably have mixed the version with the old 0.90.4 from the official repositories. Make sure you do NOT have mixed versions installed. Maybe the dependencies are not restrictively enough specified in this version. Both `autokey-gtk` and `autokey-common` must be on the same version. For newer Distribution releases I’d recommend [building your own packages](https://github.com/autokey/autokey/wiki/Packaging) or install the [packages attached to the GitHub release](https://github.com/autokey/autokey/releases). Here’s [HowTo](https://github.com/autokey/autokey/wiki/Installing#package-manager-installation)
 - Those are non-fatal warnings.
- The last line states that there is another instance already running. Make sure to exit all other instances. AutoKey won’t allow running multiple instances. So all but the first exit immediately, if you try.

**Comment by AlienKevin** [comment]
Thank you! After I update AutoKey to the newest version and install python3-xlib, the abbreviations are expanded properly. However, when I delete the expanded phrase, it comes back to the abbreviation. Is there a way to disable that? I just want to insert plain characters.

**Comment by luziferius** [comment]
Good to hear that you sorted out the installation issues.

This behaviour is the "undo" functionality for Phrases. It is meant to offer undo for unexpected or unwanted expansions.

You can disable this globally in the settings dialogue.

Also, undo won't happen if you do a mouse click after an expansion.
And it won't happen, if the Phrase contains any kind of special keys in the AutoKey special key syntax, e.g. `<left>` for a left arrow key press.

**Comment by AlienKevin** [comment]
Thanks. I get it.
