### ISSUE TITLE
Feature request - unfreezing the three Main window columns in the macro/script list on the left.

### ISSUE THREAD

**Issue by ineuw** [autokey/autokey#289]
## Classification:

(Pick one of: Bug, Crash/Hang/Data Loss, Performance, UI/Usability, Feature (New), Enhancement): Enhancement
## Reproducibility:

(Pick one of: Always, Sometimes, Rarely, Unable, I Didn't Try)

## Version

AutoKey version: 95.7
Used GUI (Gtk, Qt, or both): Gtk

If the problem is known to be present in more than one version, please list all of those.
not applicable
Linux Distribution: Linux Mint 19.1 Cinnamon
## Summary

Summary of the problem.
Would like to a bit more editing space when editing a macro/script
## Steps to Reproduce (if applicable)
not applicable

## Expected Results

not applicable

## Actual Results

not applicable

If helpful, submit screenshots of the issue to help debug.\
Debugging output, obtained by launching autokey via `autokey-gtk --verbose` (or `autokey-qt --verbose`, if you use the Qt interface) is also useful.\
Please upload the log somewhere accessible or put the output into a code block (enclose in triple backticks).
```not applicable
Example code block. Replace this whith your log content.
```not applicable
## Notes

Describe any debugging steps you've taken yourself.
not applicable
If you've found a workaround, please provide it here.
not applicable

**Comment by josephj11** [comment]
I'm sure you know this, but once a script has been initially saved, it will be stored under $HOME/.config/autokey/data or in your custom directory, if you defined one, and you can edit it with the text editor of your choice potentially using the full screen.

Last I looked, the edit panel in AutoKey had an invisible cursor and some other display issues.
I only use it when I'm making tiny changes like fixing typos. I do the rest in kate.

I'm not sure exactly how AutoKey handles script code, but changes made in kate seem to be immediately available the next time the script is run without doing anything else in AutoKey.

**Comment by ineuw** [comment]
This feature is not crucial, just helpful. If you take into account my level of programming skills and requirements, this data folder structure issufficient for a beginner like me. I also use gEdit on occasion.

**Comment by luziferius** [comment]
You can edit the configuration file to change the widths.
Exit AutoKey, then edit `.config/autokey/autokey.json` using a text editor. Look out for a key named `"columnWidths"`. It contains a list with three integer numbers representing the column width in pixels. Edit them to suit your needs.

I don’t know why the original author forced fixed column widths.
I’ll put this on the TODO list.

**Comment by ineuw** [comment]
Thanks for the info. This helps.

**Comment by josephj11** [comment]
I'm not facile with text editor nuances, but some of them have some pseudocode you can add in a comment in a piece of code that makes the editor recognize the script language and apply appropriate highlighting, colorization, and maybe even language specific completions. Visual brace matching ( for { [ ( ) is handy too because it will highlight the wrong brace on the other end if there's a nesting error.

Kate looks at a leading shebang for this and gedit probably does too. Since a shebang does nothing functional in contexts like this, it doesn't hurt to throw one in. (shebang is #!/usr/bin/python3 or similar on the first line of a script.)

**Comment by ineuw** [comment]
Thanks for your note about text editors' highlighting. gEdit also
highlights brackets and braces.
