### ISSUE TITLE
[BUG] ConfigObj script fails under AH but works fine in Python

### ISSUE THREAD

**Issue by Jilt6502** [autokey/autokey#292]
## Classification:

Bug

## Reproducibility:

Always occurs when Autokey is started from lxpanel version 0.9.3

## Version

AutoKey version: 

Gtk (have not tested on Qt)

If the problem is known to be present in more than one version, please list all of those.

Installed version 0.95.1 via: pip3

Linux Distribution: Lubuntu 18.04

## Summary
Example code runs perfectly if run directly ie. "python3.6 example.py"
Running example.py from within AutoKey that was launched from lxpanel give error "KeyError: 'section'"

## Steps to Reproduce (if applicable)

Run provided example script from within Autokey
Script fails with KeyError: 'section'

## Expected Results

Running from Autokey (with info_dialog line uncommented) should display an info dialog containing text "Hello World!" or running with same line commented out should silently complete successfully. In either case, the file config.ini should be created or updated when running from Autokey but it is not.

## Actual Results

- Instead, this happens. :(

If helpful, submit screenshots of the issue to help debug.\
Debugging output, obtained by launching autokey via `autokey-gtk --verbose` (or `autokey-qt --verbose`, if you use the Qt interface) is also useful.\
Please upload the log somewhere accessible or put the output into a code block (enclose in triple backticks).
```
from configobj import ConfigObj

configfile_name = "config.ini"
config = ConfigObj(configfile_name)
config['section']['key1'] = 'Hello World!'
config.write()
myMessage = config['section']['key1']
print(myMessage)
#dialog.info_dialog(title='info', message=myMessage)
```

## Notes

The only workaround I found was to run autokey from either a terminal window or from dmenu

**Comment by Jilt6502** [comment]
After posting this issue, I installed the i3 window manager and found that the script fails every time regardless of how Autokey is started, from a terminal emulator, from lxpanel, from dmenu. The fact that the script always fails allowed me to capture the debug log below:

X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 1226, sequence_number = 19, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 1226, sequence_number = 20, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 1226, sequence_number = 21, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 1226, sequence_number = 22, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 1226, sequence_number = 23, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 1226, sequence_number = 24, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 1226, sequence_number = 25, major_opcode = 33, minor_opcode = 0
2019-06-12 09:45:45,724 DEBUG - interface - __flushEvents: Entering event loop.
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 1226, sequence_number = 26, major_opcode = 33, minor_opcode = 0
2019-06-12 09:45:45,725 INFO - iomediator - Created IoMediator instance, current interface is: <XRecordInterface(XInterface-thread, initial daemon)>
2019-06-12 09:45:45,786 INFO - interface - XRecord interface thread starting
2019-06-12 09:45:45,791 INFO - service - Service now marked as running
2019-06-12 09:45:45,906 DEBUG - phrase-menu - Sorting phrase menu by usage count
2019-06-12 09:45:45,907 DEBUG - phrase-menu - Triggering menu item by position in list
2019-06-12 09:45:45,934 DEBUG - root - Created DBus service
2019-06-12 09:45:45,935 INFO - root - Displaying configuration window
2019-06-12 09:45:46,640 INFO - root - Entering main()
2019-06-12 09:45:47,757 ERROR - interface - Got BadWindow error.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/interface.py", line 1059, in get_window_title
    return self._get_window_title(windowvar, traverse)
  File "/usr/lib/python3/dist-packages/autokey/interface.py", line 1072, in _get_window_title
    atom = windowvar.get_property(self.__VisibleNameAtom, 0, 0, 255)
  File "/usr/local/lib/python3.6/dist-packages/Xlib/xobject/drawable.py", line 461, in get_property
    long_length = length)
  File "/usr/local/lib/python3.6/dist-packages/Xlib/protocol/rq.py", line 1369, in __init__
    self.reply()
  File "/usr/local/lib/python3.6/dist-packages/Xlib/protocol/rq.py", line 1389, in reply
    raise self._error
Xlib.error.BadWindow: <class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x01a000b7), sequence_number = 318, major_opcode = 20, minor_opcode = 0
autokey.interface BadWindow(<Xlib.display._BaseDisplay object at 0x7f9bad9ee160>, b'\x00\x03?\x01\xb7\x00\xa0\x01\x00\x00\x14\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
2019-06-12 09:46:01,082 DEBUG - service - Script runner executing: Script('example')
2019-06-12 09:46:01,118 ERROR - service - Script error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/service.py", line 465, in execute
    exec(script.code, scope)
  File "<string>", line 5, in <module>
  File "/usr/local/lib/python3.6/dist-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'section'

**Comment by josephj11** [comment]
This is probably way over my head, but I tried to reproduce it. I installed configobj using pip3 (It wasn't installed on my system.) I ran your code in Python3 and got this:

```
bigbird@sananda:~/sandbox/autokey_tests$ python3 configx.py
Traceback (most recent call last):
  File "configx.py", line 5, in <module>
    config['section']['key1'] = 'Hello World!'
  File "/home/bigbird/.local/lib/python3.6/site-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'section'

```
So whatever the issue is, at least part of it is independent of AutoKey (unless I don't know what I'm doing - quite likely - and didn't set something else up correctly.)

The other complaints from AutoKey look like something real, but should probably be looked at after ConfigObj() is not throwing an exception.

Is there any chance it's something like a function that changed between Python2 and Python3?
The error message seems to indicate that a dictionary entry for 'section' wasn't found and that would probably happen if your initial call to configobj() doesn't do what you think it does.
I have never seen configobj() before, so I don't know what it's supposed to do. I only know a little Python.

**Comment by Jilt6502** [comment]
What version of python3 are you using?

**Comment by Jilt6502** [comment]
Finally figured out what caused the problem. It was NOT a bug in autokey. It was the fact that config.ini did not exist in the current working directory in the cases where the script failed. Providing the full path to config.ini eliminates the problem. It would be better to have checked for the existence of the config.ini file and take appropriate action such as create a new file or inform the user that the config.ini file is not found.
