### ISSUE TITLE
is there a way to use autokey over ssh when I remote in?

### ISSUE THREAD

**Issue by careyjames** [autokey/autokey#298]
is there a way to use autokey over ssh when I remote in?

**Comment by netsec** [comment]
as in, have AHK run commands in the terminal for you?

**Comment by careyjames** [comment]
yes, exactly. so i can set key combinations to get type out really long commands and get stuff done fast.

**Comment by netsec** [comment]
^0::Sendinput, netsec@lavabit.com
^9::Sendinput, mysqladmin --force=true --user=root drop test

Ctrl + 9 would send the command "mysqladmin --force=true --user=root drop test" wherever your cursor was. obviously this can be re-engineered to solely output into a terminal window.

**Comment by careyjames** [comment]
sorry for the noob questions, I couldnt find any documentation when I used "ssh" as search parameters so just to be clear:

I'll have autokey installed on the remote machine and I'll be coming in via ssh say from my ipad using terminus or even my mac using terminal.
then if I have key commands setup in autokey on the remote machine and I press Ctrl + 9 like in your example it will execute the command?

so would the 2 examples you gave be input as scripts or phrases in autokey on remote machine?

**Comment by luziferius** [comment]
AutoKey is for GUI automation inside of X11 only.

The shell program (`bash`, `zsh`, etc.) run by `ssh` for your remote session is solely client controlled. The server can't force-push text into your locally shown shell input buffer. You can use the bashrc or similar to script your long input from within the shell.

You can run AutoKey from an ssh session, if you wish. Given the content of the `DISPLAY` environment variable, and the use or not use of the `-X` ssh switch, different things may happen, of which most combinations are useless.

If you local device runs X11 and you use the ssh `-X` switch, you can run the remote AK istallation locally. I have not tested, if this actually works. But then, you can also directly run AK locally.

If your server runs an X11 session for use with a VNC client, you can point AK to that session by simply setting `$DISPLAY` accordingly and automate the remote GUI (given that the ssh session has the permissions to access the X11 session).

In this case, you can then use AK on a terminal window (that is not `xterm`, for reasons) inside your remote VNC connected desktop to automate the commands you want to automate.

But this is a rather contrieved construction, so most probably "No". AK is not usable for server-side automation, unless that server is fully GUI controlled, like a Windows server would be.

**Comment by careyjames** [comment]
thank you!

**Comment by luziferius** [comment]
I just thought of another thing that should work: If your remote machine runs an X11 session with a running AutoKey instance, you can somewhat control it over ssh by using the DBus remote control interface. Use the `autokey-run` CLI tool that is shipped with AutoKey to trigger AK Scripts or Phrases inside the GUI session.
