### ISSUE TITLE
Move mouse without clicking?

### ISSUE THREAD

**Issue by sooqua** [autokey/autokey#299]
## Classification:
Enhancement

## Reproducibility:
Always

## Version
AutoKey version: 0.95.7

Used GUI: Gtk

Installed via: yay

Linux Distribution: arch

## Summary
There seem to be no method to move the mouse without clicking it

## Expected Results
Being able to move the mouse without clicking

## Actual Results
Not being able to move the mouse without clicking

**Comment by sooqua** [comment]
Used PyUserInput. Still think autokey should be able to do this without installing additional packages.

**Comment by sooqua** [comment]
nvm

**Comment by josephj11** [comment]
There has been some discussion of this inability, but I don't think any work has been done to add the capability. You can turn this into an enhancement request if you want to.

**Comment by sooqua** [comment]
I don't. I wanted to make a script to move the mouse to the bottom right corner because it gets annoying sometimes and I _hate_ to take my hands off the home row, but I found a [better solution](https://github.com/ckath/xbanish-timeout).
Other than that, there's probably no reason to move the mouse without clicking it (:

**Comment by josephj11** [comment]
xbanish is cool! I'm trying it out on my system now. Thanks for the link.

Mouse movement by itself could be useful in some situations:
Move to a field where the user has to decide what to do
Move to a field where hovering produces an effect such as selecting an object or displaying a tooltip
Move away from a field so the next input won't change an entry unintentionally
Visual animation effects
...
But, it's not a big deal at the moment.

**Comment by luziferius** [comment]
It was an oversight when the original developer implemented the API. He either didn’t think it was needed or it was just forgotten.
It is on the current TODO list, but will probably take some time to implement. Doing bare mouse movement is not that useful, if you can have proper support with optionally holding mouse buttons to implement drag&drop, etc.

**Comment by sl5net** [comment]
use autopilot https://stackoverflow.com/questions/63375098/move-mouse-relatively-in-linux

**Comment by josephj11** [comment]
I thought I had the autokey tag watched over there. I guess not. Now I have to review all those questions I missed.
