### ISSUE TITLE
Duplicated initial character of a expanded phrase

### ISSUE THREAD

**Issue by QiangF** [autokey/autokey#32]
The abbreviation for the phrase is g123
The phrase is g12345
Trigger setting is: remove abbraviation and immediatly.
The result is not consistent, sometimes the initial g is duplicated.
I am using autokey-gtk 0.90.4

**Comment by josephj11** [comment]
This looks like a problem, but we need more information to duplicate and debug it.

Standard reply to all such questions:

FAQ #1: When AutoKey does something unfortunate, document your problem by specifying:
exactly what you did, including a copy of your macro or phrase,
what it did,
what you expected it to do,
*and*
providing us with a trace log and a description of:

your OS/version
desktop manager/version
AutoKey version

and anything else you think might be relevant.

Quit AutoKey if it is currently running.

Start AutoKey from a terminal window.
Then, do the minimum required to recreate your issue and then stop AutoKey.

autokey-gtk -l
or
autokey-qt -l

depending on which version of autokey you have installed. That's a lower case "ell".

This will produce a log in the terminal window of what AutoKey is doing.

It will probably show you what is wrong.

If it doesn't make sense or you have further questions, copy and paste the log output from the terminal window into a post to this list and we'll take a look at it.

Joe

**Comment by QiangF** [comment]
Hi Joe,
Thank you for these detailed instructions. I am running Openbox 3.5.2 on debian 8.0 jessie.
Autokey version is autokey-gtk 0.90.4.
The abbreviation for the phrase is g123
The phrase is g12345
Trigger setting is: remove abbraviation and immediatly.
The result is not consistent, sometimes the initial g is duplicated.
In the log file I see there are 4 backspace sent before the expansion, but there is an error:
service - Ignored locking error in handle_keypress

log:
The following happens in chronic order, all lines has a common header like
(time stamp debug -) 2015-11-10 09:15:37,364 DEBUG -

    service - Raw key: u'g', modifiers: [], Key: g
    service - Window visible title: u'New Tab - Iceweasel', Window class: 'Navigator.Iceweasel'
    service - No phrase/script matched hotkey
    service - Input stack at end of handle_keypress: [u'g']
    service - Raw key: u'1', modifiers: [], Key: 1
    service - Window visible title: u'New Tab - Iceweasel', Window class: 'Navigator.Iceweasel'
    service - No phrase/script matched hotkey
    service - Input stack at end of handle_keypress: [u'g', u'1']
    service - Raw key: u'2', modifiers: [], Key: 2
    service - Window visible title: u'New Tab - Iceweasel', Window class: 'Navigator.Iceweasel'
    service - No phrase/script matched hotkey
    service - Input stack at end of handle_keypress: [u'g', u'1', u'2']
    service - Raw key: u'3', modifiers: [], Key: 3
    service - Window visible title: u'New Tab - Iceweasel', Window class: 'Navigator.Iceweasel'
    service - No phrase/script matched hotkey
    service - Input stack at end of handle_keypress: []
    service - Ignored locking error in handle_keypress
    iomediator - Send via event interface
    interface - Send special key: ['<backspace>']
    interface - Send special key: ['<backspace>']
    interface - Send special key: ['<backspace>']
    interface - Send special key: ['<backspace>']
    interface - Sending string: u'g12345'
    iomediator - <alt> pressed
    service - Raw key: '<tab>', modifiers: ['<alt>'], Key: <tab>
    service - Window visible title: u'New Tab - Iceweasel', Window class: 'Navigator.Iceweasel'
    service - No phrase/script matched hotkey
    iomediator - <alt> released
    service - Received mouse click - resetting buffer

**Comment by QiangF** [comment]
This is the string I get if I repeatedly typing 'g123'
gg12345gg12345g12345g12345g12345gg12345g12345g12345g1g12345g12345

**Comment by josephj11** [comment]
I don't know what the locking error thing is, but I've seen it many times
and it doesn't seem to cause any errors.

The AutoKey trace looks exactly like it should - like AutoKey worked
perfectly.

People have noted quite a few problems when using AutoKey with Firefox (and
probably Iceweasel, by extension).

I forget if you already tried this, but see how your phrase works
somewhere else like in a terminal or in an editor like gedit. If it's fine,
then the problem is Mozilla-related (not saying whose bug it is).

A possible workaround would be to write things like this as macros instead
of phrases. Then, you can take the string of characters and send it one
character at a time with a small delay between each keypress.

import time
delay = 0.1 ## seconds - adjust value as needed
keyboard.send_keys("g")
time.sleep(delay)
...

keyboard.send_keys("5")
time.sleep(delay)

Since coding this manually is a PITA, I'll try to write a function which
automates it. Then people who run into problems like this can put it in
their modules directory and call it from whatever macros need it.

Joe

**Comment by QiangF** [comment]
Thank you Joe. It works!

**Comment by josephj11** [comment]
I just wrote the following function to make this easier to use. You can include it in any macro definition which needs it.

import time

## Type a string character by character
##   from within AutoKey
##   with a small delay between characters
def type_slow(string, delay=0.1):
  if delay < 0:
    delay = 0

  for c in string:
    keyboard.send_key(c)
    time.sleep(delay)

**Comment by josephj11** [comment]
I just wrote a function to automate this, but when I pasted it here, the markdown language ate it. I posted it on the AutoKey mailing list as part of a question about how to use it as a module.

[autokey_type_slow.py.txt](https://github.com/autokey/autokey/files/33554/autokey_type_slow.py.txt)

Joe
