### ISSUE TITLE
Autokey broken with update to python 3.8?

### ISSUE THREAD

**Issue by prosoitos** [autokey/autokey#323]
## Classification:

Bug??

## Reproducibility:

Always

## Version

AutoKey version: 0.95.8-1

Used GUI (Gtk, Qt, or both): gtk

Installed via: from the AUR

Linux Distribution: Arch Linux

## Summary

I just updated to python 3.8 and can't launch autokey anymore. This is the message I get:

```
Traceback (most recent call last):
  File "/usr/bin/autokey-gtk", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'autokey==0.95.7' distribution was not found and is required by the application
```

Note: as I updated my system, I did get a warning about a python dependency cycle detected. So it might be that there is nothing to do on your end and that some of the python 3.8 dependencies will be updated on Arch Linux in the coming few days and that things will go back to normal. Nothing else seems to be broken on my system though.

Another application I use has to be uninstalled and re-installed after each python major update (and I get a very similar error message). So I tried to uninstall and re-install autokey, but that didn't do the trick.

**Comment by luziferius** [comment]
You probably have to reinstall the application. I think this happens any time a major Python update is pushed to the Arch repositories.

**Comment by prosoitos** [comment]
I did try this several time. But while it fixed my problem with the other app, it doesn't seem to work with autokey.

**Comment by prosoitos** [comment]
OK, my bad: with the other package, I simply had to uninstall and re-install. While in the case of autokey, I actually had to re-build the package. I hadn't tried this. Sorry for the noise. I will know it for the next python update!

**Comment by luziferius** [comment]
No Problem. ;)

Building creates Python Bytecode (.pyc) which is bound to a specific major/minor version (3.5, 3.6, 3.7, etc.). The Arch package installs that Bytecode _only_. (But not for the generated launcher script.) The bytecode files have the required Python version in the file name. Thus 3.8 loads the source code launcher, which can't find the bytecode by name (it loos for a different file name). And therefore can't find the installation. (As the error message says.)

This is why a full rebuild is required.
Regular Arch packages get that rebuild done by the Repo maintainers. AUR users are on their own in this regard.

**Comment by prosoitos** [comment]
I see. Thanks! Not sure why the other package (also from the AUR) didn't need one then.

Oh well. I am all sorted :) Thank you once more for your time and help! :)

**Comment by luziferius** [comment]
> I see. Thanks! Not sure why the other package (also from the AUR) didn't need one then.
> 
> Oh well. I am all sorted :) Thank you once more for your time and help! :)

The packages that don’t require rebuilds most probably run the source code. Then this issue doesn’t happen. It simply depends on how the AUR maintainer writes the build script.

**Comment by prosoitos** [comment]
I see. Thanks :slightly_smiling_face:
