### ISSUE TITLE
Now that Autokey google forums is closed, is there a place where we could share our scripts with others?

### ISSUE THREAD

**Issue by stepnjump** [autokey/autokey#329]
## Classification:

(Pick one of: Bug, Crash/Hang/Data Loss, Performance, UI/Usability, Feature (New), Enhancement)

## Reproducibility:

(Pick one of: Always, Sometimes, Rarely, Unable, I Didn't Try)

## Version

AutoKey version: 

Used GUI (Gtk, Qt, or both): 

If the problem is known to be present in more than one version, please list all of those.

Installed via: (PPA, pip3, …).

Linux Distribution:

## Summary

Summary of the problem.

## Steps to Reproduce (if applicable)

- I do this
- I do that

## Expected Results

- This should happen.

## Actual Results

- Instead, this happens. :(

If helpful, submit screenshots of the issue to help debug.\
Debugging output, obtained by launching autokey via `autokey-gtk --verbose` (or `autokey-qt --verbose`, if you use the Qt interface) is also useful.\
Please upload the log somewhere accessible or put the output into a code block (enclose in triple backticks).
```
Example code block. Replace this whith your log content.
```

## Notes

Describe any debugging steps you've taken yourself.

If you've found a workaround, please provide it here.

**Comment by josephj11** [comment]
Thanks for wanting to share!

There are a few places to share scripts, etc.:

If you have something you think would be of general interest, you can add it to our [wiki](https://github.com/autokey/autokey/wiki).
There are several pages with example scripts although the whole thing really needs to be reorganized.

Anyone with a GitHub account can edit our wiki. If you want to do major work or change things around, etc., then it would be good to discuss that on Gitter first (see below).

If it's something to discuss, then you can post it to our [forum/list](https://groups.google.com/forum/#!forum/autokey-users).

For more advanced topics, our [Gitter](https://gitter.im/autokey/autokey) page is best. Our developer(s) hang out there.

Looking forward to your contributions!
