### ISSUE TITLE
How can I backup and restore my AutoKey Abbreviations and Hotkeys?

### ISSUE THREAD

**Issue by Yekutiel** [autokey/autokey#333]
I have successfully restored my AutoKey phrases and scripts from `~/.config/autokey`.

However, how can I restore my AutoKey Abbreviations and Hotkeys associated with those phrases and scripts?

Here's my problem: after I restore my AutoKey phrases and scripts from `~/.config/autokey` I find that I then need to recreate my AutoKey Abbreviations and Hotkeys because they will have "disappeared."

**Comment by josephj11** [comment]
The first thing to check: Did you backup and restore the hidden .json files associated with each script and phrase? That's where AutoKey keeps the configurations for each script. When AutoKey starts, it reads those files and sets everything up.

Currently, AutoKey does not rescan these files if they change, so when you modify them externally from AutoKey, you have to restart AutoKey for the changes to take effect.

The actual content of scripts and phrases is not cached anywhere, so changes made to them take effect immediately. It's just the configurations which are not automatically updated.

When you have a question like this which has not risen to the level of a bug or feature  request, it's best to ask it  on our [support list](https://groups.google.com/forum/#!forum/autokey-users) or, for more advanced questions, on [Gitter](https://gitter.im/autokey/autokey). This allows the developers to stay focused on developing and there are many more people there who can see and help with solutions.

**Comment by Yekutiel** [comment]
Hi Joe,
 
Thanks for getting back to me quickly with a useful suggestion. I solved the problem!
 
It turns out that when I backed up `~/.config/autokey` to Google Drive and then downloaded `~/.config/autokey` from Google Drive to another computer, my AutoKey Abbreviations and Hotkeys failed to be restored although, strangely, my AutoKey Phrases and Scripts were successfully restored. However when I manually created a TAR file of `~/.config/autokey`, and then uploaded that TAR file to Google Drive from computer number 1 of mine, and then downloaded and extracted that TAR file from Google Drive to computer number 2 of mine, I was able to successfully restore my AutoKey Phrases and Scripts along with my corresponding AutoKey Abbreviations and Shortcut keys.
 
Thanks again for your help Joe,
 
Yekutiel

**Comment by josephj11** [comment]
Glad to know it's sorted. The use of a period to make files hidden is a Linux thing and it can make for difficulties transferring files between other systems. Putting it all in a tarball insulated it from anything on Google Drive.

There has been some discussion of getting rid of the hidden file thing in AutoKey for the config files (while maintaining compatibility with existing scripts and phrases), but it's just talk so far. The current "feature" really doesn't have any advantages and regularly causes problems such as those you experienced.

I just filed issue #337 which proposes to eliminate this problem.

**Comment by Yekutiel** [comment]
"Weinberg's Second Law: If builders built buildings the way programmers wrote programs, then the first woodpecker that came along would destroy civilization." [Gerald Weinberg](https://en.wikiquote.org/wiki/Gerald_Weinberg)

From the perspective of ordinary people, engineers often make inane decisions because engineers do not think like ordinary people.

**Comment by josephj11** [comment]
Actually, there's some hope on that front. With functional programming languages such as Haskell, it is possible to write provably correct programs. There was a military hacking test recently where a critical part of a system was written that way and hackers were given access to other subsystems, but could not break into the critical subsystem.

However, that doesn't address the second, separate concern of programmers' world views. I'm not sure much can be done about that other than having a strong beta testing effort using typical end users and management that stays focused on real world scenarios.

Here, in this small project, we'll just have to rely on you. ;)
