### ISSUE TITLE
Stop hiding the sidecar files for phrases and scripts

### ISSUE THREAD

**Issue by josephj11** [autokey/autokey#337]
## Reproducibility: N/A

AutoKey version: N/A

Linux Distribution: N/A

## Summary

All phrases and scripts have sidecar .json files which hold all the metadata that AutoKey needs to make them work. The original/current design is to name these files the same name as the script/phrase, but with a leading period to make them hidden files.

As far as I can see, there is no advantage to doing this and it causes a lot of support issues and extra explanations.

Please eliminate the leading period in the names of these sidecar files.

We obviously need to maintain compatibility with existing phrases and scripts. Or, as Thomas has suggested, we could automatically convert existing phrases and scripts to the new format.

**Comment by luziferius** [comment]
No objection from my side.

By default everything is kept below `.config/autokey`, so it shouldn’t make any major difference in the overall appearance for the average user who does not add external directories.

Unhiding the files should indeed ease the maintenance for users and supporters.

Writing a migration task should not be that hard. There are already a bunch in the code.
The only issue that can create an arbitrary high amount of complexity is trying to solve hypothetical issues, like: What if users have AutoKey folders on disconnected external media? Burnt on CD-R or placed in read-only file systems? (But those are corner cases anyways.)

**Comment by BlueDrink9** [comment]
OOoooh, that's where those files are! That should be documented somewhere! I spent ages looking in .config/autokey trying to figure out why I needed to manually add new folders.

I take it back, all that's in .local/share/autokey is the log file.

Regarding the backporting issue... We're making a lot of new changes from the legacy. At what point should we consider saying 'this is a totally new version, old stuff won't work/will need explicit conversion'?

**Comment by luziferius** [comment]
@BlueDrink9 Sorry. I quoted the wrong path. The correct one is `~/.config/autokey/`.
It contains `autokey.json` and a `data` directory that is used as the default location when creating new top-level folders in AutoKey.

**Comment by herrdeh** [comment]
I'm the culprit... (;
I tried to share my autokey files via owncloud on various machines and wondered why that does not work...  Being an autokey addict, it's frustrating having to set up phrases freshly on each machine you're working.

Special thanks to @ josephj11 to have opened this issue!

**Comment by xpusostomos** [comment]
I added a pull request:

https://github.com/autokey/autokey/pull/430

**Comment by BlueDrink9** [comment]
@josephj11 this can be closed I think

**Comment by josephj11** [comment]
How are we handling legacy files? Is there a conversion, etc.? Once I know we're OK on that, I'll close this issue.
I'd like to see the changelog entry for this. We will need to announce this when it goes into production.

Do we have a change log anywhere?

I envision running my daily rsync backup and suddenly seeing all those files getting deleted from my backup and panicking.

**Comment by BlueDrink9** [comment]
Good point. According to the code, it converts sidecars for versions prior by removing the dot.

The PR only merged into the dev branch though so probably won't be released until 0.96

**Comment by BlueDrink9** [comment]
I'm still of the opinion that this should be closed, since it is now fixed in develop (which is how closing issues normally behaves)

**Comment by josephj11** [comment]
Since this is in develop, I'm closing it.
