### ISSUE TITLE
Make all code that updates/views/removes folders/phrases be run through engine.py

### ISSUE THREAD

**Issue by BlueDrink9** [autokey/autokey#341]
I've noticed there are bits and pieces of functional code unrelated to the GUI that is present (often duplicated) in the GUI apps.

I think we should refactor out all of this into its own file. I think that, ultimately, we want all the code that creates, retrieves or removes folders, phrases, hotkeys etc. to be in one class only, so that all apps and APIs etc go through that class.

It seems logical to use `engine.py` for this, so that the scripting api will always have the same power as the gui apps, if not more. Also, they already have the docstrings for the functions, so it would be easier for collaborators to understand the core code.

The downside is that I don't know if code for running scripts fits together with modifying items.

I'd also like to combine functions like run_script and run_subscript, because they feel like duplicated code.

I also want to refactor the UIs such that any code related to the `app` setup is separate, since that could be shared also.

Doing this will help keep the two UIs more separated, and make it easier to create new UIs if we wanted to.

**Comment by luziferius** [comment]
You mean `autokey.scripting.engine`? That file should only define the API functions for the scripting API. Like the other files inside that package.

But yes, there is quite some duplicated logic in the GUIs. I think, the GTK GUI was the initial one, which already contained some "business logic" bits at the time of creation. Then the Qt/KDE GUI was created as a direct port, which copied the logic. Then both started to diverge as more contributors stuffed logic into the GTK GUI code and not porting it to the Qt GUI, which was mostly unmaintained.

The ultimate solution is ripping out all required logic and place it into common controller modules. Then both GUIs (and the scripting API) work using the same logic.

**Comment by BlueDrink9** [comment]
Yup. Then I think we should make a lot of the functions in `scripting.engine.py` just wrappers, and move the logic to a common control module. Any thoughts on what to call it?

**Comment by dulm** [comment]
I have the same require. 
I used to use osx, and use hammerspoon as a key mapping tool,  i wrote a script  https://gist.github.com/dulm/ee5ec47cfd2a71ded0e3841ee04e6ea3 ,   it could detect current app, then use different key binding.

Now i turn to linux,   and find autokey have all the basic functional:  active window detection and  listener with callback,  key listener with callback,  key press api;    and haven't found any other linux tool have these basic functional. 

but autokey hide the functional behind the gui,  the gui can  activate the key binding for diffrent window class,  but the https://autokey.github.io/   have not app change callback api.
And in gui,  key is basic unit, you need to activate key for different app;  not managed in the unit of app, which is more  intuitive

So I hope, autokey can split into two project : 1. python  package,  with all basic and essential api, and a main event loop,  can run in a standalone  python project .  2. current auto gui tool.   it will be more power full.

**Comment by josephj11** [comment]
@BlueDrink9 and @sebastiansam55 : Isn't a large part of this already implemented? Seems like it was discussed a lot.

**Comment by BlueDrink9** [comment]
Lots but not quite all. Probably enough to close this tho
