### ISSUE TITLE
Keyboard send_keys with "paste_using" option

### ISSUE THREAD

**Issue by kolibril13** [autokey/autokey#348]
Hi,
Is it possible to add a  `paste_using="ctrl+v"` option to send_keys?
e.g. my code looks like this
```py
text = clipboard.get_clipboard()
import os
name = '```py'+ os.linesep +  text  + os.linesep + "```"
keyboard.send_keys(name)
```
And it would be nice, if every character is not written one by one, but all pasted immediately, 
This could be very useful. And autokey already supports something similar for phrases, like here:
![aa](https://user-images.githubusercontent.com/44469195/71719410-92804d80-2e1e-11ea-815e-0d5a93ed9dd3.png)

**Comment by luziferius** [comment]
It is possible and in fact, I’ve added this functionality some time ago. ;) This will be one of the new features in 0.96, along some more improvements to the API:

Here is the new signature of the send_keys() function that’ll make it possible to use any of the paste modes in this function (ignore the `self`):
https://github.com/autokey/autokey/blob/bc3e656fe37770a0452e54c90ca73d89a886b86e/lib/autokey/scripting/keyboard.py#L30

But I’ll take your suggestion and rename the parameter I added to something else. Maybe I’ll take your suggested `paste_using` or use `send_using`.

**Comment by kolibril13** [comment]
Wow, that's nice!
Maybe we can make it consistent with the phrase settings pasting.
So when it's `send_using` also the textbox from my screenshot could be changed to `Send using`

**Comment by luziferius** [comment]
> Maybe we can make it consistent with the phrase settings pasting.

Good idea.
