### ISSUE TITLE
Allow creating/setting custom paste modes

### ISSUE THREAD

**Issue by luziferius** [autokey/autokey#349]
## Classification:

Enhancement

## Summary

Currently, text can be send by:

- typing with the keyboard
- pasting via X11 PRIMARY buffers (mouse middle click)
- pasting using one of the predefined keyboard combinations

But if an application uses a custom paste shortcut, pasting with the clipboard becomes impossible.
So add the possibility to use any string as the paste command.

### Required changes:

- Replace the `Paste using:` drop-down with an editable drop-down menu. (Both Qt and GTK GUI)
  ![current GTK GUI screenshot showing the Paste using drop down menu](https://user-images.githubusercontent.com/44469195/71719410-92804d80-2e1e-11ea-815e-0d5a93ed9dd3.png)
- Populate the available choices with the set union of the default choices and all user-defined choices. If a user uses this feature, they most probably use it on multiple Phrases. So making already created custom choices easily available makes the UI easier to use.
- https://github.com/autokey/autokey/blob/bc3e656fe37770a0452e54c90ca73d89a886b86e/lib/autokey/scripting/keyboard.py#L30 Update `keyboard.send_keys()` to work with arbitrary strings as paste commands.
- When loading the settings, try to convert the read value into one of the known values. If it fails, interpret the read data as a custom paste command.  

## Notes

- When using this feature, the user is responsible to provide a text that causes the clipboard to be pasted when typed using the keyboard. If the user fails to do so, pasting will fail and the undo functionality will break.
- I’m not sure how many applications don’t use one of the three default keyboard shortcuts, 
so I’m not sure how useful this’ll be.

**Comment by josephj11** [comment]
I didn't know this issue existed and i have never seen it requested so I'm closing this issue.
