### ISSUE TITLE
AppImage support

### ISSUE THREAD

**Issue by maverick74** [autokey/autokey#350]
## Classification:

Enhancement

## Reproducibility:

Always

Linux Distribution:
openSUSE / All

## Summary

It would be great to have an AppImage of AutoKey so that one could carry it everywhere :)

**Comment by josephj11** [comment]
Closing this based on lack of activity.

Don't personally see any need for this since AutoKey is basically a source package and installing dependencies isn't usually that difficult. This might change if someone wants to run it as an X11 app on a system that only has Wayland enabled.

**Comment by ikabod** [comment]
I'm using Manjaro and autokey is not in the official packages (must be build through AUR).

In the past autokey was multiple times not working after an system update anymore and must be rebuild again.

So for Manjaro/Arch users an AppImage would be a good alternative.

**Comment by maverick74** [comment]
i don't really imagine newbies or people that come from windows building it from source and installing dependencies. AppImage would "just work"... so it would be a nice addition IYAM...

**Comment by josephj11** [comment]
@maverick74 aside from advising newbies to avoid advanced distros such as Gentoo and Arch, an AppImage would be great. It might also help with testing because you don't need a VM for initial testing on environments that are different than your native install.
