### ISSUE TITLE
How to uninstall Autokey.

### ISSUE THREAD

**Issue by deragon** [autokey/autokey#352]
## Classification:

Enhancement

## Reproducibility:

Always

## Version

Unimportant

## Summary

How does one uninstall Autokey?

From the wiki:  https://github.com/autokey/autokey/wiki/Installing

> Removing Existing AutoKey
> ...
> 3. Uninstall the existing AutoKey

So... what files should be deleted?  Ideally, a script should be provided.  Some script named `autokey-uninstall` for instance.

**Comment by deragon** [comment]
BTW, I want to fully uninstall it to reinstall from scratch.  I have a bug where the icon does not appear in the app indicator bar, but I want to reinstall cleanly before reporting that bug.

**Comment by luziferius** [comment]
Depends on how it was installed.
- If it was installed from a package manager, use that to uninstall it again.
- If it was installed using `pip3`, use `pip3 uninstall autokey` on the terminal to uninstall it.
  - If it was installed using `pip3 install --user autokey` (without root rights), run `pip3 uninstall --user autokey` as the user who installed it. This depends on how `pip3` is configured by your distribution: On Debian, `pip3` defaults to use the `--user` switch, but other distributions do not configure `pip3` that way. (The last remark is only true, if you did not use `pip3` to upgrade itself, as that will overwrite with the default configuration …)
  - If it was installed to the system (i.e. to `/usr/local`), run `pip3 uninstall autokey` as root.
- If you managed to install AutoKey to a Python virtual environment, activate the virtual environment prior to running `pip3 uninstall`.

If you want to purge all configuration, also manually delete or move `$HOME/.config/autokey` and possibly the log files under `$HOME/.local/share/autokey`, even if they don’t cause harm. (Package managers will never automatically touch user data in $HOME.)

Edit: BTW: Which version do you want to install? I recommend grabbing the latest version from here: https://github.com/autokey/autokey/releases

**Comment by BlueDrink9** [comment]
*`~/.config/autohotkey`, not share

**Comment by luziferius** [comment]
> *`~/.config/autohotkey`, not share

You’re right. Edited my answer (and mentioned the log files under `.local/share/autokey`)

**Comment by deragon** [comment]
Why not add these instructions in the official documentation?  Why not simply provide a script that does all of this magically?  Take for instance my own FOSS project which provides easy means to uninstall the software: [Autopoweroff - Uninstallation](https://github.com/deragon/autopoweroff#Uninstallation)

**Comment by BlueDrink9** [comment]
@luziferius are you sure that the .config dir is the only place configuration is stored? I ran into an issue when I first started using autokey, that copying this folder didn't replace phrases (or some other behavior). is it possible autokey is storing state anywhere else?

**Comment by deragon** [comment]
I installed the software from the Git repository following the instructions in `INSTALL`:

`sudo python3 setup.py install`

How do I uninstall in this scenario?

**Comment by luziferius** [comment]
> I installed the software from the Git repository following the instructions in `INSTALL`:
> 
> `sudo python3 setup.py install`
> 
> How do I uninstall in this scenario?

`sudo pip3 uninstall autokey`. Then manually remove the executables.
INSTALL has to be updated: The currently recommended way is installing via `pip3 install .`
Edit: Updated INSTALL to reflect the current best practice: https://github.com/autokey/autokey/commit/6cf2fa6bd21f334d024633b7a6c2071dc567ddb1


When using `sudo python3 setup.py install`, removing via `pip3 uninstall autokey` does not delete the automatically generated executables that are placed in your $PATH.

So:
- `pip3 uninstall autokey`
- Find the remaining executables via `which autokey-qt` and `which autokey-gtk` and manually remove them.

**Comment by deragon** [comment]
I uninstalled with instructions found at [python setup.py uninstall](https://stackoverflow.com/questions/1550226/python-setup-py-uninstall).  I then reinstalled with `sudo pip3 install .`.

Now, the icon shows up!  But it is way to dark... Why is that?  Another bug?  Should I open a new issue for it?

![Autokey - Tray icon too dark](https://user-images.githubusercontent.com/7698377/75639088-1d9e7980-5bfd-11ea-8515-0e11122e69de.png)

**Comment by deragon** [comment]
I uninstalled with instructions found at [python setup.py uninstall](https://stackoverflow.com/questions/1550226/python-setup-py-uninstall).  The specific instructions are:

> To record a list of installed files, you can use:
> 
> sudo python3 setup.py install --record files.txt
>
> Once you want to uninstall you can use xargs to do the removal:
> 
> sudo xargs rm -rf < files.txt
