### ISSUE TITLE
v0.95.10 randomly consume 100% of the CPU and also silently crashs

### ISSUE THREAD

**Issue by MR-Diamond** [autokey/autokey#368]
## Classification:

Bug and crash

## Reproducibility:

sometimes

## Version

AutoKey version: 0.95.10-1

Used GUI (Gtk, Qt, or both): 
both

AUR repo: https://aur.archlinux.org/packages/autokey

Linux Distribution:

Manjaro Linux XFCE 64 bit, kernel 4.14.170-1-MANJARO

## What happens:

Yestarday I updated AutoKey from 0.95.9-1 to 0.95.10-1

And I encounter some issues: the first is that it randomly starts to increase the CPU usage to 100% (without using the GUI and nothing else).

The second issue is that will also randomly stop to work (I cannot use the shortcuts and scripts) because silently crashs: I investigated in the Journal logs:

```
feb 18 06:59:07 systemd-coredump[2611]: Process 1166 (autokey-gtk) of user 1000 dumped core.
                                        
Stack trace of thread 2606:
#0  0x00007fb454f33f25 raise (libc.so.6)
#1  0x00007fb454f1d897 abort (libc.so.6)
#2  0x00007fb454f1d767 __assert_fail_base.cold (libc.so.6)
#3  0x00007fb454f2c526 __assert_fail (libc.so.6)
#4  0x00007fb4530229f9 n/a (libX11.so.6)
#5  0x00007fb453022a9e n/a (libX11.so.6)
#6  0x00007fb453022f12 _XReadEvents (libX11.so.6)
#7  0x00007fb45300a356 XIfEvent (libX11.so.6)
#8  0x00007fb45288626f gdk_x11_get_server_time (libgdk-3.so.0)
#9  0x00007fb451fd38a4 n/a (libgtk-3.so.0)
#10 0x00007fb451fd3aa8 n/a (libgtk-3.so.0)
#11 0x00007fb453794d5a g_closure_invoke (libgobject-2.0.so.0)
#12 0x00007fb4537829e4 n/a (libgobject-2.0.so.0)
#13 0x00007fb45378698a g_signal_emit_valist (libgobject-2.0.so.0)
#14 0x00007fb4537877f0 g_signal_emit (libgobject-2.0.so.0)
#15 0x00007fb451fd1cdd gtk_widget_realize (libgtk-3.so.0)
#16 0x00007fb45207102e n/a (libgtk-3.so.0)
#17 0x00007fb453794d5a g_closure_invoke (libgobject-2.0.so.0)
#18 0x00007fb4537829e4 n/a (libgobject-2.0.so.0)
#19 0x00007fb45378698a g_signal_emit_valist (libgobject-2.0.so.0)
#20 0x00007fb4537877f0 g_signal_emit (libgobject-2.0.so.0)
#21 0x00007fb45208b5da gtk_widget_show (libgtk-3.so.0)
#22 0x00007fb452027c97 gtk_status_icon_set_visible (libgtk-3.so.0)
#23 0x00007fb4504c6c0e n/a (libappindicator3.so.1)
#24 0x00007fb453794d5a g_closure_invoke (libgobject-2.0.so.0)
#25 0x00007fb45378288e n/a (libgobject-2.0.so.0)
#26 0x00007fb45378698a g_signal_emit_valist (libgobject-2.0.so.0)
#27 0x00007fb4537877f0 g_signal_emit (libgobject-2.0.so.0)
#28 0x00007fb4504c555c app_indicator_set_status (libappindicator3.so.1)
#29 0x00007fb45375e69a ffi_call_unix64 (libffi.so.6)
#30 0x00007fb45375dfb6 ffi_call (libffi.so.6)
#31 0x00007fb4537fb392 n/a (_gi.cpython-38-x86_64-linux-gnu.so)
#32 0x00007fb4537fa972 n/a (_gi.cpython-38-x86_64-linux-gnu.so)
#33 0x00007fb45380049e n/a (_gi.cpython-38-x86_64-linux-gnu.so)
#34 0x00007fb454c6fad2 _PyObject_MakeTpCall (libpython3.8.so.1.0)
#35 0x00007fb454d2c7f4 _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#36 0x00007fb454d1606d _PyFunction_Vectorcall (libpython3.8.so.1.0)
#37 0x00007fb454d280ce _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#38 0x00007fb454d1606d _PyFunction_Vectorcall (libpython3.8.so.1.0)
#39 0x00007fb454d280ce _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#40 0x00007fb454d14e3b _PyEval_EvalCodeWithName (libpython3.8.so.1.0)
#41 0x00007fb454d1624b _PyFunction_Vectorcall (libpython3.8.so.1.0)
#42 0x00007fb454c6730d PyObject_Call (libpython3.8.so.1.0)
#43 0x00007fb454d29d03 _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#44 0x00007fb454d1606d _PyFunction_Vectorcall (libpython3.8.so.1.0)
#45 0x00007fb454d280ce _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#46 0x00007fb454d1606d _PyFunction_Vectorcall (libpython3.8.so.1.0)
#47 0x00007fb454d280ce _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#48 0x00007fb454d1606d _PyFunction_Vectorcall (libpython3.8.so.1.0)
#49 0x00007fb454d16a7b n/a (libpython3.8.so.1.0)
#50 0x00007fb454c6730d PyObject_Call (libpython3.8.so.1.0)
#51 0x00007fb454d7c4e1 n/a (libpython3.8.so.1.0)
#52 0x00007fb454d368f4 n/a (libpython3.8.so.1.0)
#53 0x00007fb454b204cf start_thread (libpthread.so.0)
#54 0x00007fb454ff72d3 __clone (libc.so.6)

Stack trace of thread 1166:
#0  0x00007fb454fe84cf write (libc.so.6)
#1  0x00007fb454ba2380 _Py_write_noraise (libpython3.8.so.1.0)
#2  0x00007fb454bb0d60 n/a (libpython3.8.so.1.0)
#3  0x00007fb454f33fb0 __restore_rt (libc.so.6)
#4  0x00007fb454f33f25 raise (libc.so.6)
#5  0x00007fb454f1d897 abort (libc.so.6)
#6  0x00007fb454f1d767 __assert_fail_base.cold (libc.so.6)
#7  0x00007fb454f2c526 __assert_fail (libc.so.6)
#8  0x00007fb453022984 n/a (libX11.so.6)
#9  0x00007fb453022add n/a (libX11.so.6)
#10 0x00007fb453022d92 _XEventsQueued (libX11.so.6)
#11 0x00007fb453014782 XPending (libX11.so.6)
#12 0x00007fb45289aa00 n/a (libgdk-3.so.0)
#13 0x00007fb453910a00 g_main_context_prepare (libglib-2.0.so.0)
#14 0x00007fb453911046 n/a (libglib-2.0.so.0)
#15 0x00007fb4539120c3 g_main_loop_run (libglib-2.0.so.0)
#16 0x00007fb4521cb9ef gtk_main (libgtk-3.so.0)
#17 0x00007fb45375e69a ffi_call_unix64 (libffi.so.6)
#18 0x00007fb45375dfb6 ffi_call (libffi.so.6)
#19 0x00007fb4537fb392 n/a (_gi.cpython-38-x86_64-linux-gnu.so)
#20 0x00007fb4537fa972 n/a (_gi.cpython-38-x86_64-linux-gnu.so)
#21 0x00007fb454c673a0 PyObject_Call (libpython3.8.so.1.0)
#22 0x00007fb454d29d03 _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#23 0x00007fb454d14e3b _PyEval_EvalCodeWithName (libpython3.8.so.1.0)
#24 0x00007fb454d1624b _PyFunction_Vectorcall (libpython3.8.so.1.0)
#25 0x00007fb454d2c3c8 _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#26 0x00007fb454d1606d _PyFunction_Vectorcall (libpython3.8.so.1.0)
#27 0x00007fb454d280ce _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#28 0x00007fb454d1606d _PyFunction_Vectorcall (libpython3.8.so.1.0)
#29 0x00007fb454d27c8c _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#30 0x00007fb454d14e3b _PyEval_EvalCodeWithName (libpython3.8.so.1.0)
#31 0x00007fb454d9e3d3 PyEval_EvalCode (libpython3.8.so.1.0)
#32 0x00007fb454d9e428 n/a (libpython3.8.so.1.0)
#33 0x00007fb454da2623 n/a (libpython3.8.so.1.0)
#34 0x00007fb454c3d3e7 PyRun_FileExFlags (libpython3.8.so.1.0)
#35 0x00007fb454c47f4a PyRun_SimpleFileExFlags (libpython3.8.so.1.0)
#36 0x00007fb454daf8be Py_RunMain (libpython3.8.so.1.0)
#37 0x00007fb454daf9a9 Py_BytesMain (libpython3.8.so.1.0)
#38 0x00007fb454f1f153 __libc_start_main (libc.so.6)
#39 0x000055ea57db605e _start (python3.8)

Stack trace of thread 1256:
#0  0x00007fb454fec9ef __poll (libc.so.6)
#1  0x00007fb453911120 n/a (libglib-2.0.so.0)
#2  0x00007fb4539111f1 g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007fb453911242 n/a (libglib-2.0.so.0)
#4  0x00007fb4538edbb1 n/a (libglib-2.0.so.0)
#5  0x00007fb454b204cf start_thread (libpthread.so.0)
#6  0x00007fb454ff72d3 __clone (libc.so.6)

Stack trace of thread 1263:
#0  0x00007fb454feee7b __select (libc.so.6)
#1  0x00007fb454d7505e n/a (libpython3.8.so.1.0)
#2  0x00007fb454c75f4f n/a (libpython3.8.so.1.0)
#3  0x00007fb454d2c3c8 _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#4  0x00007fb454d1606d _PyFunction_Vectorcall (libpython3.8.so.1.0)
#5  0x00007fb454d16a7b n/a (libpython3.8.so.1.0)
#6  0x00007fb454c6730d PyObject_Call (libpython3.8.so.1.0)
#7  0x00007fb454d29d03 _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#8  0x00007fb454d1606d _PyFunction_Vectorcall (libpython3.8.so.1.0)
#9  0x00007fb454d280ce _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#10 0x00007fb454d1606d _PyFunction_Vectorcall (libpython3.8.so.1.0)
#11 0x00007fb454d280ce _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#12 0x00007fb454d1606d _PyFunction_Vectorcall (libpython3.8.so.1.0)
#13 0x00007fb454d16a7b n/a (libpython3.8.so.1.0)
#14 0x00007fb454c6730d PyObject_Call (libpython3.8.so.1.0)
#15 0x00007fb454d7c4e1 n/a (libpython3.8.so.1.0)
#16 0x00007fb454d368f4 n/a (libpython3.8.so.1.0)
#17 0x00007fb454b204cf start_thread (libpthread.so.0)
#18 0x00007fb454ff72d3 __clone (libc.so.6)

Stack trace of thread 1267:
#0  0x00007fb454fec9ef __poll (libc.so.6)
#1  0x00007fb4541206d4 n/a (select.cpython-38-x86_64-linux-gnu.so)
#2  0x00007fb454c76104 n/a (libpython3.8.so.1.0)
#3  0x00007fb454d280ce _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#4  0x00007fb454d14e3b _PyEval_EvalCodeWithName (libpython3.8.so.1.0)
#5  0x00007fb454d1624b _PyFunction_Vectorcall (libpython3.8.so.1.0)
#6  0x00007fb454d280ce _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#7  0x00007fb454d1606d _PyFunction_Vectorcall (libpython3.8.so.1.0)
#8  0x00007fb454d280ce _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#9  0x00007fb454d1606d _PyFunction_Vectorcall (libpython3.8.so.1.0)
#10 0x00007fb454d280ce _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#11 0x00007fb454d1606d _PyFunction_Vectorcall (libpython3.8.so.1.0)
#12 0x00007fb454d16a7b n/a (libpython3.8.so.1.0)
#13 0x00007fb454c6730d PyObject_Call (libpython3.8.so.1.0)
#14 0x00007fb454d7c4e1 n/a (libpython3.8.so.1.0)
#15 0x00007fb454d368f4 n/a (libpython3.8.so.1.0)
#16 0x00007fb454b204cf start_thread (libpthread.so.0)
#17 0x00007fb454ff72d3 __clone (libc.so.6)

Stack trace of thread 1257:
#0  0x00007fb454fec9ef __poll (libc.so.6)
#1  0x00007fb453911120 n/a (libglib-2.0.so.0)
#2  0x00007fb4539120c3 g_main_loop_run (libglib-2.0.so.0)
#3  0x00007fb4535fcbc8 n/a (libgio-2.0.so.0)
#4  0x00007fb4538edbb1 n/a (libglib-2.0.so.0)
#5  0x00007fb454b204cf start_thread (libpthread.so.0)
#6  0x00007fb454ff72d3 __clone (libc.so.6)

Stack trace of thread 1265:
#0  0x00007fb454b29704 do_futex_wait.constprop.0 (libpthread.so.0)
#1  0x00007fb454b297f8 __new_sem_wait_slow.constprop.0 (libpthread.so.0)
#2  0x00007fb454c83a0e PyThread_acquire_lock_timed (libpython3.8.so.1.0)
#3  0x00007fb454d7c9a1 n/a (libpython3.8.so.1.0)
#4  0x00007fb454d95e1b n/a (libpython3.8.so.1.0)
#5  0x00007fb454d0bac9 n/a (libpython3.8.so.1.0)
#6  0x00007fb454d280ce _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#7  0x00007fb454d14e3b _PyEval_EvalCodeWithName (libpython3.8.so.1.0)
#8  0x00007fb454d1624b _PyFunction_Vectorcall (libpython3.8.so.1.0)
#9  0x00007fb454d280ce _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#10 0x00007fb454d14e3b _PyEval_EvalCodeWithName (libpython3.8.so.1.0)
#11 0x00007fb454d1624b _PyFunction_Vectorcall (libpython3.8.so.1.0)
#12 0x00007fb454d280ce _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#13 0x00007fb454d1606d _PyFunction_Vectorcall (libpython3.8.so.1.0)
#14 0x00007fb454d280ce _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#15 0x00007fb454d1606d _PyFunction_Vectorcall (libpython3.8.so.1.0)
#16 0x00007fb454d280ce _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#17 0x00007fb454d1606d _PyFunction_Vectorcall (libpython3.8.so.1.0)
#18 0x00007fb454d16a7b n/a (libpython3.8.so.1.0)
#19 0x00007fb454c6730d PyObject_Call (libpython3.8.so.1.0)
#20 0x00007fb454d7c4e1 n/a (libpython3.8.so.1.0)
#21 0x00007fb454d368f4 n/a (libpython3.8.so.1.0)
#22 0x00007fb454b204cf start_thread (libpthread.so.0)
#23 0x00007fb454ff72d3 __clone (libc.so.6)

Stack trace of thread 1264:
#0  0x00007fb454feee7b __select (libc.so.6)
#1  0x00007fb45412043e n/a (select.cpython-38-x86_64-linux-gnu.so)
#2  0x00007fb454c75e37 n/a (libpython3.8.so.1.0)
#3  0x00007fb454d2c3c8 _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#4  0x00007fb454d14e3b _PyEval_EvalCodeWithName (libpython3.8.so.1.0)
#5  0x00007fb454d16892 n/a (libpython3.8.so.1.0)
#6  0x00007fb454d28a9c _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#7  0x00007fb454d167a6 n/a (libpython3.8.so.1.0)
#8  0x00007fb454d2c3c8 _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#9  0x00007fb454d14e3b _PyEval_EvalCodeWithName (libpython3.8.so.1.0)
#10 0x00007fb454d1624b _PyFunction_Vectorcall (libpython3.8.so.1.0)
#11 0x00007fb454c67418 PyObject_Call (libpython3.8.so.1.0)
#12 0x00007fb454d29d03 _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#13 0x00007fb454d14e3b _PyEval_EvalCodeWithName (libpython3.8.so.1.0)
#14 0x00007fb454d1624b _PyFunction_Vectorcall (libpython3.8.so.1.0)
#15 0x00007fb454d179ab n/a (libpython3.8.so.1.0)
#16 0x00007fb454c6f962 _PyObject_MakeTpCall (libpython3.8.so.1.0)
#17 0x00007fb454d2c9f1 _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#18 0x00007fb454d167a6 n/a (libpython3.8.so.1.0)
#19 0x00007fb454d2c3c8 _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#20 0x00007fb454d1606d _PyFunction_Vectorcall (libpython3.8.so.1.0)
#21 0x00007fb454d280ce _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#22 0x00007fb454d1606d _PyFunction_Vectorcall (libpython3.8.so.1.0)
#23 0x00007fb454d280ce _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#24 0x00007fb454d1606d _PyFunction_Vectorcall (libpython3.8.so.1.0)
#25 0x00007fb454d16a7b n/a (libpython3.8.so.1.0)
#26 0x00007fb454c6730d PyObject_Call (libpython3.8.so.1.0)
#27 0x00007fb454d7c4e1 n/a (libpython3.8.so.1.0)
#28 0x00007fb454d368f4 n/a (libpython3.8.so.1.0)
#29 0x00007fb454b204cf start_thread (libpthread.so.0)
#30 0x00007fb454ff72d3 __clone (libc.so.6)

Stack trace of thread 1262:
#0  0x00007fb454b29704 do_futex_wait.constprop.0 (libpthread.so.0)
#1  0x00007fb454b297f8 __new_sem_wait_slow.constprop.0 (libpthread.so.0)
#2  0x00007fb454c83a0e PyThread_acquire_lock_timed (libpython3.8.so.1.0)
#3  0x00007fb454d7c9a1 n/a (libpython3.8.so.1.0)
#4  0x00007fb454d95e1b n/a (libpython3.8.so.1.0)
#5  0x00007fb454d0bac9 n/a (libpython3.8.so.1.0)
#6  0x00007fb454d280ce _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#7  0x00007fb454d14e3b _PyEval_EvalCodeWithName (libpython3.8.so.1.0)
#8  0x00007fb454d1624b _PyFunction_Vectorcall (libpython3.8.so.1.0)
#9  0x00007fb454d280ce _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#10 0x00007fb454d14e3b _PyEval_EvalCodeWithName (libpython3.8.so.1.0)
#11 0x00007fb454d1624b _PyFunction_Vectorcall (libpython3.8.so.1.0)
#12 0x00007fb454d280ce _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#13 0x00007fb454d1606d _PyFunction_Vectorcall (libpython3.8.so.1.0)
#14 0x00007fb454d16a7b n/a (libpython3.8.so.1.0)
#15 0x00007fb454c6730d PyObject_Call (libpython3.8.so.1.0)
#16 0x00007fb454d29d03 _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#17 0x00007fb454d1606d _PyFunction_Vectorcall (libpython3.8.so.1.0)
#18 0x00007fb454d280ce _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#19 0x00007fb454d1606d _PyFunction_Vectorcall (libpython3.8.so.1.0)
#20 0x00007fb454d280ce _PyEval_EvalFrameDefault (libpython3.8.so.1.0)
#21 0x00007fb454d1606d _PyFunction_Vectorcall (libpython3.8.so.1.0)
#22 0x00007fb454d16a7b n/a (libpython3.8.so.1.0)
#23 0x00007fb454c6730d PyObject_Call (libpython3.8.so.1.0)
#24 0x00007fb454d7c4e1 n/a (libpython3.8.so.1.0)
#25 0x00007fb454d368f4 n/a (libpython3.8.so.1.0)
#26 0x00007fb454b204cf start_thread (libpthread.so.0)
#27 0x00007fb454ff72d3 __clone (libc.so.6)
```

Then I restart it but the described issues will occurs again: furthermore sometimes, despite the fact that the scripts properly works, a notification of AutoKey is displayed on desktop: "This "scriptname" has encountered an error" or something similar.
Eg with a script which is very simple:

`output = system.exec_command("gedit '/home/dave/Documents/textfile'")`

**Comment by luziferius** [comment]
The last issue might be caused by the executed program not returning status code 0. This is interpreted as an error by AutoKey. It sounds like a nice enhancement to allow ignoring the return code or specifying the expected one(s).


The crash: The stacktrace unfortunately doesn't tell much, other than that Python crashed. Please take a look at the log file in `~/.local/share/autokey/`. As long as Python doesn't die too abruptly, it should contain additional information. Please note that it is an aggregating, rotating log, possibly from many sessions. Only the end is of interest here.

Please post any exceptions found at the end of the log

**Comment by MR-Diamond** [comment]
> Please post any exceptions found at the end of the log

I hope that I catch the right portion of the log (when I get the notification error):

>2020-03-09 11:01:51,651 INFO - config-manager - Disabling modifier key <capslock> based on the stored configuration file.
2020-03-09 11:01:51,656 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2020-03-09 11:01:51,657 INFO - config-manager - Successfully loaded configuration
2020-03-09 11:01:51,657 INFO - service - Starting service
2020-03-09 11:01:51,701 INFO - iomediator - Created IoMediator instance, current interface is: <XRecordInterface(XInterface-thread, initial daemon)>
2020-03-09 11:01:51,710 INFO - interface - XRecord interface thread starting
2020-03-09 11:01:51,711 INFO - service - Service now marked as running
2020-03-09 11:01:51,727 INFO - root - Entering main()
2020-03-09 11:01:52,706 ERROR - interface - Got BadWindow error while requesting window information.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/autokey/interface.py", line 1074, in get_window_info
    return self._get_window_info(window, traverse)
  File "/usr/lib/python3.8/site-packages/autokey/interface.py", line 1080, in _get_window_info
    new_wm_title = self._try_get_window_title(window)
  File "/usr/lib/python3.8/site-packages/autokey/interface.py", line 1128, in _try_get_window_title
    atom = self._try_read_property(window, self.__VisibleNameAtom)
  File "/usr/lib/python3.8/site-packages/autokey/interface.py", line 1145, in _try_read_property
    return window.get_property(property_name, 0, 0, 255)
  File "/usr/lib/python3.8/site-packages/Xlib/xobject/drawable.py", line 455, in get_property
    r = request.GetProperty(display = self.display,
  File "/usr/lib/python3.8/site-packages/Xlib/protocol/rq.py", line 1369, in __init__
    self.reply()
  File "/usr/lib/python3.8/site-packages/Xlib/protocol/rq.py", line 1389, in reply
    raise self._error
Xlib.error.BadWindow: <class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x02a00003), sequence_number = 450, major_opcode = 20, minor_opcode = 0
2020-03-09 11:01:52,709 ERROR - interface - Got BadWindow error while requesting window information.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/autokey/interface.py", line 1074, in get_window_info
    return self._get_window_info(window, traverse)
  File "/usr/lib/python3.8/site-packages/autokey/interface.py", line 1080, in _get_window_info
    new_wm_title = self._try_get_window_title(window)
  File "/usr/lib/python3.8/site-packages/autokey/interface.py", line 1128, in _try_get_window_title
    atom = self._try_read_property(window, self.__VisibleNameAtom)
  File "/usr/lib/python3.8/site-packages/autokey/interface.py", line 1145, in _try_read_property
    return window.get_property(property_name, 0, 0, 255)
  File "/usr/lib/python3.8/site-packages/Xlib/xobject/drawable.py", line 455, in get_property
    r = request.GetProperty(display = self.display,
  File "/usr/lib/python3.8/site-packages/Xlib/protocol/rq.py", line 1369, in __init__
    self.reply()
  File "/usr/lib/python3.8/site-packages/Xlib/protocol/rq.py", line 1389, in reply
    raise self._error
Xlib.error.BadWindow: <class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x02a00007), sequence_number = 451, major_opcode = 20, minor_opcode = 0
2020-03-09 11:02:00,941 INFO - service - Matched Script "OpenTextFile" having abbreviations "['opentxt']" against current input
2020-03-09 11:02:00,942 ERROR - service - Ignored locking error in handle_keypress
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/autokey/service.py", line 207, in __tryReleaseLock
    self.configManager.lock.release()
RuntimeError: release unlocked lock
2020-03-09 11:02:06,206 ERROR - service - Script error
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/autokey/service.py", line 485, in execute
    exec(script.code, scope)
  File "<string>", line 2, in <module>
  File "/usr/lib/python3.8/site-packages/autokey/scripting.py", line 497, in exec_command
    if output[-1] == "\n":
IndexError: string index out of range
2020-03-09 11:02:43,330 INFO - root - Displaying configuration window

I also noticed that: if i use autokey-qt, I don't get any problem which i described about autokey-gtk, but another problem occurs (using autokey-qt):
when autokey-qt is running in background, when I logout from the session, the Desktop stucks for eight seconds (by using autokey-gtk, instead, the delay is minimal, just one second), then the system logout: If i quit the background process (autokey-qt), the logout doesn't have the mentioned delay.

This is what I get from the log, using autokey-qt:

>2020-03-09 11:14:21,127 INFO - service - Starting service
2020-03-09 11:14:21,175 INFO - iomediator - Created IoMediator instance, current interface is: <XRecordInterface(XInterface-thread, initial daemon)>
2020-03-09 11:14:21,185 INFO - interface - XRecord interface thread starting
2020-03-09 11:14:21,186 INFO - service - Service now marked as running
2020-03-09 11:14:21,195 INFO - root.Qt-GUI.System-tray-notifier - Creating static context menu actions.
2020-03-09 11:14:21,197 INFO - root.Qt-GUI.System-tray-notifier - Rebuilding model item actions, adding all items marked for access through the tray icon.
2020-03-09 11:14:21,198 INFO - root.Qt-GUI.System-tray-notifier - System tray icon notifier created.
2020-03-09 11:17:13,234 ERROR - interface - __flushEvents: Connection to the X server closed. Forcefully exiting Autokey now.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/autokey/interface.py", line 911, in __flushEvents
    for x in range(self.localDisplay.pending_events()):
  File "/usr/lib/python3.8/site-packages/Xlib/display.py", line 192, in pending_events
    return self.display.pending_events()
  File "/usr/lib/python3.8/site-packages/Xlib/protocol/display.py", line 243, in pending_events
    self.send_and_recv(recv = 1)
  File "/usr/lib/python3.8/site-packages/Xlib/protocol/display.py", line 609, in send_and_recv
    raise self.socket_error
Xlib.error.ConnectionClosedError: Display connection closed by server
2020-03-09 11:17:18,933 INFO - root - Initialising application
2020-03-09 11:17:18,973 INFO - root - Initialise global hotkeys
2020-03-09 11:17:18,973 INFO - config-manager - Loading config from existing file: /home/dave/.config/autokey/autokey.json
2020-03-09 11:17:18,973 INFO - config-manager - Disabling modifier key <capslock> based on the stored configuration file.
2020-03-09 11:17:18,979 INFO - config-manager - Configuration changed - rebuilding in-memory structures
2020-03-09 11:17:18,980 INFO - config-manager - Successfully loaded configuration
2020-03-09 11:17:18,980 INFO - service - Starting service
2020-03-09 11:17:19,031 INFO - iomediator - Created IoMediator instance, current interface is: <XRecordInterface(XInterface-thread, initial daemon)>
2020-03-09 11:17:19,043 INFO - interface - XRecord interface thread starting
2020-03-09 11:17:19,045 INFO - service - Service now marked as running
2020-03-09 11:17:19,054 INFO - root.Qt-GUI.System-tray-notifier - Creating static context menu actions.
2020-03-09 11:17:19,057 INFO - root.Qt-GUI.System-tray-notifier - Rebuilding model item actions, adding all items marked for access through the tray icon.
2020-03-09 11:17:19,059 INFO - root.Qt-GUI.System-tray-notifier - System tray icon notifier created.

**Comment by josephj11** [comment]
No idea if this is related, but I have been having very long shutdown times on my system, getting "a shutdown job is running for session 3" that took 90 seconds to timeout until I reduced the timeout to 8 seconds in system.config. I read about the error, but don't know enough to debug it myself. I don't manually logout first when I shutdown.

**Comment by MR-Diamond** [comment]
The first step to do is very simple: before to shutdown your system, execute the command pkill autokey-qt (or autokey-gtk if you are using this one).
If the timeout still occurs, autokey is not the culprit in your case.
However in my case I didn't seen the message "a shutdown job is running"; just the desktop screen which stucks for eight seconds when I logout.

**Comment by MR-Diamond** [comment]
The first step to do is very simple: before to shutdown your system, execute the command pkill autokey-qt (or autokey-gtk if you are using this one).
If the timeout still occurs, autokey is not the culprit in your case.
However in my case I didn't seen the message "a shutdown job is running"; just the desktop screen which stucks for eight seconds when I logout.

**Comment by luziferius** [comment]
> the scripts properly works, a notification of AutoKey is displayed on desktop: "This "scriptname" has encountered an error" or something similar.
> Eg with a script which is very simple:
> 
> `output = system.exec_command("gedit '/home/dave/Documents/textfile'")`

This part of this issue is a duplicate of #379, which I fixed. That will be part of 0.95.11. With that change, the API call won’t fail if the run command doesn’t output anything. So no more spurious "Script failed" messages.

**Comment by Elliria** [comment]
It sounds like this issue may have been fixed and should no longer exist in AutoKey 0.96.0. Have you tried AutoKey 0.96.0, @MR-Diamond?

**Comment by MR-Diamond** [comment]
@Elliria Yes, is fixed. I close this ticket.

**Comment by Elliria** [comment]
That's great news, @MR-Diamond.
