### ISSUE TITLE
out of range error

### ISSUE THREAD

**Issue by THMonster** [autokey/autokey#379]
https://github.com/autokey/autokey/blob/master/lib/autokey/scripting.py#L497

![image](https://user-images.githubusercontent.com/5125031/75618959-32a0eb80-5bb0-11ea-9869-1df20d9da42c.png)

The `output` can be empty in some situation, and it will raise an `out of range` error.

**Comment by luziferius** [comment]
It can. But this is executed only if you are interested in the output (i.e. argument `getOutput == True`). If the command does not output anything, this is at least an unusual situation, as it is expected to output something.
So either catch the error and raise a different one with a descriptive name like `EmptyProcessOutputError` or similar or simply return an empty string.

Changing line 497 to `if output and output[-1] == "\n":` should prevent the call from raising an exception. It’ll then return an empty string.

**Comment by luziferius** [comment]
Fixed. The fix will be part of the next bugfix release (0.95.11)
