### ISSUE TITLE
latest gtk deb release is qt

### ISSUE THREAD

**Issue by dkebler** [autokey/autokey#387]
I  installed the .95.10 deb from releases for supposedly gtk version but when launched  about shows QT version and also help has about QT choice as well.

**Comment by luziferius** [comment]
Are you _sure_ you grabbed
https://github.com/autokey/autokey/releases/download/v0.95.10/autokey-gtk_0.95.10-0_all.deb
from
https://github.com/autokey/autokey/releases/tag/v0.95.10 ?

I just downloaded the .deb containing the GTK GUI and extracted it (the outer `.deb` package and `data.tar.xz`). It definitely contains this:
![AK_GTK](https://user-images.githubusercontent.com/2143820/76712075-93ced000-6715-11ea-8b4d-01d486865743.png)

These are the file listings that are used by `dpkg-buildpackage` to generate the archives. Only the files listed in those is packaged into the respective Debian package:

GTK: https://github.com/autokey/autokey/blob/master/debian/autokey-gtk.install
Qt: https://github.com/autokey/autokey/blob/master/debian/autokey-qt.install
common base package: https://github.com/autokey/autokey/blob/master/debian/autokey-common.install
