### ISSUE TITLE
关于中文字符的处理问题

### ISSUE THREAD

**Issue by YLXDXX** [autokey/autokey#396]
我的系统是manjaro，在使用autokey的过程中遇到了对于中文和特殊字符支持的问题，如下：

问题一：

例如我新建一个 Phrase ，内容如下
`sed 's/{//g;s///g;s/∶/:/g;`
1.显示有问题 
![image](https://user-images.githubusercontent.com/35033878/77997994-f30e2080-7362-11ea-97cc-c47f6bc22c35.png)
2.设置abbraviations插入也有问题
3.用其它的编辑器例打开(例如kate)，能正确显示

问题二：
例如我新建一个脚本。代码如下：
```
output = system.exec_command("tail -n 1 /home/text.sh")
keyboard.send_keys(output)
```
如果`test.sh`的最后一行有中文或其它特殊字符，也不能正确使用。

希望能够改善对与中文和特殊字符的支持

**Comment by YLXDXX** [comment]
测试用的文件
[test.zip](https://github.com/autokey/autokey/files/4407423/test.zip)

**Comment by luziferius** [comment]
`Paste using: Keyboard` and `keyboard.send_keys()` have issues with Non-ASCII symbols.
Try using `Paste using: Clipboard` instead.

In scripts, you currently have to do something like this to use the clipboard:
```python
import time
backup = clipboard.get_clipboard()
clipboard.fill_clipboard(your_text_here)
time.sleep(0.2)  # May need tweaking, up to 0.5
keyboard.send_keys("<ctrl>+v")
time.sleep(0.2)  # May need tweaking, up to 0.5
clipboard.fill_clipboard(backup)
```
The latter will be simplified in the future, as built-in text pasting using the clipboard will be available in 0.96.0

**Comment by josephj11** [comment]
I think this is a won't fix. We just use paste using clipboard for non-EN-US characters.
