### ISSUE TITLE
Output is missing (special) characters

### ISSUE THREAD

**Issue by freder** [autokey/autokey#398]
## Classification:

bug

## Reproducibility:

always

## Version

AutoKey version: 0.90.4 -- 0.95.10

Used GUI (Gtk, Qt, or both): gtk 

Installed via: apt

Linux Distribution: linux mint 19.3 cinnamon

## Summary

certain characters (`←↑→↓`) are missing from phrase

## Steps to Reproduce (if applicable)

- define new phrase: `a↓b`, trigger on abbreviation `,,test` (without trigger character)
- switch to a text editor (in my case vs code or sublime text)
- type `,,test` 

## Expected Results

- should insert `a↓b`

## Actual Results

- only inserts `ab`

**Comment by freder** [comment]
I just realized, that the version on apt is terribly out of date. -- after updating to 0.95.10 (from .deb files) the problem persists though.

**Comment by luziferius** [comment]
Yep. Known problem, because the `Keyboard` method can only reliably type what is in your keyboard layout. Use `Clipboard` as your pasting method.

**Comment by freder** [comment]
ok, that works. -- thank you!
