### ISSUE TITLE
与xclip有冲突

### ISSUE THREAD

**Issue by YLXDXX** [autokey/autokey#399]
这个可以正常运行
```
# Enter script code
import time
ouput = system.exec_command("echo ok")
time.sleep(0.1)  
keyboard.send_keys("<ctrl>+v")
```
但是这个却不可以
```
# Enter script code
import time
system.exec_command("echo ok | xclip -selection clipboard")
time.sleep(0.1)  
keyboard.send_keys("<ctrl>+v")
```

运行自定义的脚本(shell)时，如果里面包含`xclip`的命令，也会有冲突，具体表现为：设定了快捷键，第一次使用该快捷键没有作用，第二次使用可以起作用，但是后面使用一些其它的快捷键(例如系统的粘贴`ctrl+x`)时，第一次会跳出选择，后面才能正常使用。

现在使用的是`xsel`作为替代。

若有时间，望修复

**Comment by josephj11** [comment]
While this may be a real bug, why do you need to use xclip with AutoKey?
Our API <https://autokey.github.io/index.html> provides provides calls to
get and fill both the X selection and the clipboard.

**Comment by YLXDXX** [comment]
明白了，谢谢
