### ISSUE TITLE
Python 3.4 and QT4 fixes

### ISSUE THREAD

**Issue by katodev** [autokey/autokey#40]
I need to patch the source code for openSUSE Leap42.1 with KDE and Python 3.4. Could someone check if the QT fix has some sideeffects for GTK or other parts of autokey? 

# fix README.srt (has non ASCII characters) 
sed -i 's|“--user”|"--user"|g' README.rst
iconv -c -t ascii -o README.rst README.rst

#fix syntax error in src/lib/scripting_highlevel.py
sed -i 's|int,int|int|g' src/lib/scripting_highlevel.py

# fix autokey-run
sed -i 's|print(str(e), file=sys.stderr)|print >>sys.stderr, str(e)|g' autokey-run

sed -i '2i# -*- coding: UTF-8 -*-' autokey-{gtk,qt,run,shell}

# fix for QT
sed -i 's|return self.windowInfoRegex.pattern + _(" (Recursive)")|return self.windowInfoRegex.pattern|g' src/lib/model.py
sed -i 's|return self.get_filter_regex() + _(" (Inherited)")|return self.get_filter_regex()|g' src/lib/model.py

**Comment by troxor** [comment]
Still working on #35 , will test changes after I can get it running better.
