### ISSUE TITLE
Missing Characters when pasting text-based emojis

### ISSUE THREAD

**Issue by realmayus** [autokey/autokey#407]
## Classification:
Bug

## Reproducibility:
Always
## Version

AutoKey version: 0.95.10

Used GUI (Gtk, Qt, or both): Qt

Linux Distribution: Pop!_Os (basically Ubuntu) with KDE desktop environment

## Summary
Text-based emojis and other special characters don't get pasted correctly.
What I defined in the GUI is: ( ͡° ͜ʖ ͡°)
What gets pasted is: ( °  °) 

## Steps to Reproduce (if applicable)
- Add a phrase with special characters (you can use [textface.es](https://textfac.es) for testing)
- Trigger phrase

## Expected Results
- The phrase should be pasted the same way as I defined it: ( ͡° ͜ʖ ͡°)

## Actual Results
- AutoKey removes some special characters and the result looks like this:  ( °  °)

**Comment by josephj11** [comment]
Did you select the Paste using clipboard ctrl+v option? The keyboard module can't handle things that aren't on your native keyboard and has trouble with locales other than English-US.

**Comment by realmayus** [comment]
Yeah, that works, thanks :)
