### ISSUE TITLE
Add missing special key

### ISSUE THREAD

**Issue by Elliria** [autokey/autokey#408]
## Classification:

Enhancement

## Reproducibility:

Always

## Version

AutoKey version: 0.90.4 (also the current version)

Used GUI (Gtk, Qt, or both): Gtk

Installed via: Ubuntu package manager.

Linux Distribution: Ubuntu MATE 16.04.6 LTS

## Summary

All of the numpad keys except for one can be pressed and released by using ```keyboard.press_key()``` and ```keyboard.release_key()``` using their AutoKey **special key** values. The number 5 numpad key, however, doesn't have an AutoKey **special key** value.

## Steps to Reproduce (if applicable)

Put these contents into a script and run it with a text editor focused:

```
#Press the numlock key:
keyboard.press_key("<numlock>")

#Press and release the numpad 0 key:
keyboard.press_key("<np_insert>")
keyboard.release_key("<np_insert>")

#Press and release the numpad 1 key:
keyboard.press_key("<np_end>")
keyboard.release_key("<np_end>")

#Press and release the numpad 2 key:
keyboard.press_key("<np_down>")
keyboard.release_key("<np_down>")

#Press and release the numpad 3 key:
keyboard.press_key("<np_page_down>")
keyboard.release_key("<np_page_down>")

#Press and release the numpad 4 key:
keyboard.press_key("<np_left>")
keyboard.release_key("<np_left>")

#Press and release the numpad 5 key:
#???
#???

#Press and release the numpad 6 key:
keyboard.press_key("<np_right>")
keyboard.release_key("<np_right>")

#Press and release the numpad 7 key:
keyboard.press_key("<np_home>")
keyboard.release_key("<np_home>")

#Press and release the numpad 8 key:
keyboard.press_key("<np_up>")
keyboard.release_key("<np_up>")

#Press and release the numpad 9 key:
keyboard.press_key("<np_page_up>")
keyboard.release_key("<np_page_up>")

#Release the numlock key:
keyboard.release_key("<numlock>")
```

## Expected Results

If the number 5 numpad key had a **special key** value, then that would have been used in the script and  the result would have been:

0123456789

## Actual Results

Since there is no **special key** value for the number 5 numpad key, these are the actual results:

012346789

## Notes

GNU/Linux users can use xev to find out the key code of the number 5 numpad key. When I ran xev, I got code84 for that key in Ubuntu MATE. I'm not sure if other GNU/Linux users who use different distributions would need to use a different key code, but they can use xev to check. I'm also not sure if a Windows user can use the same key code and am not certain how they would get the actual key code. Either way, this is a work-around that will produce a 5 from the number 5 numpad key:

```
keyboard.press_key("<numlock>")

keyboard.press_key("<code84>")
keyboard.release_key("<code84>")

keyboard.release_key("<numlock>")
```

**Comment by Gogowitsch** [comment]
You can use this to type a 5:
```
keyboard.press_key("<np_5>")
keyboard.release_key("<np_5>")
```

**Comment by josephj11** [comment]
@fonata Thanks for pointing that out. How did you find it? It's missing from our documentation.

@Elliria interface.py line 1364 is `           XK.XK_KP_Begin: Key.NP_5,`, so it looks  like this is a thing. If so, this becomes a documentation issue to modify our [wiki](https://github.com/autokey/autokey/wiki/Special-Keys) so people know this key macro exists.

I didn't research GitHub to try to determine when that line was added. If you have 0.90.4 on your system somewhere, you can see if it was already there or was added in 0.96.0.

**Comment by Elliria** [comment]
Thank you so much, @fonata. It's always nice to get the answers to unanswered questions once and for all.

It's fascinating, @josephj11. I wonder how many more of these Easter eggs are hidden away inside the code.

It seems that it's used as [the "Begin" key in Java](https://stackoverflow.com/questions/25259852/what-is-the-begin-key) and it only works on the X window system.

It's on lines 1349 and 1371 in the interface.py file in AutoKey 0.95.10. I don't have 0.90.4 installed any more (and can't currently install it because of a kernel bug that prevents the installation of new virtual machines).

I went back as far as 2016 in the [Git version history of the interface.py file](https://github.com/autokey/autokey/commits/master?after=fbcc72b8d9b6d87c0c49520eef7e0abef3750177+34&branch=master&path%5B%5D=lib&path%5B%5D=autokey&path%5B%5D=interface.py&qualified_name=refs%2Fheads%2Fmaster) and it was [already in that file](https://github.com/autokey/autokey/blob/fd7bf4d53970917ead112d111657a41fa3f0a5f5/lib/autokey/interface.py), so it goes way back and deserves to be added to the [Special Keys page in the wiki](https://github.com/autokey/autokey/wiki/Special-Keys). I'll do that in a moment.
