### ISSUE TITLE
Scrambled letters in Phrase

### ISSUE THREAD

**Issue by BoaTheCrafter** [autokey/autokey#409]
## Classification:

Bug

## Reproducibility:

Always

## Version

AutoKey version: 0.95.10
Used GUI (Gtk, Qt, or both): Gtk

Installed via: apt-get and Ubuntu Software-Center

Linux Distribution: Ubuntu 20.04

## Summary

I tried to run a phrase to get an output, but the letters/characters are just scrambled. 

## Steps to Reproduce (if applicable)

pressed the corresponding hotkey

## Expected Results

Outputs the example Adress
"22 Avenue Street
 Brisbane
 QLD
 4000"

## Actual Results

but instead writes
"22 Aeuven Srette
 Birsbane
 QLD
 4000"
And the output changes with every retry

```
2020-04-27 16:15:20,111 DEBUG - root - AutoKey is already running as pid 8563
```

## Notes

Reinstalled Autokey using the apt-get command and the Ubuntu Software Center

**Comment by josephj11** [comment]
Did you select the Paste using clipboard option for your phrase? The keyboard module has trouble with longer phrases and those with multibyte characters. Also, it types at machine speed which is too fast for some applications.

See issue #410 .

**Comment by BoaTheCrafter** [comment]
Ah, thanks man. Now it works.
