### ISSUE TITLE
Change default to Paste using clipboard (ctrl+v) for new phrases

### ISSUE THREAD

**Issue by josephj11** [autokey/autokey#410]
## Classification:

Enhancement

## Reproducibility:

N/A

## Version

AutoKey version: All - longstanding problem

Used GUI (Gtk, Qt, or both): Both

Installed via: All

Linux Distribution: All

## Summary

The current default - Paste using keyboard - has a number of problems

1) Fails on long phrases - especially in slow target windows
2) Fails to handle some keys which are not on the physical keyboard
3) Fails with multibyte character sets (everything except EN-US)
4) Fails for some characters on remapped keyboards

## Steps to Reproduce (if applicable)

Define a phrase with any of the above problem characteristics
Define a long phrase (> 20 characters) and use it with a slow application such as a word processor

## Expected Results

Phrase contents should be accurately reproduced

## Actual Results

Phrases are emitted with missing, out of order, and/or wrong characters

We get unnecessary support questions and issues filed, including a couple in the last few days.

## Notes

This has been discussed at length on our forum, Gitter, and in other issues.

Selecting Paste using clipboard (ctrl+v) fixes most issues

I am not suggesting that we get rid of Paste using keyboard or that we do anything unexpected to change the method used automatically. It should still be an option and continue to work as is for the great many preexisting phrases which use it.

**Comment by josephj11** [comment]
See also: #29 which also highlights why Paste using keyboard is still needed for `<cursor>` ...
#241 Emoji
#263 - closed

**Comment by josephj11** [comment]
We seem to be getting a lot of reports of problems like this. I just answered one in #101  .

It might even make sense to add a new Paste using option which works like my type_slow() function to handle extreme cases. It would be better than forcing a user to convert a lot of their phrases to scripts when all they need is for them to paste slower.

**Comment by BlueDrink9** [comment]
Changed in latest beta

**Comment by vvasuki** [comment]
Is this live in 0.96.0?  @josephj11 @BlueDrink9  ??

**Comment by josephj11** [comment]
Paste using clipboard (Ctrl+V) is the new default in 0.96.0. That's why this issue is closed.

 If you're still using 0.95.10, the option is there, but it's not the default.

If you'd like to upgrade and it's not yet available in your distribution's repositories, see these [instructions](https://github.com/autokey/autokey/wiki/Installing). The current release is [here](https://github.com/autokey/autokey/releases/).

0.96.0 contains a lot of bug fixes and several new features. Be sure to read the change log.

**Comment by josephj11** [comment]
@vvasuki  Paste using clipboard (Ctrl+V) is the new default in 0.96.0. That's why this issue is closed.

 If you're still using 0.95.10, the option is there, but it's not the default.

If you'd like to upgrade and it's not yet available in your distribution's repositories, see these [instructions](https://github.com/autokey/autokey/wiki/Installing). The current release is [here](https://github.com/autokey/autokey/releases/).

0.96.0 contains a lot of bug fixes and several new features. Be sure to read the change log.

Took a look at your main link. Nice. If you are working with Sanskrit, you'll need Paste using clipboard a lot!
Also, if you haven't seen it already, take a look at our [wiki](https://github.com/autokey/autokey/wiki/Emitting-Keyboard-Events) and [here](https://github.com/autokey/autokey/wiki/Unicode-Characters). Namaste.
