### ISSUE TITLE
Window Filter to exclude gnome terminal

### ISSUE THREAD

**Issue by osopolar** [autokey/autokey#42]
I am using autokey on ubuntu 16.04 and want to get it work everywhere except on gnome terminal. What should the Window Filter look like?

**Comment by josephj11** [comment]
I can survive simple GNU regexes, but the Python 2.7 re module (used by AutoKey) uses perl style regexes, so I'm a bit lost.

Here are some hints.

I seem to find that the regex should match the whole window title or class (although this probably shouldn't be necessary).

You want a perl regex which says match any window with `.*gnome-terminal.*` in the title wrapped in a "not". The `.*`s eat up the rest of the title on both ends.

[This](https://docs.python.org/2.7/howto/regex.html) will get you started.

I'll pass this question to another team member who may know perl regexes.

Questions such as this are not really "issues" and are much better handled on our support 
[list](https://groups.google.com/forum/#!forum/autokey-users).

As of now, AFAIK, I'm the only person watching here, but we have a lot of users on the support list who may be able to help with usage questions.

**Comment by osopolar** [comment]
Thank you @josephj11 for answering my support request anyway. I have seen the support list before and also the correct issue there, but didn't read to the end as I thought my problem is different as the window title of the gnome terminal constantly changes.

The filter would look like: `^((?!gnome-terminal-server).)*$` or `^((?!.*gnome-terminal-server.*).)*$` (using zero-width negative lookahead).

The problem is with the negation while both, window class and window title is checked, as uj said in https://groups.google.com/d/msg/autokey-users/ZYrQLPveh4g/T5qmhSn45wAJ:

> I found that it's because the filter means (1) it matches to the
> Window title or (2) it matches to the Window class.
> 
> src/lib/model.py
> 268     def _should_trigger_window_title(self, windowInfo):
> 269         r = self.get_applicable_regex()
> 270         if r is not None:
> 271             return r.match(windowInfo[0]) or
> r.match(windowInfo[1])
> 272         else:
> 273             return True
> 
> line 271 is the key.
> 
> So if you want to exclude a Window, you always have to specify a
> keyword that doesn't match neither its title nor class. I think
> "VirtualBox OSE" is a good keyword for the title but I don't think it
> unmatches to the class.
> 
> This issue is basically caused by the asymmetricity of matching/
> unmatching. I propose that autokey provides negate option in the
> Window filtering. 

So this may be solved in two ways:
1) provide negate option in the window filtering. 
or
2) provide options for window title and window class, if both are selected the filter would check both (as current behavior) if just one of them is selected, then just that one would be considered by the filter. In my case I just want to check the window class, not the title.

I guess it would take a while to get that fixed (in linux distributions like ubuntu 16.04) so I guess  I need to fix that my own (just removing `or r.match(windowInfo[1])` would do the job in my case) and have to compile the program myself as described for example [here](https://groups.google.com/d/msg/autokey-users/VQxZqoglirU/Fn2V-BKEgLEJ), right?

**Comment by josephj11** [comment]
Yeah .... Right ... What you said.  <G>

You can go that route if you have the skills and fortitude, but it would be much simpler to:

1) Forget about the window filter and just add code to the start of your macro to examine the Window class. If it's gnome-terminal, either exit or reissue the hotkey keypresses and exit. If it's anything else do the rest of your macro.

And

2) File a separate enhancement issue asking for the feature as you did in this thread. It sounds reasonable to me.

As for getting anything fixed, we are sorely in need of developers. Currently nothing is happening although we have one developer who is interested if he can find any time to actually work on things.
