### ISSUE TITLE
hang   while setting keybindings

### ISSUE THREAD

**Issue by leword** [autokey/autokey#42]
On Xubuntu 16.10.. when I'm in 'Set Hotkey' dialog and click 'Press to Set' and press a key..  I'd say about 20-30% of the time autokey locks hard and I have to kill and restart it from the command line.  Sometimes the first re-start doesn't work and I have to restart 2 or 3 times.   (it also randomly stops working during the day, so I have a alias setup to do this.  I will probably create a non-autokey keybinding in my windowmanager to kill and restart...)  So although I have pretty high tolerance for this kind of pain at the moment, I finally got stuck-- there's one phrase that I've been trying to set the keybinding and it has hung 10-15 times in a row.  Any pointers on how to debug this kind of thing?
![autokey-bug](https://cloud.githubusercontent.com/assets/8879/20312111/84de50fe-ab0f-11e6-835b-bf1bcfa5f4ad.png)

**Comment by leword** [comment]
3rd retry after deleting and re-creating the phrase worked.  so I'm unstuck at the moment but basically living in fear of the next time trying to set one keybinding is going to eat 15-20 minutes.

**Comment by troxor** [comment]
Randomly-occurring issues are a pain in the butt to diagnose. Can you come up with a reliable test case?

**Comment by troxor** [comment]
Please reopen once you have a test case or any further information.
