### ISSUE TITLE
NameError: name 'HOMEPAGE_PY3' is not defined

### ISSUE THREAD

**Issue by katodev** [autokey/autokey#43]
lib/autokey/qtapp.py 
line 65 
`         aboutData_py3 = KAboutData(APP_NAME, CATALOG, PROGRAM_NAME_PY3, VERSION, DESCRIPTION_PY3,`
`-                                    LICENSE, COPYRIGHT_PY3, TEXT, HOMEPAGE_PY3, BUG_EMAIL_PY3)`
`+                                    LICENSE, COPYRIGHT_PY3, TEXT)`

lib/autokey/qtui/configwindow.py
line 1111
`-        self.__createAction("about", i18n("About AutoKey"), "help-about", self.on_about)`
` +       self.__createAction("about", i18n("About AutoKey_PY3"), "help-about", self.on_about_py3)`

**Comment by troxor** [comment]
Still setting up a QT test environment, sorry for the temporary tumult
