### ISSUE TITLE
Insert cursor feature

### ISSUE THREAD

**Issue by owcz** [autokey/autokey#44]
I'm transitioning from another text expander, which had a "magic word"-style feature in which the cursor would be placed wherever the magic word was placed in the expanded text.

For example, "Hello {^} Goodbye" would place post-expansion active cursor in-between the two words.

Is there a function like this in Autokey? If not, is it worth considering?

**Comment by troxor** [comment]
As far as I'm aware, no such feature exists in AutoKey. Patches would be welcome, since this sounds like a nice feature.
