### ISSUE TITLE
AutoKey producing "IndexError: string index out of range" error with xdotool minimize command

### ISSUE THREAD

**Issue by ghost** [autokey/autokey#440]
I'm trying to get AutoKey to minimise the current window.

I think there's a problem with how Autokey is handling some `xdotool` commands, and thus this is a bug, but I could be wrong.

**Comment by josephj11** [comment]
This is way over my pay grade, but consider this:
AutoKey is designed to communicate with the current active window. Your command minimizes that window, which probably means it's no longer the active window and it did this without "telling" AutoKey about it (there's no way to tell AutoKey that, AFAIK.) So, not knowing the code base/internals, this is something I would just logically expect to cause problems.

**Comment by mindfulsource** [comment]
That makes sense, but I thought AutoKey can 'do anything', so to speak. E.g. documentation says it can start any external script:

https://github.com/autokey/autokey/wiki/Scripting#start-external-scripts

I think I just don't know the ins and outs of python scripting, but again, it could be a bug. Think another dev will chime in and elucidate?

**Comment by josephj11** [comment]
Being able to "do anything" doesn't mean that you should. With great power ... The devs have been silent for a month or so. Thomas also disappeared last summer, so, hopefully, he'll be back in awhile. Bluedrink hasn't been here long enough to establish any pattern, although he has made significant contributions.

**Comment by mindfulsource** [comment]
OK, fingers crossed some will come back again, Thanks for answering, and thanks for contributing to the project!

**Comment by johnngone** [comment]
Hello, try adding `getOutput=False`, like this:
`system.exec_command("xdotool windowminimize $(xdotool getactivewindow)", getOutput=False)`

Let me know if that works for you.

**Comment by mindfulsource** [comment]
> Hello, try adding `getOutput=False`, like this:
> `system.exec_command("xdotool windowminimize $(xdotool getactivewindow)", getOutput=False)`
> 
> Let me know if that works for you.

@JohnNgOne That fixed it. Thank you so much!

---

@josephj11, now that my minimize function is working, I'd like to submit a new useful script to the wiki list at https://github.com/autokey/autokey/wiki/Scripting#advanced-scripts. I don't feel comfortable using a Google account to use the autokey Google Group, so I'm hoping you can consider adding it via this ticket.

It's an extension of the "Switch Or Start Firefox" script to make it a full toggle - i.e. if Firefox is current window, it minimizes. I tested it for other apps which needed a slight adjustment to other lines.

Could be placed after the "Switch or Start" sample. Great that it's GPL, I'm fully happy to submit it under that.

---

### **Toggle an Application**

**Author:** mindfulsource

**Description:** this script toggles the primary window of any application like this example for Firefox. 'winClass' and binary path will vary depending on your scenario. Install 'xdotool' package if needed.

```
#
import subprocess
command = 'wmctrl -lx'
output = system.exec_command(command, getOutput=True)

if 'Navigator.Firefox' in output:
    winClass = window.get_active_class()
    if winClass == 'Navigator.Firefox':
        system.exec_command("xdotool windowminimize $(xdotool getactivewindow)", getOutput=False)
    else:
        system.exec_command("wmctrl -xa Navigator.Firefox", getOutput=False) 
else:
    subprocess.Popen(["/usr/bin/firefox"])
#
```

Firefox probably is best example for this one too as it's the most common app by far to be on any Linux distro.

Then, after you decide whether to add it to the wiki or not, this ticket can be closed. :) Thanks.

**Comment by josephj11** [comment]
Glad it works now!
Addressing your other points.
You can join our support [listserv](autokey-users+subscribe@googlegroups.com) by sending it an email using any email account. You will see all email and forum posts and be able to post as well.That's how I get the list. I almost never go to the forum itself.
Our wiki may be edited directly by anyone with a GitHub account. Feel free to contribute.
Once this ticket is closed, it will still be here, so you can close it if you want to.
You can also visit us on [Gitter](https://gitter.im/autokey/autokey), which is a better place for more advanced issues.

**Comment by mindfulsource** [comment]
Added to wiki, and thanks for all the information. Case closed! :)
