### ISSUE TITLE
Unable to have AutoKey insert an em dash (—)

### ISSUE THREAD

**Issue by xebico** [autokey/autokey#444]
## Version
AutoKey version: 0.95.10

Used GUI (Gtk, Qt, or both): Gtk

Linux Distribution: Mint

## Summary
Unable to have AutoKey insert an em dash (—)

## Steps to Reproduce (if applicable)
I create a simple phrase consisting entirely of the em dash character (—). I assign it to a hotkey (I tried several), e.g., <ctrl>+<shift>+- or <ctrl>+<f9> 

## Expected Results
Pressing the hotkey would insert/type an em dash.

## Actual Results
Nothing happens. In some programs it blinks for a moment, but the character never appears. 

## Notes
Substituting other text for the em dash, such as random characters, works just fine — the hotkey sends those characters as expected. It's only the em dash I've been unable to get to work.

![Screenshot from 2020-09-23 11-38-52](https://user-images.githubusercontent.com/19582721/94035950-c0813580-fd91-11ea-9bfc-d9388b70a8a3.png)

**Comment by josephj11** [comment]
When using non-English US characters, thou shalt not use Paste using keyboard. It won't work and probably can't be fixed. Use Paste using Ctrl+v in phrases or fill the clipboard and type a ctrl+v in scripts.

If that doesn't work, then post a followup here.

**Comment by ineuw** [comment]
I was given two working solutions for the same problem as discussed on gitter [https://gitter.im/autokey/autokey] 

```
# alt + = insert mdash surrounded by one space  — 
import sys
spc = " "
char = spc + "\u2014" + spc
clipboard.fill_clipboard(char)
keyboard.send_keys("<ctrl>+v")
sys.exit()
```

**Comment by ineuw** [comment]
This is a solved post. I don't see why Autokey should keep this as an open issue.
