### ISSUE TITLE
No desktop integration in Ubuntu because of missing autokey-gtk.desktop

### ISSUE THREAD

**Issue by deragon** [autokey/autokey#45]
I installed autokey-py3 following instruction provided for Ubuntu.  It installed and runs flawlessly, except that Autokey would appear nowhere in the desktop environment; the only way to start it up was from the command line, calling `autokey-gtk`.

Found the solution.  Simply run:

    ln -s /usr/share/app-install/desktop/autokey-gtk\:autokey-gtk.desktop /usr/share/applications/.

Please add the following statement in the installation script.  Maybe more logic needs to be added to detect if the main user prefer GTK or QT, but still, better have something than nothing.

**Comment by troxor** [comment]
Still working on the Ubuntu package/PPA, which will obviate the need for this. Also, --user installs would be better served with a .desktop file in ~/.local/share/applications instead, leaving /usr/share/applications for desktop files provided by package-manager-managed applications

**Comment by deragon** [comment]
I understand your reasoning, and if a PPA is around the corner, I agree,  However, if the PPA is not going to appear for years because the amount of work involved, adding this simple line (or similar) would help users in the mean time.
