### ISSUE TITLE
Another small feature request

### ISSUE THREAD

**Issue by ineuw** [autokey/autokey#453]
`## Classification: Enhancement

Could you please add a toolbar button to access "View Script error"? To me, it's the most logical place for it. I am using the gtk version 95.10. Thanks.

**Comment by josephj11** [comment]
This sounds like a good idea. Having to first click on Tools is not intuitive.

I think it would be great to have some sort of notification/widget I could add to my KDE Notifications panel such that it would remain hidden (Auto) until an error occurs and then appear. Then, it would be accessible even when the AutoKey Main Menu is not visible.  I know this is a lot more than what you are asking for.

**Comment by ineuw** [comment]
Considering the number of errors I generate, it would be a most welcome addition/change.

**Comment by josephj11** [comment]
I assure you, you're not the only one. :)

**Comment by BlueDrink9** [comment]
0.96.0 has a new script error system. Check that out, and let us know if you are satisfied
