### ISSUE TITLE
*Fatal error starting Autokey \n /usr/lib/libc.so: invalid elf header* when start autokey

### ISSUE THREAD

**Issue by OriLiMu** [autokey/autokey#458]
## Classification:
Crash
(Pick one of: Bug, Crash/Hang/Data Loss, Performance, UI/Usability, Feature (New), Enhancement)

## Reproducibility:
Clone the repo now(sorry I dont know how to check the version when the autokey crashed, the date I clone is 2020-11-03) and running with the zero-install way, 
running command `/usr/bin/python -m autokey.gtkui`

I get a msgbox with *Fatal error starting Autokey \n /usr/lib/libc.so: invalid elf header*

(Pick one of: Always, Sometimes, Rarely, Unable, I Didn't Try)

## Version

AutoKey version: 
Clone the repo now(sorry I dont know how to check the version when the autokey crashed, the date I clone is 2020-11-03) and running with the zero-install way, 

Used GUI (Gtk, Qt, or both): 
Gtk

If the problem is known to be present in more than one version, please list all of those.

Installed via: (PPA, pip3, …).
Zero-install way

Linux Distribution:
Manjaro 20.1.2

## Summary

Summary of the problem.

## Steps to Reproduce (if applicable)

Clone the repo now(sorry I dont know how to check the version when the autokey crashed, the date I clone is 2020-11-03) and running with the zero-install way, 
running command `/usr/bin/python -m autokey.gtkui`

## Expected Results

- Running Successfully

## Actual Results

- Instead, this happens. :(
Error msg box shown

If helpful, submit screenshots of the issue to help debug.\
Debugging output, obtained by launching autokey via `autokey-gtk --verbose` (or `autokey-qt --verbose`, if you use the Qt interface) is also useful.\
Please upload the log somewhere accessible or put the output into a code block (enclose in triple backticks).
```
Example code block. Replace this whith your log content.
```

## Notes

Describe any debugging steps you've taken yourself.

If you've found a workaround, please provide it here.

**Comment by sebastiansam55** [comment]
AutoKey uses python3, you can check what version your "python" binary is with `python --version`. 

In addition your need to make sure you are running the command from the right location. It needs to be run from `~/autokey/lib/` (where I have it installed); the way that I launch it is;
`cd autokey/lib`
`python3 -m autokey.gtkui`

**Comment by josephj11** [comment]
@woshichuanqilz Did you ever resolve this problem? I will close this issue if I don't hear from you shortly.
