### ISSUE TITLE
TXT file: line break instead of paragraph break

### ISSUE THREAD

**Issue by gazeto** [autokey/autokey#46]
Sorry for this simple question but I just don't find a solution:

I have a very simple _greets.txt_ template:

`Yours sincerely,`
`Anonymus`

The difficulty: I want to use a line break instead of paragraph break (for office or mail apps, wherever it really makes a difference). But I just don't know how to use a linebreak-charakter in the autokey window or text editor.
Is there any solution or do I have to use a script?

Thanks!

**Comment by ineuw** [comment]
I used  "\n" with success in a script.  Here is the code 
# alt-d	{{dhr}}
dhr = "{{dhr}}"
cr = "\n"
home = "<home>"
keyboard.send_keys(home + cr + dhr + cr)

**Comment by josephj11** [comment]
I don't know if '\n' will be interpreted as a line break or as a paragraph
break. I would try Ineu's solution first.

The other thing to try would be to find the character code for a line break
and see if you can specify it as a Unicode character.

See:
https://docs.python.org/2/howto/unicode.html#unicode-literals-in-python-source-code

I don't know if you can put one of those in a phrase, but they will
certainly work in a macro.

Please let us know what works for you.

BTW, for general questions, you will be much better off posting at
https://groups.google.com/forum/#!forum/autokey-users

There are a lot of members who may know your answer, while here, there are
only two of us

**Comment by gazeto** [comment]
Thanks a lot for your help
@ineuw 's suggestion results in the same "new paragraph" behaviour for office apps. What I need is Shift-Enter. Therefore, the very best and simple solution is using a script with one command:

`keyboard.send_keys("Yours sincerely"+"<shift>+<enter>"+"Anonymus") `

Problem solved :)

PS.: ok, I'll direct my questions to the google group next time ;-)
