### ISSUE TITLE
Allow non-character keys to be used in abbreviations (e.g. arrows, PgUp, home, end etc)

### ISSUE THREAD

**Issue by MichaelNZ85** [autokey/autokey#465]
## Version

AutoKey version: 0.95.10

Used GUI (Gtk, Qt, or both): 

Gtk (I think - using Cinnamon desktop environment)

Linux Distribution: Linux Mint 20 ("Ulyana") with Cinnamon

## Summary

I think it would be a good idea if abbreviations could include non-character keys, such as the arrow keys, PgUp/Down, home, end, media keys etc. For example, on my Mac I have BetterTouchTool configured to send the cursor to the end of the line and insert a semicolon upon the End key being pressed twice in quick succession. I would like to see the same functionality available in Autokey for Linux.

**Comment by josephj11** [comment]
I don't know the code base, but this sounds like it might be difficult to implement with the way AutoKey differentiates between regular keys and special keys.

Currently, I believe there is a pull request which would support modal hotkeys triggering phrases and scripts by pressing successive hotkeys for hierarchical selection that might address part of what you want to do. I don't see it at the moment. We also have a wait for keypress API call in the works that might also help a bit.

When any of this will be released is an open question as we do not currently have any lead developer(s) to integrate new changes which are being developed.

**Comment by sebastiansam55** [comment]
You can work around much of the limitations of autokey because its basically just python shortcuts haha.

```
keyboard.send_key("<end>")
time.sleep(0.01)
r = keyboard.wait_for_keypress("<end>", timeOut=0.2)
if r: # if <end> was pressed again
        print("End pressed twice")
        keyboard.send_keys(";")
```
This works great for me, you might want to tune timings if you don't hammer the end key like I tend to, the wait_for_keypress eats the next keystroke, so if the `timeOut` value is too long and you are doing something else it will eat a keystroke.
neat.

**Comment by BlueDrink9** [comment]
Afaik you can include `<left>` in a phrase content and it will send as a key. I'll re-open if that isn't the case
