### ISSUE TITLE
How can I use multiple combinations in one script ?

### ISSUE THREAD

**Issue by shpinog** [autokey/autokey#47]
Like this : 

"if Im press key X"
keyboard.send_keys("e")
"if Im press key Y"
keyboard.send_keys("e 1 2")

And all this in an endless loop, that would not assign individual keys for each script file,
is this possible?

**Comment by troxor** [comment]
Please use the [autokey-users](https://groups.google.com/forum/#!forum/autokey-users) for general usage questions.
