### ISSUE TITLE
engine.create_phrase() does not enable the phrase. 

### ISSUE THREAD

**Issue by sebastiansam55** [autokey/autokey#473]
## Classification:
The engine.create_phrase function does not operate as expected, while it does create the phrase it does not "activate" the phrase to the point where it would immediately start working

## Reproducibility:
*Always*

## Version

AutoKey version: current development version

Used GUI (Gtk, Qt, or both): GTK but Qt would presumably be equally effected

If the problem is known to be present in more than one version, please list all of those.

Installed via: git, tested on current develop branch.

Linux Distribution: ubuntu 20.04

## Summary

When using `engine.create_phrase` it does not add the phrase and "activate" as it seems it should. The cause of this seems to be that the a "mode" isn't added anywhere to the phrase in the function. 

However adding this mode either manually in the autokey script or in the function itself has unexpected results;
```
folder = engine.get_folder("numberpad")
hot = engine.create_phrase(folder, name="one", hotkey=([],"j"), contents="1")
hot.modes.append(autokey.model.helpers.TriggerMode.HOTKEY)
hot.persist()
```
The phrase object in question will correctly add and save the mode in the json file but the hotkey will not be handled correctly, when the hotkey is triggered it will send both the hotkey and the phrase, so after running this script when I press "j" instead of getting a "1" I get "j1".

If autokey (entire process not closing/reopen window) is restarted after the addition of the key there are no issues and it functions as expected.

## Steps to Reproduce (if applicable)
Adding a phrase should activate the phrase in the autokey internals, hotkeys also "eat" the keystroke used to activate them except in the case of a newly "engine" created hotkey/phrase.

## Expected Results

With the script provided above, I want to press "j" and only output "1". 

## Actual Results

It outputs "j1"

## Notes
If you've found a workaround, please provide it here.
I suppose one could add something to restart autokey at the end of the script. But that would be a pretty extreme workaround.

**Comment by BlueDrink9** [comment]
Did you fix this?

**Comment by josephj11** [comment]
@sebastiansam55 @BlueDrink9  I think one of you is using this feature, so it's probably fixed.

**Comment by sebastiansam55** [comment]
yeah, this reads like I didn't understand the difference between hotkeys and abbreviations based on the code. 

If I had used the `abbreviations` argument it would have more along the lines of what I was looking for.
