### ISSUE TITLE
Monospace font in Qt GUI doesn’t follow system settings.

### ISSUE THREAD

**Issue by Janfel** [autokey/autokey#474]
Hi, I noticed that the monospace font used by the Qt GUI doesn’t follow my system settings and looks really out of place. I think I tracked the issue to this function.

https://github.com/autokey/autokey/blob/b35fa51b3d8c2e048f065acc78b7f1744ab68a38/lib/autokey/qtui/common.py#L61-L68

I’ve looked through the documentation a bit and I think this might be the correct function to use:

```c++
QFontDatabase::systemFont
```
Accessible through PyQt as:
```python
PyQt5.QtGui.QFontDatabase.systemFont
```

**Comment by sebastiansam55** [comment]
Don't use Qt myself and I didn't notice any change in the font when I implemented this suggestion (likely because my system font is the same as the font found with `QFont("monospace")`. If you can upload before and after screenshots that show it does what you want it to I can open a PR with the changes

https://github.com/sebastiansam55/autokey/commit/31de5a0b45fff2d92e38be69c7ab1b121ab46105

**Comment by Janfel** [comment]
This is before the change:
![2020-11-19 12:14:34 AutoKey Before](https://user-images.githubusercontent.com/33464477/99659317-fc1e4000-2a60-11eb-82c1-6f066c72b1a0.png)

This is after the change:
![2020-11-19 12:15:08 AutoKey After](https://user-images.githubusercontent.com/33464477/99659346-09d3c580-2a61-11eb-9b8b-21172e78ec42.png)

**Comment by Elliria** [comment]
I'm having the same issue in Kubuntu 22.04 LTS with the AutoKey-Qt front-end.

**Environment:**
- Operating System: Kubuntu 22.04
- KDE Plasma Version: 5.24.4
- KDE Frameworks Version: 5.92.0
- Qt Version: 5.15.3
- Kernel Version: 5.15.0-27-generic (64-bit)
- Graphics Platform: X11
- AutoKey-Qt version: 0.95.10 installed via the Ubuntu repositories
- AutoKey-GTK version: 0.95.10 installed via the Ubuntu repositories

Before I get to the demonstration, I just wanted to point out that the script performs in the same way in both front-ends. Pressing the run button or using another trigger causes the correct dialog to be displayed. It's impossible to edit the script in the Qt front-end, though, and it looks all kinds of wrong.

Here's what an example script looks like in **AutoKey-GTK version 0.95.10**:

![EditorFontInGTK](https://user-images.githubusercontent.com/25792925/167326574-d2f33866-ceb5-4523-b732-c743b9cc0604.png)

And here's what the same script looks like in **AutoKey-Qt version 0.95.10** (notice the strange gaps between some of the characters):

![EditorFontInQt](https://user-images.githubusercontent.com/25792925/167326607-0deed116-09f2-405b-8b8d-21722154087e.png)

The script in the **Qt** front-end also behaves oddly. Here's an animated GIF in which I'm putting the cursor just to the right of the word "dialog" in the script and repeatedly pressing the **Del** key until there are no more characters to the right of the cursor, at which point I press the **Backspace** key repeatedly until all characters are deleted. Notice that it's deleting characters to the **left** of the cursor, which shouldn't be possible, it's causing a strange highlight at times, and when I get to the point where I'm backspacing, notice that the cursor stays in the same place the entire time I'm pressing the **Del** key and only begins moving to the left once I start hitting the **Backspace** key. Notice, also, that there's a gap between the cursor and the characters until the last character, at which point it snugs itself up right against it.

![AutoKeyQtDeletingCharacters](https://user-images.githubusercontent.com/25792925/167329753-cdb82e5d-beae-4fba-b7f6-d93f0e39ceaf.gif)

In this state, the Qt front-end can only be used to run scripts. All editing has to be done in the GTK front-end.

**Comment by josephj11** [comment]
That looks substantially weird. Based on this, I'm reopening this issue to bring it to the devs' attention.

**Comment by Elliria** [comment]
Thank you. It's really quite strange. Something else I didn't mention above is that it's impossible to set the cursor right next to a character. It will only allow itself to be placed in the strange white space that's between some of the characters. Another thing I didn't mention is that if I type the entire script contents one character at a time with no spaces, AutoKey-Qt inserts those odd spaces in for me automatically as I'm typing it.

**Comment by Elliria** [comment]
I've done a bit of further testing:

- If I select the messed-up-looking contents and copy them and then paste them into a text editor, they look fine and do not contain those odd spaces.
- If I create a new script that has the odd spaces in it while I'm in the Qt front-end, that same script looks normal if I load up AutoKey with the GTK front-end.
- In all cases, the behavior of the script is not affected. In other words, the script does what it was written to do despite how strange it looks and acts when you try to write it or edit it.

**Comment by josephj11** [comment]
This is starting to sound like a compatibility problem such as when versions of libraries don't quite match. It also sounds a bit like it might involve non-printable characters although the text editor would probably complain about those. Just to be sure, you might want to copy and paste the offending text into a file and display it with a hex tool such as  okteta or hexdump. (Okteta is a really nice tool for the rare occasions when you have to see or change data exactly as it is without something else interpreting or changing it first.)

**Comment by Elliria** [comment]
Okay, I copied that script's messed-up command and pasted it into Okteta. Hopefully this is usefu:

![HexEdit](https://user-images.githubusercontent.com/25792925/167519125-e8e04cd7-6a6c-444f-9936-98b6964ba607.png)

**Comment by josephj11** [comment]
I didn't check every byte, but it looks like there's nothing funny in there, so it 's probably a Qscintilla thing that's messed up. We'll leave that for the experts. Good luck, @BlueDrink9 and/or @sebastiansam55, LOL

**Comment by BlueDrink9** [comment]
@josephj11 not really appropriate to re-open this because it's a separate bug. Elliria was experiencing the old one as well because she was on a version prior to merge of Sam's fix.

But, it's here now. Probably won't look into it. Confirm it behaves the same on beta if you don't mind @Elliria

**Comment by Elliria** [comment]
Yep. This is still broken in AutoKey Qt 0.95.10 (which is the latest version available in Kubuntu 22.04 LTS), but has been fixed in AutoKey Qt 0.96.0-beta.10 and is working perfectly there now.

**Comment by BlueDrink9** [comment]
Thank goodness for that!

**Comment by Elliria** [comment]
As they always said on the A-Team, "I love it when a plan comes together,"

**Comment by Elliria** [comment]
It seems that I spoke too soon. It may have been (or seemed to be) fixed for me when I was using an older version of Ubuntu MATE, but it's not fixed for me now, at least not in the development version, which should be greater than 0.96.0.

This was also reported in issue #435.
