### ISSUE TITLE
Does anything actually work?

### ISSUE THREAD

**Issue by traderhut** [autokey/autokey#477]
## Classification:

bug

## Reproducibility:

always

## Version

AutoKey version: latest as of 11/19/2020

Used GUI (Gtk, Qt, or both): 
qt - Raspberry Pi 400 (i.e. 4)
If the problem is known to be present in more than one version, please list all of those.

Installed via: (PPA, pip3, …).
downloaded a zip from your website and unzipped it.

Linux Distribution:
Raspban (sp?)
## Summary

Wow, what works?  Some of your sample scripts work.
ALL of the menu items under the 'Help' menu do nothing - no feedback, just a crappy 'do nothing' response.
Running the script to Display Window Info doesn't work.

If you type in 'import clipboard' it autopopulates the word clipboard, so that must be the correct module to import to run fill_clipboard (self??, "test"), which I've tried with and without he word 'self' and well, it isn't defined...

No examples in any of the help of a simple valid script, nothing in your 'documentation' that says how you can ACTUALLY call fill_clipboard - it gives an error... what I was really trying to do was to do a mouse.click_absolute(100,100), but that doesn't seem to be in whatever the default thing is... I tried 'import time' and that works, I copied that from another script.. doesn't help, as I think I need the QtClipboard object installed.. but how to do that?

A simple example that finds a window and clicks at 10,10 would be really nice...

Oh, and I figured out how to install Xlib on my own.. but not figured out how to install the Magic Stuff to get the finding things on screen stuff to work.

Basically, this appears to be an app that will end up in the trash can due to no documentation that HELPS..
All of the class defs don't help if I have no idea how to 'use'/'import' them..

Oh, I'm a Software Architect of 35 years of programming, so I should be able to pick this stuff up WAY faster than 99% of the people who try to use your software...

Oh, and clicking the 'Run Script' button seems to run some random script that dies on line 485 or so, but has nothing to do with the 10 line script I'm editing.. I have to go over to the left and select the script, right click and do 'run script' every time I want to run it.. How about deleting the stupid button you have, and adding one that runs the script in your editor?   It too me a while to figure out that if I do 'new script' edit it, and hit 'run script' it runs some other freaking script that throws an error..

Oh, and the test code that gets the window information blows up because it can't open a dialog (well, it just quietly does nothing like about 99% of the rest of the app...)  I'm up to about 2 hours of screwing around with this...

It *seems* like it should do what I want it to, but just zero clue...

Oh, and if you run it as root, it won't even open the screen... took me a while to figure that one out too  A popup that says "Hey, I don't run as root' might be good... Oh, and why the heck not?

Frustrated in Texas.
## Steps to Reproduce (if applicable)

- I do this
- I do that

## Expected Results

- This should happen.

## Actual Results

- Instead, this happens. :(

If helpful, submit screenshots of the issue to help debug.\
Debugging output, obtained by launching autokey via `autokey-gtk --verbose` (or `autokey-qt --verbose`, if you use the Qt interface) is also useful.\
Please upload the log somewhere accessible or put the output into a code block (enclose in triple backticks).
```
Example code block. Replace this whith your log content.
```

## Notes

Describe any debugging steps you've taken yourself.

If you've found a workaround, please provide it here.

**Comment by traderhut** [comment]
Oh, version 0.95.10, Python version 3.7.3 - July 2020...  And the About box DOES come up...  AND I just selected the documentation menu item and it just worked too..

Script that ships with it: 
Script name: 'Display window info'
Traceback (most recent call last):
  File "/src/autokey/lib/autokey/service.py", line 485, in execute
    exec(script.code, scope)
  File "<string>", line 8, in <module>
  File "/src/autokey/lib/autokey/scripting.py", line 276, in info_dialog
    return self._run_kdialog(title, ["--msgbox", message], kwargs)
  File "/src/autokey/lib/autokey/scripting.py", line 259, in _run_kdialog
    universal_newlines=True) as p:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'kdialog': 'kdialog'

**Comment by traderhut** [comment]
I got the clipboard to work... it is clipboard.fill_clipboard and you don't need an import... Who'd have guessed.. Ah, why have to guess?

**Comment by sebastiansam55** [comment]
Sounds like raspbian OS doesn't have the packages we use installed. The rp400 is like 1 month old so chill.

sudo apt-get install kdialog

Will fix the error you posted in a comment.

In your main issue it sounds like the webbroswer python module isn't installed or is not functioning. If you pop open python3 and run `import webbroswer` you can see if that is even installed by default on raspbian.

The scripting modules are all imported automatically (you don't have to import stuff like clipboard system window etc detailed in the documentation)

**Comment by traderhut** [comment]
Ah, yeah, so I should chill a bit.. been a very long day at the end of a very long week... (12-16 hour days) and I decided to 'relax' and do this... LOL...  I googled and installed the kdialog, and that is working... I took the window title, and pasted it into the 'window.activate()' call and ran the script again and it still says that AutoKey is the active window, so that didn't appear to work..

**Comment by traderhut** [comment]
it would be very useful to create a script that does pretty much every feature... that way, if I want to say, sleep 1 second, I can find that example in the 'everything' script and copy and paste it out and I don't need to learn anything... would just make things easier..

**Comment by sebastiansam55** [comment]
If you run `autokey-qt -l` or use something like `xwininfo` you can see exactly what the title of the window is. sometimes the way that stuff is handled is weird in X. It also activates the first match (from what I remember, don't remember exactly how it is sorted). 

You need to make sure to install `wmctrl`.

You're def right that our package requirements should be in the main readme in case some one installs via git first.

**Comment by sebastiansam55** [comment]
> it would be very useful to create a script that does pretty much every feature... that way, if I want to say, sleep 1 second, I can find that example in the 'everything' script and copy and paste it out and I don't need to learn anything... would just make things easier..

The wiki here has more up to date api examples. There was an issue this week about one of them being outdated so don't take them as gospel.

**Comment by traderhut** [comment]
Also, how to you get/set the mouse position?  The easy way to figure out where to click is to do it once and monitor it

**Comment by traderhut** [comment]
I also need to click (down) wait then (up), the super fact click isn't even being considered as a click by the app that I'm running - it is expecting a finger press...

**Comment by sebastiansam55** [comment]
The mouse functions are relatively barebones at the moment.

```
from Xlib import X, display
d = display.Display().screen().root.query_pointer() #get pointer location
x = str(d.root_x) # get x coord and convert to string
y = str(d.root_y) # get y coord and convert to string
dialog.info_dialog("(X, Y)", x+", "+y) #create an info 
```

Is a script I wrote the other day for autokey to display the current mouse coords in a info dialog.

**Comment by sebastiansam55** [comment]
> I also need to click (down) wait then (up), the super fact click isn't even being considered as a click by the app that I'm running - it is expecting a finger press...

I'm on my phone atm but I opened a pr the other day that should show you how to do this more or less titled Mousemove

```
from Xlib.ext import xtest
  xtest.fake_input( etc. Etc.
```
If has a button press and release which is what it sounds like you need. You can time.sleep(1) for one second pause. I don't think you have to `import time`? Not sure off the top of my head

**Comment by josephj11** [comment]
@traderhut Take a look at our [wiki](https://github.com/autokey/autokey/wiki/). We have a lot of example code there and are always happy to accept more.

In particular, see our [API examples](https://github.com/autokey/autokey/wiki/API-Examples).

**Comment by BlueDrink9** [comment]
I'm going to close this until a polite and succinct list of documentation/usability improvements can be suggested. Until then, this was just one user's experience using an unsupported distro with missing dependencies.
