### ISSUE TITLE
f6|f7|f8|f9 not working as hotkeys

### ISSUE THREAD

**Issue by ghost** [autokey/autokey#485]
## Classification:

Feature (New)

## Reproducibility:

Always

## Version

AutoKey version: latest

Used GUI (Gtk, Qt, or both): both

Installed via: apt,pip

Linux Distribution: debian

## Summary

I want to set f6|f7|f8|f9 hotkeys for my scripts but aren't recognized. Instead f4|f5|f10 are recognized.

## Steps to Reproduce (if applicable)

Create a script, go to Hotkey > set > press to set > "here press f6|f7|f8|f9"

## Expected Results

Add f6|f7|f8|f9 keys as hotkeys

## Actual Results

Instead, this not happens. :(

**Comment by ghost** [comment]
This is the result when I press f6|f7|f8|f9 with Settings > show log view enabled.
![image](https://user-images.githubusercontent.com/48352419/100548586-c867c500-326d-11eb-9e3c-24d8473abfd9.png)

**Comment by sebastiansam55** [comment]
I'm not familiar with where your screenshot comes from? Seems like it is the autokey log? 

Can you provide information about what kind of keyboard you are using? I recently started using a keyboard that is designed for apple devices and by default the F[1-12] and FN keys are weird.

see: 
https://unix.stackexchange.com/questions/121395/on-an-apple-keyboard-under-linux-how-do-i-make-the-function-keys-work-without-t

for more information, by default apple keyboards only send F1-F12 signals when holding down the FN key. And after I did the above recommend stuff some F6 area keys were still not reading right, I don't remember  what I did next to change that.

You can use `xev -event keyboard` or `sudo evtest` to see if your keyboard is sending the right signals. If you can provide logs of that showing the correct signals being sent alongside autokey reading the wrong signals we can continue to work on it but this sounds like a keyboard issue more than a autokey one.

**Comment by ghost** [comment]
Yes, they are the logs of the pressed buttons seen from the autokey qt graphic screen.
Anyway you were right, it's the keyboard itself that doesn't work, being a historical relic I didn't expect anything different... think that it doesn't even have the fn button.
I solved it by taking another keyboard that I had at home and now everything works perfectly.
Thanks @sebastiansam55  for your help!
