### ISSUE TITLE
Fatal error starting AutoKey

### ISSUE THREAD

**Issue by Curbuntu** [autokey/autokey#49]
I fired up my Linux Mint 17.3 (64-bit) laptop today and received this error message:

Fatal error starting AutoKey.
'ascii' codec can't encode character u'\xed' in position 20: ordinal not in range(128)
![Uploading Screenshot from 2017-04-03 11:28:24.png…]()

I haven't used the system in about 5 days, because I've been away.  There were some updates this morning, but this error message appeared right after log-in, before I updated anything. I couldn't discover any similar issues that were resolved.

Thanks in advance for any help.

**Comment by josephj11** [comment]
We've had a bunch or errors similar to this. I don't think we ever figured out exactly what causes it. It may have to do with multi-byte character sets like UTF-8. ASCII shouldn't be a limitation any more. It's a bug.

I seem to recall that uninstalling and then reinstalling AutoKey fixed it sometimes.
_Before_ you do that, make a backup of everything under `~/.config/autokey` (being sure to include hidden files). It shouldn't get touched (as long as you don't purge AutoKey), but you can't be too careful.

What version of AutoKey do you have installed? The one from here is the latest (last?) version of the main branch. Run `autokey -v` . The last things that were fixed had to do with multi-byte character sets.

BTW, your link to the screenshot just links back to this page (no picture). Maybe you should try a file name like "junk.png" with no special characters in it.

If reinstalling doesn't fix it, I'll dig into the list and see if I can find anything helpful.

If you want to, you can also try installing the [Python 3 branch of AutoKey](https://github.com/guoci/autokey-py3) . It's newer and shinier and has a developer who can actually fix things. ;)

We support both versions on our [support](https://groups.google.com/forum/#!forum/autokey-users) list.
