### ISSUE TITLE
[BUG] I can't launch it and it says that the package isn't installed,but I installed it

### ISSUE THREAD

**Issue by ghost** [autokey/autokey#496]
## Classification:

Bug

## Reproducibility:

Always I try to launch it,it doesn't work.

## Version

AutoKey version: AutoKey-common 0.95.10-2

Used GUI (Gtk, Qt, or both):AutoKey-qt

Installed via:AUR with Pamac

Linux Distribution:Manjaro Kde
## Summary

That it doesn't launch

## Steps to Reproduce (if applicable)

Go into krunner and launch AutoKey (qt)

## Expected Results

That it launches

## Actual Results

That it doesn't launch,I can't see a system tray or taskbar icon after trying to launch the program.

```
Traceback (most recent call last):
  File "/usr/bin/autokey-qt", line 33, in <module>
    sys.exit(load_entry_point('autokey==0.95.10', 'console_scripts', 'autokey-qt')())
  File "/usr/bin/autokey-qt", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: autokey

**Comment by josephj11** [comment]
Welcome to AutoKey. We hope you can resolve this quickly and will help if we can.

You are installing AutoKey from an Arch package. Each distribution does their own packaging and we have no control (and, usually, no influence) over that process.

You have (at least) two good options for resolving this.
1) Ask other Arch/Manjaro users for support on your distro's support lists/forums. We do have a number of users successfully using AutoKey with Manjaro/Arch.
2) Install AutoKey yourself from GitHub by following these [instructions](https://github.com/autokey/autokey/wiki/Installing).

If you get stuck at any point or have questions, feel free to post on our support [forum/list](https://groups.google.com/forum/#!forum/autokey-users).
