### ISSUE TITLE
"View script error" fails

### ISSUE THREAD

**Issue by ntrrgc** [autokey/autokey#50]
```
Traceback (most recent call last):
  File "/home/ntrrgc/.local/lib/python3.5/site-packages/autokey/gtkui/notifier.py", line 270, in on_show_error
    self.app.show_script_error()
TypeError: show_script_error() missing 1 required positional argument: 'parent'
```

**Comment by troxor** [comment]
Can you provide a way to reproduce what you're getting? Trying a different script, I get the following traceback instead:

`Traceback (most recent call last):
  File "/home/troxor/.local/lib64/python3.4/site-packages/autokey/gtkui/configwindow.py", line 1250, in on_show_error
    self.app.show_script_error(self.ui)
  File "/home/troxor/.local/lib64/python3.4/site-packages/autokey/gtkapp.py", line 277, in show_script_error
    self.notifier.icon.set_from_icon_name(ConfigManager.SETTINGS[NOTIFICATION_ICON])
AttributeError: 'IndicatorNotifier' object has no attribute 'icon'`

**Comment by ntrrgc** [comment]
As I put in the title, I wrote a script, presumably with a programming error, run it and the used the "View script error" option in the tray icon. I was using autokey-gtk from this git.

**Comment by TheoRet** [comment]
I probably have the same issue. I use Linux Mint 18 Mate and autokey-gtk. After getting notified that one of my scripts has an error, I press "View Script Error" and the appearing dialog is empty. I did not have this issue in autokey python2, where it worked fine. The problem appeared when I changed to the py3 version.

**Comment by TheoRet** [comment]
I can also try to post the Traceback, but you need to tell me how to get it...

**Comment by troxor** [comment]
@TheoRet please see https://github.com/autokey/autokey/wiki/Problem-Reporting-Guide and https://github.com/autokey-py3/autokey/blob/master/README.rst

**Comment by TheoRet** [comment]
Thanks!

This line appears when starting autokey-gtk from the command line:
`(autokey-gtk:7125): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed`
There is no visible problem though, autokey starts normal.

Then I created a script error and pressed "View Script Error", where I get the same message as ntrrgc:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/autokey/gtkui/notifier.py", line 269, in on_show_error
    self.app.show_script_error()
TypeError: show_script_error() missing 1 required positional argument: 'parent'
```

**Comment by troxor** [comment]
@ntrrgc @TheoRet can you retry from latest `git HEAD`? The latest commit works as expected on my test machines.

**Comment by troxor** [comment]
This should be fixed, please update if you still encounter the issue.

**Comment by TheoRet** [comment]
Thanks a lot! It works now.
