### ISSUE TITLE
Feature request: TextExpander Compatibility

### ISSUE THREAD

**Issue by gunar** [autokey/autokey#50]
It would be great to be able to import, or even sync settings with TextExpander.com.
I love AutoKey. Unfortunately the rest of my team uses TextExpander (mac-only).

Thanks for awesome piece of software :-)

**Comment by josephj11** [comment]
Sorry, but we do not currently have a developer for this branch of the project, so there's no one to implement that for you.

You may want to visit the [Python 3 branch](https://github.com/autokey/autokey). It's new and improved (TM) and, most importantly, has a developer.

We offer [support](https://groups.google.com/forum/#!forum/autokey-users) for both versions.
(And I check that list daily.)

Come on by and let us know what you are doing with AutoKey.

Joe
