### ISSUE TITLE
Feature Request: Be able to build complex visual apps

### ISSUE THREAD

**Issue by kreezxil** [autokey/autokey#505]
## Classification: 

- Feature

## Version

AutoKey version: 95.10

## Summary

I'd like to be able to specify a window that I can then control elements on such as buttons, inputs, dropdowns, etc. Autokey supports quite of few of the elements already as dialogs. I would like to see autokey taken that extra mile to be able to make full apps. I would be great way to easily prototype a concept. And some of us autokey fanatics probably wouldn't even go beyond that.

A possible test application would be to duplicate the common calculator for example:
![image](https://user-images.githubusercontent.com/3880072/105187976-03ada400-5af9-11eb-9351-5dddc42b1046.png)

**Comment by josephj11** [comment]
You can do most of this now by calling out to an external dialog manager such as kdialog, Zenity, or yad using subprocess(). I have seen a whole simple media player front end built in yad.

If you know enough, you can probably call Qt or GTK directly from your script to do almost anything.

While such a feature would be cool to have, I think other packages can supply these capabilities better than we can and we certainly have more than enough to do without expanding the scope of the project.

**Comment by BlueDrink9** [comment]
This is definitely out of autokey scope. You can make GUIs with python. If autokey can't control or access a particular python dialog, open a separate issue
