### ISSUE TITLE
Why Package in AUR  Removed?

### ISSUE THREAD

**Issue by SmartManoj** [autokey/autokey#509]
[Link](https://github.com/autokey/autokey/wiki/Installing#user-content-arch-linux:~:text=(AUR%20package).)

**Comment by josephj11** [comment]
We build the AutoKey application and then packagers do or don't do whatever they please with it and usually don't even communicate with us at all. We have no control over that. Ask on your distribution support forums.

However, we do have a number of Arch and Manjaro users, so it does work for them. And, you can always manually install it yourself. It's pretty easy to do following these [instructions](https://github.com/autokey/autokey/wiki/Installing#arch-linux). And, if that doesn't work, the pip instructions below it on that page. The only difficulty with doing a pip install is that you have to manually get all the dependencies installed without breaking anything else on your system. That's part of the "charm" of Arch. :)

**Comment by sebastiansam55** [comment]
The autokey AUR package was split a few months ago into Qt and Gtk versions to avoid dependency issues, I have updated the install page to reflect this change, see the changes here https://github.com/autokey/autokey/wiki/Installing/_compare/a3cfbdc7123a89886bff4a97708b65c41cd01dd1...3d82a2e409f77920780978a4348426d054e0b43f

This issue can probably be closed now assuming there is nowhere else the old packages are referenced.

**Comment by josephj11** [comment]
OK. When I update the wiki, I do it directly, but you have managed to do it with git - which is better.

Can you add a note to our wiki, etc. that explains how to do it this better way?

**Comment by sebastiansam55** [comment]
Editing anything directly on the github website is equivalent to using git, I just opened the webpage and clicked the edit button for the page and made the changes, I will say the diff link was a bit harder to find but it's all there, just sort of hidden.

I submitted the one line PR the same way (after testing!) just because it was faster than figuring out how to rebase my fork again.
