### ISSUE TITLE
ImportError: No module named 'dbus.mainloop.qt'

### ISSUE THREAD

**Issue by ntrrgc** [autokey/autokey#51]
```
symlink from /home/ntrrgc/.local/share/kde4/apps/autokey to /home/ntrrgc/.kde/share/apps/autokey created.
Traceback (most recent call last):
  File "/home/ntrrgc/.local/bin/autokey-qt", line 56, in <module>
    from autokey.qtapp import Application
  File "/home/ntrrgc/.local/lib/python3.5/site-packages/autokey/qtapp.py", line 22, in <module>
    import sys, traceback, os.path, signal, logging, logging.handlers, subprocess, queue, time, dbus, dbus.mainloop.qt
ImportError: No module named 'dbus.mainloop.qt'
deleting symlink /home/ntrrgc/.kde/share/apps/autokey
```

OS: ArchLinux
Installed with the instructions from the README.

**Comment by troxor** [comment]
Are you installing from git HEAD, or using the AUR PKGBUILD?

**Comment by ntrrgc** [comment]
git HEAD

**Comment by karmicdude** [comment]
The same problem

**Comment by troxor** [comment]
What distribution are you using here, and do you have python-qt4-dbus or equivalent package installed? I use the GTK frontend, so autokey-qt may get less attention.

**Comment by karmicdude** [comment]
ArchLinux. 
For example autokey-gtk without virtualenv:
```bash
autokey-gtk
Traceback (most recent call last):
  File "/usr/bin/autokey-gtk", line 28, in <module>
    from autokey.gtkapp import Application
  File "/usr/lib/python3.5/site-packages/autokey/gtkapp.py", line 24, in <module>
    from gi.repository import Gtk, Gdk, GObject, GLib
  File "/usr/lib/python3.5/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'
```
With an virtualenv - the same problem

I found only one package in all official repos and user repos with name dbus qt4: `libdbusmenu-qt4`.

Virtualenv:
```bash
(autokey)
[14:09] ~ [zengine@zen]
 $ type pip
pip is hashed (/home/zengine/autokey/bin/pip)

(autokey) 
[14:09] ~ [zengine@zen]
 $ pip freeze
appdirs==1.4.0
autokey-py3==0.93.7
cached-property==1.3.0
chardet==2.3.0
dbus-python==1.2.4
docker-compose==1.9.0
docker-py==1.10.6
docker-pycreds==0.2.1
dockerpty==0.4.1
docopt==0.6.2
gi==1.2
httpie==0.9.8
isc==2.0
jsonschema==2.5.1
packaging==16.8
pyalpm==0.8
Pygments==2.1.3
pyinotify==0.9.6
pyparsing==2.1.10
python-libtorrent==1.1.1
python-xlib==0.18
pyxdg==0.25
PyYAML==3.12
Reflector==2016.12.3.19.6.12
requests==2.12.4
six==1.10.0
team==1.0
texttable==0.8.7
typing==3.5.2.2
urllib3==1.19.1
virtualenv==15.0.3
websocket-client==0.40.0

(autokey)
[14:18] ~ [zengine@zen]
 $ autokey-gtk
Traceback (most recent call last):
  File "/home/zengine/autokey/bin/autokey-gtk", line 11, in <module>
    load_entry_point('autokey-py3==0.93.7', 'console_scripts', 'autokey-gtk')()
  File "/home/zengine/autokey/lib/python3.5/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/zengine/autokey/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/home/zengine/autokey/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/home/zengine/autokey/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/zengine/autokey/lib/python3.5/site-packages/autokey/gtkui/__main__.py", line 4, in <module>
    from autokey.gtkapp import Application
  File "/home/zengine/autokey/lib/python3.5/site-packages/autokey/gtkapp.py", line 24, in <module>
    import gi
  File "/usr/lib/python3.5/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'

(autokey)
[14:19] ~ [zengine@zen]
 $ autokey-qt
Traceback (most recent call last):
  File "/home/zengine/autokey/bin/autokey-qt", line 56, in <module>
    from autokey.qtapp import Application
  File "/home/zengine/autokey/lib/python3.5/site-packages/autokey/qtapp.py", line 22, in <module>
    import sys, traceback, os.path, signal, logging, logging.handlers, subprocess, queue, time, dbus, dbus.mainloop.qt
ImportError: No module named 'dbus.mainloop.qt'
```
By the way `gi` also was required, I install it manully

**Comment by troxor** [comment]
Thanks for the information. I'll take a look when I get some time.

**Comment by troxor** [comment]
It's interesting that a file installed to python3's site-packages directory isn't legitimate Python 3 syntax though...

**Comment by karmicdude** [comment]
If I'm not mistaken, in python3 `print` is a function, i.e. `print(url)`.  `print url` is a python2 syntax

**Comment by troxor** [comment]
python-pyqt4 provides /usr/lib/python3.5/site-packages/dbus/mainloop/qt.so, but Archlinux removed kdebindings-python (PyKDE4). Until the codebase can be updated to use PyQt5 (#56), autokey-qt won't run on Archlinux without workarounds. I recommend using autokey-gtk in the meantime.

**Comment by rtizzy** [comment]
Experiencing this same issue on Ubuntu 18. @troxor

**Comment by IS-Kuan** [comment]
Same issue with Chakra (tested in 2018/01), installed via `sudo pip3 install autokey`

**Comment by luziferius** [comment]
A bit off-topic: About that SyntaxError with `gi` you discussed: You simply installed the wrong package. What you want is https://pygobject.readthedocs.io/en/latest/, but by using `pip3 install gi`, you got this (probably abadoned and) conflicting `gi` instead: https://pypi.python.org/pypi/gi/1.2
This is python2 only without specifying so, which causes pip to happily install it and break your environment.

**Comment by SFreiheit** [comment]
i have the same Problem:

:~/Programme/autokey$ autokey-qt 
Traceback (most recent call last):
  File "/usr/local/bin/autokey-qt", line 4, in <module>
    __import__('pkg_resources').run_script('autokey==0.94.0', 'autokey-qt')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/autokey-0.94.0-py3.5.egg/EGG-INFO/scripts/autokey-qt", line 56, in <module>
    from autokey.qtapp import Application
  File "/usr/local/lib/python3.5/dist-packages/autokey-0.94.0-py3.5.egg/autokey/qtapp.py", line 33, in <module>
    import dbus.mainloop.qt
ImportError: No module named 'dbus.mainloop.qt'

i use Ubuntu 16.04.4
i hae downloaded autokey today an i have install it with this command:

sudo apt install python3-pip
sudo python3.5 setup.py install 

what can i do?

**Comment by josephj11** [comment]
@SFreiheit - for now, try the GTK version. It is "more" likely to work until we make more progress on the QT front. I am also gradually assembling installation instructions [here](https://github.com/autokey/autokey/wiki/Installing). Feedback appreciated.

**Comment by luziferius** [comment]
@SFreiheit 
How to debug this issue: (This is quite common and I got bitten by this, too.)
- I assume that the Ubuntu package `python3-dbus.mainloop.qt` is already installed, but it still does not work.
- In a terminal, start `python3`
In the python prompt, execute the following 2 lines (only the grey blocks, no dots at the end):
- `import dbus.mainloop`. This should work. (On success, nothing is printed)
- `help(dbus.mainloop)` to open the module help. It has a `FILE` section at the bottom of that document which shows the absolute path of the module in use. (You can quit the help and python prompt by using `q`, then `[Ctrl]+[D]`)
- Note that path down. It should be `/usr/lib/python3/dist-packages/dbus/mainloop/__init__.py`, which means that the system supplied version is used. 
If the path is different, like `/usr/local/lib/[…]` or `/home/[username]/.local/lib/[…]`, a local, pip-installed version of `dbus.mainloop` is in use, which takes precedence and _shadows_ the system supplied one. The pip-installed version lacks `dbus.mainloop.qt`, which is therefore unavailable until you remove the local one.
- To remove pip-installed dbus-python(if any): If in `/usr/local/`: use `sudo -H pip3 uninstall dbus-python`, if in `/home`, use `pip3 uninstall dbus-python`
After uninstall, importing `dbus.mainloop.qt` should work, and AutoKey should start.

**Comment by Newkely** [comment]
Maybe you can try to reinstall the package python-qt4-dbus [https://bugs.launchpad.net/ubuntu/+source/kdebindings/+bug/335811](url)
