### ISSUE TITLE
Czech characters

### ISSUE THREAD

**Issue by matata86** [autokey/autokey#51]
Hi,
I installed Autokey python version, work great, but no paste czech character ex. 'ščřž'?

Any solution?

**Comment by josephj11** [comment]
Known issue. For problems with International character sets, please install [autokey-py3](https://github.com/guoci/autokey-py3). It has much better support for international character sets and has a developer who can address issues.

For general support questions like this, please visit us at the support [list](https://groups.google.com/forum/#!forum/autokey-users). We support both branches of AutoKey.
