### ISSUE TITLE
Can I exit a script with a keyboard interrupt?

### ISSUE THREAD

**Issue by jumpy72red** [autokey/autokey#515]
## Classification:

Enhancment

## Reproducibility:

Always

## Version

AutoKey version:  0.95.10

Used GUI (Gtk, Qt, or both): Gtk

If the problem is known to be present in more than one version, please list all of those.

Installed via: (PPA, pip3, …). Installed from github and used dpkg commands

Linux Distribution: Kali Linux

## Summary

Basically, I am trying to make an autoclicker and I'm not sure if I'm being stupid but I can't find a way to stop it. The toggle turns it on, however I want to use a keyboardinterrupt or even use the toggle again to stop a forever loop. I have tried the script in multiple different ways that should make it work in a regular program, but AutoKey won't seem to pickup a KeyboardInterrupt.

## Steps to Reproduce (if applicable)

`import sys
import time
from time import sleep
try:
    while True:
        mouse.click_relative_self(0, 0, 1)
        time.sleep(0.15)
except KeyboardInterrupt:
    sys.exit()`

That was the last code I tried, but all of them had the same sort of idea, just a while true loop with a small delay and a way to end it with a variable or a function

## Expected Results

I would like to be able to stop a script with a keyboard shortcut

## Actual Results

Instead, it doesn't end and I have had to restart my laptop twice to stop the code.

If helpful, submit screenshots of the issue to help debug.\
Debugging output, obtained by launching autokey via `autokey-gtk --verbose` (or `autokey-qt --verbose`, if you use the Qt interface) is also useful.\
Please upload the log somewhere accessible or put the output into a code block (enclose in triple backticks).
```
No log content needed, although I will say that you spelt "with" wrong on the template at this area.```

## Notes

Describe any debugging steps you've taken yourself.
Tried multiple different ways of stopping the script, to no avail

If you've found a workaround, please provide it here.

**Comment by jumpy72red** [comment]
I apologise that this isn't an issue or anything but I honestly couldn't find a single way to do it.

**Comment by RolandSherwin** [comment]
I was facing this same issue, i finally gave up and got the number of clicks as an input and just used that.

**Comment by josephj11** [comment]
I thought I answered this before, but here goes:

I don't know anything about detecting keyboard interrupts on Linux, but here's a workaround:

Write the script as follows:
Set an AutoKey [global variable](https://github.com/autokey/autokey/wiki/API-Examples#store) to "true". "True" can be any value that you can distinguish from "false".
Start your loop.
Inside your loop, retrieve the value of the AutoKey global variable. If it is no longer set to "true", break out of the loop.

Write a second script and assign it to a hotkey.
In this script, set the above AutoKey global variable to "false" and quit.

Now, when the first script is running, press the hotkey for the second script and the first script should terminate.

**Comment by jumpy72red** [comment]
> I thought I answered this before, but here goes:
> 
> I don't know anything about detecting keyboard interrupts on Linux, but here's a workaround:
> 
> Write the script as follows:
> Set an AutoKey [global variable](https://github.com/autokey/autokey/wiki/API-Examples#store) to "true". "True" can be any value that you can distinguish from "false".
> Start your loop.
> Inside your loop, retrieve the value of the AutoKey global variable. If it is no longer set to "true", break out of the loop.
> 
> Write a second script and assign it to a hotkey.
> In this script, set the above AutoKey global variable to "false" and quit.
> 
> Now, when the first script is running, press the hotkey for the second script and the first script should terminate.

Thanks so much! I hadn't realised you could use global variables! Thank you so much for the reply!

**Comment by jumpy72red** [comment]
Closed
