### ISSUE TITLE
Feature Request: Export/Import phrases and scripts

### ISSUE THREAD

**Issue by SpinningCubeSolutions** [autokey/autokey#516]
## Classification:

Feature (New)

I think it would be a really good idea to add the ability to export all your phrases and scripts (possibly to a JSON file) and import scripts from such a file. That way, if you have multiple computers using AutoKey or you need to reformat your computer, you can simply export your scripts and then import them on the other computer(s).

**Comment by josephj11** [comment]
This could be documented better, but it's easy to do now.

Copy the directory subtree from $HOME/.config/autokey (including all the hidden files) and you're good to go.

If you just want your phrases and scripts, then, by default, they are stored under $HOME/.config/autokey/data.

However, when you create a new folder from within the AutoKey main menu, you can choose any path you like. It can even be in something like a Dropbox folder. 

To be safe, always create the external directory from scratch and then copy your existing phrases and scripts into it. (Older versions of AutoKey used to delete all the content of a pre-existing folder when you created it within AutoKey.)

If you use an external folder (directory subtree), it has the added benefit that it is unaffected if you ever need to uninstall/reinstall AutoKey and is convenient for including in any backup system you may be using.

There is no master file coordination within AutoKey, so you can pick and choose which phrases and scripts to copy/backup/restore. Just remember that each one has a hidden sidecar file which holds its metadata. A phrase called myphrase consists of two files, myphrase.txt and .myphrase.json. A script called myscript consists of myscript.py and .myscript.json. (The leading dots on the json file names make them hidden files. These files will be no longer be hidden in the next release of AutoKey.)

When you manually add script/phrase files into folders AutoKey knows about, it may notice them and add them to the main menu, but it will always see them if you exit AutoKey and restart it after any such changes.
