### ISSUE TITLE
adressing shift key

### ISSUE THREAD

**Issue by stef-a** [autokey/autokey#517]
## Classification: Bug, Performance

(Pick one of: Bug, Crash/Hang/Data Loss, Performance, UI/Usability, Feature (New), Enhancement)

## Reproducibility:Always

(Pick one of: Always, Sometimes, Rarely, Unable, I Didn't Try)

## Version: 0.95.10

AutoKey version: gtk

Used GUI (Gtk, Qt, or both): 

If the problem is known to be present in more than one version, please list all of those.

Installed via: (PPA, pip3, …).

Linux Distribution: elementary OS 5.1.7 Hera

## Summary
i am having a very hard time adressing the shift key. I don't know if it's my hardware but everything seems to work just fine until i try to press-release the shift key. 
i am trying to run this script for writing in latex 
\\\ keyboard.send_keys('\\begin{center}')
keyboard.send_key('<enter>')
keyboard.send_key('<tab>')
keyboard.press_key('<shift>')
keyboard.fake_keypress('4')
keyboard.release_key('<shift>')
keyboard.send_key('b')
keyboard.send_key('<enter>', repeat = 2 )
keyboard.press_key('<shift>')
keyboard.fake_keypress('4')
keyboard.release_key('<shift>')
keyboard.send_key('<enter>')
keyboard.send_keys('\\end{center}')
keyboard.send_key('<left>', repeat = 23) \\\

Summary of the problem.

## Expected Results

- This should happen. 
-\begin{center}
         $
         
        $
\end{center}

## Actual Results
\begin{center}
44
\end{center}

- Instead, this happens. :(

If helpful, submit screenshots of the issue to help debug.\
Debugging output, obtained by launching autokey via `autokey-gtk --verbose` (or `autokey-qt --verbose`, if you use the Qt interface) is also useful.\
Please upload the log somewhere accessible or put the output into a code block (enclose in triple backticks).
```
Example code block. Replace this whith your log content.
```

## Notes

Describe any debugging steps you've taken yourself.

If you've found a workaround, please provide it here.

**Comment by stef-a** [comment]
Won't show the code i pasted so im adding a screenshot
![Screenshot_20210309-174957_Chrome](https://user-images.githubusercontent.com/80348295/110507074-faf04c00-80ff-11eb-92ce-4d0027962f63.jpg)

**Comment by josephj11** [comment]
Welcome to AutoKey, stef-a!

First, a quick note: GitHub uses markdown, so whenever you need to post code, you need to protect it. Snippets can be enclosed in single backticks and blocks are started and ended with lines containing just triple backticks. For all the details, there's a small icon of an M-down-arrow in the lower right corner of a posting panel you can click on.

It's not a bug, it's a feature. ;)

But, seriously,

1) Never use `keyboard.send_key()` unless nothing else works (or you need its repeat parameter. Always  use `keyboard.send_keys()`. `keyboard.send_key()` can only deal with single keypresses of things that appear on your physical keyboard. It doesn't deal with things like modifier keys such as Shift.

2) `keyboard.send_keys()` is somewhat better. It can do things like `keyboard.send_keys("<shift>+[")` to get a left curly brace or other longer strings. It does have some limitations. It can't deal with multibyte characters (anything other than EN-US) and it is very limited in dealing with anything you can't generate with normal physical keypresses without getting convoluted.

3) Whenever possible, put whatever you want to emit into a string, load it into the clipboard, and then paste it using `keyboard.send_keys("<ctrl>+V")`. This will almost always work and avoids a bunch of other problems.

With phrases, always start with the `Paste using clipboard (Ctrl+V)` option unless your phrase needs to include macros such as `<cursor>` or active keys that the application has to respond to directly like arrow keys.

The only way to actually fix this issue would be to replace the keyboard module with something better and, so far, no one has figured out how to do that.

I've never quite figured out what `keyboard.fake_keypress()` is for, but you probably don't need it.

**Comment by stef-a** [comment]
thank you very much josephj11! 
i will definitely read better the clipboard section on the documentation.
as for `keyboard.fake_keypress`  i cannot really say much. i just switched from windows 2 days ago.

**Comment by josephj11** [comment]
It's not your fault. It's not documented anywhere. I should add it to our wiki. It comes up frequently.
RTFM only works if there's an FM. :)

**Comment by josephj11** [comment]
Welcome to Linux. Once you get used to it, you'll probably love it.

I highly recommend learning the basics of bash or zsh. It will open all sorts of possibilities. Whenever I don't have a command that does what I want, I just string together a few existing programs in a bash script and I have my new command just the way I want it.

I live mostly in the GUI, but I switch back to the command line all the time to do specific tasks. I even have bash scripts that use dialog boxes, etc., so they work when called from the GUI as well.

**Comment by stef-a** [comment]
can you alse look at 
    ` keyboard.wait_for_keypress` 
documentation?? it's says it returns a boolean however i am having a hard time using it. 
does it use an event listener??  i really need it a lot since i am triyng to "automate" matrix writing in latex 
thank you very much!!

**Comment by josephj11** [comment]
`keyboard.wait_for_keypress` - See our [API wiki](https://github.com/autokey/autokey/wiki/API-Examples#wait-for-key-press). 

If that doesn't help, ask on [Gitter](https://gitter.im/autokey/autokey). That's the best place to get help with advanced questions. The developers hang out there with advanced users. For less advanced questions and discussion see our [support forum](https://groups.google.com/forum/#!forum/autokey-users).

**Comment by josephj11** [comment]
Closed by accident.

**Comment by IshanChhangani** [comment]
Shouldn't this be closed as there doesn't seem to be any issues anymore?
