### ISSUE TITLE
Fatal error starting AutoKey

### ISSUE THREAD

**Issue by luckylinux** [autokey/autokey#52]
Hi,

I am running Gentoo GNU/Linux and had to install Autokey-p3 using pip3 because otherwise it wouldn't work.

Anyway when using autokey-gtk as a normal user I get lots of warnings and theme parsing errors, but no window shows up. If I press any key on the keyboard I get debugging informations so the application seems to be responding.

When running autokey-gtk as root (just to try for a different result) I get the following message:
Fatal error starting AutoKey
org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

Any ideas on how to possibly solve this ? I definitively would like to give this application a try in order to increase my productivity.

**Comment by troxor** [comment]
Please direct support requests to the autokey-users Google Group. If this is an actual bug in the software, then please reopen this issue.
