### ISSUE TITLE
Numpad Numbers

### ISSUE THREAD

**Issue by ssetaiLe** [autokey/autokey#52]
Whats the String for Numpad numbers ?

**Comment by josephj11** [comment]
Hi. I don't believe there are special symbols for the numpad number keys. If you need to differentiate them, you'll probably have to get the scan codes for the keys pressed and process them "manually" in a macro.

I don't know how to do that, but if you come over to the support [list](https://groups.google.com/forum/#!forum/autokey-users) and ask, I have a pile of general reference URLs that may help you get started.
