### ISSUE TITLE
Hold mouse button?

### ISSUE THREAD

**Issue by thedocruby** [autokey/autokey#523]
## Classification:

Feature, Enhancement (maybe bug)

## Reproducibility:

Always

## Version

AutoKey version: 0.95.10

Used GUI: GTK

If the problem is known to be present in more than one version, please list all of those.

Installed via: (Debian/Ubuntu Repo).

Linux Distribution: Linux Mint

## Summary

There doesn't seem to be a way to make the mouse button hold down (eg. by press-release functions) that produces behavior similar to holding the button in reality. described below is the scenario when using the keyboard `press()` and `release()` functions with the `<left_mouse_button>` token.

## Expected Results

When dragging the mouse around during script execution, text should be highlighted and any draggables under the cursor should be dragged along.

## Actual Results

Cursor acts as if the left mouse button were being pressed in quick succession, instead of being held; while this may be normal behavior for a key, it is not for a mouse button.

## Notes

I scoured the GitHub Wiki, but came up empty. I would not have even known that `<left_mouse_button>` was a thing if not for my thorough search of an unrelated section in the Known Limitations page. This is because it lacks an entry in the Special Keys page, where I would have expected to find information on it.

**Comment by sebastiansam55** [comment]
We have code for this in the develop branch, https://github.com/autokey/autokey/blob/develop/lib/autokey/scripting/mouse.py

It will eventually make it to master and then to release/distro packages but the project is lacking in manpower right now. I would not tell you to hold your breath waiting for it. 

You can follow some of the installation instructions found here https://github.com/autokey/autokey/wiki/Installing

`pip install --user https://github.com/autokey/autokey/archive/develop.zip`

The above command should install the current develop version.

RE: the wiki; feel free to make whatever additions that you see as necessary. We are aware of the outdated documentation issue and are working on it. 

Here is a temporary location for the develop documentation
https://samuelsebastian.dev/autokey/develop/api/mouse.html

You can also always refer to the in-code documentation or post in our gitter if you have any questions/issues.

**Comment by thedocruby** [comment]
@sebastiansam55 Nice! This is honestly more than I was expecting to hear. I thought I would get a "yeah we'll get to it" or "yeah we're working on it" and then never hear anything again because I couldn't find anything that actually discussed the problem. (ofc I didn't check the git history of the dev branch lol) Thanks for going above and beyond!

**Comment by josephj11** [comment]
See #231 and #243. If you feel these address your issue, please close this one. If not, then tell us why. Thanks.

**Comment by thedocruby** [comment]
@josephj11 Ok cool, turns out that this is a duplicate of #243 . Thanks for letting me know!
