### ISSUE TITLE
Map Super+1, Super+2 on Ubuntu doesn't work

### ISSUE THREAD

**Issue by cjh9** [autokey/autokey#528]
## Classification:
Bug

## Reproducibility:
Always
## Version

##AutoKey version: 
0.95.10

##Used GUI (Gtk, Qt, or both): 
Gtk I guess, standard install on Ubuntu

Installed via: (PPA, pip3, …).
apt 

Linux Distribution:
Ubuntu 20.04

## Summary
Trying to remap Super+1, Super+2 etc.
It seems that the dash-to-dock gnome extension steals the command. In order to use the hotkey I need to disable in dconf.

```
dconf write /org/gnome/shell/keybindings/switch-to-application-1 "['']"
dconf write /org/gnome/shell/keybindings/switch-to-application-2 "['']"
dconf write /org/gnome/shell/keybindings/switch-to-application-3 "['']"
dconf write /org/gnome/shell/keybindings/switch-to-application-4 "['']"
dconf write /org/gnome/shell/keybindings/switch-to-application-5 "['']"
dconf write /org/gnome/shell/keybindings/switch-to-application-6 "['']"
dconf write /org/gnome/shell/keybindings/switch-to-application-7 "['']"
dconf write /org/gnome/shell/keybindings/switch-to-application-8 "['']"
dconf write /org/gnome/shell/keybindings/switch-to-application-9 "['']"
dconf write /org/gnome/shell/extensions/dash-to-dock/hot-keys false
```

Summary of the problem.

## Steps to Reproduce (if applicable)
Create a script to exectue on Super+1, for example send_keys('hello')

## Expected Results
Should output hello

## Actual Results
Switches to application 1 and shows dock with icon numbers.

## Notes

If you've found a workaround, please provide it here.
Workaround to disable in dconf editor.

**Comment by cjh9** [comment]
Also super+d is show desktop and can not be used.

**Comment by cjh9** [comment]
Super+right/left will both run the script and toggle-tiled-right/left

**Comment by cjh9** [comment]
Also autokey can not forward super command to the Ubuntu system. For example if you map alt + d to `keyboard.send_keys('<super>+d')` it will not show desktop, but just output the letter 'd'.

**Comment by josephj11** [comment]
AutoKey talks directly to the active window, not to the desktop. We don't have a way around that at the moment. And, as you have discovered, there is a keypress food chain where some keypresses get intercepted and consumed before AutoKey even sees them.

When you suspect such issues are in play, running an AutoKey [trace](https://github.com/autokey/autokey-python2/wiki/Problem-Reporting-Guide) will let you see things from AutoKey's point of view which often helps with figuring out what's wrong.

**Comment by BlueDrink9** [comment]
Yeah, this isn't our bug. X11 just doesn't let multiple applications hook the same key events. `sxhkd` has the same issue.
