### ISSUE TITLE
CAPSLOCK as a modifier

### ISSUE THREAD

**Issue by proProbe** [autokey/autokey#53]
Hello everyone!

Im trying to extend the lib to include CAPSLOCK as a modifier. I have gotten all the UI to work and script to register and run when I use the modifier. I have a problem though where `modifier + key` also prints out the `key`. So `<capslock>+k` that run script `send_key("<up>")` result in `k then <up>`. Anyone who has an idea where in the code this could happen? If you need my code I will provide a fork but I wanted to ask here first and see if anyone perhaps knew.

**Comment by josephj11** [comment]
Always great to see someone extending our code, but ...

Basically, there's nobody home. We do not currently have a developer, but ... ;)
There's a newer branch of AutoKey which has been converted to Python 3. It has a few very nice new features, a bunch of bug fixes, and, most importantly, a developer.

Take a visit to [autokey-py3](https://github.com/guoci/autokey-py3).

For non-"issue" items such as this, we'd love to hear from you on our support [list].(https://groups.google.com/forum/#!forum/autokey-users). We support all current versions of AutoKey (and I read the list more than once a day).

If you know enough to modify AutoKey, we would very much appreciate your input on the list.
I don't know much Python and I end up answering most of the questions - sometimes with simple macro code (and I don't even know what "Pythonic" means yet.)  ;)

**Comment by josephj11** [comment]
I just realized that another approach could involve remapping the Capslock key to something else which could be used as a trigger/hotkey. I haven't done this, but if you ask on our list, I have a bunch of URLs with information on how to do such things.

**Comment by proProbe** [comment]
@josephj11 I have tried this before. My problem is that it interacts a lot with other hotkeys in other applications. So I turned off the activation of toggling uppercase with capslock and only have it as an inactive key. Would actually be awesome if a user was able to make any key as a modifier as that would actually solve my situation too :)
