### ISSUE TITLE
Step by step to install on OpenSuse Tumbleweed

### ISSUE THREAD

**Issue by anavarre** [autokey/autokey#54]
I'm trying to install the dev version on OpenSuse Tumbleweed (with KDE) and can't find a way to make autokey work. I've been trying to install as many required packages as necessary, by reading the how-to for other Linux distributions but it seems I'm out of luck.

I have the below packages installed:

```
wmctrl hicolor-icon-theme python-pyinotify zenity xautomation imagemagick
```

There's no `xorg-xwd` package and the closest seems to be:

```
S | Name | Summary                                 | Type
--+------+-----------------------------------------+--------
i | xwd  | Utility to dump an image of an X window | package
```

So I installed it.

There's no `python-dbus` and the closest seems to be:

```
S | Name           | Summary                   | Type
--+----------------+---------------------------+--------
i | dbus-1-python3 | Python bindings for D-Bus | package
```

So I installed it.

I did find `python-qscintilla` but prefered its QT5 equivalent `python-qscintilla-qt5`.

Lastly, I couldn't find anything similar to `kdebindings-python`. Installing with pip3 did work okay though.

In any case, when I'm trying to launch autokey, it just fails and displays a popup with:

> Could not find the program 'autokey-qt'

I'd like to know if there's anything wrong I'm doing or if OpenSuse really isn't supported? Happy to file a PR to document the installation procedure for OpenSuse if we can make it work.

**Comment by troxor** [comment]
I haven't tested on openSUSE yet, but in theory just finding which packages correspond to the various python modules (and external dependencies) should be all you need. PRs are appreciated and more than welcome if anyone figures it out and wishes to contribute.
