### ISSUE TITLE
change ".json" files to "json" to improve sync phrases over the cloud to multiple machines

### ISSUE THREAD

**Issue by herrdeh** [autokey/autokey#545]
## Classification:
Usability
## Reproducibility:

Always

## autokey Version: 
0.95.10 
Used GUI (Gtk, Qt, or both): all
Installed via: PPA
Linux Distribution: ubuntu focal

## Summary
I'd like to use my set of phrases on several machines, therefore would like to sync the ~/.config/autokey/ dir over the cloud. Unluckily, in ~/.config/autokey/data/<my_phrases> there live "invisible" `.json` files, which are ignored by some standard cloud software like owncloud or nextcloud. Could this leading `. ` please be removed in a further revision?

## Workaround
We can use dropbox (and probably some other cloud services) on that behalf - dropbox does sync "invisible" `.files` as well. But for data protection reasons, we should be able to use OC or NC. 

## Notes
More advanced syncing features (as a GUI-supported setup for symlinks etc) are welcome, but not really essential.

**Comment by josephj11** [comment]
You're in luck. I've been beating on this soapbox for a couple of years and there are no more hidden files in 0.96 which is just entering into beta testing. See #337.
