### ISSUE TITLE
Fatal IO error 11 (Resource temporarily unavailable) on X server :0

### ISSUE THREAD

**Issue by ineuw** [autokey/autokey#548]
## Classification:
Mostly crash  sometimes hangs

## Reproducibility:
Always 

## Version 
95.10

AutoKey version:  gtk

##Installation
use locally stored .deb installation files (common and gtk)

Linux Distribution: Linux Mint 20.1 Cinnamon

## Summary
I tested the code in a Python terminal and it works.  In Autokey, the app crashes. 

```
# win + INS insert current date, time, and filename

import os, time, datetime, gi, threading

ts = time.time()
time_stamp = datetime.datetime.fromtimestamp(ts).strftime('%Y-%m-%d %H:%M') + " - "

gi.require_version("Wnck", "3.0")
from gi.repository import Wnck

time.sleep(0.2)
scr = Wnck.Screen.get_default()
time.sleep(0.2)
scr.force_update()
time.sleep(0.2)
active = (scr.get_active_window().get_name())
keyboard.send_keys(time_stamp + " " + active) 

```

## Expected Results
output the window title

## Actual Results
It crashes

The attached document contains the verbose output.

[autokey-gtk_win-ins-failure.txt](https://github.com/autokey/autokey/files/6489575/autokey-gtk_win-ins-failure.txt)

**Comment by josephj11** [comment]
Renamed this. The original title refers to a benign error message which has persisted for over a decade with no consequences and has been eliminated in 0.96. Also copied your script into the question for ease of reference.

Please describe what your script is intended to do. In particular, what does it do that using our API can't do?

E.G.:

`window.get_active_title()`

`window.activate(title, switchDesktop=False, matchClass=False)`

The other error message looks like a real problem of some sort although it's not clear if it is within AutoKey.

Please run `dmesg -T` in a terminal immediately after running your script and post the last 20 lines or so of it so we can see if the system noticed any errors.

Also, take a look at the end of `/var/log/Xorg.0.log` and see if there are any errors or warnings.

**Comment by ineuw** [comment]
I pasted the requested info in the attached file.

There are no error messages in the Xorg.0.log, 

[dmesg-T.txt](https://github.com/autokey/autokey/files/6489860/dmesg-T.txt)

**Comment by josephj11** [comment]
The original error message is X11 crashing for some reason.

The system messages in the file look like they might be related to a malfunctioning DVD drive on your system. I don't believe they are related to this issue.
 
I did some searching and found some hints about threading problems.
The rest was over my head.

Can you address my question about what your code is supposed to do that our API can't?

AutoKey sets up an environment to work in connecting it to the rest of your system. When you use other modules which might modify that environment in ways AutoKey does not expect, then things happen. I don't know enough to say that's what happening here, but that's what it looks like.

I did a little more searching and [this](https://github.com/ssokolow/quicktile/issues/95) post seems to suggest that the Wnck module was depreciated a long time ago. I can't fully evaluate it, but that's what it looks like.

[This](https://stackoverflow.com/questions/43333071/get-wnck-working-with-python-3-5#43349245) post says it was built into the go introspection package (whatever that is :)  ).  It does sound like you may be poking the infrastructure.

**Comment by BlueDrink9** [comment]
Hmm, we use GObject so maybe it's shadowing something. Edit: no, I think you're probably using that library correctly. It _is_ now built into GO, but `gi` is the name of the Gobject introspection module for python. So Joe hasn't found the right tree there

Having someone else reproduce this would be nice, but I don't have time to right now.

**Comment by ineuw** [comment]
I know that Wnck is old, but it works and Python accepted it.  All I wanted is to get the experts' attention, but please don't spend any time on it. The script started to function  again. 

The script's output is a string of the formatted date and time, followed by the title of the window in which the script was activated. 

**"2021-05-17 01:06 - Fatal IO error 11 (Resource temporarily unavailable) on X server :0 · Issue #548 · autokey/autokey  Mozilla Firefox"**

The only change I made was to remove "os" library from import.

**Comment by sebastiansam55** [comment]
Kind of late to this, but is there any reason you aren't just using the `window.get_active_title`? It's native to autokey and does not require any sleeps/delays.

Also threading is complicated and I would not recommend using it in autokey scripts. There is probably some negative interaction from launching a thread from the main autokey thread.

 If you must I would use something like `system.exec_command` before threading.

(Although it looks like you're just importing threading not using it)

**Comment by ineuw** [comment]
Thanks for the suggestion. `window.get_active_title()`  works fine.
