### ISSUE TITLE
simple date insertion fails

### ISSUE THREAD

**Issue by troywweber7** [autokey/autokey#55]
Very simple script:

```py
from datetime import datetime as dt
out = dt.now().strftime('%F')
keyboard.send_keys(out)
```

I give it the abbreviation "scriptdate" but when I type this, it deletes the word and never inserts the date.

**Comment by josephj11** [comment]
Just tested this under 0.90.4 (I haven't upgraded yet). It worked fine and typed "2017-07-02" in konsole.

It may have something to do with the application receiving the text or your system environment.
We need more information to find your issue. Please see the problem reporting [guide](https://github.com/autokey/autokey/wiki/Problem-Reporting-Guide) and reply on our support https://groups.google.com/forum/#!forum/autokey-users.

You'll probably need to run a trace to see if AutoKey isn't sending the text or if your application isn't getting it.

For questions (including this one) which are not (yet) issues, please post on our support [list](https://groups.google.com/forum/#!forum/autokey-users). There are more people who can assist you there and you'll get much faster replies.

FYI, this original branch of AutoKey is no longer being developed. If possible, you should upgrade to [autokey-py3](https://github.com/guoci/autokey-py3).
