### ISSUE TITLE
PyKDE4 support in KDE 16.12+

### ISSUE THREAD

**Issue by dark-saber** [autokey/autokey#55]
After the recent KDE 16.12 update in Arch Linux the kdebindings-python and kdebindings-python-common packages were removed from the repos. The only package left from kdebindings group is kross-interpreters, but it optdepends on python2 only and, I guess, is irrelevant to autokey-py3. So running autokey-qt became more problematic.

Also, I see the [emails](https://wiki.debian.org/Qt4WebKitRemoval) regarding PyQt4 WebKit and, subsequently, PyKDE4 removal from other distros too. Are there any plans to move on to something like PyQt5?

**Comment by troxor** [comment]
That would be nice, but personally I use the GTK frontend so would need to figure out what's involved. PRs  are welcome in the meantime.
