### ISSUE TITLE
Must change font color of editor

### ISSUE THREAD

**Issue by ineuw** [autokey/autokey#552]
## Classification:
Enhancement

## Reproducibility:
Please see attached image.
If possible, please point me to the module? script? code where I can change the font colors.
If using autokey-qt is easier to make the changes, I will switch.

## Version
autokey-gtk 95.10

Installed via: Linux Mint Software Manager

OS: Linux Mint Cinnamon 20.1

![autokey editor lacks conrast](https://user-images.githubusercontent.com/10367016/119820935-0281ee80-bec0-11eb-8b25-7562900216a3.jpg)

**Comment by sebastiansam55** [comment]
Did you see the comments made in the gitter? You can edit the css files for gtksource view manually and there is an option in the settings panel in some newer version (not sure which one) to change the theme used like in gedit.

Additionally this looks to be due to whatever system wide theme you're using? If you could provide that info as well.

I added the change theme option to fix this exact issue as I could not read the comments in the editor either.

**Comment by sebastiansam55** [comment]
Interesting python feature but you can multiply strings; 
Instead of `<tab><tab>` you can do

```python
t="<tab>"
t*2

```

**Comment by sebastiansam55** [comment]
https://github.com/autokey/autokey/pull/452

So the changes are in either latest develop or the current beta.

Be aware these are development versions and there are already some bugs that have not been resolved as of yet

**Comment by ineuw** [comment]
Thanks for the replies. Especially,  on how to code repeat keystrokes. I just noticed the posts on gitter. I am about to follow the instructions, but just to let you know, it's the same font colors in any theme. I am using Linux Mint Cinnamon, 20.1.

**Comment by Git-Forked** [comment]
I agree, the blue comments are horrible to read.  I found this thread in trying to find a solution to change that blue color.

**Comment by josephj11** [comment]
@Git-Forked There is a theme selection option in the GTK front end for AutoKey. It's in our [0.96.0 beta release](github.com/autokey/autokey/releases/). It is not present in the Qt front end.

The theme in the script editing panel has been a longstanding problem. The text cursor is still invisible in the Qt editing panel.

 The beta is almost ready for release and is safe to install if you'd like to try it. Back up your scripts and phrases before installing it as the sidecar metadata files will all be renamed to non-hidden files and will not be found by the older versions of AutoKey if you revert to an older version. For support, join us on [Gitter](https://gitter.im/autokey/autokey).
