### ISSUE TITLE
Could not install deb package (0.96.0 beta 4)

### ISSUE THREAD

**Issue by nemonein** [autokey/autokey#556]
## Classification:

Crash

## Reproducibility:

Always

## Version

AutoKey version: https://github.com/autokey/autokey/releases/tag/v0.96.0-beta.4

Used GUI : Qt

Installed via: deb package (built by myself)

Linux Distribution: KDE Neon

## Summary

I built the deb package using 0.96.0 beta 4.
```
debuild -uc -uc
```
Then I got these packages.

```
autokey-common_0.96.0b-0_all.deb
autokey-gtk_0.96.0b-0_all.deb
autokey-qt_0.96.0b-0_all.deb
```

First install the common package which has no issue at all.
Then, I tried to install the qt package(because I was on KDE Neon), but it failed.
```
sudo dpkg -i autokey-qt_0.96.0b-0_all.deb 
(Reading database ... 399065 files and directories currently installed.)
Preparing to unpack autokey-qt_0.96.0b-0_all.deb ...
Unpacking autokey-qt (0.96.0b-0) ...
dpkg: error processing archive autokey-qt_0.96.0b-0_all.deb (--install):
 trying to overwrite '/usr/lib/python3/dist-packages/autokey/qtapp.py', which is also in package autokey-common 0.96.0b-0
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 autokey-qt_0.96.0b-0_all.deb
```

**Comment by josephj11** [comment]
Not sure if this is relevant, but it used to be the case that you had to install both packages at the same time because of their interdependencies.

    sudo dpkg -i autokey-qt_0.96.0b-0_all.deb autokey-common_0.96.0b-0_all.deb

Start by uninstalling either part that was installed separately.

Be sure to make a backup of your phrases and scripts before running the new version because it will unhide all your script and phrase sidecar files and if you want to go back to the old version, you'll have to manually undo that or none of them will work.

**Comment by nemonein** [comment]
Thanks @josephj11.
However the result is the same.

```
sudo dpkg -i autokey-qt_0.96.0b-0_all.deb autokey-common_0.96.0b-0_all.deb                             
(Reading database ... 399065 files and directories currently installed.)
Preparing to unpack autokey-qt_0.96.0b-0_all.deb ...
Unpacking autokey-qt (0.96.0b-0) ...
dpkg: error processing archive autokey-qt_0.96.0b-0_all.deb (--install):
 trying to overwrite '/usr/lib/python3/dist-packages/autokey/qtapp.py', which is also in package autokey-common 0.96.0b-0
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack autokey-common_0.96.0b-0_all.deb ...
Unpacking autokey-common (0.96.0b-0) over (0.96.0b-0) ...
Setting up autokey-common (0.96.0b-0) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for man-db (2.9.1-1) ...
Not building database; man-db/auto-update is not 'true'.
Errors were encountered while processing:
 autokey-qt_0.96.0b-0_all.deb
```

**Comment by josephj11** [comment]
Again, don't know if it's relevant, but it looks like you didn't uninstall before installing again.

    Unpacking autokey-common (0.96.0b-0) over (0.96.0b-0)

**Comment by nemonein** [comment]
It's the same.

```
$ sudo dpkg -i autokey-qt_0.96.0b-0_all.deb autokey-common_0.96.0b-0_all.deb
(Reading database ... 398918 files and directories currently installed.)
Preparing to unpack autokey-qt_0.96.0b-0_all.deb ...
Unpacking autokey-qt (0.96.0b-0) over (0.96.0b-0) ...
Preparing to unpack autokey-common_0.96.0b-0_all.deb ...
Unpacking autokey-common (0.96.0b-0) ...
dpkg: error processing archive autokey-common_0.96.0b-0_all.deb (--install):
 trying to overwrite '/usr/lib/python3/dist-packages/autokey/qtapp.py', which is also in package autokey-qt 0.96.0b-0
dpkg: dependency problems prevent configuration of autokey-qt:
 autokey-qt depends on autokey-common (= 0.96.0b-0); however:
  Package autokey-common is not installed.
 autokey-qt depends on python3-pyqt5.qsci; however:
  Package python3-pyqt5.qsci is not installed.
 autokey-qt depends on python3-pyqt5.qtsvg; however:
  Package python3-pyqt5.qtsvg is not installed.

dpkg: error processing package autokey-qt (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for man-db (2.9.1-1) ...
Not building database; man-db/auto-update is not 'true'.
Errors were encountered while processing:
 autokey-common_0.96.0b-0_all.deb
 autokey-qt
```

**Comment by josephj11** [comment]
That's weird. Still says:

    Unpacking autokey-qt (0.96.0b-0) over (0.96.0b-0)

One last thing to try for now. Maybe the order in which you specify the packages to dpkg makes a difference (though I kind of doubt it). See [this](https://github.com/autokey/autokey/wiki/Installing#debian-and-derivatives).

    sudo dpkg -i autokey-common_0.96.0b-0_all.deb autokey-qt_0.96.0b-0_all.deb
    
If that doesn't fix it, we'll leave it for the devs to look at.

**Comment by nemonein** [comment]
Well, I'm the maintainer of the PPA, and I know what I'm doing.

```
$ apt policy autokey-common     
autokey-common:
  Installed: (none)
  Candidate: 0.95.10-0-0build1~ubuntu20.04
  Version table:
     0.96.0b-0 -1
        100 /var/lib/dpkg/status
     0.95.10-0-0build1~ubuntu20.04 500
        500 http://ppa.launchpad.net/nemonein/efficient/ubuntu focal/main amd64 Packages
        500 http://ppa.launchpad.net/nemonein/efficient/ubuntu focal/main i386 Packages
     0.95.10-1 500
        500 https://mirror.yongbok.net/ubuntu focal/universe amd64 Packages
        500 https://mirror.yongbok.net/ubuntu focal/universe i386 Packages

$ sudo dpkg -i ./autokey-common_0.96.0b-0_all.deb ./autokey-qt_0.96.0b-0_all.deb
Selecting previously unselected package autokey-common.
(Reading database ... 398979 files and directories currently installed.)
Preparing to unpack .../autokey-common_0.96.0b-0_all.deb ...
Unpacking autokey-common (0.96.0b-0) ...
Preparing to unpack ./autokey-qt_0.96.0b-0_all.deb ...
Unpacking autokey-qt (0.96.0b-0) ...
dpkg: error processing archive ./autokey-qt_0.96.0b-0_all.deb (--install):
 trying to overwrite '/usr/lib/python3/dist-packages/autokey/qtapp.py', which is also in package autokey-common 0.96.0b-0
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Setting up autokey-common (0.96.0b-0) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for man-db (2.9.1-1) ...
Not building database; man-db/auto-update is not 'true'.
Errors were encountered while processing:
 ./autokey-qt_0.96.0b-0_all.deb
```

**Comment by josephj11** [comment]
@nemonein Do you happen to know enough to build AutoKey in some kind of container to get around problems like this?

**Comment by nemonein** [comment]
Sorry, I have no idea.
If I had knew, I'd have fixed it.

**Comment by BlueDrink9** [comment]
> Well, I'm the maintainer of the PPA, and I know what I'm doing.

The problem is, I'm the maintainer (more-or-less) of the git, and I don't know what I'm doing 😛
At least, not in terms of debian builds, that is. It seems like the manifest for common is including qtapp.py, which it probably shouldn't do. However, I have no idea how debian packaging chooses what to include.

A bisection of this bug would be helpful, if somewhat time-consuming.

**Comment by BlueDrink9** [comment]
Ah, no, I see what I did wrong. I was trying to get autokey debs to build as part of the CI process, and inadvertently included qtapp.py and gtkapp.py using `*.py`, not realising that that would create conflicts. I'll fix it asap

**Comment by BlueDrink9** [comment]
Give the latest beta (7) another try, please

**Comment by nemonein** [comment]
I'll give it a shot. Thanks.

**Comment by nemonein** [comment]
It now works fine.
![image](https://user-images.githubusercontent.com/5688288/126947797-fe17b4f2-9921-484e-baef-5eb920a2182d.png)

You can close the issue.
