### ISSUE TITLE
Display Window Info Error

### ISSUE THREAD

**Issue by breamoreboy** [autokey/autokey#558]
## Classification:

Bug

## Reproducibility:
Always

## Version

AutoKey version: 0.95.10

Used GUI (Gtk, Qt, or both): 

Installed via: (PPA, pip3, …).

Linux Distribution:
Ubuntu 21.04
## Summary

Summary of the problem.

Display Window Info produces a Python AttributeError
## Steps to Reproduce (if applicable)
Simply select Display Window Info

## Expected Results
The window should be displayed :)
## Actual Results
The script crashes
![AutoKeyDisplayWindowInfoError](https://user-images.githubusercontent.com/203652/120941000-365ae080-c718-11eb-96d0-ff72d77ec28d.png)

**Comment by josephj11** [comment]
Cleaned up the original  report.

Please specify how you installed AutoKey and which AutoKey front end (Qt or GTK) you were running.

**Comment by breamoreboy** [comment]
Installed via sudo apt-get install autokey-gtk so looks like GTK is the front end.

**Comment by ineuw** [comment]
Can you post the code?

**Comment by josephj11** [comment]
@ineuw I believe the OP is just selecting a command from the AutoKey main menu with no code involved.

**Comment by breamoreboy** [comment]
@josephj11 you're completely correct, I am just selecting a command.  All of this started as I cannot get autokey to do text expansion on Ubuntu 21.04 but I've never previously had any problems with it, but I'm assuming that is a different issue to this one, although perhaps related due to changes to python???

**Comment by 0xNetay** [comment]
I get the same error after updating to Ubuntu Hirsute Hippo (21.04) Update.
Seems that something is off here regarding "get_window_info".

**Comment by sebastiansam55** [comment]
Can anyone currently experiencing this error post the full log from launching autokey via `autokey-gtk -lc` (verbose logging and show window flags)?

**Comment by Elliria** [comment]
It's the **Display window info** script that comes with AutoKey by default. I tested it in **AutoKey 0.95.10** under Kubuntu 22.04 LTS and it works fine for me in both `autokey-gtk` and `autokey-qt`. Is it still not working for you, @breamoreboy?

**Comment by josephj11** [comment]
@Elliria They are experiencing the issue in 21.04. There's a chance that whatever this is was fixed by the time 22.04 came out.

**Comment by Elliria** [comment]
Since it was reported two years ago, I figured it was worth a shot to see if the issue has been resolved. It's possible that 21.04 got some updates that fixed it, too, independent of any changes by us.

**Comment by breamoreboy** [comment]
I can't even find the command I was running (where is it?) but as autokey 0.95.10 is working just fine for me on Ubuntu 22.04.3 I'm not that bothered.

**Comment by josephj11** [comment]
I'm thinking we should close this issue. If it recurs in newer distros or in 0.96.x, then a new issue can be opened (and refer back to this one).

@breamoreboy I assume that the "command" you ran was from the panel icon context menu - something like "display window properties". I just tried to do that and that option appears to be missing in autokey-qt 0.96.0 which was totally unexpected.

**Comment by breamoreboy** [comment]
The command I used was as the title of this issue, "Display Window Info". As I said above now I can't find it and I don't even remember where I ran it from. Feel free to close this issue as I no longer consider it to be relevant.

**Comment by Elliria** [comment]
We should probably make sure it's working for @breamoreboy before closing this issue.
 
It's the **Display window info** script that comes with AutoKey by default. It's in your scripts. Here's how to put it into the panel-icon's context menu and use it:

1. Open the AutoKey main window.
2. Left-click on the **Sample Scripts** folder in the left pane.
3. Left-click on the **Display window info** script in the left pane.
4. Scroll down to the **Script Settings** section beneath the script.
5. Left-click in the box next to the **Show in notification icon menu** option to put a check-mark in the box.
6. Left-click the **Save** button in the toolbar.
7. Left-click the AutoKey icon in the panel.
8. Left-click the **Display window info** entry in the AutoKey panel's context menu.
9. Left-click on any window.

**Comment by josephj11** [comment]
That's weird. I don't remember having to do that. I thought it was just there. Maybe it should be by default.

**Comment by Elliria** [comment]
I wouldn't make it a default entry because it's a niche need that's mainly used when writing scripts, which most people probably don't.
