### ISSUE TITLE
using <script> in a phrase freezes autokey and parts of the desktop

### ISSUE THREAD

**Issue by mariusa** [autokey/autokey#56]
Define this phrase:
  <script  src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
  
Set an abbreviation (remove typed abber, replace immediately), then try to use it in Chrome (not sure if all the desktop)
Autokey freezes, and parts of the desktop too, eg can't switch windows anymore.

**Comment by josephj11** [comment]
I was able to duplicate this, at least partially, in kate using AutoKey 0.90.4 (older than this repo). My desktop seemed fine, but I couldn't type anything into the kate window after triggering the phrase.
However, this branch of AutoKey no longer has a developer, so nothing will get fixed.

If you install [autokey-py3](https://github.com/guoci/autokey-py3), and reproduce this issue, you can file an issue there. That branch has an active developer and has several enhancements as well as a number of bug fixes.

Please visit us on the support [list](https://groups.google.com/forum/#!forum/autokey-users) for both versions.
