### ISSUE TITLE
Problem with removing abbreviations with tab as trigger key inside the autokey script editor

### ISSUE THREAD

**Issue by TheoRet** [autokey/autokey#57]
Hello, I use autokey-gtk on Linux Mint 18 Mate.
I want to create phrases triggered by abbreviations with the following options:
Paste using Keyboard
Trigger Key: Tab
Remove typed abbreviation = on
Omit trigger character = on
Match case= off
ignore case = off
trigger as part of word = off
trigger immediately = off

I use these phrases inside the Autokey script editor. When I type an abbreviation, Autokey fails to remove it completely. Let's say, "my phrase" is the phrase and "q", "qw", "qwe", "qwer" are abbreviations for it. What happens after pressing tab:
"q" -> "q my phrase"
"qw" -> "qmy phrase"
"qwe"  ->  "my phrase"  
"qwer"  -> "qwemy phrase"
The number of characters left can change if the cursor is not at the beginning of the line...

This problem does not occur in the standard text editor (xed). Maybe it has to do with the Autokey editor replacing a tab by a number of spaces? xed treats a tab as single character.

**Comment by troxor** [comment]
It's working as expected for me. Can you post autokey-gtk --verbose output? Specifically, the portion of the output that displays the current Input stack when "it works" and when "it doesn't work". 

Also, with the phrase configuration you describe above, try the key sequence 

"<esc>q<tab>qw<tab>qwe<tab>qwer<tab>"

This should result in 

"my phrasemy phrasemy phrasemy phrase"

**Comment by TheoRet** [comment]
Thanks for looking at this!

For the key sequence "qqwqweqwer", where exactly do you want me to press the trigger character (Tab)?

Anyway, the verbose output makes it pretty clear what is happening. I open the autokey GUI and open an empty phrase window.

First case:  I type `q<tab>` and get `q my phrase`:

> 2017-03-11 07:02:39,363 DEBUG - service - Raw key: 'q', modifiers: [], Key: q
> 2017-03-11 07:02:39,363 DEBUG - service - Window visible title: 'AutoKey', Window class: 'autokey-gtk.Autokey-gtk'
> 2017-03-11 07:02:39,364 DEBUG - service - No phrase/script matched hotkey
> 2017-03-11 07:02:39,364 DEBUG - service - Input stack at end of handle_keypress: deque(['q'], maxlen=150)
> 2017-03-11 07:02:43,652 DEBUG - service - Raw key: '`<tab>`', modifiers: [], Key: `<tab>`
> 2017-03-11 07:02:43,652 DEBUG - service - Window visible title: 'AutoKey', Window class: 'autokey-gtk.Autokey-gtk'
> 2017-03-11 07:02:43,652 DEBUG - service - No phrase/script matched hotkey
> 2017-03-11 07:02:43,652 DEBUG - iomediator - Send via event interface
> 2017-03-11 07:02:43,652 DEBUG - service - Input stack at end of handle_keypress: deque([], maxlen=150)
> 2017-03-11 07:02:43,653 DEBUG - service - Ignored locking error in handle_keypress
> 2017-03-11 07:02:43,653 DEBUG - interface - Send special key: ['<backspace>']
> 2017-03-11 07:02:43,653 DEBUG - interface - Send special key: ['<backspace>']
> 2017-03-11 07:02:43,654 DEBUG - interface - Sending string: 'my phrase'

So in order to replace `q<tab>`, autokey sends two backspaces.
When I deactivate the auto-replacement and enter `q<tab>`, I get `q<three spaces>`. The autokey-editor inserts 3 spaces for pressing Tab once. So 4 backspaces would be necessary for the replacement.
Unfortunately, the number of spaces per tab-press seems to depend on the cursor's horizontal position. That makes fixing it difficult.


Second case:
`qw<tab>` --> `qmy phrase`  (with auto-replacement)

> 2017-03-11 07:15:15,149 DEBUG - service - Raw key: 'q', modifiers: [], Key: q
> 2017-03-11 07:15:15,150 DEBUG - service - Window visible title: 'AutoKey', Window class: 'autokey-gtk.Autokey-gtk'
> 2017-03-11 07:15:15,150 DEBUG - service - No phrase/script matched hotkey
> 2017-03-11 07:15:15,150 DEBUG - service - Input stack at end of handle_keypress: deque(['q'], maxlen=150)
> 2017-03-11 07:15:15,545 DEBUG - service - Raw key: 'w', modifiers: [], Key: w
> 2017-03-11 07:15:15,546 DEBUG - service - Window visible title: 'AutoKey', Window class: 'autokey-gtk.Autokey-gtk'
> 2017-03-11 07:15:15,546 DEBUG - service - No phrase/script matched hotkey
> 2017-03-11 07:15:15,546 DEBUG - service - Input stack at end of handle_keypress: deque(['q', 'w'], maxlen=150)
> 2017-03-11 07:15:16,122 DEBUG - service - Raw key: '`<tab>`', modifiers: [], Key: `<tab>`
> 2017-03-11 07:15:16,122 DEBUG - service - Window visible title: 'AutoKey', Window class: 'autokey-gtk.Autokey-gtk'
> 2017-03-11 07:15:16,122 DEBUG - service - No phrase/script matched hotkey
> 2017-03-11 07:15:16,122 DEBUG - iomediator - Send via event interface
> 2017-03-11 07:15:16,123 DEBUG - service - Input stack at end of handle_keypress: deque([], maxlen=150)
> 2017-03-11 07:15:16,123 DEBUG - service - Ignored locking error in handle_keypress
> 2017-03-11 07:15:16,123 DEBUG - interface - Send special key: ['<backspace>']
> 2017-03-11 07:15:16,124 DEBUG - interface - Send special key: ['<backspace>']
> 2017-03-11 07:15:16,124 DEBUG - interface - Send special key: ['<backspace>']
> 2017-03-11 07:15:16,124 DEBUG - interface - Sending string: 'my phrase'

`qw<tab>` --> `qw<two spaces>`  (without auto-replacement)

**Comment by TheoRet** [comment]
__

**Comment by luziferius** [comment]
The same thing will happen if your Phrase content contains `<tab>` characters.

I think, this can’t be fixed reliably, if the underlying application replaces characters with something else having a different character count, like  `ss` with `ß`, or `<tab>` with multiple spaces.
For example, in the text editor Kate, the space character count depends on the configured indention level, which can be switched on-the-fly.
You can always find contrived examples, where the undo logic fails.

I’ve documented this behaviour in the Wiki here:
https://github.com/autokey/autokey/wiki/Known-limitations

Thus I’ll close this as WONTFIX. I’ll accept pull requests or algorithm suggestions, if you can find a way to _reliably_ check the replacement, without the need to guess things.
