### ISSUE TITLE
How to bring the dialog.list_menu window to the front

### ISSUE THREAD

**Issue by artemsok** [autokey/autokey#57]
I'm trying to automate spelling correction notes fields of the bib-management tool [Zotero](http://zotero.org/) (standalone) on Ubuntu 16.04, using a system call to aspell, parsing the results and creatin a list_menu out of returned options:
`retCode, choice = dialog.list_menu(variants, title='', message='')`
But window gets created on the foreground (below the Zotero window and some others) and does not have focus.

Is there a way to bring it to foreground and, optionally, position it around the selected word?

**Comment by josephj11** [comment]
Theoretically, yes. ;)
Fixing problems with window/dialog focus is something I've been trying to figure out for a long time - with limited success.
AutoKey (especially this old branch) can't address this itself, but you can manipulate the windows and dialogs from within your macro with system calls to xdotool. If you post on the [support list](https://groups.google.com/forum/#!forum/autokey-users), we can talk about this further. I have a bunch of reference links.
