### ISSUE TITLE
Remapping Keyboard via Ubuntu input settings does not remap Autokey

### ISSUE THREAD

**Issue by sebastiansam55** [autokey/autokey#576]
## Classification:
Bug

## Version

AutoKey version: 

Linux Distribution: Ubuntu 20.04

## Summary

When remapping via the option provided in the Ubuntu 20.04 settings menu (Region & Language) the remap is above the level at which autokey listens to events. 

Ex. using dvorak layout typing the top row would be seen by autokey as typing the top row on a qwerty layout keyboard.

## Notes

As suggested by @BlueDrink9 using `setxkbmap us -variant dvorak` (or the equivalent for your layout) will fix the issue.

**Comment by sebastiansam55** [comment]
Closed because workaround is a adequate fix.

**Comment by josephj11** [comment]
Something good to add to our wiki somewhere. Especially if it works for various international keyboard layouts.
