### ISSUE TITLE
dbus error on pip install

### ISSUE THREAD

**Issue by lindeloev** [autokey/autokey#58]
On Ubuntu 16.04, doing the recommended pip-install fails with the error pasted in the bottom of this issue. I have installed `python-dbus` and `dbus` from Ubuntu repositories. I tried sudo apt-get installing `dbus-1-dbg` and `python-dbus*` but it didn't change the error.

Autokey worked previously on this Ubuntu (I have not re-installed or upgraded Ubuntu or made any risky tweaking of system files). I don't recall whether it was installed using pip or an ubuntu repository. I tried re-installing because some scripts stopped working.

Thanks for this great software! I really appreciate your work.

```
    checking for DBUS... no
    configure: error: Package requirements (dbus-1 >= 1.6) were not met:
    
    No package 'dbus-1' found
    
    Consider adjusting the PKG_CONFIG_PATH environment variable if you
    installed software in a non-standard prefix.
    
    Alternatively, you may set the environment variables DBUS_CFLAGS
    and DBUS_LIBS to avoid the need to call pkg-config.
    See the pkg-config man page for more details.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-PH1win/dbus-python/setup.py", line 106, in <module>
        'build_ext': BuildExt,
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-PH1win/dbus-python/setup.py", line 62, in run
        cwd=builddir)
      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-build-PH1win/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/usr/bin/python', '--prefix=/tmp/pip-build-PH1win/dbus-python/build/temp.linux-x86_64-2.7/prefix']' returned non-zero exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-PH1win/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-5_VA5J-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-PH1win/dbus-python/
```

**Comment by troxor** [comment]
That traceback shows Python 2.7.

**Comment by troxor** [comment]
dbus-python module compiles native extensions, so you need the actual header files. Those are in

$ dpkg -l | grep dbus | grep dev
ii  libdbus-1-dev:amd64                        1.10.6-1ubuntu3.1                             amd64        simple interprocess messaging system (development headers)
ii  libdbus-glib-1-dev                         0.106-1                                       amd64        simple interprocess messaging system (GLib interface)

The README has also been updated, albeit not specifically to Ubuntu since the PPA package should do everything, and package names vary between distributions.

**Comment by lindeloev** [comment]
You are right. However, doing

`pip3 install --user git+https://github.com/autokey-py3/autokey`

resulted in the same error (see below). It's not a problem for me anymore since I can now install using the repos, so I'm just writing this if it's of interest to you. I'm happy to try out any solutions.

```
    checking for DBUS... no
    configure: error: Package requirements (dbus-1 >= 1.6) were not met:
    
    No package 'dbus-1' found
    
    Consider adjusting the PKG_CONFIG_PATH environment variable if you
    installed software in a non-standard prefix.
    
    Alternatively, you may set the environment variables DBUS_CFLAGS
    and DBUS_LIBS to avoid the need to call pkg-config.
    See the pkg-config man page for more details.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ojz_uonc/dbus-python/setup.py", line 106, in <module>
        'build_ext': BuildExt,
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-ojz_uonc/dbus-python/setup.py", line 62, in run
        cwd=builddir)
      File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-build-ojz_uonc/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/usr/bin/python3', '--prefix=/tmp/pip-build-ojz_uonc/dbus-python/build/temp.linux-x86_64-3.5/prefix']' returned non-zero exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ojz_uonc/dbus-python/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-5pf8gsdp-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-ojz_uonc/dbus-python/
```

**Comment by ding3my** [comment]
To install `dbus-python-devel` can solve `configure: error: Package requirements (dbus-1 >= 1.6) were not met:`

**Comment by mplulu** [comment]
I have the same error and this is what I did
`sudo apt-get install libdbus-1-dev libdbus-glib-1-dev`
`pip3 install autokey`

**Comment by t-hofmann** [comment]
mplulu's answer slightly adopted:
`$> apt-get install -z libdbus-1-dev libdbus-glib-1-dev && sudo -H pip3 install autokey`
also fixed the install for me.
System is a Linux Mint 18.3 Cinnamon

Install of autokey's python3 version was necessary because German umlauts had a problem.

**Comment by josephj11** [comment]
@t-hofmann - You're much better off with the Python3 version anyway. 0.90.4 is over six years old and not supported. The newer version is under active development with lots of bug fixes and a few new features like Xautomation integration so you can do "visual" searches on the screen to find elements of interest. And Python3 offers greatly enhanced support for multibyte character sets (German umlauts ...)
What does `apt-get install -z` do? I don't see `-z` in my `apt-get` man page.

**Comment by swapneilbasutkar** [comment]
I was using notify2 package and I was getting an error for 'failed building wheel for dbus-python' while installing pip install dbus-python.
This solved my issue.
`sudo` apt-get install libdbus-1-dev `libdbus-glib-1-dev`

**Comment by kleinjm** [comment]
I tried all the above and still seeing this error.
```
    checking for DBUS... no
    configure: error: Package requirements (dbus-1 >= 1.8) were not met:

    No package 'dbus-1' found

    Consider adjusting the PKG_CONFIG_PATH environment variable if you
    installed software in a non-standard prefix.

    Alternatively, you may set the environment variables DBUS_CFLAGS
    and DBUS_LIBS to avoid the need to call pkg-config.
    See the pkg-config man page for more details.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-y587h0mg/dbus-python/setup.py", line 109, in <module>
        tests_require=['tap.py'],
      File "/home/james/.pyenv/versions/3.7.0/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/home/james/.pyenv/versions/3.7.0/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/james/.pyenv/versions/3.7.0/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/james/.pyenv/versions/3.7.0/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/james/.pyenv/versions/3.7.0/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/james/.pyenv/versions/3.7.0/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/james/.pyenv/versions/3.7.0/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/james/.pyenv/versions/3.7.0/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-y587h0mg/dbus-python/setup.py", line 62, in run
        cwd=builddir)
      File "/home/james/.pyenv/versions/3.7.0/lib/python3.7/subprocess.py", line 328, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-install-y587h0mg/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/home/james/.pyenv/versions/3.7.0/bin/python3.7', '--prefix=/tmp/pip-install-y587h0mg/dbus-python/build/temp.linux-x86_64-3.7/prefix']' returned non-zero exit status 1.

    ----------------------------------------
Command "/home/james/.pyenv/versions/3.7.0/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-y587h0mg/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ius31u36/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-y587h0mg/dbus-python/
```

**Comment by josephj11** [comment]
@kleinjm What distro and what version of AutoKey? There are several in this thread.

**Comment by luziferius** [comment]
@josephj11  I think I’ll just remove the dependency from `setup.py` for the next version. This keeps coming up again and again. `pip3` seems to insist on not recognizing that `dbus` is indeed installed  totally fine and importable from the python interpreter.
It will then try to install from PyPi, which will most probably fail at compiling the C binding library. Many users don’t have a C compiler and dbus C-header installed. Even if they have, the version from PyPi will probably clash because of a version mismatch and fail.

When installed from pre-built debian packages (generated by some `setup.py build` commands), it magically finds the `dbus` module…

If `dbus` is removed from the dependency list, one has to tell the users to manually install the dbus module. But at least pip3 will stop trying to replace the system installed version with something from PyPi.

It will also help users using other PyQt applications that use the `dbus` Qt interoperability plugin (like HPLIP). If it happens to be installed correctly, the PyPi version shadows all dbus plugins (like `dbus.mainloop.qt`), making them inaccessible and crash the PyQt applications using them.

(Site note: The last paragraph is the reason why I ported autokey-qt away from the Python `dbus` module to the Qt5 built-in dbus support for 0.95.0.)

**Comment by josephj11** [comment]
@luziferius Sounds good. We'll just add a note to the install instructions so users know what to do if they get the error during/after an install.

**Comment by kleinjm** [comment]
@josephj11 I'm back on Mac for the time being but if I hop back on Linux and still have the issue I will post here. Thanks!

**Comment by andriyor** [comment]
In my case, installing dbus with brew helped `brew install dbus`

**Comment by henkess** [comment]
> J'ai la même erreur et c'est ce que j'ai fait
> `sudo apt-get install libdbus-1-dev libdbus-glib-1-dev`
> `pip3 install autokey`

it worked for me in a virtual environment thanks.
