### ISSUE TITLE
Why can't my phrases work? (My script does)

### ISSUE THREAD

**Issue by hub2git** [autokey/autokey#58]
I can successfully use a script when I type my keyword. But now I can't get my "phrases" to work.

Here's a [screenshot](https://i.imgur.com/Q91kejl.png) 

![screenshot of autokey-gtk](https://i.imgur.com/Q91kejl.png)

**Comment by josephj11** [comment]
Not sure. Here's a couple of things to try:
1) Try different options for Paste using:
2) See if it works with your window filter turned off. (Yours does look right.)
If that makes it work, then you have to limit its action to gedit windows another way.
You can try 'gedit.Gedit' which is the window class.

If these quick fixes don't work, post on our [support list](https://groups.google.com/forum/#!forum/autokey-users) and we can explore this further.
