### ISSUE TITLE
Feature: Map left and right shift in Keyboard API (alongside other buttons like alt and ctrl)

### ISSUE THREAD

**Issue by Coqueiro** [autokey/autokey#582]
I searched a lot and couldn't find how to do it, so I'm assuming it's not currently supported. It'd be great to be able to use something like `keyboard.press_key('<shift_r>')` to press right shift specifically.

Some softwares let you map those keys separately, and I'd love to be able to do some automation on top of it!

**Comment by josephj11** [comment]
AutoKey can't do this now. I'm not sure if it's possible with the upstream modules we use. One of the developers will have to comment on that. It would  be nice to have.

**Comment by BlueDrink9** [comment]
Not supported by the underlying X apis, I'm pretty sure. Sorry
