### ISSUE TITLE
Documentation for .json phrase configurations?

### ISSUE THREAD

**Issue by randolf-scholz** [autokey/autokey#599]
The wiki mentions that phrases can be added as .json files, but I couldn't find any documentation of how to do that? What are the allowed / required keys?

**Background:** I want to port the [Julia Unicode Abbreviations](https://docs.julialang.org/en/v1/manual/unicode-input/) so that they become available system-wide. (Very useful when typing lots of math and LaTeX / MathJax isn't available, or character limit is in place.) I already copied the table into a .csv file, and now I want to write a script to autogenerate the corresponding .json files. Just like in the julia terminal, I want these to trigger by pressing [tab].

Side question: Since there are >3000 characters will there be possibly any performance issue? Would it be better idea to implement this directly as a script?

**Comment by sebastiansam55** [comment]
I don't think that we have any documentation about save files other than what is in the code itself. The easiest way to do this; 
* Create one and configure it the way that you want it in the UI
* Go to the directory it is stored in
* Make sure you can see hidden files in your file browser, and there should be both a `phrasename.txt` and a `.phrasename.json` (a leading dot in a file name is a hidden file for linux/unix), the json file contains all of the configuration information autokey needs.

Pictured below is an example of mine that I changed to use tab completion;
![Screenshot from 2021-08-24 15-00-01](https://user-images.githubusercontent.com/1707320/130674412-f5261c8d-242f-4c86-a521-640c7db806c2.png)

The tab trigger is indicated in the `"wordChars": "[^\\t]"`, I think that most of the other items the save file uses are self descriptive enough, ask if you have more questions.

You should make sure that each json file has a unique `"description"` as this is part of what AK uses to distinguish items.

RE: performance, no idea, not sure there are many people running that many expansions. If it is feel free to open another issue but I'm not sure how much could be done about it.

**Comment by randolf-scholz** [comment]
@sebastiansam55  Thanks for the swift response! When I hard code the json like this can I also use other triggers (The GUI only allows `[tab]` or `[space]+[enter]`)? I would prefer `[tab]` but I noticed that unfortunately it interferes with the built-in `[tab]`-completions in some other programs I use.

I was also wondering why there is the need for both a `.json` and a `.txt`. I suppose this is a relic from python 2 days when strings weren't unicode by default?

**Comment by sebastiansam55** [comment]
I am opening a can of worms here but the `wordChars` does appear to be a regex thing, so you might be able to have anything you want there, if you change it to the space+enter the json changes to `[^ \\n]` (notice the space and the newline symbol) leading me to believe you could probably change it to something you'd find more useful. This is absolutely not "supported" but it might work just from the way it is coded. As always you can open an issue asking for the selection of trigger characters to be expanded, doesn't seem like that would be too difficult, and user feedback about what options are wanted is always welcome.

The separate files is mostly just a design decision made at some point in AK's history, from working with python it was probably the easiest/most reliable way to store and retrieve data about the scripts/phrases.

**Comment by josephj11** [comment]
It's implied above, but I'll make it explicit. Once you have one phrase or script that does one of the things you want, you can make a copy of it and its JSON file to use as templates. To make it easy to use, you could replace the phrase text with TEXT, the abbreviation with ABBR and the hotkey with HOTKEY, etc. This gives you unique tokens to search for and lets you ignore most of the JSON syntax.

Then, you can write a bash script that loops through your CSV file making a fresh copy of both of the template files (with appropriate new names) and use sed or awk to find and replace the tokens in the new copies of the template files with the values from your CSV file. (You can add the new file names to your CSV file.)

This will automate the process nicely.

I would do this in a separate directory outside of AutoKey until the process is debugged and complete. Then, you can add that directory to AutoKey using the GUI or create a new directory in the GUI and then copy the new files into it.

Be sure to make a backup of all your new phrases or scripts before adding them to AutoKey. We used to have a problem (which I'm pretty sure was fixed) where creating a new directory inside AutoKey would delete an existing directory with the same path.

When you install your new phrases or scripts, it would be best if AutoKey wasn't running. It might work with AutoKey running, but starting AutoKey afterward will cause it to scan all of its files to build a new menu and that will work.

Obviously, using bash is just a suggestion. Any language that supports convenient string manipulation tools will work.

When you create a new directory in AutoKey, it can be anywhere on your system as long as it will always be available when AutoKey is running. I like to put mine outside of the AutoKey config tree. This makes them easy to maintain and backup and they won't be affected  if you ever have to reinstall or even purge AutoKey.

**Comment by josephj11** [comment]
Having the sidecar files seems like a good idea to me. This way, most users will not accidentally modify the metadata for scripts and phrases and will not even see it unless they actually need to modify it. In most cases, it would just be clutter that would confuse users. It also makes it so that AutoKey doesn't need some sort of tables or a database to hold this information.

**Comment by randolf-scholz** [comment]
@josephj11 @sebastiansam55 Thanks again, I was able to create just what I wanted: https://github.com/randolf-scholz/autokey_julia_unicode

**Comment by josephj11** [comment]
@randolf-scholz Nice piece of work! When it's stable, you might want to add something to our Wiki so others can find it. I'm not a math person, so my understanding of this is rudimentary.

----
For future reference:

BTW: Whenever you have a question (as opposed to an issue) it's better to post it on our [list](https://groups.google.com/forum/#!forum/autokey-users) or on [Gitter](https://gitter.im/autokey/autokey). The list is more user oriented whereas more technical questions will get a better answer on Gitter.

Both of these venues have a number of active users, so you are likely to get more, better, and faster answers on them than here on GitHub where only our very busy developers and a few users see the posts. We also prefer to have the developers developing rather than taking time to answer questions and manage issues that the user community could handle for them.
