### ISSUE TITLE
Autokey install failed on manjaro

### ISSUE THREAD

**Issue by srikk73** [autokey/autokey#611]
## Version:

AutoKey version: 0.95.4

Used GUI (Gtk, Qt, or both): both

Installed via: (PPA, pip3, …). pip3

Linux Distribution:Manjaro 21.1

## Summary

Summary of the problem.
I tried to install autokey but it failed with an error message.

## Steps to Reproduce (if applicable)

- sudo pip3 install autokey

## Expected Results
install autokey

## Actual Results
It stops with error message. Autokey not installed.

## Notes

[Autokey Error.txt](https://github.com/autokey/autokey/files/7194905/Autokey.Error.txt)

**Comment by josephj11** [comment]
You should be getting 0.95.10, so something is wrong.
Besides that, I don't think pip installs any dependencies for you, so see [this](https://github.com/autokey/autokey/wiki/Installing#arch-linux).

Then, get back to us with specifics. We have users successfully using AutoKey on Arch and Manjaro,

**Comment by BlueDrink9** [comment]
`pamac install python-wheel python-dbus` aught to fix it. Alternatively, consider installing autokey from the AUR instead

**Comment by srikk73** [comment]
Installed from AUR
