### ISSUE TITLE
mouse.wait_for_click should have a return code like the keyboard counterpart

### ISSUE THREAD

**Issue by troywweber7** [autokey/autokey#615]
## Classification:

Feature (New)

## Reproducibility:

Always

## Version

AutoKey version: 0.95.10

Used GUI (Gtk, Qt, or both): Gtk (Gnome) 

Installed via: (PPA, pip3, …). Honestly can't remember.

Linux Distribution: Ubuntu 20.04

## Summary

`mouse.wait_for_click` does not have a return code so there is no way to know if it was clicked or if it timed out.

## Steps to Reproduce (if applicable)

- grab return value from `mouse.wait_for_click()`
- log the return value, it is always `None`

## Expected Results

- similar to `keyboard.wait_...` it should have a return code.

## Actual Results

- always return `None`

**Comment by BlueDrink9** [comment]
Would love a PR on this. Sounds like a sensible behavior.

Otherwise, @sebastiansam55 ?
