### ISSUE TITLE
Autokey crashes because python3-xlib is actually python-xlib under Arch Linux

### ISSUE THREAD

**Issue by nick-s-b** [autokey/autokey#62]
Classification: Crash

Reproducibility: Always

## Summary

After installing Autokey-py3 under Arch Linux, it crashes with the following error message:

## Version
0.93.7
Distro: Arch Linux

```
$ /usr/bin/autokey-gtk
Traceback (most recent call last):
  File "/usr/bin/autokey-gtk", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python3-xlib' distribution was not found and is required by autokey
```

Maintainer dark-saber mentioned this in his notes:

> dark-saber commented on 2017-01-14 15:20			 
> The recent problems were introduced by this commit: https://github.com/autokey-py3/autokey/commit/2250d90d31aec0fac029ea2f9c2f1c71cfd09daf and in fact they consist of two parts:
> 1. 'python3-xlib' in Ubuntu is 'python-xlib' in Arch, this patches easily.
> 2. 'dbus-python' is somehow not found in Arch, even if python-dbus and python-dbus-common are installed. Other aliases, like 'dbus', 'python-dbus' etc. don't work too. I just patched this dep out of setup.py, especially since we still control dependencies by our distribution tools. But I still wonder what's wrong with python-dbus, some people had the same problem with blockify (https://aur.archlinux.org/packages/blockify/?comments=all), but that was resolved when this dep was removed from upstream.
>pip install would work, of course, but using that we're mixing Arch and python's package managers, and get all kinds of problems on further updates/removes. It would be wiser to just install autokey via pip if we're going this way.
>autokey-py3 0.93.9-2  (2017-01-14 15:04)

And dark-saber's patch does indeed work but I'm hoping this can be fixed in the autokey itself so every update doesn't break autokey and we don't have to wait day(s) until it's patched by someone.

Thank you so much for a great tool and I hope this issue can be fixed.

**Comment by troxor** [comment]
This broke the Ubuntu packaging process briefly too, as debhelper tries to helpfully resolve dependencies. However, the [Python Packaging Guide](https://packaging.python.org/distributing/?highlight=install_requires#install-requires) among other places suggests that install_requires is "better". So, I'll keep it the way it is for now, unless someone submits a PR that is better.
