### ISSUE TITLE
[Feature Request] Allow Autokey to run on any window manager.

### ISSUE THREAD

**Issue by kreezxil** [autokey/autokey#620]
## Classification:

(Pick one of: Bug, Crash/Hang/Data Loss, Performance, UI/Usability, Feature (New), Enhancement)
Feature?

## Reproducibility:

(Pick one of: Always, Sometimes, Rarely, Unable, I Didn't Try)
Always

## Version
96 beta 6

AutoKey version: 

Used GUI (Gtk, Qt, or both): neither, testing on xfce4

If the problem is known to be present in more than one version, please list all of those.

Installed via: (PPA, pip3, …). pip3

Linux Distribution: manjaro xfce4

## Summary

Summary of the problem.

xfce4 supports neither KDE or Zenity (gnome) wmctrlz
is it possible to have AK break free of this cage?

if so that would be a great feature opening it to a great many Linux desktops.

**Comment by josephj11** [comment]
This sounds like a major enhancement.

It might be easier to build an AutoKey container of some sort (AppImage, flatpak, ...), but AFAIK, none of our devs are familiar with this technology. But, if we could get it to work, it would address a wider set of environments.

**Comment by kreezxil** [comment]
i'm cool with a containerized version of it.

**Comment by BlueDrink9** [comment]
What is the alternative to using `wmctrl`? Is xfce4 not EWMH/NetWM compatible?

Autokey is more or less window manager agnostic. It certainly runs on 
most of them, and main functionality should work. Is it specifically wmctrl behavior that you are talking about?

**Comment by kreezxil** [comment]
I tried to run it on XFCE4 and it said "wmctrl required" and the associated
gtk or qt libs depending on which framework you went with. Had the same
experience with i3wm.

**Comment by BlueDrink9** [comment]
Thank you, would have been good to include that detail in the issue report. Have you installed wmctrl? According to a search, xfce4 supports it.

**Comment by kreezxil** [comment]
Heh, I erroneously assumed you guys knew it didn't run on many window
managers by default. I'll go back to super verbose mode which is my modus
operandi. I'll install that next time I give this a go, later today or
tomorrow.

**Comment by BlueDrink9** [comment]
I think it does run on most window managers by default. I think you have erroneously diagnosed the issue, at least from what you have reported here. Happy to be proven wrong, but as far as I can tell this report is just a case of not installing the dependencies listed on the wiki

**Comment by kreezxil** [comment]
video challenge accepted.

**Comment by BlueDrink9** [comment]
@kreezxil closing this until reproduction provided
