### ISSUE TITLE
Clicking on Show Main Window opens the window minimized

### ISSUE THREAD

**Issue by arunkumaraqm** [autokey/autokey#625]
## Classification:

UI/Usability

## Reproducibility:

Always

## Version

AutoKey version: 0.95.10

Used GUI (Gtk, Qt, or both): Gtk

Installed via: pip 21.1.3 

Linux Distribution: Ubuntu 20.04

DE: Gnome 
## Summary

When Autokey's window is not open, clicking on the Autokey indicator applet and selecting Show Main Window opens the window below other windows and not in the foreground.

**Comment by josephj11** [comment]
Haven't seen this one before. We have a lot of users with similar environments, so it leads me to suspect it has something to do with your environment, but what that might be isn't obvious.

I still haven't upgraded from kubuntu 18.04, but I have never seen this issue.

Possible workarounds:

Try the Qt front end. (Both front ends can be installed can be installed on the same system without conflicts and you can run the one you want with the autokey-gtk or autokey-qt commands.)

Open a terminal window and type `autokey-gtk -c` and see how that works. You can run it at any time. If AutoKey is not running, it will start it and display the main window. If AutoKey is running, it will just display the main window. See if the AutoKey window displays as desired.

If it doesn't, then report that here.

If it does work, then you can add an icon to your desktop or panel which invokes the above command. We can help with that on our [support forum](https://groups.google.com/forum/#!forum/autokey-users).

**Comment by arunkumaraqm** [comment]
>Try the Qt front end. 

This error does not occur in the Qt front end.

>Open a terminal window and type autokey-gtk -c and see how that works

`ModuleNotFoundError: No module named 'dbus'`

**Comment by josephj11** [comment]
As on your other issue, the first thing I would do is a fresh install (after backup) using apt.

Since dbus is all about interprocess communication, getting it installed and working correctly with AutoKey might really help.

**Comment by Elliria** [comment]
My environment is Kubuntu 22.04 LTS and I use the same version of AutoKey as you do, but haven't seen this issue. Is this still an issue for you today, @arunkumaraqm?

**Comment by josephj11** [comment]
@Elliria Me too (on my other notebook).

If we don't get any feedback, I would be in favor of closing this as completed in a few days.

**Comment by arunkumaraqm** [comment]
@Elliria I haven't upgraded by Ubuntu and I haven't had to edit anything in Autokey for at least a year.

You can close this issue.
