### ISSUE TITLE
AutoKey panel icon hides on script error

### ISSUE THREAD

**Issue by Elliria** [autokey/autokey#631]
## Classification:
Bug

## Reproducibility:
Always

## AutoKey version:
autokey-gtk 0.96.0-beta.9

## Used GUI:
Gtk

## Installed via:
pip3

## Linux distribution:
- Kubuntu 20.04 LTS running inside of VirtualBox
- KDE Plasma Version 5.18.5
- KDE Frameworks Version: 5.68.0
- Qt Version: 5.12.8
- Kernel Version: 5.11.0-40-generic
- OS Type: 64-bit
- Memory: 3.2 GiB of RAM
- Processor: 1 x Intel Core i5-8600K CPU @ 3.60 GHz

## Summary of the problem:
The AutoKey panel icon hides on script error.

## Steps to reproduce:
1. Launch autokey-gtk.
2. Find the AutoKey icon in your panel and note its location.
3. Write an AutoKey script that will trigger an AutoKey error notification. For example: ```return("foo")```
4. Run the script, either by using its trigger or by clicking the "Play" button in the toolbar.
5. When AutoKey gives you an error notification, look in the panel for the AutoKey icon.

## Expected result:
The icon should remain visible in the location you noted in step 2 above.

## Actual result:
The icon is invisible, but there in the location you noted in step 2 above.

## Notes:
This work-around will allow you to view the script error and will also "unhide" the AutoKey icon so you can continue to use AutoKey uninterrupted:
1. Right-click the invisible icon's location to open the AutoKey context menu.
2. Click on "View script error" to examine the error in the window that opens.

**Comment by BlueDrink9** [comment]
Thanks for this. I can't reproduce it on plasma. It would be great if someone on another system can check it. I am using a non-default icon set, which might be why.

**Comment by Elliria** [comment]
I do use the default icon set in this copy of Kubuntu, but it turns out this was my mistake. I happen to love hot pink, and the icon turns red when there's a script error. It blends in rather nicely into my hot pink background so that it's nearly invisible, but on close inspection, it's there and I can see what's happening. This is a non-issue after all. Sorry for the noise.

**Comment by josephj11** [comment]
The icons AutoKey uses for light and dark are just files saved in the code. You can replace them with ones that work better for you, but you'll have to reapply them when the package gets updated.

```
bigbird@sananda:~/installs/autokey/autokey
$ find . -iname 'autokey-status*.svg'
./config/autokey-status.svg
./config/Humanity/autokey-status.svg
./config/Humanity/autokey-status-error.svg
./config/autokey-status-error.svg
./config/ubuntu-mono-dark/autokey-status.svg
./config/ubuntu-mono-dark/autokey-status-error.svg
./config/autokey-status-dark.svg
./config/ubuntu-mono-light/autokey-status.svg
./config/ubuntu-mono-light/autokey-status-error.svg
```

**Comment by Elliria** [comment]
Thanks. I added that information to my AutoKey cheat sheet in case I decide to do it. For now, I'm aware that the red icon is hard to see on my hot-pink panel, but that I should look closely to see if it's there.
