### ISSUE TITLE
Pakinay_saree

### ISSUE THREAD

**Issue by Pakinay** [autokey/autokey#647]
## Classification:
(Pick one: Bug, Crash/Hang/Data loss, Enhancement, Feature (new), Performance, UI/Usability)

## Reproducibility:
(Pick one: Always, Sometimes, Rarely, Unable, I didn't try)

## AutoKey version:
(Paste in your AutoKey version and, if the problem is known to be present in more than one version, please list them all.)

## Used GUI:
(Pick one: Gtk, Qt, Both):

## Installed via:
(Pick one: PPA, pip3, Git, package manager, etc.)

## Linux distribution:
(Provide information about your Linux distribution and its release or version number.)

## Summary:
(Provide a brief summary of the problem.)

## Steps to reproduce:
- I do this.
- Then I do that.

## Expected result:
(Explain what should happen.)

## Actual result:
(Explain what actually happens.)

## Screenshot (if applicable):
(Include one or more screenshots of the issue by dragging the image file(s) here to help with debugging.)

## Verbose output (if applicable):
(Include the output from launching AutoKey via the `autokey-gtk --verbose` or `autokey-qt --verbose` command to help with debugging. Please upload the output somewhere accessible or paste it into a code block here, enclosing it in triple backticks.)
```
Example code block. Replace this with your output content.
```

## Notes:
(Describe debugging steps you've taken, a workaround you've figured out, or any other information you think we might need.)

**Comment by Elliria** [comment]
We may be able to help, Pakinay. We'll need some details to head us in the right direction. Feel free to reply to this message if you receive a copy of it in email or visit this issue page and add a comment,

You might also like to participate in the [AutoKey Gitter chat](https://gitter.im/autokey/autokey), which is good for technical questions, or the [AutoKey Google Group](https://groups.google.com/g/autokey-users), which is more user-oriented.
