### ISSUE TITLE
Cannot match string with window.wait_for_focus

### ISSUE THREAD

**Issue by MrOats** [autokey/autokey#66]
Classification: Bug

Reproducibility: Always

## Summary

Using a string like "#my-channel - Discord" in `window.wait_for_focus()` returns the results below. If one uses `window.wait_for_exist()` instead, then it will match correctly.

## Steps to Reproduce
Use this:
```
window.wait_for_focus("#my-channel - Discord", timeOut=1)
```
and get below results instead of it working, unlike `window.wait_for_exist()`.

## Expected Results

It finds the window title matching the string.

## Actual Results

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/autokey/service.py", line 460, in execute
    exec(script.code, scope)
  File "<string>", line 9, in <module>
  File "/usr/lib/python3.6/site-packages/autokey/scripting.py", line 849, in wait_for_focus
    if regex.match(self.mediator.interface.get_window_title()):
TypeError: cannot use a string pattern on a bytes-like object
```

If helpful, submit screenshots of the issue to help debug. `autokey-gtk --verbose` output is also useful.

## Version

AutoKey-Py3 version: 0.93.9-2

If the problem is known to be present in more than one version, please list all of those.

Installed via: AUR via Pacman

Distro: Arch Linux

## Notes

If you've found a workaround, provide it here: use `window.wait_for_exist` instead.

**Comment by troxor** [comment]
Using the below script, and then causing a browser window titled "Discord" to be focused, I don't get a traceback. Can you provide a complete reproduction case?

```
# Displays the information of the next window to be left-clicked
import time
window.wait_for_focus("Discord")
time.sleep(0.2)
winTitle = window.get_active_title()
winClass = window.get_active_class()
dialog.info_dialog("Window information", 
          "Active window information:\nTitle: '%s'\nClass: '%s'" % (winTitle, winClass))
```
