### ISSUE TITLE
Can't run autokey-gtk

### ISSUE THREAD

**Issue by moon-chilled** [autokey/autokey#67]
Classification: Crash/Hang/Data Loss

Reproducibility: Always

## Summary

When I run autokey-gtk on arch, I get the following:

    X protocol error:
    <class 'Xlib.error.BadAccess'>: code = 10, resource_id = 209, sequence_number = 27, major_opcode = 33, minor_opcode = 0
    X protocol error:
    <class 'Xlib.error.BadAccess'>: code = 10, resource_id = 209, sequence_number = 28, major_opcode = 33, minor_opcode = 0
    X protocol error:
    <class 'Xlib.error.BadAccess'>: code = 10, resource_id = 209, sequence_number = 29, major_opcode = 33, minor_opcode = 0
    X protocol error:
   <class 'Xlib.error.BadAccess'>: code = 10, resource_id = 209, sequence_number = 30, major_opcode = 33, minor_opcode = 0

I tried both the AUR version, and installing the github version through pip.  The oddest thing is, though, if I leave an instance of autokey-gtk running and run up another one, it opens fine.

**Comment by troxor** [comment]
Please provide a reproduction case in a clean environment, with as much detail as possible.

**Comment by MultiStorm** [comment]
How is it going on
What do you need for information to further work?
I only have the environment in which the error occurs. But the system was installed 4 weeks before.

System:
Lenovo E51.80 x64
Ubuntu 16.04 LTS -> apt-get Update / upgrade is current.
8 GB of RAM

Python3 -V = Python 3.5.2
Python -V = Python 2.7.12

Do you need more information? If yes, which?

**Comment by MultiStorm** [comment]
Here the log from my first installation try
i think her try to install whit python 2 !?!?!?!

~/Downloads/autokey-py3/autokey$ sudo python setup.py install
running install
running bdist_egg
running egg_info

...
...

Installed /usr/local/lib/python2.7/dist-packages/dbus_python-1.2.4-py2.7-linux-x86_64.egg
Finished processing dependencies for autokey==0.93.9

**Comment by troxor** [comment]
@MultiStorm This is a Python3 project, don't use Python2 to install.
@Elronnd Could it be that the tray icon isn't showing up (or is very thin and transparent), but the process is actually running?

**Comment by MultiStorm** [comment]
Yes i Know that -> NOW !
But install after that fail over the PPA -> Result -> Dont Running!

Install over sudo python3 setup.py ?

**Comment by moon-chilled** [comment]
@troxor I'm not in a WM that has tray icons, but I know that a window isn't opening up; but it does when I run again while the first one is still running.

**Comment by johnbeard** [comment]
I see this too on Arch using i3 when running `autokey-gtk` in a terminal.

```
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 214, sequence_number = 19, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 214, sequence_number = 20, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 214, sequence_number = 21, major_opcode = 33, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadAccess'>: code = 10, resource_id = 214, sequence_number = 22, major_opcode = 33, minor_opcode = 0
autokey.interface BadWindow(<Xlib.display._BaseDisplay object at 0x7f8b180ad240>, b'\x00\x03j\x12\x02\x00\x00\x04\x00\x00\x14\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
autokey.interface BadWindow(<Xlib.display._BaseDisplay object at 0x7f8b180ad240>, b'\x00\x03k\x12\x02\x00\x00\x04\x00\x00\x14\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
```

The tray icon does appear however, and you can access the window by right click and 'Show Main Window'.

Leaving this one running and running `autokey-gtk` in another terminal brings the window up. Running using the desktop file with a launcher always works, even first time.

**Comment by troxor** [comment]
To start `autokey-gtk` in the "foreground", use the `-c` or `--configure` option.

**Comment by MultiStorm** [comment]
and my problem?
