### ISSUE TITLE
Update README.rst

### ISSUE THREAD

**Issue by josephj11** [autokey/autokey#681]
### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Documentation

### Which Linux distribution did you use?

N/A

### Which AutoKey version did you use?

0.96.0 Beta 10

### How did you install AutoKey?

N/A

### Can you briefly describe the issue?

Needs updating and to be made more user friendly

### Anything else?

Documentation section should first link to our wiki. New in this release/new in this major version should be added with more descriptive text. This should be a bit more promotional ("look at these great new features" ... )

API documentation link should point to the new improved format document.

**Comment by Elliria** [comment]
If you're talking about the first link in the document, it currently points to the AutoKey main project page at [https://github.com/autokey/autokey](https://github.com/autokey/autokey) and I can see how that could be disconcerting to visitors who aren't used to seeing repository file listings.

Would pointing it lower down on the same AutoKey main project page, like [https://github.com/autokey/autokey#readme](https://github.com/autokey/autokey#readme) work? That way, the newcomers would have a more user-friendly greeting while those of us who are comfortable with the repository file listings or who would like to get at them would know to scroll up.

**Comment by Elliria** [comment]
I missed updating the API link when I did the recent update and will do that after the current PR is merged.

**Comment by josephj11** [comment]
The links I'm talking about are in the document under the Documentation heading. It looks like they have mostly been fixed already. One that I missed is on the next line about Examples. The wiki link there should point to https://github.com/autokey/autokey/wiki/Example-Scripts instead of to the head of the wiki.

The Running unit tests section should be deleted. It needs to be added to CONTRIBUTORS.rst (maybe under the Testing section). The section here should be replaced by a contributors section that links to CONTRIBUTORS.rst after a few lines of welcoming/encouragement.

new_features.rst needs a complete rewrite. It is extremely old. We might want to just delete it and replace it with a wiki page for ease of editing. The example code it contains needs to be saved unless there is already better code in our wiki.

CONTRIBUTORS.rst is also very old and needs a rewrite. It says "I" when it should say "we", etc.

```
Just open a PR for discussion and I’ll try to answer any questions that arise. I suggest writing new features on top of develop.
```

should be 


```
Just open a PR against the develop branch for discussion and we’ll try to answer any questions that arise.

We prefer to leave our main branch relatively untouched between releases as a reference for current issues and user support.
```

**Comment by Elliria** [comment]
Okay, putting all of that together and adding a bit to it, how does this sound for changes to the **develop** branch's [README.rst](https://github.com/autokey/autokey/blob/develop/README.rst) file?

1. Update the **API scripting** link in the **Documentation** section with [API scripting](https://autokey.github.io/autokey/api.html) (I missed that).

2. Replace the **wiki** link in the **Documentation** section with: [wiki](https://github.com/autokey/autokey/wiki/Example-Scripts)

3. Replace the **Contributing or modifying the source** section heading with the **Contributing** section heading.

4. Replace the **Contributing** section's contents with these contents:

   Pull requests are welcome from anyone who would like to modify or contribute to the source code. Useful tips for working with and testing the code can be found in the [CONTRIBUTORS.rst](https://github.com/autokey/autokey/blob/develop/CONTRIBUTORS.rst) file. AutoKey also participates in [CodeTriage](https://www.codetriage.com/autokey/autokey), where members can sign up to receive a daily email with a link to an open AutoKey issue that needs help.

5. Remove the **Running the unit tests** section.

6. Remove the **Changelog.** section. That is and should be dealt with in the [CONTRIBUTORS.rst](https://github.com/autokey/autokey/blob/develop/CONTRIBUTORS.rst) file.

7. Replace the contents of the **License** section with these contents:

   AutoKey uses the [GNU GPL v3](https://www.gnu.org/licenses/gpl.html). See the [LICENSE](https://github.com/autokey/autokey/blob/master/LICENSE) file for a plain text copy of the license.

8. Alphabetize all of the sections.

**Comment by Elliria** [comment]
I thought I'd add that the zero-installation steps should also probably be removed from the [README.rst](https://github.com/autokey/autokey/blob/develop/README.rst) file's **Installation** section since that already links to the wiki's [Installing](https://github.com/autokey/autokey/wiki/Installing) page.

**Comment by Elliria** [comment]
The [CONTRIBUTORS.rst](https://github.com/autokey/autokey/blob/develop/CONTRIBUTORS.rst) file needs an entire rewrite. I've added your suggestions to issue #718 and we'll follow up on it there.

**Comment by Elliria** [comment]
We can continue discussion of the [new_features.rst](https://github.com/autokey/autokey/blob/develop/new_features.rst) file in issue #680.

**Comment by josephj11** [comment]
3. We might want to leave the title as is. People frequently clone a project so they can make some "personal" changes that are not intended for inclusion in the general project.They still need to know how to do that and may want to run our unit tests, etc. to make sure they haven't inadvertently broken something.

4. The code triage  thing should say "periodically", not "daily". Daily is the default, but I quickly changed mine to weekly because I was getting overwhelmed.

6. No. That's where regular users can see what we have fixed and what the new features are in detail, etc. the new_features.rst page addresses some of this (once it gets rehabilitated), but should probably be an overview/summary rather than all the details. Also, an up to date change log is mandatory IMO, but an updated new features page is only "important".

7. We need to verify whether it says "3.0" or "3.0 or newer at your descretion" as many projects do.

8. I'm not into sorting for sorting's sake. I like things in order of what's most important first. I like the current order, but I am open to discussing it further. I have one vote in anything like this.

**Comment by Elliria** [comment]
Okay, with most of those changes, how does the amended list of intended changes to the [README.rst](https://github.com/autokey/autokey/blob/develop/README.rst) file look?

1. Update the **scripting API** link to [scripting API](https://autokey.github.io/autokey/api.html).
2. Replace the **wiki** link in the **Documentation** section with: [wiki](https://github.com/autokey/autokey/wiki/Example-Scripts).
3. Replace the **Contributing or modifying the source** section's contents with these contents:

   > Pull requests are welcome from anyone who would like to modify or contribute to the source code. Useful tips for working with and testing the code can be found in the [CONTRIBUTORS.rst](https://github.com/autokey/autokey/blob/develop/CONTRIBUTORS.rst) file. AutoKey also participates in [CodeTriage](https://www.codetriage.com/autokey/autokey), where members can sign up to receive a periodic email with a link to an open AutoKey issue that needs help.

4. Remove the **Running the unit tests** section.
5. Replace the contents of the **License** section with these contents:

   > AutoKey uses the [GNU GPL v3](https://www.gnu.org/licenses/gpl-3.0.html). See the [LICENSE](https://github.com/autokey/autokey/blob/master/LICENSE) file for a plain text copy of the license.

6. Remove the zero-installation steps from the **Installation** section and put them into the wiki's **Installing** page instead.

**Comment by Elliria** [comment]
For item number 6 in the amended list above, I took the text from the original **README.rst** file. You can see it on the **master** branch [here](https://github.com/autokey/autokey/blob/master/README.rst). I'm not sure what the protocol is, but GNU refers to it as **GPLv3** on their [https://www.gnu.org/licenses/gpl-3.0.html](https://www.gnu.org/licenses/gpl-3.0.html) page, but we can use **GNU GPL v3.0** to be absolutely clear.

**Comment by josephj11** [comment]
LGTM!

**Comment by Elliria** [comment]
It looks like this issue is done unless you would like to keep it open until we do the same to the one in **master**.

**Comment by josephj11** [comment]
Doesn't matter to me. Whatever is easier for you.

**Comment by Elliria** [comment]
* The [README.rst](https://github.com/autokey/autokey/tree/beta) file in the **beta** branch is done.
* The [README.rst](https://github.com/autokey/autokey/tree/develop) file in the **develop** branch is done.
* The [README.rst](https://github.com/autokey/autokey/tree/master) file in the **master** branch is done.
