### ISSUE TITLE
clipboard.get_selection() gives previous selection when there's no selection

### ISSUE THREAD

**Issue by chang-zhao** [autokey/autokey#685]
### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Bug

### Which Linux distribution did you use?

Manjaro Linux Release:	21.2.5, kernel 5.15 LTS

### Which AutoKey GUI did you use?

GTK

### Which AutoKey version did you use?

0.96.0-beta.10

### How did you install AutoKey?

autokey-git from Archlinux (AUR) repo

### Can you briefly describe the issue?

When no text is selected, clipboard.get_selection() gives the text that was selected when the previous clipboard.get_selection() was invoked.

### Can the issue be reproduced?

Sometimes

### What are the steps to reproduce the issue?

1. Open a new file in `geany` editor.
2. Write there two lines: `aaa` and `bbb`.
3. Select `aaa` and invoke a script like `~/.config/autokey/data/Sample Scripts/Selection Test.py`
4. It shows that `aaa` was the selection.
5. Click on `bbb` string (so that no text is selected).
6. Invoke the same script.
7. It shows again that the selection is `aaa`.

### What should have happened?

Instead of `aaa` as selection there should be an exception saying there was nothing selected.

### What actually happened?

The previous selection was returned though no text was selected.

### Anything else?

This bug didn't happen in an another editor: Mousepad (XFCE desktop).

**Comment by sebastiansam55** [comment]
I think that this is just the way the underlying library handles it, xclip will show the same behavior (`xclip -selection primary -o`). I would think that this extends to all x based libraries but I don't know for sure. 

Not sure why you weren't getting the same behavior in mousepad, that editor must be doing something that is clearing it, I get the same behavior.

**Comment by ineuw** [comment]
This is why I had to to clear the clipboard at the start and end of my scripts. I had the identical problem + more. The X clipboard copies same data to either the permanent or the secondary memory area. 

```
import os
os.system("sleep .1; xsel -cb")
```
The + means that other apps using the clipboard do not clear their clipboard data in a timely fashion when terminated and this can also end up pasted. To prevent such an occurrence, I also use the following at the end of my scripts. This clears all three x clipboard storage areas.

```
sleep .1; xsel -cb && sleep .1; xsel -cp && sleep .1; xsel -cs
```

**Comment by chang-zhao** [comment]
@ineuw thank you. I try `system.exec_command("sleep .1; xsel -cp")` at the start and end of my scripts, and it seems that it solves my problem.

**Comment by vvasuki** [comment]
> @ineuw thank you. I try `system.exec_command("sleep .1; xsel -cp")` at the start and end of my scripts, and it seems that it solves my problem.

Better to just clipboard.fill_selection("")

**Comment by josephj11** [comment]
This issue should be closed.
