### ISSUE TITLE
Folder name consistency on default installation

### ISSUE THREAD

**Issue by Elliria** [autokey/autokey#693]
### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

UI/Usability

### Which Linux distribution did you use?

Environment:

- Kubuntu 20.04
- KDE Plasma Version 5.18.8
- KDE Frameworks Version: 5.68.0
- Qt Version: 5128
- Kernel Version: 5.13.0-40-generic
- OS Type: 64-bit

### Which AutoKey GUI did you use?

Both

### Which AutoKey version did you use?

0.95.10

### How did you install AutoKey?

Ubuntu repository.

### Can you briefly describe the issue?

When you first install AutoKey, the folder names that are provided by default are different from one another. You get the "My Phrases" and "Sample Scripts" folders.

### Can the issue be reproduced?

Always

### What are the steps to reproduce the issue?

Install either or both front ends of AutoKey.
Open either or both front ends of AutoKey.
Look at the default folder names.

### What should have happened?

Although the folder names can be customized, it might be nice if they were similar by default. For example, as either "My Phrases" and "My Scripts" or as "Sample Phrases" and "Sample Scripts".

### What actually happened?

The default folder names aren't similar.

### Anything else?

My reason for this issue report is purely from an organizational viewpoint (it would look nicer), but also because "My Phrases" implies ownership and makes the user automatically feel sort of a kinship with phrases, while "Sample Scripts" is kind of like the donuts (or other treats) the person at the grocery store has on a plate for you to try that you don't actually buy, so the naming may do a very subtle job of discouraging script use.

Oh, and I did search to see if this has been reported before, but it's possible it has and my search didn't turn it up. If so, then my apologies.

**Comment by josephj11** [comment]
Here's how I understand it:

Sample scripts and phrases are actual example scripts and phrases that get installed to give users a head start (and something to test with to make sure everything is working.)
My scripts and My phrases both start out empty and encourage the user to keep the two types of actions separate.

I don't see any problem with this. (Although I try very hard not to create file and directory names with embedded blanks in them.)

That being said, the first thing I do is use AutoKey to create an empty folder at $HOME/Autokey and then I externally populate that with all my existing scripts and phrases in their own subtree. (Sometimes, this folder is actually a symlink e.g. points to my subtree for 0.95.10 or to my subtree for 0.96.0).

So I don't actually use the default folders for anything. This has the added benefit of being untouched by uninstalling/reinstalling or even purging AutoKey and could even be stored in the cloud if you can assure cloud availability whenever AutoKey is needed. Something like Dropbox, where you always have a local copy, would work fine.

**Comment by Elliria** [comment]
I actually use the default folders, but I rename them. They can easily be renamed, as I had mentioned, but I just figured it might be nice if they were named in a consistent way from the outset and it probably would be a trivial change in the code.

I may adopt your method of putting my phrases and scripts outside of AutoKey and letting AutoKey know about them. I've always just put them in the default location and backed up the hidden AutoKey directory, but your method may be more convenient for reinstallations or testing purposes, as you mentioned.

**Comment by josephj11** [comment]
It's a matter of personal preference. I like to keep the "demo" scripts and phrases separate from mine. I don't delete them and that's where #665 came from. I tested them after installing the Beta before installing all my stuff.

Note: Since 0.96 was not backwards compatible with previous releases, I also created a separate copy of my external AutoKey scripts and phrases directory subtree and used a symlink for that too.

If you continue testing multiple releases (as I hope you do), then you may need to do something similar as well. You don't want a script or phrase that uses a new feature breaking tests of an older release. It's hard to remember what you changed when, so keeping things separate should make your testing easier.

I haven't really used it, but I wrote a bash script to switch my symlinks between the two releases.

**Comment by Elliria** [comment]
It makes sense, although I'd probably still rename the default folders and then put symlinks to my actual folder locations inside of them so that the program would still look and behave as it does now.

I had been doing all of my testing in separate dedicated virtual machines, but those got intentionally wiped out as part of my recent upgrade so I can start fresh. I'll just be running AutoKey 0.95.10 in my new operating system for the time being, Once I get around to setting up several environments on my server, I'll go back to testing the beta.

**Comment by josephj11** [comment]
Years ago, I tried to use VMs and they were a huge pain. I'm sure they are much better now, but I haven't tried them again.

**Comment by Elliria** [comment]
VirtualBox is really quick to set up nowadays, but my frustration is now with the operating system. I'll be wanting to hunt around for something smaller than Ubuntu. It now requires more than 20 GB for each virtual machine and that's a bit ridiculous for testing something as small as AutoKey, especially when you're making multiple VMs to do the tests in different versions or in different environments. I figured putting those tests on a dedicated server may be easier in the long run.

**Comment by BlueDrink9** [comment]
This issue seems very opinionated, so I'm not sure how to approach it. If you canvas opinion on gitter and get a majority, we'll make the change

**Comment by Elliria** [comment]
That won't be necessary. It isn't something that's broken and it's easy enough to customize. I'll go ahead and close this one.
