### ISSUE TITLE
Need to enlarge the font size of the built in the 09.10beta editor

### ISSUE THREAD

**Issue by ineuw** [autokey/autokey#696]
## Classification:
important Enhancement

## Reproducibility:
Always

## AutoKey version:
96.10beta

## Used GUI:
Gtk

## Installed via:
pip3

## Linux distribution:
Linux Mint Cinnamon 20.3

## Summary:
Did the font-size of the built in editor changed? Can I increase the size on my own?

My current external code editor is Xed. It shares the same Gtk theme and font-family, but Xed is set to 12pts font-size which has no effect on the AK internal editor. They used to be the same font-size in the past. After adjusting Xed to match the font family and size, Ubuntu Mono Regular, with the font-size: 11pts is indicated.

**Comment by josephj11** [comment]
I think this would be quite useful. You could make the font smaller to fit more code in the panel or larger if it's hard to read.

I poked around the Qt GUI  code (I know you're using GTK) and it sets a default font from the larger environment without ever specifying a size.

The GTK code looks the same. It's in configwindow.py under class ScriptPage.

I looked a little further, but didn't immediately see anything about how to set a font manually. That will have to be figured out first before adding anything to the GUI to allow the user to modify it.

**Comment by josephj11** [comment]
See also #474 which I just reopened for similar problems in the Qt front end.

**Comment by ineuw** [comment]
I've been following the various discussions on the topic and wondered if it couldn't be corrected by adding a CSS file somewhere.

This seems to be a recent bug because it wasn't so a month ago. Adjusting the system mono font setting has no effect any longer.

**Comment by ineuw** [comment]
This is no longer an issue.
