### ISSUE TITLE
Feature Request: Stop running script via hotkey toggle.

### ISSUE THREAD

**Issue by Git-Forked** [autokey/autokey#698]
### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Enhancement

### Which AutoKey GUI did you use?

GTK

### Which AutoKey version did you use?

latest

### Can you briefly describe the issue?

Feature request to add an option to stop a script via hotkey toggle:

![Auto_Key_feature_request](https://user-images.githubusercontent.com/66106762/172048517-b0178855-92b8-41db-b78a-beb46cc5c21b.png)

**Comment by BlueDrink9** [comment]
(Note to others viewing this thread: see #694 for a workaround)

**Comment by josephj11** [comment]
Given the lack of activity on this request and our lack of developers, I'm closing this as a won't fix.
