### ISSUE TITLE
dbus error with Ubuntu PPA

### ISSUE THREAD

**Issue by sicherist** [autokey/autokey#70]
Classification: Bug

Reproducibility: Always

## Summary

Autokey-py3 does not run at all on Kubuntu 16.04 when installed from the PPA.

## Steps to Reproduce

1. Install Autokey-py3 from the PPA:
`sudo add-apt-repository ppa:troxor/autokey`
`sudo apt update`
`sudo apt install autokey-gtk`
2. Try to run autokey-qt
`autokey-qt`

## Expected Results

3. Autokey should start.

## Actual Results

3. Autokey doesn't start. Error message:

> Traceback (most recent call last):
  File "/usr/bin/autokey-qt", line 56, in <module>
    from autokey.qtapp import Application
  File "/usr/lib/python3/dist-packages/autokey/qtapp.py", line 22, in <module>
    import sys, traceback, os.path, signal, logging, logging.handlers, subprocess, queue, time, dbus, dbus.mainloop.qt
ImportError: No module named 'dbus.mainloop.qt'

## Version

AutoKey-Py3 version 0.93.9-1

Installed via: PPA

Distro: Kubuntu 16.04

## Notes

I couldn't get it to work with the PPA. Installation via PIP worked.

**Comment by troxor** [comment]
Can you try to install the `python3-dbus.mainloop.qt` package and retry? Perhaps there is a missing package dependency.

**Comment by troxor** [comment]
There were a couple issues, but I got autokey-qt launching in a VM, can you retry with the latest `git HEAD`?

**Comment by troxor** [comment]
Try the latest version, 0.93.10, which should be fine.

**Comment by sicherist** [comment]
Thank you it works now!

When running autokey-qt from the terminal and then opening the autokey window I get the following message on the terminal:

> QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed: Datei oder Verzeichnis nicht gefunden
QFileSystemWatcher: failed to add paths: /home/user/.config/ibus/bus
Bus::open: Can not get ibus-daemon's address. 
IBusInputContext::createInputContext: no connection to ibus-daemon 


The application is working fine so far, despite the error message.
