### ISSUE TITLE
All custom defined keybindings stopped working in "sticky keys" mode.

### ISSUE THREAD

**Issue by genehwung** [autokey/autokey#720]
### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### Which Linux distribution did you use?

Debian.

### Which AutoKey version did you use?

AutoKey-gtk

### How did you install AutoKey?

apt install autokey-gtk

### Can you briefly describe the issue?

All custom defined keybindings stopped working in "sticky keys" mode. For example, if I have defined control+f to be right_arrow, but it stops working once I am "sticky keys" mode after activated "Treat a sequence of modifier keys as a combination" in Debian's "Accessibility" -> "Typing assistance" tab.

### Can the issue be reproduced?

Always

### What are the steps to reproduce the issue?

Enable "sticky keys:Treat a sequence of modifier keys as a combination" in Debian's "Accessibility" -> "Typing assistance" tab.
Type any keybinding defined in AutoKey.

### What should have happened?

The keybinding should remain the same.

### What actually happened?

Nothing as if the keybinding isn't triggered.

**Comment by josephj11** [comment]
Sticky keys is an accessibility feature of your desktop environment. I do not believe I have seen anyone try to use it with AutoKey before. I suspect that the desktop is consuming the keystrokes before AutoKey gets to see them.

To see what AutoKey is doing, we'll need a [trace](https://github.com/autokey/autokey-python2/wiki/Problem-Reporting-Guide).

We also need more precise information on your setup including the Debian version and the AutoKey version.

**Comment by genehwung** [comment]
This is the Debian testing branch. As of today, The version is Debian 5.17.11-1. 
Autokey 0.95.10

I checked the log, it looks like the OS didn't see it at all. Whenever I pushed "shift" then "i", in keyboard, I get "I" but autokey saw "shift pressed" "shift released" and "raw i", it didn't even see the capitalized "I" that the OS sent. 

So you are right, this does not look like an issue that can be solved by Autokey. Feel free to the close the bug if you don't want to investigate further from your side.

**Comment by josephj11** [comment]
Thanks for the followup.

If you _really_ need stuff like this to work, you can probably do it by getting a tiny computer like a Raspberry Pi and placing it between your keyboard and your main computer. Most or all of the software to do this already exists. It might even be possible to do it wirelessly so you don't have it dangling off of your keyboard. Once you have that working, you can do almost anything you can think of and all your computer will see is the desired results.

If you or anyone else reading this pursues this, please post on [Gitter](https://gitter.im/autokey/autokey) and tell us how you did it!
