### ISSUE TITLE
Key capture seems broken on Ubuntu 22.04

### ISSUE THREAD

**Issue by sbroenner** [autokey/autokey#728]
### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Bug

### Which Linux distribution did you use?

I've been using AutoKey on Ubuntu 20.04 LTS for months now with this setup and it worked perfectly. Since updating to 22.04 LTS AutoKey no longer captures keys properly.

### Which AutoKey GUI did you use?

GTK

### Which AutoKey version did you use?

Autokey-gtk 0.95.10 from apt.

### How did you install AutoKey?

Distro's repository, didn't change anything during upgrade to 22.04LTS.

### Can you briefly describe the issue?

AutoKey no longer seems to capture keys reliably.

My old scripts are set up like: ALT+A = ä, ALT+SHIFT+A = Ä, ALT+S=ß etc. This worked perfectly on 20.04LTS across multiple machines.

Since the update to 22.04LTS, these scripts only work sporadically, and only in some apps.

Firefox (Snap):
ALT+A works in Firefox if pressed slowly.
ALT+SHIFT+A produces the same output as ALT+A in Firefox if pressed slowly.
If combination is pressed quickly while typing a word, such as "ändern", Firefox will capture the release of the ALT key and send the letters "ndern" to the menu, triggering EDIT=>SETTINGS.

Geany (text editor): ALT key is immediately captured by the menu
Gedit (text editor): ALT key is immediately captured by the menu

Setting hotkeys in AutoKey-GTK itself also doesn't seem to work any more. If I click "Press to Set" the program no longer recognizes any keypresses, hanging on "press a key..." indefinitely.

![image](https://user-images.githubusercontent.com/409535/187735841-e2ee339f-d941-40f9-9049-2607c371658b.png)

My scripts are set up as follows:
![image](https://user-images.githubusercontent.com/409535/187736163-cbfbd11f-b817-4089-9de1-9cd754931a5b.png)

### Can the issue be reproduced?

Sometimes

### What are the steps to reproduce the issue?

I've reproduced this on two different machines, both of which were upgraded from 20.04LTS to 22.04LTS and run the same script files.

### What should have happened?

Same perfect performance as on 20.04LTS

### What actually happened?

See issue description. AutoKey seems to no longer be capturing the keys properly, or rather the foreground app is grabbing them before AutoKey has a chance to do so.

**Comment by sbroenner** [comment]
I've been digging around to find additional info. The following is what happens when I try to capture a key in AutoKey to assign it as a new hotkey:

![image](https://user-images.githubusercontent.com/409535/187739284-fbb8ed08-2fee-4b86-a69d-c0bdd10dc688.png)

When I (slowly) try to use ALT+A in Firefox, the following happens. Output is a ä as expected.

![image](https://user-images.githubusercontent.com/409535/187739489-0fe1ca49-ce2a-4015-8e9c-cff08e8f9b15.png)

When I (slowly) try to use ALT+SHIFT+A in Firefox, the following happens. Output is a ä when it should be upper case instead.

![image](https://user-images.githubusercontent.com/409535/187739603-4cc61e7a-2255-40f4-b1e8-5a31cd979da2.png)


Pressing the same hotkeys (i.e. ALT+A) while one of the text editors in the foreground produces no change in the console whatsoever. Same thing when any other key is pressed - no console output whatsoever. Is that normal?

**Comment by Elliria** [comment]
This sounds like it could have a number of causes. A keyboard issue, interference from other hotkeys on the system, Wayland, etc. I'm betting on Wayland even though you're having an intermittent issue. Are you using a Wayland session? You can type `echo $XDG_SESSION_TYPE` in a terminal window to find out.

AutoKey isn't able to be used in Wayland yet, so if you're using it, you may want to try switching back to an X session to see if that solves the issue. You can do that by going to the log-in screen and clicking the gear icon under the password field to get a choice between Ubuntu (which uses Wayland) and Ubuntu on Xorg (which uses X11).

**Comment by sbroenner** [comment]
Gaaaaaaaaaaaaaah. You're right, upgrading to 22.04 switched me over to Wayland without me even noticing!

Thank you so much, I was tearing my hair out at the thought of having to use a German keyboard layout.

**Comment by Elliria** [comment]
I'm glad it worked. I know the feeling with the German letters. Those were the reason I went looking for AutoKey to begin with.
