### ISSUE TITLE
Allow customization of left mouse button

### ISSUE THREAD

**Issue by NSC9** [autokey/autokey#737]
## Classification:
 Enhancement, Feature (new)

## AutoKey version:
0.95.10

## Used GUI:
Gtk:

## Installed via:
 pip3

## Linux distribution:
Linux Mint 20.3

## Summary:

I am trying to port [this program](https://github.com/NSC9/Sample_of_Work/blob/Main/Personal_Projects/RS4_Mouse_Improvement_Macro) in Autohotkey to be usable on Linux. I reached out to an AutoKey discord and they said that there is no way to change the way the left mouse button behaves or how to check key state. In the meantime, would it be possible for my script to work using Wine?

The functionality I want with Autokey that I can't do Window's AutoHotKey is:
A macro that, when the left mouse button is held down for more than 105milliseconds, continuously send left mouse clicks to the current mouse pointer location every 66 milliseconds. When the left mouse button is released, stop sending clicks. To drag items on the desktop, use shift click to drag items. 

Is there a reason the left mouse button can not be a hotkey?

**Comment by josephj11** [comment]
Welcome to AutoKey!

There are several similar requests already. TL;DR: the main reason is probably our lack of developers. We currently have one great developer who is very occupied with the rest of his life and can only devote a little time to our project.
 Anything anyone can do to get us more developers would be greatly appreciated.

#519 is the primary request. (making this a duplicate which will be closed. If you feel that's not correct, we can reopen this with appropriate clarification/differentiation.)

See also #622 #243 #180 

You can also get limited use of AutoHotKey itself by running it under proton, but there was something mentioned about it only having access to programs running under the same prefix. I have no idea what that means.

Finding those other issues took a bit of sifting, but was done by opening the issues page and adding mouse as a search term after is:open.
