### ISSUE TITLE
AutoKey is already running as pid 1776 but is not responding

### ISSUE THREAD

**Issue by davduf** [autokey/autokey#77]
Hello great team !

## Summary

AutoKey is already running as pid 1776 but is not responding

## Actual Results

org.freedesktop.DBus.Error.ServiceUnknown: The name org.autokey.Service was not provided by any .service files

## Version

AutoKey-Py3 version qt

Installed via: (PPA, pip, …) DNF

Distro: Fedora 25

Thank you !

**Comment by troxor** [comment]
Try removing ~/.config/autokey/autokey.pid . If you can reproduce this, it would be worth implementing a more permanent solution.

**Comment by nick-s-b** [comment]
I'm getting the same error at least once a week. I think it might have something to do with with update of some of the python library packages but I'm not sure. I'm running it under Arch.

**Comment by ineuw** [comment]
Using Linux Mint 18.1 Cinnamon 32bit and 64bit, I have the same error but it is easily correctable in my case.When  starting Autokey-qt in the Startup Applications, the system tray icon is not showing, (it is running, but I am never sure.), so I click on the menu and get the same error message.
The  "Show a notification icon" is selected in Preferences, but the icon is displayed only when Autokey is manually started on the menu.
PS. There is no autokey.pid created with this installation, but I know what you are referring to.

**Comment by luziferius** [comment]
This should be fixed in 0.95.1, which contains a rewrite of the Qt GUI. It both contains a rewrite of the DBus handling and tray icon handling.

The report is quite old, so I just close it now. Please comment or re-open, if the issue still persists in 0.95.1 (or newer).

**Comment by Vinzent03** [comment]
3 years later, I'm facing this issue.
version 0.95.10
installed via pip on KDE neon 5.23.3
Qt-Version: 5.15.3
```
AutoKey is already running as pid 3530 but is not responding

org.freedesktop.DBus.Error.ServiceUnknown: The name org.autokey.Service was not provided by any .service files
```
I enabled the autostart setting, which causes the error window to pop up, every time I start my pc.

**Comment by josephj11** [comment]
@vinzent03 Are you on Arch or one of its derivatives as well?

The first thing to check is whether you have KDE set to restore the previous session when it starts. It might be launching AutoKey and then the AutoKey entry in ~/.config/autostart/autokey.desktop may be trying to do it as well.

I have no issues with this, but I'm way behind you with kubuntu 18.04.

While installing with pip should be fine, if you're using a Debian derivative, you can just install with apt or one of its front ends. If you are on arch, the packages (one for either front end) are in aur as well. That usually gets things right.

If you choose to reinstall, first backup all of ~/.config/autokey including hidden files so none of your work is lost if something goes wrong. Then uninstall the current version of AutoKey. then you're set to install from apt.

**Comment by Vinzent03** [comment]
@josephj11 Thanks for your answer. Disabling autostart in the autokey settings fixed the issue. Didn't know that Autokey is affected by the "restore previous session" feature.
