### ISSUE TITLE
Add a CodeTriage badge to AutoKey

### ISSUE THREAD

**Issue by Elliria** [autokey/autokey#779]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Xorg

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Enhancement

### Which AutoKey GUI did you use?

None

### Can you briefly describe the issue?

We need to add a CodeTriage badge, like this [![Open Source Helpers](https://www.codetriage.com/autokey/autokey/badges/users.svg)](https://www.codetriage.com/autokey/autokey) one, to the AutoKey project now that [AutoKey is listed there](https://www.codetriage.com/autokey/autokey).

### Can the issue be reproduced?

N/A

### Anything else?

Here's the Markdown:
```
[![Open Source Helpers](https://www.codetriage.com/autokey/autokey/badges/users.svg)](https://www.codetriage.com/autokey/autokey)
```
Here's the image URL in case we need to put it inside of an HTML file:
[https://www.codetriage.com/autokey/autokey/badges/users.svg](https://www.codetriage.com/autokey/autokey/badges/users.svg)

**Comment by josephj11** [comment]
Where would we put this? We don't have a project website other than our GitHub page.

**Comment by Elliria** [comment]
Perhaps in the [CONTRIBUTORS.rst](https://github.com/autokey/autokey/blob/develop/CONTRIBUTORS.rst) file and/or perhaps in the [Bug reports and Pull Requests](https://github.com/autokey/autokey/blob/develop/README.rst#bug-reports-and-pull-requests) section of the [README.rst](https://github.com/autokey/autokey/blob/develop/README.rst) file.

**Comment by Elliria** [comment]
This is done in the [README.rst](https://github.com/autokey/autokey/blob/beta/README.rst) file in the **beta** branch.

**Comment by Elliria** [comment]
This is done in the [README.rst](https://github.com/autokey/autokey/blob/develop/README.rst) file in the **develop** branch.

**Comment by Elliria** [comment]
This is done in the [README.rst](https://github.com/autokey/autokey/blob/master/README.rst) file in the **master** branch.
