### ISSUE TITLE
Multi-platform?

### ISSUE THREAD

**Issue by zohozer** [autokey/autokey#78]
Hi. I just discovered this project. I'm searching for an automation tool that can be run on all three major OS (Windows, Linux, MacOS).

I need to know if this tool can be the answer to my needs? Basically have the potential, because Python3 is running on all this OS. What is missing to get fully  #multi-platform?

**Comment by troxor** [comment]
Nope. Technically it would run but it's based on Xlib, which is specific to Xorg.
