### ISSUE TITLE
Add milleseconds to script start and error timestamps

### ISSUE THREAD

**Issue by Elliria** [autokey/autokey#792]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Xorg

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Enhancement

### Which AutoKey GUI did you use?

None

### Can you briefly describe the issue?

Now that the AutoKey minimum Python version is **3.7**, this **TODO** in [line 35-36 of the show_recent_errors.py file](https://github.com/autokey/autokey/blob/master/lib/autokey/qtui/dialogs/show_recent_script_errors.py#L35-L36) can be completed:
```python
    # TODO: When the minimal python version is raised to >= 3.6, add millisecond display to both the script start
    # timestamp and the error timestamp.
```

### Can the issue be reproduced?

Always

**Comment by K0Stek122** [comment]
If it's okay and free i'd like to tackle that.

Waiting for confirmation.

**Comment by josephj11** [comment]
Welcome to the AutoKey community, @K0Stek122 !

That would be great! Please base any PRs against our develop branch.

You may find some useful information in our [wiki](https://github.com/autokey/autokey/wiki/) in the pages listed under Development in the index on the right side of the pages.

Bear in mind that we do not currently have any active AutoKey developers to review PRs, so unless the changes are so simple that I understand them, they probably won't get merged any time soon. We have one former junior developer who knows a lot more Python than I do whom I can ask to review code, but they won't do merges.

I wouldn't be surprised if this particular issue is simple enough for me to merge.

If you want to discuss anything not directly related to an issue, feel free to join us over on [Gitter](https://gitter.im/autokey/autokey). It's pretty quiet there, but I check it almost every day. I'd like to know how you found AutoKey and what you use it for.

**Comment by K0Stek122** [comment]
Sorry, just noticed this issue is not closed. It probably should be closed now.

Thanks.
