### ISSUE TITLE
Convert Namespace to a class in argument_parser.py

### ISSUE THREAD

**Issue by Elliria** [autokey/autokey#793]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Xorg

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Enhancement

### Which AutoKey GUI did you use?

None

### Can you briefly describe the issue?

Now that the AutoKey minimum Python version is **3.7**, this **TODO** in [line 30 of the argument_parser.py file](https://github.com/autokey/autokey/blob/master/lib/autokey/argument_parser.py#L30) can be completed:
```
# TODO: Convert to a class when the minimum Python version is risen to >= 3.6.
```

### Can the issue be reproduced?

Always

### Anything else?

Suggested labels:
* development
* help-wanted
* technical-debt

**Comment by josephj11** [comment]
When you file one of these, it would be helpful if you could suggest appropriate labels for it (if you can't set the labels yourself yet). Especially if something is an easy fix or a good beginner issue.

Maybe a suggested labels item should be added to our issue reporting form.

It would be beneficial to have as few unlabelled issues as possible and the OP is in tihe best position to _suggest_ these although someone who may have more perspective needs to have the final say.

I assume you have some understanding of what this issue entails and are not just acting on a comment in the code that may or may not have aged well.

**Comment by josephj11** [comment]
If this is technical debt, maybe it's not really an "enhancement". (I just added that label, but IDK what, if anything, should be done on our issue reporting form to support it.)

**Comment by Elliria** [comment]
> When you file one of these, it would be helpful if you could suggest appropriate labels for it (if you can't set the labels yourself yet). Especially if something is an easy fix or a good beginner issue.

Okay, I'll do that from now on.
 
> Maybe a suggested labels item should be added to our issue reporting form.

I can add a prompt for those in the issue template. Would you like it to be an open-ended question without prompting the user with the existing labels? Or would you prefer check-boxes that the user can pick from?

I realize there are a lot of labels, but check-boxes wouldn't look bad. I did a quick test by adding them to the bottom of my dummy repository's example issue template. You can see the example by creating a new issue [here](https://github.com/Elliria/hello-world/issues) and scrolling to the bottom of the issue report form.
 
> I assume you have some understanding of what this issue entails and are not just acting on a comment in the code that may or may not have aged well.

Nope. I'm acting on a **TODO** comment in the code. My only understanding is that for some reason, the Namespace had to be in a tuple until AutoKey's  minimum Python version reached at least 3.6, at which point it should be converted to a class. Since AutoKey meets the requirement, I figured it might not be a bad idea to turn that **TODO** into an issue so that it's not forgotten about. After all, [now that we're on CodeTriage](https://www.codetriage.com/autokey/autokey), perhaps a well-intended person will be assigned this issue and will take care of it (or I'll figure it out - whichever comes first).

> If this is technical debt, maybe it's not really an "enhancement". (I just added that label, but IDK what, if anything, should be done on our issue reporting form to support it.)

Yeah, it was the best of the bunch. What do you think of **Development** or **Code cleanup** as a more suitable choice in the "What type of issue is this?" drop-down in the issue template?

**Comment by Elliria** [comment]
> When you file one of these, it would be helpful if you could suggest appropriate labels for it (if you can't set the labels yourself yet). Especially if something is an easy fix or a good beginner issue.

Okay, I'll do that from now on.
 
> Maybe a suggested labels item should be added to our issue reporting form.

I can add a prompt for those in the issue template. Would you like it to be an open-ended question without prompting the user with the existing labels? Or would you prefer check-boxes that the user can pick from?

I realize there are a lot of labels, but check-boxes wouldn't look bad. I did a quick test by adding them to the bottom of my dummy repository's example issue template. You can see the example by creating a new issue [here](https://github.com/Elliria/hello-world/issues) and scrolling to the bottom of the issue report form.
 
> I assume you have some understanding of what this issue entails and are not just acting on a comment in the code that may or may not have aged well.

Nope. I'm acting on a **TODO** comment in the code. My only understanding is that for some reason, the Namespace had to be in a tuple until AutoKey's  minimum Python version reached at least 3.6, at which point it should be converted to a class. Since AutoKey meets the requirement, I figured it might not be a bad idea to turn that **TODO** into an issue so that it's not forgotten about. After all, [now that we're on CodeTriage](https://www.codetriage.com/autokey/autokey), perhaps a well-intended person will be assigned this issue and will take care of it (or I'll figure it out - whichever comes first).

> If this is technical debt, maybe it's not really an "enhancement". (I just added that label, but IDK what, if anything, should be done on our issue reporting form to support it.)

Yeah, it was the best of the bunch. What do you think of **Development** or **Code cleanup** as a more suitable choice in the "What type of issue is this?" drop-down in the issue template?

**Comment by josephj11** [comment]
> > When you file one of these, it would be helpful if you could suggest appropriate labels for it (if you can't set the labels yourself yet). Especially if something is an easy fix or a good beginner issue.
> 
> Okay, I'll do that from now on.
> 
> > Maybe a suggested labels item should be added to our issue reporting form.
> 
> I can add a prompt for those in the issue template. Would you like it to be an open-ended question without prompting the user with the existing labels? Or would you prefer check-boxes that the user can pick from?
> 
> I realize there are a lot of labels, but check-boxes wouldn't look bad. I did a quick test by adding them to the bottom of my dummy repository's example issue template. You can see the example by creating a new issue [here](https://github.com/Elliria/hello-world/issues) and scrolling to the bottom of the issue report form.
> 
That's a good idea, but:
There are a number of labels a new reporter should never select like won't fix, unsupported version, or duplicate, so a reduced list would be better, if possible.
There needs to be an "other" with a fill in the blank as one of the choices or as a searate item.
> > I assume you have some understanding of what this issue entails and are not just acting on a comment in the code that may or may not have aged well.
> 
> Nope. I'm acting on a **TODO** comment in the code. My only understanding is that for some reason, the Namespace had to be in a tuple until AutoKey's minimum Python version reached at least 3.6, at which point it should be converted to a class. Since AutoKey meets the requirement, I figured it might not be a bad idea to turn that **TODO** into an issue so that it's not forgotten about. After all, [now that we're on CodeTriage](https://www.codetriage.com/autokey/autokey), perhaps a well-intended person will be assigned this issue and will take care of it (or I'll figure it out - whichever comes first).
I'm ambivalent about this. My gut feeling is that the **TODO:** is good enough as is. You're turning a "maybe" into a "yes". That should only be done when you can really justify the "yes". Maybe, by the time someone gets to this, the whole section of code will need a rewrite or  an even better data structure will suggest itself. That requires understanding the issue and the surrounding code.

Don't forget that the developer who added this probably knew what they were doing and could have openned an issue for it theselves if they thought it was justified.

I would translate **TODO:** as: "If you're here anyway making substantial changes, _think_ about fixing this too."
rather than as "This needs to be done."

Of course, it depends on why it needs to be done. Maybe a planned feature will need it or something is depreciated and will eventually break if not fixed. If  something like this is not indicated in the comment, then you have to actually understand the issue to know what to do and how important/how pressing it is to do it.
> 
> > If this is technical debt, maybe it's not really an "enhancement". (I just added that label, but IDK what, if anything, should be done on our issue reporting form to support it.)
> 
> Yeah, it was the best of the bunch. What do you think of **Development** or **Code cleanup** as a more suitable choice in the "What type of issue is this?" drop-down in the issue template?

**technical debt** seems better to me. It's more inclusive. (Now, you're adding Caps back in too, LOL.) If someone doesn't know what technical debt is, they shouldn't be selecting it or anything similar as a choice (especially when it's a quick internet search to look it up if needed.)

**Comment by josephj11** [comment]
I'm getting the code triage suggestions now. It seems to select anything that's open. The last one I got was a quite advanced issue, but I looked at it anyway and may have thought of something. See my post on Gitter.

Maybe they're looking for a specific label that we don't use, so they select anything.

**Comment by Elliria** [comment]
> That's a good idea, but: There are a number of labels a new reporter should never select like won't fix, unsupported version, or duplicate, so a reduced list would be better, if possible. 

No problem. Here's the full list of issue labels:
* 0.96.1
* autokey triggers
* autokey-gtk
* autokey-qt
* beta
* bug
* critical
* development
* documentation
* duplicate
* easy fix
* enhancement
* good first issue
* help-wanted
* installation/configuration
* invalid
* low-priority
* phrase expansion
* scripting
* technical debt
* unsupported version
* upstream bug
* user interface
* user support
* wontfix

I'll take a stab at which ones should be in the form. Feel free to critique and correct this list:
* autokey triggers
* autokey-gtk
* autokey-qt
* beta
* bug
* critical
* development
* documentation
* enhancement
* installation/configuration
* phrase expansion
* scripting
* unsupported version
* user interface

> There needs to be an "other" with a fill in the blank as one of the choices or as a searate item.

The **other** with a fill-in-the-blank is a nice idea, but isn't possible with GitHub. The **other** label also won't make sense unless we have such a label. Would you be adding one? If so, we can add it to the list with, perhaps, a "(please describe below)" note next to it, although the note might not be necessary. After all, if they're choosing **other**, that's already a red flag to you that this is such an unusual issue that it can't be corralled into any of our existing categories and will need to be scrutinized anyway.

> > I'm ambivalent about this. My gut feeling is that the **TODO:** is good enough as is. You're turning a "maybe" into a "yes". That should only be done when you can really justify the "yes".

Isn't it justified by us having reached Python version 3.6 or above? 

> Maybe, by the time someone gets to this, the whole section of code will need a rewrite or  an even better data structure will suggest itself. That requires understanding the issue and the surrounding code.

Okay.

> Don't forget that the developer who added this probably knew what they were doing and could have openned an issue for it theselves if they thought it was justified.

Okay.
 
> I would translate **TODO:** as: "If you're here anyway making substantial changes, _think_ about fixing this too." rather than as "This needs to be done."

Okay.
 
> Of course, it depends on why it needs to be done. Maybe a planned feature will need it or something is depreciated and will eventually break if not fixed. If something like this is not indicated in the comment, then you have to actually understand the issue to know what to do and how important/how pressing it is to do it.

Okay. I'll close this issue.
 
> > Yeah, it was the best of the bunch. What do you think of **Development** or **Code cleanup** as a more suitable choice in the "What type of issue is this?" drop-down in the issue template?
> 
> **technical debt** seems better to me. It's more inclusive.

That wasn't a choice in the list and I would vote against making it a choice. It's going to be difficult for most people to understand what something like that means.

> (Now, you're adding Caps back in too, LOL.)

Ah, you've been tricked. That list is from the "What type of issue is this?" question at the top of the issue template. The suggested types in its drop-down menu use capital letters.

We were also discussing adding a new question to the issue template that asks the user to choose a label or labels. Those are all lower-case (except for the **User interface** label, which needs to be made all lower-case).

It occurs to me that rather than adding a section for labels, we could replace the choices in the "What type of issue is this?" question at the top of the form with a whittled-down version of our list of labels and give the user check-boxes instead of a drop-down menu for that question and be done with it. The user will choose an issue type and you'll know that their answer to that question actually gives you the label name(s).

> If someone doesn't know what technical debt is, they shouldn't be selecting it or anything similar as a choice (especially when it's a quick internet search to look it up if needed.)

It would still be a stumbling-block for many and is intended only for developers. Trust your developers to get to know how you like things done and to do them that way. Hopefully we'll all remember to give you some extra labels (like **duplicate** or **technical debt**, etc.) in the bottom section (or wherever) of the issue form and if we don't, feel free to give us a nudge.

**Comment by Elliria** [comment]
> I'm getting the code triage suggestions now. It seems to select anything that's open. The last one I got was a quite advanced issue, but I looked at it anyway and may have thought of something. See my post on Gitter.

Will do. I'm also getting some that are too advanced for me.
 
> Maybe they're looking for a specific label that we don't use, so they select anything.

No idea, but they actually credited me with having done one, although I didn't do any of the ones they suggested. They must have counted a commit or PR that I did as activity.

**Comment by josephj11** [comment]
> > That's a good idea, but: There are a number of labels a new reporter should never select like won't fix, unsupported version, or duplicate, so a reduced list would be better, if possible.
> 
> No problem. Here's the full list of issue labels:
> 
> * 0.96.1
> * autokey triggers
> * autokey-gtk
> * autokey-qt
> * beta
> * bug
> * critical
> * development
> * documentation
> * duplicate
> * easy fix
> * enhancement
> * good first issue
> * help-wanted
> * installation/configuration
> * invalid
> * low-priority
> * phrase expansion
> * scripting
> * technical debt
> * unsupported version
> * upstream bug
> * user interface
> * user support
> * wontfix
> 
> I'll take a stab at which ones should be in the form. Feel free to critique and correct this list:
> 
> * autokey triggers
> * autokey-gtk
> * autokey-qt
> * beta
> * bug
> * critical
> * development
> * documentation
> * enhancement
> * installation/configuration
> * phrase expansion
> * scripting
> * unsupported version
> * user interface
> 

Perfect except no unsupported version unless you have a reason you want it there.

> > There needs to be an "other" with a fill in the blank as one of the choices or as a searate item.
> 
> The **other** with a fill-in-the-blank is a nice idea, but isn't possible with GitHub. The **other** label also won't make sense unless we have such a label. Would you be adding one? If so, we can add it to the list with, perhaps, a "(please describe below)" note next to it, although the note might not be necessary. After all, if they're choosing **other**, that's already a red flag to you that this is such an unusual issue that it can't be corralled into any of our existing categories and will need to be scrutinized anyway.
> 

Not sure what this is about. These are "suggested" labels. not actual ones, so if one of the choices is "trivia", there's no reason for a corresponding "trivia" issue label to be created.

Since my original idea won't work, I would either add "Other" to the buttons or just make selecting one or more of the buttons optional and have a separate item below the list labelled "Other Label" (or something better) with a user entry text box.

> > > I'm ambivalent about this. My gut feeling is that the **TODO:** is good enough as is. You're turning a "maybe" into a "yes". That should only be done when you can really justify the "yes".
> 
> Isn't it justified by us having reached Python version 3.6 or above?

That would be true if it no longer worked the old way. This is a classic "if it ain't broke, don't fix it."

Why bother unless you intend to build upon it with new code, etc.?

Every fix has to be thought about and tested.

Later, if anything breaks in this file, this change will have to be ruled out as the cause. Changes to software are not "set and forget".

The goal is to get the maximum benefit with the minimum effort. We would want to answer the questions:

Does making this change contribute anything to the actual software functionaliy, quality, or performance?

Does it make it easier to understand or modify in the future?

Does it bring the softiware into compliance with project coding guidelines (which, AFAIK, we don't have other than the PEPs which I have never read),  etc. 

How do I know that this suggested change is actually an improvement/good idea as opposed to someone's passing thought or their personal coding style preferences...?

How do I know it's not a bad idea whose implications/consequences weren't fully considered?

Or, does it just add to cognitive and testing overhead and the potential defect/bug surface?

> 
> > Maybe, by the time someone gets to this, the whole section of code will need a rewrite or  an even better data structure will suggest itself. That requires understanding the issue and the surrounding code.
> 
> Okay.
> 
> > Don't forget that the developer who added this probably knew what they were doing and could have openned an issue for it theselves if they thought it was justified.
> 
> Okay.
> 
> > I would translate **TODO:** as: "If you're here anyway making substantial changes, _think_ about fixing this too." rather than as "This needs to be done."
> 
> Okay.
> 
> > Of course, it depends on why it needs to be done. Maybe a planned feature will need it or something is depreciated and will eventually break if not fixed. If something like this is not indicated in the comment, then you have to actually understand the issue to know what to do and how important/how pressing it is to do it.
> 
> Okay. I'll close this issue.
> 
> > > Yeah, it was the best of the bunch. What do you think of **Development** or **Code cleanup** as a more suitable choice in the "What type of issue is this?" drop-down in the issue template?
> > 
> > 
> > **technical debt** seems better to me. It's more inclusive.
> 
> That wasn't a choice in the list and I would vote against making it a choice. It's going to be difficult for most people to understand what something like that means.

Then, hopefully, most people will not select it or you could change it to "Technical Debt (things  that  work, but need to  be done better)" or "Technical Debt (if you don't know what this is, don't select it.)" LOL

While I'm thinking of it (just in case it wasn't obvious), the above is not a radio button list, multiple selections need to be allowed.

> 
> > (Now, you're adding Caps back in too, LOL.)
> 
> Ah, you've been tricked. That list is from the "What type of issue is this?" question at the top of the issue template. The suggested types in its drop-down menu use capital letters.
> 

OK, my mistake.

> We were also discussing adding a new question to the issue template that asks the user to choose a label or labels. Those are all lower-case (except for the **User interface** label, which needs to be made all lower-case).
> 

Oops. Fixed it.

> It occurs to me that rather than adding a section for labels, we could replace the choices in the "What type of issue is this?" question at the top of the form with a whittled-down version of our list of labels and give the user check-boxes instead of a drop-down menu for that question and be done with it. The user will choose an issue type and you'll know that their answer to that question actually gives you the label name(s).
> 

That might work, but I'd kind of like to know the "main reason" they're filing the issue at first glance, not just all the things that apply. If there's a way to do that as well, it would be great.

> > If someone doesn't know what technical debt is, they shouldn't be selecting it or anything similar as a choice (especially when it's a quick internet search to look it up if needed.)
> 
> It would still be a stumbling-block for many and is intended only for developers. Trust your developers to get to know how you like things done and to do them that way. Hopefully we'll all remember to give you some extra labels (like **duplicate** or **technical debt**, etc.) in the bottom section (or wherever) of the issue form and if we don't, feel free to give us a nudge.

That's reasonable. BTW, it's "us", not me. It's your project as much as it is mine.

**Comment by josephj11** [comment]
> > I'm getting the code triage suggestions now. It seems to select anything that's open. The last one I got was a quite advanced issue, but I looked at it anyway and may have thought of something. See my post on Gitter.
> 
> Will do. I'm also getting some that are too advanced for me.
> 
> > Maybe they're looking for a specific label that we don't use, so they select anything.
> 
> No idea, but they actually credited me with having done one, although I didn't do any of the ones they suggested. They must have counted a commit or PR that I did as activity.

I think just clicking on the link gets you "credit". It would be a lot more work  for them to analyse your actual activity and whether what you did was actually helpful is up to the target project team, not to them.

**Comment by Elliria** [comment]
> Perfect except no unsupported version unless you have a reason you want it there.

I had no reason for it, so here's the updated list that will be offered as a checklist so the user can pick as many as he or she likes:
* autokey triggers
* autokey-gtk
* autokey-qt
* beta
* bug
* critical
* development
* documentation
* enhancement
* installation/configuration
* phrase expansion
* scripting
* technical debt
* user interface

And right beneath it, we would have: 

Other custom label(s):
[a text box goes here]

The plan is to do what I did last time and make the updated issue template in my dummy repository so that we can see it and try it and see what we think before making the change in the AutoKey repository.

> Then, hopefully, most people will not select it or you could change it to "Technical Debt (things that work, but need to be done better)" or "Technical Debt (if you don't know what this is, don't select it.)" LOL

I added it into the list above as is and we can see if we get any reactions, if it's just accepted as being there, or if it gets used. I'm certain I'll be using it.
 
In reference to not having a separate section for labels and using the issue-type question for them:
 
> That might work, but I'd kind of like to know the "main reason" they're filing the issue at first glance, not just all the things that apply. If there's a way to do that as well, it would be great.

Okay, we can leave the "What type of issue is this?" drop-down as is and add the label section beneath it.
 
> BTW, it's "us", not me. It's your project as much as it is mine.

You're right, of course, although you've been with it longer than me, so I'll always think of you as having seniority.

**Comment by josephj11** [comment]
Great!

Do you think "critical" makes sense for people reporting issues? I'm not sure. What's critical is a value judgement and requires more perspective than many users have.

I don't really like "Other custom label(s):". I came up with "Additional issue characterizations" which says what I mean, but is probably way to dense for most people.

**Comment by Elliria** [comment]
> Do you think "critical" makes sense for people reporting issues? I'm not sure. What's critical is a value judgement and requires more perspective than many users have.

I kind of figured it would be useful for times when the program won't run at all or all phrases/scripts/abbreviations/etc. have been lost, or any other kind of "OMG" moment, but we can leave it off if you like.
 
> I don't really like "Other custom label(s):". I came up with "Additional issue characterizations" which says what I mean, but is probably way to dense for most people.

Ah, I was thinking of calling the new section "Suggested labels" and if that's what it's called, the next section asking for other custom labels would make sense. Regardless of what we call the section, we should be able to [link to them](https://github.com/autokey/autokey/labels) from within the issue template, so that the user could see the kind of thing we're asking for. We can also add explanatory text to that section the way we do for some of the other questions on that form.

**Comment by josephj11** [comment]
"critical" - I'm sitting with that for now. Might as well leave it in and see if it gets abused or ignored.

Your other suggestions are good as well. I don't want the form to get too cluttered or busy, so additions should be short. If people stop reading and start scanning/skimming then it hurts more than it helps.

Would collapsible text work here? There could be a few "More,,,"/"Less..." tags so the info is there on demand, but doesn't get in the way.

I expect yaml doesn't support tooltips, but they would be a nice way to add information on demand.

Yaml is nice, but it seems quite dated/limited compared to the UI/UX other tools offer.

**Comment by josephj11** [comment]
I think what's bugging me, is that, other than a few developers, nobody cares about "labels" or will even search on them. What they care about is "What kind of issue is this?" and "How much do I care about it getting fixed?" "What can I do to convince the developers/community to get this implemented?". That's why I started with "characterizations".  It just seems like too big a word to use. "Choose one or more terms that describe this issue" might be better.

"Label" describes a technical implementation detail/artifact of GitHub.

**Comment by Elliria** [comment]
I've started a tentative mock-up of the [AutoKey issue template](https://github.com/autokey/autokey/blob/master/.github/ISSUE_TEMPLATE/bug.yaml) in my dummy repository. Note that the [dummy issue template](https://github.com/Elliria/dummy/blob/main/.github/ISSUE_TEMPLATE/bug.yaml) is identical to the one in the AutoKey repository except for these additions that we're working on. Once the dummy's template is the way we like it, we can just copy its contents to AutoKey's `bug.yaml` file. You can try out the dummy's template [here](https://github.com/Elliria/dummy/issues). I also enabled [Discussions](https://github.com/Elliria/dummy/discussions) in the dummy repository in case you'd like to continue this there.

**Comment by Elliria** [comment]
> Would collapsible text work here?

No idea, but I'll experiment with it in the dummy repository.

> I expect yaml doesn't support tooltips, but they would be a nice way to add information on demand.

No, [it doesn't](https://learnxinyminutes.com/docs/yaml/), but I'd like those, too.
 
> Yaml is nice, but it seems quite dated/limited compared to the UI/UX other tools offer.

Yeah, it's very limited. Still, we're lucky to have it for our fancy interactive issue report form.
