### ISSUE TITLE
Can't install Autokey on Ubuntu 17.04 (The repository does not have a Release file)

### ISSUE THREAD

**Issue by zaughon** [autokey/autokey#81]
## Classification:
Bug/Enhancement

## Reproducibility:
Always

## Summary
Trying to install Autokey on 17.04 gives: 
E: The repository 'http://ppa.launchpad.net/troxor/autokey/ubuntu zesty Release' does not have a Release file.

Any plans on adding 17.04 (Zesty Zapus) to the repository?

## Steps to Reproduce
On Ubuntu 17.04: 
sudo add-apt-repository ppa:troxor/autokey
sudo apt update
sudo apt install autokey-gtk

## Expected Results
Autokey should be installed

## Actual Results
Hit:1 http://dk.archive.ubuntu.com/ubuntu zesty InRelease
Hit:2 http://dk.archive.ubuntu.com/ubuntu zesty-updates InRelease                          
Hit:3 http://dk.archive.ubuntu.com/ubuntu zesty-backports InRelease                        
Hit:4 http://archive.canonical.com/ubuntu zesty InRelease                                  
Get:5 http://security.ubuntu.com/ubuntu zesty-security InRelease [89.2 kB]
Hit:6 http://ppa.launchpad.net/hluk/copyq/ubuntu zesty InRelease    
Ign:7 http://ppa.launchpad.net/troxor/autokey/ubuntu zesty InRelease                 
Hit:8 http://ppa.launchpad.net/webupd8team/atom/ubuntu zesty InRelease               
Err:9 http://ppa.launchpad.net/troxor/autokey/ubuntu zesty Release
  404  Not Found
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/troxor/autokey/ubuntu zesty Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

## Version
None

Installed via: (PPA, pip, …).
Unable to install at all

Distro:
Ubuntu 17.04 (Zesty Zapus)

## Notes

**Comment by troxor** [comment]
Zesty packages are on the horizon, see #80 for a workaround.

**Comment by Mathspy** [comment]
How about Artful packages?

**Comment by davduf** [comment]
How About Ubuntu packages ? Can't install AutoKey :-)

`E: The repository 'http://ppa.launchpad.net/troxor/autokey/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`


My best

**Comment by luziferius** [comment]
For now, we have an up-to-date PPA, supporting bionic (18.04).
17.04 has reached its end of life, so closing this.
