### ISSUE TITLE
Update the Google Archive

### ISSUE THREAD

**Issue by Elliria** [autokey/autokey#814]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Wayland

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Documentation

### Choose one or more terms that describe this issue:

- [ ] autokey triggers
- [ ] autokey-gtk
- [ ] autokey-qt
- [ ] beta
- [ ] bug
- [ ] critical
- [ ] development
- [X] documentation
- [ ] enhancement
- [X] installation/configuration
- [ ] phrase expansion
- [ ] scripting
- [x] technical debt
- [ ] user interface

### Other terms that describe this issue if not provided above:

archive, hosting

### Which AutoKey GUI did you use?

None

### Can you briefly describe the issue?

The Google Archive contains some outdated information and is missing several releases. We might also want to add a zipped copy of the legacy documentation to the archive before it gets replaced with the new documentation.

### Can the issue be reproduced?

None

### What should have happened?

Recent information and files should be available.

### What actually happened?

Outdated information is available and several files are missing.

### Anything else?

The most recent [AutoKey release](https://github.com/autokey/autokey/releases) available in [the Google Archive](https://code.google.com/archive/p/autokey/downloads?page=1) is 0.90.4 and these releases should be added:

* [0.96.0](https://github.com/autokey/autokey/archive/refs/tags/v0.96.0.tar.gz)
* [0.96.0-beta.10](https://github.com/autokey/autokey/archive/refs/tags/v0.96.0-beta.10.tar.gz)
* [0.96.0-beta.9](https://github.com/autokey/autokey/archive/refs/tags/v0.96.0-beta.9.tar.gz)
* [0.96.0-beta.8](https://github.com/autokey/autokey/archive/refs/tags/v0.96.0-beta.8.tar.gz)
* [0.96.0-beta.7](https://github.com/autokey/autokey/archive/refs/tags/v0.96.0-beta.7.tar.gz)
* [0.96.0-beta.6](https://github.com/autokey/autokey/archive/refs/tags/v0.96.0-beta.6.tar.gz)
* [0.96.0-beta.5](https://github.com/autokey/autokey/archive/refs/tags/v0.96.0-beta.5.tar.gz)
* [0.96.0-beta.4](https://github.com/autokey/autokey/archive/refs/tags/v0.96.0-beta.4.tar.gz)
* [0.96.0-beta.3](https://github.com/autokey/autokey/archive/refs/tags/v0.96.0-beta.3.tar.gz)
* [0.96.0-beta.2](https://github.com/autokey/autokey/archive/refs/tags/v0.96.0-beta.2.tar.gz)
* [0.96.0-beta.1](https://github.com/autokey/autokey/archive/refs/tags/v0.96.0-beta.1.tar.gz)
* [0.95.10](https://github.com/autokey/autokey/archive/refs/tags/v0.95.10.tar.gz)
* [0.95.9](https://github.com/autokey/autokey/archive/refs/tags/v0.95.9.tar.gz)
* [0.95.8](https://github.com/autokey/autokey/archive/refs/tags/v0.95.8.tar.gz)
* [0.95.7](https://github.com/autokey/autokey/archive/refs/tags/v0.95.7.tar.gz)
* [0.95.6](https://github.com/autokey/autokey/archive/refs/tags/v0.95.6.tar.gz)
* [0.95.5](https://github.com/autokey/autokey/archive/refs/tags/v0.95.5.tar.gz)
* [0.95.4](https://github.com/autokey/autokey/archive/refs/tags/v0.95.4.tar.gz)
* [0.95.3](https://github.com/autokey/autokey/archive/refs/tags/v0.95.3.tar.gz)
* [0.95.2](https://github.com/autokey/autokey/archive/refs/tags/v0.95.2.tar.gz)
* [0.95.1](https://github.com/autokey/autokey/archive/refs/tags/v0.95.1.tar.gz)
* [0.95.0](https://github.com/autokey/autokey/archive/refs/tags/v0.95.0.tar.gz)
* [0.94.1](https://github.com/autokey/autokey/archive/refs/tags/v0.94.1.tar.gz)
* [0.94.0](https://github.com/autokey/autokey/archive/refs/tags/v0.94.0.tar.gz)
* [0.93.10](https://github.com/autokey/autokey/archive/refs/tags/v0.93.10.tar.gz)
* [0.93.9](https://github.com/autokey/autokey/archive/refs/tags/v0.93.9.tar.gz)
* [0.93.8](https://github.com/autokey/autokey/archive/refs/tags/v0.93.8.tar.gz)
* [0.93.7](https://github.com/autokey/autokey/archive/refs/tags/v0.93.7.tar.gz)

*Note that each file name will need to be changed to match the naming conventions used by the rest of the files that we already have hosted on Google Archive.*

We might also want to [download a zipped copy of the legacy documentation](https://github.com/autokey/autokey.github.io/archive/refs/heads/master.zip) and add it to the Google Archive before it gets replaced with the new documentation.

The introductory text shown on [the main Google Archive page](https://code.google.com/archive/p/autokey/) is outdated and should be updated.

The wiki pages in [the Google Archive](https://code.google.com/archive/p/autokey/wikis) are also outdated and several of them are missing.

**Comment by josephj11** [comment]
Not sure where you're going with this. If you have a copy of the Google archive somewhere, you can do tihings like this, but the archive itself has been read-only for a few years.

The archive was created when Google discontinued offerring the code.google service so that all the content would not be lost. It's amazing they still have it online. (They're not entirely evil.)

**Comment by Elliria** [comment]
I didn't realize that. Sorry for the noise.

And, yeah, it's cool that it's still up.
