### ISSUE TITLE
Update the documentation link on the AutoKey page

### ISSUE THREAD

**Issue by Elliria** [autokey/autokey#838]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Xorg

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Documentation

### Choose one or more terms that describe this issue:

- [ ] autokey triggers
- [ ] autokey-gtk
- [ ] autokey-qt
- [ ] beta
- [ ] bug
- [ ] critical
- [ ] development
- [X] documentation
- [ ] enhancement
- [ ] installation/configuration
- [ ] phrase expansion
- [ ] scripting
- [ ] technical debt
- [ ] user interface

### Other terms that describe this issue if not provided above:

easy fix

### Which AutoKey GUI did you use?

None

### Can you briefly describe the issue?

The URL in the upper right corner of the [AutoKey](https://github.com/autokey/autokey) page needs to be updated.

### Can the issue be reproduced?

Always

### What are the steps to reproduce the issue?

Visit the [AutoKey](https://github.com/autokey/autokey) page and hover the mouse over the link in the upper right corner.

### What should have happened?

The link should lead to the [new documentation](https://autokey.github.io/index.html).

### What actually happened?

The link leads to the [old documentation](https://autokey.github.io/autokey).

**Comment by josephj11** [comment]
Good catch. Done.
