### ISSUE TITLE
The create_single_phrase tox test fails

### ISSUE THREAD

**Issue by Elliria** [autokey/autokey#860]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Xorg

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

None

### Choose one or more terms that describe this issue:

- [ ] autokey triggers
- [ ] autokey-gtk
- [ ] autokey-qt
- [ ] beta
- [ ] bug
- [ ] critical
- [X] development
- [ ] documentation
- [ ] enhancement
- [ ] installation/configuration
- [ ] phrase expansion
- [ ] scripting
- [ ] technical debt
- [ ] user interface

### Other terms that describe this issue if not provided above:

testing

### Which Linux distribution did you use?

Kubuntu 22.04 LTS

### Which AutoKey GUI did you use?

None

### Which AutoKey version did you use?

AutoKey 0.96.0 in development.

### How did you install AutoKey?

Cloned from GitHub **development** branch.

### Can you briefly describe the issue?

The `tox -- tests/create_single_phrase.py` test fails with a name error that "engine" is not defined.

### Can the issue be reproduced?

Always

### What are the steps to reproduce the issue?

1. Open a terminal window in a directory you'd like to put a cloned directory of AutoKey into.
2. Clone the AutoKey **develop** branch:
     ```
     git clone --branch develop --single-branch https://github.com/autokey/autokey.git
     ```
3. Change to the directory you just created:
   ```
   cd autokey
   ```
4. Run a tox test on the [create_single_phrase.py](https://github.com/autokey/autokey/blob/develop/tests/create_single_phrase.py) file:
   ```
   tox -- tests/create_single_phrase.py
   ```

### What should have happened?

All tests should pass.

### What actually happened?

The test failed with a name error for "engine" being undefined:
```
$ tox -- tests/create_single_phrase.py
GLOB sdist-make: /home/elliria/Desktop/autokey/setup.py
test create: /home/elliria/Desktop/autokey/.tox/test
test installdeps: pytest, pytest-cov, pytest-xvfb, pyhamcrest>=1.8.1, PyQt5, dbus-python, PyGObject
test inst: /home/elliria/Desktop/autokey/.tox/.tmp/package/1/autokey-0.96.0b9.zip
test installed: autokey @ file:///home/elliria/Desktop/autokey/.tox/.tmp/package/1/autokey-0.96.0b9.zip,coverage==7.2.5,dbus-python==1.3.2,exceptiongroup==1.1.1,iniconfig==2.0.0,packaging==23.1,pluggy==1.0.0,pycairo==1.23.0,PyGObject==3.44.1,PyHamcrest==2.0.4,pyinotify==0.9.6,PyQt5==5.15.9,PyQt5-Qt5==5.15.2,PyQt5-sip==12.12.1,pytest==7.3.1,pytest-cov==4.0.0,pytest-xvfb==2.0.0,python-xlib==0.33,PyVirtualDisplay==3.0,six==1.16.0,tomli==2.0.1
test run-test-pre: PYTHONHASHSEED='4202582772'
test run-test: commands[0] | pytest --no-cov tests/create_single_phrase.py
=================================================================== test session starts ====================================================================
platform linux -- Python 3.10.6, pytest-7.3.1, pluggy-1.0.0
cachedir: .tox/test/.pytest_cache
rootdir: /home/elliria/Desktop/autokey
configfile: setup.cfg
plugins: cov-4.0.0, xvfb-2.0.0
collected 0 items / 1 error                                                                                                                                

========================================================================== ERRORS ==========================================================================
______________________________________________________ ERROR collecting tests/create_single_phrase.py ______________________________________________________
tests/create_single_phrase.py:4: in <module>
    args = engine.get_macro_arguments()
E   NameError: name 'engine' is not defined
--------------------------------------------------------------------- Captured stdout ----------------------------------------------------------------------
running
================================================================= short test summary info ==================================================================
ERROR tests/create_single_phrase.py - NameError: name 'engine' is not defined
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
===================================================================== 1 error in 0.05s =====================================================================
ERROR: InvocationError for command /home/elliria/Desktop/autokey/.tox/test/bin/pytest --no-cov tests/create_single_phrase.py (exited with code 2)
_________________________________________________________________________ summary __________________________________________________________________________
ERROR:   test: commands failed
```

**Comment by josephj11** [comment]
That's weird. The engine module is a normal part of AutoKey (in its namespace?), so if that's not found, I would expect other modules should be missing as well. Does there need to be an import statement somewhere? Is the Python path (the thing that tells Python where to look for imports, etc.) set correctly?

**Comment by Elliria** [comment]
No idea. I tried `from autokey.scripting import Engine` and `from autokey.scripting import Engine as engine` and neither of them fixed it. Other things may also need to be imported to make either of those work. I'll mess with it. It shouldn't take too long. It's just here as a reminder that it needs to be fixed.

**Comment by Elliria** [comment]
If I add this to the file:
```python
import autokey.service
from autokey.scripting import Engine as engine
```
then I get this error instead:
```bash
TypeError: Engine.get_macro_arguments() missing 1 required positional argument: 'self'
```
I'm not sure what it would like as an argument. Also, the `# flake8: noqa: F821` line indicates that it wants the file to be ignored by the linter. Perhaps it also indicates that it wants the file to be ignored by `tox`, but I'm not certain of that. Feel free to jump in, @sebastiansam55 or @BlueDrink9, if either of you know.

If it's supposed to be ignored by `tox`, then it was user-error on my part for trying to `tox` it to begin with, this issue can then be closed, and a note to that effect needs to be added into the developer notes.

**Comment by BlueDrink9** [comment]
This isn't a standalone test so not sure why you're trying to run it. That being said, your fix suggests there may have been a dev (I.e me) screwup somewhere… either that or this is meant to be a fixture.

What's your end goal?

**Comment by BlueDrink9** [comment]
Also can't recall why the linter has been told to ignore it, linter would have caught this error

**Comment by BlueDrink9** [comment]
Oh looking at it now I remember. That isn't a test, it's a file used to test macros. As in, it's the script a test macro tries to run. The macro defines engine.

Actual tests all start with `test_`.

**Comment by josephj11** [comment]
Aside from all of that, the file on my system is called engine.py - no caps.

**Comment by Elliria** [comment]
Thanks for looking into it, @BlueDrink9, and for explaining it. My end goal is always to learn. I tend to predominantly use the **slam**, **blunder**, and **stumble** methods of learning. I either slam against a wall full-tilt or blunder around for a while or stumble across the answer(s) unexpectedly. You caught me blundering. From now on, I'll remember that tests start with **test_**. That's a nugget of pure gold.

About the two lines I had tried out as a fix, should I make that change or should we leave the file as it is since it's not a test failure after all?

Thanks, too, @josephj11, for your feedback. I think the capital E is from the **Engine** class.

**Comment by BlueDrink9** [comment]
Outstanding, better to try and blunder safely that to remain ignorant or never try.

No change, though feel free to PR a better comment.

**Comment by Elliria** [comment]
It's all slowly sinking in. The stuff that seems to stick the best is the times when everything goes horribly wrong. Those are memorable.

> No change, though feel free to PR a better comment.

Like by changing `# This script is used to test script macros only.` to something that makes it clear that the script is used by other scripts that test script macros?

**Comment by josephj11** [comment]
Isn't it "pythonic" to name such functions/scripts with an underscore prefix to indicate they're for internal use...?

**Comment by Elliria** [comment]
Yes, but that won't help here since the actual tests and the files they use are all for internal use. It's incredibly handy to know that only **test_** files get tested, though.
