### ISSUE TITLE
Mouse script doesn't work properly

### ISSUE THREAD

**Issue by Linko-3D** [autokey/autokey#88]
I have the latest version 0.93.10.

The mouse script doesn't work properly in the game Dota 2, the game is free and to test i go in the Heroes tab then Demo Mode (did some quick tests on GIMP and it doesn't work well too). My goal is to set automatically some patrol points on the mini map (there is one map) with the shift key holded.

I use this command: mouse.click_absolute(x, y, button)

When i enter an X and Y coordinate it only works if i enter the coordinate of an icon to use an ability or buy an item, but if i enter a coordinate of something in the 3D view or (and it's what i want) somewhere on the minimap the click is always done under my cursor's current position instead of the coordinates like if i was just clicking with my own mouse. I have tested all the different display modes: Desktop-Friendly Fullscreen (the one i am using), Windowed and Borderless, Window but it doesn't solve the problem it keeps clicking under my cursor. I run the game in 1920x1080.

I have seen some issue, maybe it's similar in Dota 2, in GIMP the left click on a coordinate only works if i had a sleep 0.1 second before the left click but for the right click that opens a pop-up menu in GIMP it always occur at the mouse current position. Maybe there is not enough delay between the mouse move and the click.

To make it work and have more control I suggest to split it into two scripts: one to move the cursor at an XY coordinate on the script or relative to the current position and another one to click so we can adjust a delay in between. And a third script to get the current X mouse position and current Y so at the end i can move the mouse back to where it was when the script was started (with a short delay the mouse movement should be almost unnoticeable).

**Comment by troxor** [comment]
Please come up with a simple reproduction case (and everything else that's templated in the issue, as much as possible.
