### ISSUE TITLE
Possibility to include other phrases in a phrase.

### ISSUE THREAD

**Issue by BenjaminHerbert** [autokey/autokey#89]
## Classification:
Feature

## Summary

I would like to include phrases in another phrase. This would allow to centrally organize 
snippets that can be included elsewhere. An example would be a footer for email replies.

**Comment by troxor** [comment]
Since Autokey exposes the full Python interpreter, you could create python modules for each script, and use those in other scripts. 

For example, running this within Autokey will show you the paths the interpreter looks for modules.
```
import sys
print(sys.path)
keyboard.send_keys(str(sys.path))
```
