### ISSUE TITLE
Cannot add phrases / scripts, anything.  I fail to find any means to do so.

### ISSUE THREAD

**Issue by deragon** [autokey/autokey#90]
## Classification:

Bug

## Reproducibility:

Always

## Summary

Cannot add phrases / scripts, anything.   I fail to find any means to do so.

## Detailed description

I fail to find any button or means to add a phrase.  However, whenever I right click on an entry (such as 'My phrases', the following error appears on the terminal:

```
  File "/usr/local/lib/python3.5/dist-packages/autokey/qtui/configwindow.py", line 662, in on_treeWidget_customContextMenuRequested
    menu.popup(QCursor.pos())
AttributeError: 'NoneType' object has no attribute 'popup'
```

## Version

AutoKey-Py3 version:  latest, up to date master branch from git://github.com/autokey-py3/autokey-py3.git as of 2017-07-16 04:12:18 EDT

Distro:  Ubuntu 16.04 LTS Xenial Xerus, up to date as of 2017-07-16 04:12:18 EDT

## Notes

I tried AutoKey previously and found it buggy, so I never used it really; but I was able to add my phrases.  I now wanted to try it again, updated my git repository, fire it up again and to my surprise, I fail to find any button to add a phrase in the main window.  I can edit the current ones, but cannot add anything.

## Screenshot

Screenshot of what I see, with no button or means to add a phrase or entry.  Remember, right-click an entry shows nothing on screen, but an error message shows up.

![autokey_006](https://user-images.githubusercontent.com/7698377/28490888-fa1f1ae4-6eb2-11e7-8510-2aecb5707540.png)

**Comment by troxor** [comment]
You might be stuck using the GTK frontend. The Qt version relies on a bunch of deprecated-upstream libraries, and may be deprecated itself soon unless someone knows Qt and wants to port the interface to Qt5. Just be sure to make sure any previous installations have been removed first, as there have been reports of conflict in the past.

**Comment by luziferius** [comment]
@deragon Are you still interested in using autokey?
I refactored/rewrote the Qt based UI (here: https://github.com/luziferius/autokey/tree/qt4_ui_cleanup).
Would you mind checking it out and testing if the new version works for you?

**Comment by luziferius** [comment]
Qt GUI is re-written, closing this for now.
Please comment/re-open if this bug still applies.
