### ISSUE TITLE
Macro keys on Logitech keyboard

### ISSUE THREAD

**Issue by Lurgainn** [autokey/autokey#904]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Xorg

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Enhancement

### Choose one or more terms that describe this issue:

- [ ] autokey triggers
- [ ] autokey-gtk
- [ ] autokey-qt
- [ ] beta
- [ ] bug
- [ ] critical
- [ ] development
- [ ] documentation
- [X] enhancement
- [ ] installation/configuration
- [ ] phrase expansion
- [ ] scripting
- [ ] technical debt
- [ ] user interface

### Which Linux distribution did you use?

Xubuntu 23.04

### Which AutoKey GUI did you use?

GTK

### Which AutoKey version did you use?

0.96.0

### How did you install AutoKey?

GIT

### Can you briefly describe the issue?

Autokey does not accept a macro key as a hotkey

### Can the issue be reproduced?

Always

### What are the steps to reproduce the issue?

1 Open Autokey GUI
2 Select a script
3 Press "Hotkey" "Set"
4 Press "Press to Set"
5 On Logitech Keyboard (or I guess every keyboard that has macro keys) press a macro key (one from "G1" to "G12") or a LCD key (my keyboard is Logitech G510 so it has a LCD)
6 Nothing is registered as a hotkey

### What should have happened?

The macro key (for instance "G1") shoul be set as the hotkey for this script

### What actually happened?

Nothing. The macro key is ignored.

### Anything else?

Is it possible to implement the management of all the macro keys that are set in linux kernel's file "input-event-codes.h", the "KEY_MACRO1" ... "KEY_MACRO30", "KEY_KBD_LCD_MENU1" ... "KEY_KBD_LCD_MENU5",  "KEY_MACRO_PRESET1" ... "KEY_MACRO_PRESET3" and "KEY_MACRO_RECORD_START", "KEY_MACRO_RECORD_STOP", "KEY_MACRO_PRESET_CYCLE" ?
Thanks so much

**Comment by josephj11** [comment]
Welcome to the AutoKey community, @Lurgainn ! Be sure to take  look at our [wiki](https://github.com/autokey/autokey/wiki/) which has a number of helpful articles and a lot of example scripts.

As you note, there are a few aspects to this.

One is the wonderful world of custom/gaming keyboards. Since these are varied and a lot of them really don't even want to work with Linux. there's not much we can do with them and we would probably have to have the specific hardware for implementation and ongoing testing.

Another aspect appears to be some capabilities already built into Linux (input event codes). I have not seen these before, but maybe @sebastiansam55 knows something about them.

Although these input event codes can't be used directly by AutoKey now, it might be possible to launch a script some other way and have it detect and process these codes. There would have to be a Python module (or some other way) to detect the events.

While this might work, we generally don't encourage users to implement long running scripts. They will work, but we don't have a lot of experience with them, so there may be bugs. Also, such things often work better as standalone scripts/programs using tools like xdotool, wmctrl, and Zenity directly - independent of AutoKey.

In general, the problem with a request like this is that it's a niche feature that wouldn't be very high priority.

Currently, we have very limited developer resources and aren't really looking at any enhancements. However, any developer capable of implementing such features is welcome to contribute almost anything they want to work on as long as we feel it would be valuable and compatible. (In other words, check with us before expending a lot of effort on something that might never get merged.)

Soapbox: Nobody has tried it yet (or at least told us about it), but basic hardware and software exists that will support placing a small computer such as an Arduino or Raspberry Pi between your keyboard and your computer. Once you do that, you can implement almost any feature relatively independent of what your keyboard and OS can support. This would probably also work with wireless connectivity so you wouldn't necessarily have to end up with a cable and a box dangling from your keyboard.

**Comment by Lurgainn** [comment]
Josephj11, thanks for your quick reply.
I understand your motivations, but I thought since those keys of the Logitech keyboards are officially recognized by the Linux kernel, then they should also be taken into consideration by this program.
And the scripts that I would like to launch with those keys would actually be short (for example launching another program from a key).
However, can I ask you at least some indications? Since I know a little bit (just a bit) of programming in Python, to simplify what I'm looking for in the source code, can you indicate which you think are the files to be modified to implement the functionality I ask?
I found "model/key.py", "iomediator/keygrabber.py" and "iomediator/iomediator.py", but I don't know for example which syntax I have to use to add "MACRO1" key to the "key.py" file. Have I to add "MACRO1 = "<macro1>" somewhere into the "class Key"? 
Thanks anyway, best regards

**Comment by Lurgainn** [comment]
> As you note, there are a few aspects to this.
> 
> One is the wonderful world of custom/gaming keyboards. Since these are varied and a lot of them really don't even want to work with Linux. there's not much we can do with them and we would probably have to have the specific hardware for implementation and ongoing testing.
> 
> Another aspect appears to be some capabilities already built into Linux (input event codes). I have not seen these before, but maybe @sebastiansam55 knows something about them.

Josephj11, thanks for your quick reply.
I understand your motivations, but I thought since those keys of the Logitech keyboards are officially recognized by the Linux kernel, then they should also be taken into consideration by this program.
And the scripts that I would like to launch with those keys would actually be short (for example launching another program from a key).
However, can I ask you at least some indications? Since I know a little bit (just a bit) of programming in Python, to simplify what I'm looking for in the source code, can you indicate which you think are the files to be modified to implement the functionality I ask?
I found "model/key.py", "iomediator/keygrabber.py" and "iomediator/iomediator.py", but I don't know for example which syntax I have to use to add "MACRO1" key (keycode 656) to the "key.py" file. Have I to add "MACRO1 = "\<macro1\>" somewhere into the "class Key"?
Thanks anyway, best regards

**Comment by Elliria** [comment]
I suspect that that key doesn't work like an ordinary key and doesn't talk to the operating system in the same way, but it's worth a try.

Does `xev` recognize the key?
* Display keycodes for all keyboard events:
  ```bash
  xev -event keyboard
  ```
* Display keycodes for all keyboard events:
  ```bash
  xev -event keyboard | grep -Po '(?<=keycode\s)[^\s]*'
  ```
* Display keycodes for all keyboard events and preface each with the specified text:
  ```bash
  xev -event keyboard | grep -Eo ".{,0}keycode.{,4}"
  ```

I did a search for **alt_gr** (as an example key) in the AutoKey files and got this list of files that you'd probably want to mess around with to try to get it working:
* [lib/autokey/interface.py](https://github.com/autokey/autokey/blob/develop/lib/autokey/interface.py)
* [lib/autokey/model/key.py](https://github.com/autokey/autokey/blob/develop/lib/autokey/model/key.py)
* [lib/autokey/gtkui/dialogs.py](https://github.com/autokey/autokey/blob/develop/lib/autokey/gtkui/dialogs.py)
* [lib/autokey/qtui/dialogs/hotkeysettings.py](https://github.com/autokey/autokey/blob/develop/lib/autokey/qtui/dialogs/hotkeysettings.py)
* [lib/autokey/iomediator/iomediator.py](https://github.com/autokey/autokey/blob/develop/lib/autokey/iomediator/iomediator.py)
* [tests/test_iomediator.py](https://github.com/autokey/autokey/blob/develop/tests/test_iomediator.py)

**Comment by sebastiansam55** [comment]
@Lurgainn do you know if your keyboard has the ability to remap those macro keys to the extended Function keys (ie F13-F35). these are supported in autokey and is likely the fastest way for you to get those keys mapped to an autokey script.

In order to implement them yeah we'd probably need to see `xev` output to see exactly what X signals the keys are sending. 

Once we have that information you'd have to add an entry to `key.py` and the dictionary at the bottom of `interface.py`.

For reference, here is the complete list of XK events we can map to;
```
Xlib.XK.XK_0                  Xlib.XK.XK_F                  Xlib.XK.XK_Hyper_L            Xlib.XK.XK_KP_Up              Xlib.XK.XK_Q                  Xlib.XK.XK_Y                  Xlib.XK.XK_egrave             Xlib.XK.XK_parenleft
Xlib.XK.XK_1                  Xlib.XK.XK_F1                 Xlib.XK.XK_Hyper_R            Xlib.XK.XK_Kana_Lock          Xlib.XK.XK_R                  Xlib.XK.XK_Yacute             Xlib.XK.XK_equal              Xlib.XK.XK_parenright
Xlib.XK.XK_2                  Xlib.XK.XK_F10                Xlib.XK.XK_I                  Xlib.XK.XK_Kana_Shift         Xlib.XK.XK_R1                 Xlib.XK.XK_Z                  Xlib.XK.XK_eth                Xlib.XK.XK_percent
Xlib.XK.XK_3                  Xlib.XK.XK_F11                Xlib.XK.XK_Iacute             Xlib.XK.XK_Kanji              Xlib.XK.XK_R10                Xlib.XK.XK_Zen_Koho           Xlib.XK.XK_exclam             Xlib.XK.XK_period
Xlib.XK.XK_4                  Xlib.XK.XK_F12                Xlib.XK.XK_Icircumflex        Xlib.XK.XK_Katakana           Xlib.XK.XK_R11                Xlib.XK.XK_Zenkaku            Xlib.XK.XK_exclamdown         Xlib.XK.XK_periodcentered
Xlib.XK.XK_5                  Xlib.XK.XK_F13                Xlib.XK.XK_Idiaeresis         Xlib.XK.XK_L                  Xlib.XK.XK_R12                Xlib.XK.XK_Zenkaku_Hankaku    Xlib.XK.XK_f                  Xlib.XK.XK_plus
Xlib.XK.XK_6                  Xlib.XK.XK_F14                Xlib.XK.XK_Igrave             Xlib.XK.XK_L1                 Xlib.XK.XK_R13                Xlib.XK.XK_a                  Xlib.XK.XK_g                  Xlib.XK.XK_plusminus
Xlib.XK.XK_7                  Xlib.XK.XK_F15                Xlib.XK.XK_Insert             Xlib.XK.XK_L10                Xlib.XK.XK_R14                Xlib.XK.XK_aacute             Xlib.XK.XK_grave              Xlib.XK.XK_q
Xlib.XK.XK_8                  Xlib.XK.XK_F16                Xlib.XK.XK_J                  Xlib.XK.XK_L2                 Xlib.XK.XK_R15                Xlib.XK.XK_acircumflex        Xlib.XK.XK_greater            Xlib.XK.XK_question
Xlib.XK.XK_9                  Xlib.XK.XK_F17                Xlib.XK.XK_K                  Xlib.XK.XK_L3                 Xlib.XK.XK_R2                 Xlib.XK.XK_acute              Xlib.XK.XK_guillemotleft      Xlib.XK.XK_questiondown
Xlib.XK.XK_A                  Xlib.XK.XK_F18                Xlib.XK.XK_KP_0               Xlib.XK.XK_L4                 Xlib.XK.XK_R3                 Xlib.XK.XK_adiaeresis         Xlib.XK.XK_guillemotright     Xlib.XK.XK_quotedbl
Xlib.XK.XK_AE                 Xlib.XK.XK_F19                Xlib.XK.XK_KP_1               Xlib.XK.XK_L5                 Xlib.XK.XK_R4                 Xlib.XK.XK_ae                 Xlib.XK.XK_h                  Xlib.XK.XK_quoteleft
Xlib.XK.XK_Aacute             Xlib.XK.XK_F2                 Xlib.XK.XK_KP_2               Xlib.XK.XK_L6                 Xlib.XK.XK_R5                 Xlib.XK.XK_agrave             Xlib.XK.XK_hyphen             Xlib.XK.XK_quoteright
Xlib.XK.XK_Acircumflex        Xlib.XK.XK_F20                Xlib.XK.XK_KP_3               Xlib.XK.XK_L7                 Xlib.XK.XK_R6                 Xlib.XK.XK_ampersand          Xlib.XK.XK_i                  Xlib.XK.XK_r
Xlib.XK.XK_Adiaeresis         Xlib.XK.XK_F21                Xlib.XK.XK_KP_4               Xlib.XK.XK_L8                 Xlib.XK.XK_R7                 Xlib.XK.XK_apostrophe         Xlib.XK.XK_iacute             Xlib.XK.XK_registered
Xlib.XK.XK_Agrave             Xlib.XK.XK_F22                Xlib.XK.XK_KP_5               Xlib.XK.XK_L9                 Xlib.XK.XK_R8                 Xlib.XK.XK_aring              Xlib.XK.XK_icircumflex        Xlib.XK.XK_s
Xlib.XK.XK_Alt_L              Xlib.XK.XK_F23                Xlib.XK.XK_KP_6               Xlib.XK.XK_Left               Xlib.XK.XK_R9                 Xlib.XK.XK_asciicircum        Xlib.XK.XK_idiaeresis         Xlib.XK.XK_script_switch
Xlib.XK.XK_Alt_R              Xlib.XK.XK_F24                Xlib.XK.XK_KP_7               Xlib.XK.XK_Linefeed           Xlib.XK.XK_Redo               Xlib.XK.XK_asciitilde         Xlib.XK.XK_igrave             Xlib.XK.XK_section
Xlib.XK.XK_Aring              Xlib.XK.XK_F25                Xlib.XK.XK_KP_8               Xlib.XK.XK_M                  Xlib.XK.XK_Return             Xlib.XK.XK_asterisk           Xlib.XK.XK_j                  Xlib.XK.XK_semicolon
Xlib.XK.XK_Atilde             Xlib.XK.XK_F26                Xlib.XK.XK_KP_9               Xlib.XK.XK_Mae_Koho           Xlib.XK.XK_Right              Xlib.XK.XK_at                 Xlib.XK.XK_k                  Xlib.XK.XK_slash
Xlib.XK.XK_B                  Xlib.XK.XK_F27                Xlib.XK.XK_KP_Add             Xlib.XK.XK_Massyo             Xlib.XK.XK_Romaji             Xlib.XK.XK_atilde             Xlib.XK.XK_l                  Xlib.XK.XK_space
Xlib.XK.XK_BackSpace          Xlib.XK.XK_F28                Xlib.XK.XK_KP_Begin           Xlib.XK.XK_Menu               Xlib.XK.XK_S                  Xlib.XK.XK_b                  Xlib.XK.XK_less               Xlib.XK.XK_ssharp
Xlib.XK.XK_Begin              Xlib.XK.XK_F29                Xlib.XK.XK_KP_Decimal         Xlib.XK.XK_Meta_L             Xlib.XK.XK_Scroll_Lock        Xlib.XK.XK_backslash          Xlib.XK.XK_m                  Xlib.XK.XK_sterling
Xlib.XK.XK_Break              Xlib.XK.XK_F3                 Xlib.XK.XK_KP_Delete          Xlib.XK.XK_Meta_R             Xlib.XK.XK_Select             Xlib.XK.XK_bar                Xlib.XK.XK_macron             Xlib.XK.XK_t
Xlib.XK.XK_C                  Xlib.XK.XK_F30                Xlib.XK.XK_KP_Divide          Xlib.XK.XK_Mode_switch        Xlib.XK.XK_Shift_L            Xlib.XK.XK_braceleft          Xlib.XK.XK_masculine          Xlib.XK.XK_thorn
Xlib.XK.XK_Cancel             Xlib.XK.XK_F31                Xlib.XK.XK_KP_Down            Xlib.XK.XK_Muhenkan           Xlib.XK.XK_Shift_Lock         Xlib.XK.XK_braceright         Xlib.XK.XK_minus              Xlib.XK.XK_threequarters
Xlib.XK.XK_Caps_Lock          Xlib.XK.XK_F32                Xlib.XK.XK_KP_End             Xlib.XK.XK_Multi_key          Xlib.XK.XK_Shift_R            Xlib.XK.XK_bracketleft        Xlib.XK.XK_mu                 Xlib.XK.XK_threesuperior
Xlib.XK.XK_Ccedilla           Xlib.XK.XK_F33                Xlib.XK.XK_KP_Enter           Xlib.XK.XK_MultipleCandidate  Xlib.XK.XK_SingleCandidate    Xlib.XK.XK_bracketright       Xlib.XK.XK_multiply           Xlib.XK.XK_twosuperior
Xlib.XK.XK_Clear              Xlib.XK.XK_F34                Xlib.XK.XK_KP_Equal           Xlib.XK.XK_N                  Xlib.XK.XK_Super_L            Xlib.XK.XK_brokenbar          Xlib.XK.XK_n                  Xlib.XK.XK_u
Xlib.XK.XK_Control_L          Xlib.XK.XK_F35                Xlib.XK.XK_KP_F1              Xlib.XK.XK_Next               Xlib.XK.XK_Super_R            Xlib.XK.XK_c                  Xlib.XK.XK_nobreakspace       Xlib.XK.XK_uacute
Xlib.XK.XK_Control_R          Xlib.XK.XK_F4                 Xlib.XK.XK_KP_F2              Xlib.XK.XK_Ntilde             Xlib.XK.XK_Sys_Req            Xlib.XK.XK_ccedilla           Xlib.XK.XK_notsign            Xlib.XK.XK_ucircumflex
Xlib.XK.XK_D                  Xlib.XK.XK_F5                 Xlib.XK.XK_KP_F3              Xlib.XK.XK_Num_Lock           Xlib.XK.XK_T                  Xlib.XK.XK_cedilla            Xlib.XK.XK_ntilde             Xlib.XK.XK_udiaeresis
Xlib.XK.XK_Delete             Xlib.XK.XK_F6                 Xlib.XK.XK_KP_F4              Xlib.XK.XK_O                  Xlib.XK.XK_THORN              Xlib.XK.XK_cent               Xlib.XK.XK_numbersign         Xlib.XK.XK_ugrave
Xlib.XK.XK_Down               Xlib.XK.XK_F7                 Xlib.XK.XK_KP_Home            Xlib.XK.XK_Oacute             Xlib.XK.XK_Tab                Xlib.XK.XK_colon              Xlib.XK.XK_o                  Xlib.XK.XK_underscore
Xlib.XK.XK_E                  Xlib.XK.XK_F8                 Xlib.XK.XK_KP_Insert          Xlib.XK.XK_Ocircumflex        Xlib.XK.XK_Thorn              Xlib.XK.XK_comma              Xlib.XK.XK_oacute             Xlib.XK.XK_v
Xlib.XK.XK_ETH                Xlib.XK.XK_F9                 Xlib.XK.XK_KP_Left            Xlib.XK.XK_Odiaeresis         Xlib.XK.XK_Touroku            Xlib.XK.XK_copyright          Xlib.XK.XK_ocircumflex        Xlib.XK.XK_w
Xlib.XK.XK_Eacute             Xlib.XK.XK_Find               Xlib.XK.XK_KP_Multiply        Xlib.XK.XK_Ograve             Xlib.XK.XK_U                  Xlib.XK.XK_currency           Xlib.XK.XK_odiaeresis         Xlib.XK.XK_x
Xlib.XK.XK_Ecircumflex        Xlib.XK.XK_G                  Xlib.XK.XK_KP_Next            Xlib.XK.XK_Ooblique           Xlib.XK.XK_Uacute             Xlib.XK.XK_d                  Xlib.XK.XK_ograve             Xlib.XK.XK_y
Xlib.XK.XK_Ediaeresis         Xlib.XK.XK_H                  Xlib.XK.XK_KP_Page_Down       Xlib.XK.XK_Otilde             Xlib.XK.XK_Ucircumflex        Xlib.XK.XK_degree             Xlib.XK.XK_onehalf            Xlib.XK.XK_yacute
Xlib.XK.XK_Egrave             Xlib.XK.XK_Hankaku            Xlib.XK.XK_KP_Page_Up         Xlib.XK.XK_P                  Xlib.XK.XK_Udiaeresis         Xlib.XK.XK_diaeresis          Xlib.XK.XK_onequarter         Xlib.XK.XK_ydiaeresis
Xlib.XK.XK_Eisu_Shift         Xlib.XK.XK_Help               Xlib.XK.XK_KP_Prior           Xlib.XK.XK_Page_Down          Xlib.XK.XK_Ugrave             Xlib.XK.XK_division           Xlib.XK.XK_onesuperior        Xlib.XK.XK_yen
Xlib.XK.XK_Eisu_toggle        Xlib.XK.XK_Henkan             Xlib.XK.XK_KP_Right           Xlib.XK.XK_Page_Up            Xlib.XK.XK_Undo               Xlib.XK.XK_dollar             Xlib.XK.XK_ordfeminine        Xlib.XK.XK_z
Xlib.XK.XK_End                Xlib.XK.XK_Henkan_Mode        Xlib.XK.XK_KP_Separator       Xlib.XK.XK_Pause              Xlib.XK.XK_Up                 Xlib.XK.XK_e                  Xlib.XK.XK_oslash             
Xlib.XK.XK_Escape             Xlib.XK.XK_Hiragana           Xlib.XK.XK_KP_Space           Xlib.XK.XK_PreviousCandidate  Xlib.XK.XK_V                  Xlib.XK.XK_eacute             Xlib.XK.XK_otilde             
Xlib.XK.XK_Eth                Xlib.XK.XK_Hiragana_Katakana  Xlib.XK.XK_KP_Subtract        Xlib.XK.XK_Print              Xlib.XK.XK_W                  Xlib.XK.XK_ecircumflex        Xlib.XK.XK_p                  
Xlib.XK.XK_Execute            Xlib.XK.XK_Home               Xlib.XK.XK_KP_Tab             Xlib.XK.XK_Prior              Xlib.XK.XK_X                  Xlib.XK.XK_ediaeresis         Xlib.XK.XK_paragraph   
``` 

From a quick review of the above I don't see anything that would match "MACRO1" etc.

**Comment by sebastiansam55** [comment]
also, to plug one of my other projects, https://github.com/sebastiansam55/uinput-macropad

should allow you to remap any keyevent to any other. 

creating that configuration file may be a bit intense but should work without issue.

**Comment by Lurgainn** [comment]
> Does xev recognize the key?
>
>    Display keycodes for all keyboard events:
>
>    xev -event keyboard

Unfortunately xev don't display anything when I press the "G.." keys. Only "showkey" display the keycodes (656 for G1 and so on).
If I remember right, these keys, even if implemented in kernel, are not managed from X11, so if you asked me to use "xev", I guess that autokey use X11 functions, so I think that I'm unlucky.

**Comment by sebastiansam55** [comment]
the current version does yeah, if it's not detected by `xev` I don't think theres much we can do. 

there is a `uinput` version that is in development that should be compatible but it's still a WIP with more work to be done.

if you can remap via the keyboard firmware or something else like my uinput-macropad script you should be able to use the keys in autokey

**Comment by Elliria** [comment]
> Unfortunately xev don't display anything when I press the "G.." keys. Only "showkey" display the keycodes (656 for G1 and so on).

I see that you're using Xubuntu, so you could go to your log-in screen and choose to use a **Xorg** session, then run `xev` and then go back to the log-in screen and choose a **Wayland** session again. It would just be temporary to get the information.

If your keyboard is anything like my [Razer Blackwidow](https://www.razer.com/pc/gaming-keyboards/blackwidow-line), though, then the macro is handled internally by the keyboard and not by the operating system, so there's probably no hope for getting it to communicate with AutoKey in some way. My macros are stored in the keyboard itself and follow it around from computer to computer.

**Comment by Lurgainn** [comment]
> I see that you're using Xubuntu, so you could go to your log-in screen and choose to use a **Xorg** session, then run `xev` and then go back to the log-in screen and choose a **Wayland** session again. It would just be temporary to get the information.
> 

Hi Elliria and thanks for your message. Unfortunately Xubuntu (XFCE desktop) is not ready for wayland, so I can use Xorg only.

> If your keyboard is anything like my [Razer Blackwidow](https://www.razer.com/pc/gaming-keyboards/blackwidow-line), though, then the macro is handled internally by the keyboard

Again, unfortunately Logitech's keyboards with macro keys are not like the Razer. The keyboard has not any internal memory for the macro keys, but send keycodes from 656 and following for every macro keys. It's responsibility of some PC program to convert these keycodes to something useful, like for example macros.

Thanks anyway

**Comment by josephj11** [comment]
> Unfortunately xev don't display anything when I press the "G.." keys. Only "showkey" display the keycodes (656 for G1 and so on). If I remember right, these keys, even if implemented in kernel, are not managed from X11, so if you asked me to use "xev", I guess that autokey use X11 functions, so I think that I'm unlucky.

Sam's new test version uses another system for Wayland, but that still needs to detect the new hotkeys somehow.

**Comment by Lurgainn** [comment]
> @Lurgainn do you know if your keyboard has the ability to remap those macro keys to the extended Function keys (ie F13-F35). these are supported in autokey and is likely the fastest way for you to get those keys mapped to an autokey script.
> 

Hi and thanks for your reply.
While waiting for an Autokey version that will support Wayland (I guess that will function even in X11 with keycodes \> 255), I accept that I could convert the G.. keys into F13...F35, but if possible, I don't want to install additional programs and create complicated chains of events.
Can you show me (or give me a URL) a way to realize the conversion using simple standard programs/configurations already available in a standard installation of Ubuntu?

**Comment by Elliria** [comment]
It's not looking good. Here's [another recommendation for the use of `xev`](https://www.reddit.com/r/LogitechG/comments/jtg3tc/is_there_a_way_to_change_what_g_keys_of_g915_do/) and this [Reddit page](https://www.reddit.com/r/LogitechG/comments/p6060n/logitech_g_hub_on_linux/) may be helpful for explaining why this is so challenging. I suspect that without @sebastiansam55's program, it might not be possible. The world, for some strange reason, designs most things for Windows.

Some of those posts about this have mentioned the **piper** program that's in the Ubuntu repositories and is for configuring gaming devices. It doesn't sound like it can do intricate things, but someone suggested that lighting may be controlled with it, so I might give that a whirl for customizing my keyboard's lighting effects (since it's a gaming keyboard). To accomplish that currently, I have to unplug the keyboard, plug it into my work computer (which uses Windows), configure it, unplug it, bring it back in here, and plug it back in.

**Comment by Elliria** [comment]
One other thought. Depending on what you are trying to accomplish with the macro, AutoKey might be able to accomplish the same thing on its own. After all, it's automation software. If you don't mind sharing what the macro does, we might be able to figure out how to create an AutoKey script that can do it for you with any hotkey or abbreviation, bypassing your G keys entirely.

**Comment by Lurgainn** [comment]
Thanks again, but I need to use G keys so I'm stuck into the problem to convert G keys  keycodes to F13..F35.
The "Piper" utility it's not compatible with my Logitech G510.

The macro that I want to use, are very simple like a "subprocess.Popen()" to launch some external programs.

**Comment by josephj11** [comment]
Not a solution, but you can add icons to your desktop or panel that launch anything you like. I even do this to launch bash scripts, some of which have GUI dialogs. Might be better than nothing.

**Comment by sebastiansam55** [comment]
Leaving this here again  @Lurgainn 

https://github.com/sebastiansam55/uinput-macropad

The `cmd` directive in the config file is literally just subprocess.Popen

You could also use this to remap your g keys to extended function keys

**Comment by Lurgainn** [comment]
> Leaving this here again @Lurgainn
> 
> https://github.com/sebastiansam55/uinput-macropad

Thanks for your suggestion. I'll try for sure but can I ask why in your "README.md" under "Usage" you wrote:
"_Make sure you are not grabbing the main keyboard that you use for input as this can lock you with out a way to kill the program._"
Is it a simple invite to be careful with the configuration or there are  some other problems?
I need to use the program with my main keyboard, so I'm just a bit scared ;-)

**Comment by sebastiansam55** [comment]
You should be careful with the configuration. But that functionality (intercepting all input events for a device) is central to the functionality of the script. Otherwise you would not be able to remap keystrokes to other keystrokes.

In your case you'd want;
full_grab - true
only_defined - false

So the program will be absorbing all of the input events from your device (full_grab true) but it will pass through anything that does not match the defined macros (only_defined false). So in effect it will pass through all events except for the G keybuttons, instead it will send whatever you tell it to as defined in the config file. 

If you're only using it with your keyboard you'd still be able to use your mouse to close the terminal window if you lock yourself out. And if you disconnect and reconnect the keyboard there will be a 5 second delay before the mapping kicks in again. You can alter that in the file (last line of macropad.py, increase the time.sleep() value to whatever) or you can just replace that line with sys.exit() and the program will quit when the input device disconnects.

**Comment by Lurgainn** [comment]
> You should be careful with the configuration. But that functionality (intercepting all input events for a device) is central to the functionality of the script. Otherwise you would not be able to remap keystrokes to other keystrokes.
> 
> In your case you'd want; full_grab - true only_defined - false
> 

Hi Sebastian, I'm testing you program and it's like perfect for my needs.
I even discovered that the Linux kernel create a specific uinput device for the macro keys of my Logitech G510 (the name is "Logitech Gaming Keyboard Gaming Keys"), so I can intercept and configure just the G.. keys a leave undisturbed all the others. Simply PERFECT.

Can I open some issue on uinput-macropad github just to resolve a few micro nuisances?

Thanks so much for your help

**Comment by sebastiansam55** [comment]
absolutely you can, no guarantees that I'll do anything about them tho

**Comment by josephj11** [comment]
@Lurgainn Once you have this working and stable, we'd love to have a post about it on our [wiki](https://github.com/autokey/autokey/wiki/) if AutoKey is still part of the solution.

**Comment by Lurgainn** [comment]
> @Lurgainn Once you have this working and stable, we'd love to have a post about it on our [wiki](https://github.com/autokey/autokey/wiki/) if AutoKey is still part of the solution.

Unfortunately at the moment Autokey is not compatible with the macro-keys (G..) of my Logitech G510 keyboard.
My solution is to use sebastiansam55's "uinput-macropad" program, so I don't think that I can be useful for your wiki. Let me know what do you think.
Obviously I hope that a future version of Autokey (a one using "uinput" and compatible with Wayland) will be compatible with my Logitech G510 too.

Anyway thanks for all help that I received in this forum.

**Comment by josephj11** [comment]
OK. Till next  time.  :)

**Comment by Lurgainn** [comment]
> absolutely you can, no guarantees that I'll do anything about them tho

Even if I'm not so confident with git, instead of opening issues I'll try to fork and then submit some pull request, if you'r not against it.

Besides that, if there aren't any other necessity, tomorrow I'll close this topic.

**Comment by josephj11** [comment]
@Lurgainn Thanks for anything you contribute.

Elleria created a form for filling out issues that makes it pretty easy to do. You used it for this one.

When we get PRs, it helps us track them if they are associated with an issue. We assign labels to categorize issues and we search them when researching a problem. We don't tend to do those with PRs.

In general, discussions of what the issue is and how it is/should be addressed should be in the issue whereas comments on the code itself or concerns with installing it might be in the PR.

If you just want to discuss anything or want to ask a question about how to approach an issue, the best place for that is on [Gitter](https://gitter.im/autokey/autokey) where the advanced users and developers hang out. We do not have strict rules over there, so you can post almost anything as long as it is civil and constructive.

**Comment by Elliria** [comment]
I'm not great at git, but I'd be happy to help if you run into any trouble, @Lurgainn.

**Comment by Lurgainn** [comment]
> @Lurgainn Thanks for anything you contribute.

Sorry for the misunderstandig, but I'm contributing to sebastian's uinput-macropad.
The transition from "X11" to "uinput" in Autokey is way above my abilities. Anyway I'm eager to see a future version of Autokey that will be able to function under Wayland and to manage keyboards with macro keys recognized by Linux kernel, like my Logitech G510.

So I thank anyone for your help, and I close this issue.
