### ISSUE TITLE
Missing wiki page - Contributed Scripts 3

### ISSUE THREAD

**Issue by Elliria** [autokey/autokey#913]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Xorg

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Documentation

### Choose one or more terms that describe this issue:

- [ ] autokey triggers
- [ ] autokey-gtk
- [ ] autokey-qt
- [ ] beta
- [ ] bug
- [ ] critical
- [ ] development
- [X] documentation
- [ ] enhancement
- [ ] installation/configuration
- [ ] phrase expansion
- [ ] scripting
- [ ] technical debt
- [ ] user interface

### Which AutoKey GUI did you use?

None

### Can you briefly describe the issue?

I was going to add a clipboard script to the [Contributed Scripts 3](https://github.com/autokey/autokey/wiki/Contributed-Scripts-3) page in the wiki, but the page is missing. You can see that there are supposed to be four scripts in it if you look on the [Contents of contributed script files](https://github.com/autokey/autokey/wiki/Contents-of-contributed-script-files) page.

A look at the git log of the wiki repository shows that the last time that file was touched was in **commit 63425ce06484d44ba9937c287d6bab6240fcf986** on July 10, 2023 when @kreezxil updated the page.

I'm not a savvy enough git user to be able to figure out how to see the deletion, let alone how to get it back. Any help would be appreciated.

### Can the issue be reproduced?

Always

### What are the steps to reproduce the issue?

1. Try to visit the [Contributed Scripts 3](https://github.com/autokey/autokey/wiki/Contributed-Scripts-3) page in the wiki in your browser.

### What should have happened?

The page should open.

### Do you have screenshots?

The page doesn't exist.

**Comment by sebastiansam55** [comment]
it looks like it was renamed to [kreezxil](https://github.com/autokey/autokey/wiki/kreezxil) in that same commit

**Comment by sebastiansam55** [comment]
you can git clone the wiki git and use whatever git tool to view the changes

`git clone https://github.com/autokey/autokey.wiki.git`
`git whatchanged 63425ce06484d44ba9937c287d6bab6240fcf986`

when it lists two file names it means it was renamed from orig=>newname. Included an example of when it was explicitly listed that a file was renamed at the bottom of the screenshot
![2023-08-15 15-46-38 939823](https://github.com/autokey/autokey/assets/1707320/4b4dfd3c-d744-4554-ab16-3be499b5a7b9)

**Comment by kreezxil** [comment]
weird that it showed me renaming it to my name too. why would i rename a
page to my name? lol. but there it is.

**Comment by sebastiansam55** [comment]
Then I assume you have no objection to that page being re-renamed?

I've seen stuff like that happen at my job as a result of autocomplete gone
wrong, it may have just autoreplaced the title with your username because
it thought it was a login field or something like that.

**Comment by kreezxil** [comment]
yeah i have no issue with that at all.

**Comment by Elliria** [comment]
Ah, thank you for the explanation of how to read the git log entries. I'll know what to look for from now on. And this looks like a simple fix, so I'm renaming the page back to what it was before.
