### ISSUE TITLE
broken link in ABOUT

### ISSUE THREAD

**Issue by steanne** [autokey/autokey#94]
## Summary

about file links to the autokey website: 
https://code.google.com/archive/p/autokey/
that's 404.  

and it seems like you sidestepped describing what the program does by pointing to the autokey website instead (which is reasonable when it works), so now there is none at all.

**Comment by troxor** [comment]
The link in the README.rst? It looks fine from here.
```
% curl -sL https://code.google.com/archive/p/autokey/ -I  | grep HTTP
HTTP/1.1 200 OK
```

**Comment by steanne** [comment]
i get a 200 using curl, too, but a 404 actually clicking it, and i've cleared cache.

ah, never mind, it's isp-level caching.  tested with a different one and it's fine.
