### ISSUE TITLE
Help requested with lint and pytest errors in workflows

### ISSUE THREAD

**Issue by Elliria** [autokey/autokey#965]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Xorg

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Enhancement

### Choose one or more terms that describe this issue:

- [ ] autokey triggers
- [ ] autokey-gtk
- [ ] autokey-qt
- [ ] beta
- [ ] bug
- [ ] critical
- [X] development
- [ ] documentation
- [ ] enhancement
- [ ] installation/configuration
- [ ] phrase expansion
- [ ] scripting
- [ ] technical debt
- [ ] user interface

### Other terms that describe this issue if not provided above:

update

### Which AutoKey GUI did you use?

None

### Can you briefly describe the issue?

We're getting two errors when pull requests are merged:

## Lint error:
The [lint error](https://github.com/autokey/autokey/actions/runs/10863552720/job/30147823053?pr=958) has this complaint:
```python
Running: flake8 --count --select=E9,F63,F7,F82 --show-source --statistics --builtins=_ --max-complexity=10 --max-line-length=127 lib/autokey tests
lib/autokey/uinput_interface.py:174:35: F821 undefined name 'IoMediator'
        self.mediator = mediator  # type: IoMediator
                                  ^
lib/autokey/uinput_interface.py:827:79: F821 undefined name 'keyName'
            logger.warning("Error sending modified key %r %r: %s", modifiers, keyName, str(e))
                                                                              ^
2     F821 undefined name 'IoMediator'
2
Flake8 error
```
It's complaining about [line 174](https://github.com/autokey/autokey/blob/b51c6bab269b6c4381f737d1d7ddd733cf6b0638/lib/autokey/uinput_interface.py#L174) of the `uinput_interface.py` file. Interestingly, that file only exists on the **develop** branch.

[Line 174](https://github.com/autokey/autokey/blob/b51c6bab269b6c4381f737d1d7ddd733cf6b0638/lib/autokey/uinput_interface.py#L174) of that file looks like this:
```python
        self.mediator = mediator  # type: IoMediator
```
It seems that a comment on that line is causing the trouble. What I don't know is whether the comment should be edited (and if so, to what?) or deleted and whether there would be any negative consequences to either of those. Google isn't very forthcoming when asked for information on "IoMediator". Any help with this would be appreciated.

## pytest error:
The [pytest error](https://github.com/autokey/autokey/actions/runs/10863552720/job/30147822981?pr=958) looks like this:
```python
report: commands[2]> coverage html
/home/runner/work/autokey/autokey/.tox/report/lib/python3.10/site-packages/coverage/html.py:123: CoverageWarning: No contexts were measured
  self.coverage._warn("No contexts were measured")
Wrote HTML report to test_coverage_report_html/index.html
  clean: OK (2.21=setup[1.95]+cmd[0.26] seconds)
  coverage: FAIL code 2 (18.21=setup[11.63]+cmd[6.57] seconds)
  report: OK (6.21=setup[1.72]+cmd[0.10,1.25,3.15] seconds)
  evaluation failed :( (26.83 seconds)
Error: Process completed with exit code 255.
```
It's complaining about **code 2**, which means invalid use of a shell built-in command, and it's exiting with **code 255**, which means there's an environment issue.

[This WordPress page](https://dotjoeblog.wordpress.com/2021/03/14/github-actions-aws-error-exit-code-255/) suggests that this is an AWS error due to a change in `ubuntu-latest`, which our project does use. That page makes these recommendations for us to pick from:
```
The quick, guaranteed-to-break-later workaround is to change the actions runner to ubuntu-18.04.

A better solution is to add AWS_DEFAULT_REGION to the action’s environment. 
```
The second one sounds better to me, but I'm not sure how to implement it. Some Googling suggested that we need to put the **AWS_DEFAULT_REGION** environment variable into the `AWS` config file. We don't have an `AWS` config file, so we'd need to find out where to put it and whether we would **just** put **AWS_DEFAULT_REGION** into it to solve that problem or whether it would need more contents (and what they would need to be). I'm assuming the file would go into the [.github/workflows](https://github.com/autokey/autokey/tree/master/.github/workflows) directory, but maybe it goes into the [config](https://github.com/autokey/autokey/tree/master/config) directory or elsewhere entirely.

Any help with this would be appreciated.

### Can the issue be reproduced?

None

### What are the steps to reproduce the issue?

1. Submit a pull request.
2. Merge the pull request.

### What should have happened?

The pull request should go through with no errors.

### What actually happened?

A [lint error](https://github.com/autokey/autokey/actions/runs/10863552720/job/30147823053?pr=958) and a [pytest error](https://github.com/autokey/autokey/actions/runs/10863552720/job/30147822981?pr=958) are produced.

<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #965</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @Elliria</code> (replace <code>20</code> with the amount, and <code>@Elliria</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

**Comment by Elliria** [comment]
It looks like updating the action versions (pull request #963) fixed these issues, but I'll wait until it's merged to be sure before closing this out.

**Comment by BlueDrink9** [comment]
Great research. Since updating the actions fixes the issues, I think we can stick to that.

FYI, the comment is a python type hint, and it's optional so wouldn't break anything if removed. To set something "in the environment" you'd want to google "github actions set environment variable".

**Comment by josephj11** [comment]
On the first error: AFAIK, uinput is only used in the new Wayland code from Sam. That's why it only appears in develop. 

On the second error, AFAIK, we don't directly use AWS for anything, so that seems like it would be an upstream issue.

**Comment by Elliria** [comment]
No worries, @josephj11. Both errors vanished when the actions were bumped up to current versions.
