### ISSUE TITLE
How can I use CapsLock as a Hotkey in AutoScript?

### ISSUE THREAD

**Issue by osama-h-rana** [autokey/autokey#97]
## Classification:

Usability

## Summary

I'm trying to repurpose the capslock button, but AutoKey doesn't recognize it when I press it when setting the Hotkey for a script

## Expected Results

The CapsLock button should be map-able to any combination of my choice

## Actual Results

I cannot set the hotkey to CapsLock

**Comment by xircon** [comment]
## 1>. Disable caps lock:
```
xmodmap -e 'clear Lock'
```
## 2>. Use xcape to assign a key sequence e.g. Left super+f
```
xcape -e '#66=Super_L|f'
```
## 3>.  Attach autokey script to the assigned key sequence.

## 4>.  Reassign capslock to (say) pressing both shift keys.
```
setxkbmap -option "caps:none"
setxkbmap -option "shift:both_capslock"
```

Caps lock key is really out of autokey's scope, you just need to use other utilities to get the desired effect.

**Comment by troxor** [comment]
Good info, thanks! It has been added to the Wiki for future reference.

**Comment by osama-h-rana** [comment]
AutoKey is the closest thing to AutoHotKey (on Windows). CapsLock is useless for me so it's always nice to be able to repurpose it. I will try xircon's method and update this post.

**Comment by xircon** [comment]
I will post this as an example (I run bspwm):
```

cat my-xcape.sh
#!/bin/bash
#
#################
# Kill X server #
#################
setxkbmap -option terminate:ctrl_alt_bksp

############################################
# Set both shift keys to trigger caps lock #
############################################
setxkbmap -option "caps:none"
setxkbmap -option "shift:both_capslock"

killall xcape

################
# Super Keys:  #
################
xmodmap -e "keycode 135 = Super_R"
xmodmap -e "keycode 134 = Super_R"
xcape -e 'Super_L=Alt_L|Tab'
xcape -e 'Super_R=Super_L|1' # <<Menu key

#################
# Control keys: #
#################
xcape -e 'Control_L=Super_L|2' # << terminal desktop (2)
xcape -e 'Control_R=Super_L|z' 

############
# Alt Keys #
############
xcape -e 'Alt_L=Alt_L|w' # << browser
#Reconfigure Alt_gr
xmodmap -e "keycode 108 = Alt_R" && xset -r 108
xcape -e 'Alt_R=Alt_L|a'   # << Ulauncher

##############
# Shift Keys #
##############
xcape -e 'Shift_L=BackSpace'
xcape -e 'Shift_R=Control_L|Alt_L|m'

#############
# Caps Lock #
#############
#Disable caps lock key
xmodmap -e 'clear Lock'
xcape -e '#66=Super_L|f'
```
This is in my autostart script.
