### ISSUE TITLE
I can't output a combination of three keys using AutoKey on Ubuntu 17.04

### ISSUE THREAD

**Issue by osama-h-rana** [autokey/autokey#98]
## Classification:

Bug

## Reproducibility:

Always

## Summary

Here's what I've done so far:

mapped `<super>+h` to `keyboard.send_keys("<ctrl>+<f4>")`, works
mapped `<super>+h` to `keyboard.send_keys("<alt>+<f4>")`, works
mapped `<super>+h` to `keyboard.send_keys("<ctrl>+<alt>+<f4>")`, doesn't work

Incidentally, `keyboard.send_key("<super>")` doesn't work either. Not sure if that is related to the original issue or not.

## Version

AutoKey-Py3 version 0.90.4

**Comment by xircon** [comment]
This works (requires pyautogui):
```
import pyautogui
pyautogui.hotkey('ctrl', 'alt', 'F4')
```
Takes me straight to a VT.

Super key is probably swallowed by your desktop environment:
xfce4 - whiskermenu
KDE - plasma menu
and so on.

You can use xcape, but will not work in all use cases.

**Comment by osama-h-rana** [comment]
Thanks, it works!
